'use strict';
const { finite, integer, text, freeze } = require('./contracts');

const MIN_CLASSICAL_N = 5;
const MIN_DIF_GROUP_N = 20;
function mean(values){ return values.length?values.reduce((a,b)=>a+b,0)/values.length:null; }
function variance(values){ if(values.length<2)return null; const m=mean(values); return values.reduce((s,v)=>s+(v-m)**2,0)/(values.length-1); }
function pointBiserial(scores,total){ if(scores.length!==total.length||scores.length<3)return null; const ones=[],zeros=[]; for(let i=0;i<scores.length;i+=1)(scores[i]>=0.5?ones:zeros).push(total[i]); if(!ones.length||!zeros.length)return null; const sd=Math.sqrt(variance(total)||0); if(sd===0)return null; return ((mean(ones)-mean(zeros))/sd)*Math.sqrt((ones.length*zeros.length)/(scores.length**2)); }
function optionStats(rows){ const options=new Map(); for(const row of rows){ const id=String(row.optionId||'').trim(); if(!id)continue; const bucket=options.get(id)||{count:0,correctCount:0}; bucket.count+=1; if(row.correct===true)bucket.correctCount+=1; options.set(id,bucket); } return Object.freeze([...options.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([optionId,v])=>Object.freeze({optionId,count:v.count,selectionRate:v.count/Math.max(1,rows.length),correctSelectionRate:v.correctCount/Math.max(1,v.count)}))); }
function analyzeClassicalItem(rows=[]){ const valid=(Array.isArray(rows)?rows:[]).filter(r=>Number.isFinite(Number(r.itemScore))&&Number.isFinite(Number(r.totalScore))); const n=valid.length; if(n<MIN_CLASSICAL_N)return freeze({status:'INSUFFICIENT_DATA',sampleSize:n,difficulty:null,discrimination:null,optionStats:optionStats(rows),reviewFlags:Object.freeze([]),autoDecisionAllowed:false}); const itemScores=valid.map(r=>Number(r.itemScore)); const totalScores=valid.map(r=>Number(r.totalScore)); const difficulty=mean(itemScores); const discrimination=pointBiserial(itemScores,totalScores); const flags=[]; if(discrimination!=null&&discrimination<0)flags.push('NEGATIVE_DISCRIMINATION_REVIEW'); if(difficulty!=null&&(difficulty<0.1||difficulty>0.95))flags.push('EXTREME_DIFFICULTY_REVIEW'); return freeze({status:'OBSERVED',sampleSize:n,difficulty,discrimination,optionStats:optionStats(rows),reviewFlags:Object.freeze(flags),autoDecisionAllowed:false}); }
function compareDifGroups(groups={}){ const entries=Object.entries(groups).map(([group,values])=>[group,(Array.isArray(values)?values:[]).map(Number).filter(Number.isFinite)]); if(entries.length<2||entries.some(([,v])=>v.length<MIN_DIF_GROUP_N))return freeze({status:'INSUFFICIENT_DATA',groups:Object.freeze(entries.map(([group,v])=>Object.freeze({group,n:v.length,mean:null}))),differences:Object.freeze([]),autoDecisionAllowed:false}); const summaries=entries.map(([group,v])=>Object.freeze({group,n:v.length,mean:mean(v)})); const differences=[]; for(let i=0;i<summaries.length;i+=1)for(let j=i+1;j<summaries.length;j+=1)differences.push(Object.freeze({a:summaries[i].group,b:summaries[j].group,observedDifference:summaries[i].mean-summaries[j].mean,statisticalSignificanceClaimed:false})); return freeze({status:'OBSERVED_DESCRIPTIVE_ONLY',groups:Object.freeze(summaries),differences:Object.freeze(differences),autoDecisionAllowed:false}); }
function equatingPosture({anchorOverlap=0,forms=0}={}){ const overlap=integer(anchorOverlap,'anchorOverlap',{min:0,max:100000}),formCount=integer(forms,'forms',{min:0,max:1000}); return freeze({status:overlap>=5&&formCount>=2?'REVIEWABLE_INPUT_AVAILABLE':'INSUFFICIENT_DATA',method:'NO_AUTOMATIC_EQUATING',anchorOverlap:overlap,forms:formCount,automaticScoreTransformationAllowed:false,humanPsychometricReviewRequired:true}); }
module.exports={MIN_CLASSICAL_N,MIN_DIF_GROUP_N,analyzeClassicalItem,compareDifGroups,equatingPosture};
