'use strict';
const {ANALYTICS_METHOD_VERSION,SUFFICIENCY}=require('./contracts');
function finite(v){const n=Number(v);return Number.isFinite(n)?n:null;}
function mean(xs){return xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:null;}
function pearson(pairs){if(pairs.length<3)return null;const xs=pairs.map(p=>p[0]),ys=pairs.map(p=>p[1]),mx=mean(xs),my=mean(ys);let num=0,dx=0,dy=0;for(let i=0;i<pairs.length;i++){const x=xs[i]-mx,y=ys[i]-my;num+=x*y;dx+=x*x;dy+=y*y;}return dx>0&&dy>0?num/Math.sqrt(dx*dy):null;}
function sampleState(n,{descriptiveMin=2,analysisMin=30}={}){if(n<descriptiveMin)return SUFFICIENCY.INSUFFICIENT;if(n<analysisMin)return SUFFICIENCY.DESCRIPTIVE;return SUFFICIENCY.SUPPORTED;}
function facility(events){const scored=events.map(e=>{const earned=finite(e.itemScore),max=finite(e.itemMax);return earned!=null&&max>0?earned/max:null;}).filter(v=>v!=null);return Object.freeze({value:mean(scored),sampleSize:scored.length,state:sampleState(scored.length),method:'mean_proportion_of_available_item_score',methodVersion:ANALYTICS_METHOD_VERSION});}
function discrimination(events,{minSample=30}={}){const pairs=[];for(const e of events){const item=finite(e.itemScore),max=finite(e.itemMax),total=finite(e.packageScore),totalMax=finite(e.packageMax);if(item==null||!(max>0)||total==null||!(totalMax>0))continue;const itemP=item/max;const restMax=totalMax-max;const rest=total-item;if(!(restMax>0))continue;pairs.push([itemP,rest/restMax]);}if(pairs.length<minSample)return Object.freeze({value:null,sampleSize:pairs.length,state:pairs.length>=2?SUFFICIENCY.DESCRIPTIVE:SUFFICIENCY.INSUFFICIENT,method:'corrected_item_rest_pearson',methodVersion:ANALYTICS_METHOD_VERSION});const value=pearson(pairs);return Object.freeze({value,sampleSize:pairs.length,state:value==null?SUFFICIENCY.DESCRIPTIVE:(value<0?SUFFICIENCY.REVIEW:SUFFICIENCY.SUPPORTED),method:'corrected_item_rest_pearson',methodVersion:ANALYTICS_METHOD_VERSION});}
function distractors(events,optionOrder){const ids=(optionOrder||[]).map(o=>String(o.optionId));if(!ids.length)return Object.freeze({state:SUFFICIENCY.NOT_APPLICABLE,sampleSize:events.length,options:Object.freeze([]),methodVersion:ANALYTICS_METHOD_VERSION});const counts=new Map(ids.map(id=>[id,0]));let responses=0;for(const e of events){const id=e.selectedOptionId==null?null:String(e.selectedOptionId);if(id&&counts.has(id)){counts.set(id,counts.get(id)+1);responses++;}}const options=ids.map((id,ordinal)=>Object.freeze({optionId:id,ordinal,selected:counts.get(id),proportion:responses?counts.get(id)/responses:null,functioningState:responses<30?SUFFICIENCY.DESCRIPTIVE:(counts.get(id)===0?SUFFICIENCY.REVIEW:SUFFICIENCY.SUPPORTED)}));return Object.freeze({state:sampleState(responses),sampleSize:responses,options:Object.freeze(options),method:'stable_option_selection_frequency',methodVersion:ANALYTICS_METHOD_VERSION});}
function omissions(events){const omitted=events.filter(e=>e.omitted===true).length;return Object.freeze({count:omitted,proportion:events.length?omitted/events.length:null,sampleSize:events.length,state:sampleState(events.length),method:'explicit_or_blank_response_rate',methodVersion:ANALYTICS_METHOD_VERSION});}
function cronbachAlpha(matrix){if(!Array.isArray(matrix)||matrix.length<30)return null;const k=Math.max(...matrix.map(r=>Array.isArray(r)?r.length:0));if(k<2||matrix.some(r=>!Array.isArray(r)||r.length!==k))return null;const variances=[];for(let j=0;j<k;j++){const col=matrix.map(r=>finite(r[j])).filter(v=>v!=null);if(col.length!==matrix.length)return null;const m=mean(col);variances.push(col.reduce((s,v)=>s+(v-m)**2,0)/(col.length-1));}const totals=matrix.map(r=>r.reduce((s,v)=>s+Number(v),0)),mt=mean(totals),vt=totals.reduce((s,v)=>s+(v-mt)**2,0)/(totals.length-1);if(!(vt>0))return null;return k/(k-1)*(1-variances.reduce((a,b)=>a+b,0)/vt);}
function packageStatistics({scoreMatrix=[],constructSupportsInternalConsistency=false}={}){if(!constructSupportsInternalConsistency)return Object.freeze({state:SUFFICIENCY.NOT_APPLICABLE,reliability:null,method:'cronbach_alpha',methodVersion:ANALYTICS_METHOD_VERSION});const alpha=cronbachAlpha(scoreMatrix);if(alpha==null)return Object.freeze({state:scoreMatrix.length>=2?SUFFICIENCY.DESCRIPTIVE:SUFFICIENCY.INSUFFICIENT,reliability:null,sampleSize:scoreMatrix.length,method:'cronbach_alpha',methodVersion:ANALYTICS_METHOD_VERSION});return Object.freeze({state:SUFFICIENCY.SUPPORTED,reliability:alpha,sampleSize:scoreMatrix.length,method:'cronbach_alpha',methodVersion:ANALYTICS_METHOD_VERSION});}
function fairnessGate({authorizedGrouping=false,sampleSize=0,methodConfigured=false,privacyApproved=false}={}){if(!authorizedGrouping||!privacyApproved)return Object.freeze({state:SUFFICIENCY.NOT_APPLICABLE,claimAllowed:false});if(sampleSize<100)return Object.freeze({state:SUFFICIENCY.INSUFFICIENT,claimAllowed:false});if(!methodConfigured)return Object.freeze({state:SUFFICIENCY.NOT_APPLICABLE,claimAllowed:false});return Object.freeze({state:SUFFICIENCY.SUPPORTED,claimAllowed:true});}
function equatingGate({linkedDesign=false,sampleSize=0,methodConfigured=false}={}){if(!linkedDesign||!methodConfigured)return Object.freeze({state:SUFFICIENCY.CONTENT_ONLY,claimAllowed:false});if(sampleSize<100)return Object.freeze({state:SUFFICIENCY.INSUFFICIENT,claimAllowed:false});return Object.freeze({state:SUFFICIENCY.SUPPORTED,claimAllowed:true});}
function reviewSignals({facility:fac,discrimination:disc,distractors:dist,omissions:omit}={}){const signals=[];if(disc?.state===SUFFICIENCY.REVIEW||Number(disc?.value)<0)signals.push('LOW_OR_NEGATIVE_DISCRIMINATION');if(dist?.options?.some(o=>o.functioningState===SUFFICIENCY.REVIEW))signals.push('NONFUNCTIONING_DISTRACTOR_REVIEW');if(Number(omit?.proportion)>=0.25&&Number(omit?.sampleSize)>=30)signals.push('HIGH_OMISSION_REVIEW');if(fac?.value!=null&&Number(fac.sampleSize)>=30&&(fac.value<0.05||fac.value>0.98))signals.push('EXTREME_FACILITY_REVIEW');return Object.freeze(signals);}
function analyzeItem({events=[],optionOrder=[]}={}){const fac=facility(events),disc=discrimination(events),dist=distractors(events,optionOrder),omit=omissions(events),signals=reviewSignals({facility:fac,discrimination:disc,distractors:dist,omissions:omit});return Object.freeze({methodVersion:ANALYTICS_METHOD_VERSION,sampleSize:events.length,facility:fac,discrimination:disc,distractors:dist,omissions:omit,reviewSignals:signals,automaticAcademicMutation:false,requiresGovernedReview:signals.length>0});}
module.exports={mean,pearson,sampleState,facility,discrimination,distractors,omissions,cronbachAlpha,packageStatistics,fairnessGate,equatingGate,reviewSignals,analyzeItem};
