'use strict';
const D28_CONTRACT_VERSION='teaching.d28.operational-hardening.v1';
const D28_ITEM_ANALYTICS_POLICY_VERSION='teaching.d28.item-analytics.v1';
const D28_PPL_BUDGET_POLICY_VERSION='teaching.d28.ppl-budget.v1';
const D28_RETENTION_POLICY_VERSION='teaching.d28.retention.v1';
const D28_ROLLOUT_POLICY_VERSION='teaching.d28.rollout.v1';
const D28_TASK_IDS=Object.freeze([...Array.from({length:30},(_,i)=>`TCH-${String(599+i).padStart(4,'0')}`),'TCH-0678','TCH-0777','TCH-0867','TCH-0868','TCH-0869','TCH-0870','TCH-0899','TCH-0900','TCH-0916']);
const OPERATION_CLASSES=Object.freeze({CONTROLLER_TRANSITION:'CONTROLLER_TRANSITION',AI_EXECUTION:'AI_EXECUTION',VALIDATION:'VALIDATION',SCHEDULE:'SCHEDULE',ASSESSMENT:'ASSESSMENT',MARKING:'MARKING',MODERATION:'MODERATION',GRADEBOOK:'GRADEBOOK',AUTOSAVE:'AUTOSAVE',SECURITY:'SECURITY',RETENTION:'RETENTION',PPL:'PPL',ITEM_ANALYTICS:'ITEM_ANALYTICS',INTEGRATION:'INTEGRATION'});
const INTERACTION_LATENCY_BUDGETS_MS=Object.freeze({LIVE_CLASS_RESPONSE:12000,LIVE_RESPONSE_EVALUATION:12000,HINT_OR_REPRESENTATION_CHANGE:10000,CLASS_TRANSITION:5000,ASSESSMENT_AUTOSAVE:2500,ASSESSMENT_SUBMISSION_ACK:5000,BACKGROUND_PREPARATION:120000,BATCH_MARKING:120000});
// A complete PPL consists of Skeleton→Candidate→Pre-Lock Ready and may
// legitimately require validated model repairs. An 80k-token workspace cap
// could be consumed by 3 normal ~30k-token structured calls before the first
// Candidate. Keep strict per-workspace upper bounds, unlike an unmetered retry.
const DEFAULT_RETENTION_POLICY=Object.freeze({version:D28_RETENTION_POLICY_VERSION,operationalEventDays:90,qualitySampleReferenceDays:90,itemAnalyticsHistoryDays:730,rolloutHistoryDays:730,retentionAuditDays:2555,academicAuditHistory:'PRESERVE_PER_ACADEMIC_POLICY',gradebookHistory:'PRESERVE',evidenceHistory:'PRESERVE',assessmentDrafts:'DELETE_OR_SUPPRESS_WHEN_NO_LONGER_REQUIRED',boardHistory:'COURSE_POLICY_SCOPED',transcriptLikeClassContent:'COURSE_POLICY_SCOPED',studyPackArtifacts:'SUPPRESS_ON_DISMISSAL_OR_SOURCE_DELETION',cardReferences:'SUPPRESS_IF_SOURCE_CARD_UNAVAILABLE',protectedAssessmentContent:'SERVER_ONLY_UNTIL_RELEASE_POLICY_ALLOWS'});
const TRUSTED_BACKEND_ACTIONS=Object.freeze(new Set(['GRADE_FINALIZE','ASSESSMENT_PACKAGE_LOCK','COURSE_ACTIVATE','REQUEST_APPROVE','REQUEST_APPLY','PROGRESSION_FINALIZE','ATTENDANCE_CORRECT','GRADING_POLICY_LOCK','ASSESSMENT_TIMER_START','ASSESSMENT_TIMER_EXPIRE']));
const PROHIBITED_OPERATIONAL_KEYS=Object.freeze(new Set(['password','token','access_token','refresh_token','authorization','cookie','secret','api_key','apikey','service_role_key','database_url','prompt','raw_prompt','chain_of_thought','reasoning_trace','hidden_reasoning','student_response','response_text','answer_text','protected_payload','protected_marking_payload','hidden_validation_trace']));
function n(v,f,min,max){const p=Number(v);return Number.isFinite(p)?Math.max(min,Math.min(p,max)):f;}
function createD28PolicyConfig(env=process.env){return Object.freeze({contractVersion:D28_CONTRACT_VERSION,itemAnalytics:Object.freeze({version:D28_ITEM_ANALYTICS_POLICY_VERSION,descriptiveMinN:n(env.TEACHING_D28_ANALYTICS_DESCRIPTIVE_MIN_N,5,2,1000),discriminationMinN:n(env.TEACHING_D28_ANALYTICS_DISCRIMINATION_MIN_N,20,5,5000),distractorMinN:n(env.TEACHING_D28_ANALYTICS_DISTRACTOR_MIN_N,10,3,5000),difEnabled:String(env.TEACHING_D28_DIF_ENABLED||'').toLowerCase()==='true',difMinGroupN:n(env.TEACHING_D28_DIF_MIN_GROUP_N,50,20,10000)}),ppl:Object.freeze({version:D28_PPL_BUDGET_POLICY_VERSION,maxScheduledReviews:n(env.TEACHING_D28_PPL_MAX_SCHEDULED_REVIEWS,6,1,20),maxCandidatesPerWorkspace:n(env.TEACHING_D28_PPL_MAX_CANDIDATES,8,1,100),maxConcurrentExecutions:n(env.TEACHING_D28_PPL_MAX_CONCURRENCY,2,1,20),maxModelCalls:n(env.TEACHING_D28_PPL_MAX_MODEL_CALLS,12,1,100),maxTotalTokens:n(env.TEACHING_D28_PPL_MAX_TOKENS,240000,1000,2000000),maxEstimatedCostMicrounits:n(env.TEACHING_D28_PPL_MAX_COST_MICROUNITS,5000000,1000,1000000000)}),retention:DEFAULT_RETENTION_POLICY,rollout:Object.freeze({version:D28_ROLLOUT_POLICY_VERSION})});}
module.exports={D28_CONTRACT_VERSION,D28_ITEM_ANALYTICS_POLICY_VERSION,D28_PPL_BUDGET_POLICY_VERSION,D28_RETENTION_POLICY_VERSION,D28_ROLLOUT_POLICY_VERSION,D28_TASK_IDS,OPERATION_CLASSES,INTERACTION_LATENCY_BUDGETS_MS,DEFAULT_RETENTION_POLICY,TRUSTED_BACKEND_ACTIONS,PROHIBITED_OPERATIONAL_KEYS,createD28PolicyConfig};
