'use strict';
const crypto=require('node:crypto');
const {createD28Repository}=require('./repository');
const {createD28Service}=require('./service');
const {decidePplExecution,buildPplProvenance}=require('./ppl-governance');
const {resolveOwnerReleaseAuthorization}=require('../d31/owner-release-override');
const {redactOperationalMetadata}=require('./security');

function requireAnalyticsPseudonymSecret(env={}){const secret=String(env.TEACHING_D28_ANALYTICS_PSEUDONYM_SECRET||env.SESSION_SECRET||env.JWT_SECRET||'').trim();if(!secret){const e=new Error('D28 post-administration analytics requires a private server-side pseudonym secret.');e.code='TEACHING_D28_ANALYTICS_PSEUDONYM_SECRET_REQUIRED';throw e;}return secret;}
function stableOptionId(value){if(value==null)return null;if(typeof value==='string'||typeof value==='number')return String(value);if(typeof value!=='object')return null;const id=value.option_id??value.optionId??value.id??value.choice_id??value.choiceId;return id==null?null:String(id);}
function extractOptionOrder(contract,payload){const source=Array.isArray(contract?.stable_option_ids)?contract.stable_option_ids:Array.isArray(contract?.options)?contract.options:Array.isArray(payload?.options)?payload.options:[];return [...new Set(source.map(stableOptionId).filter(Boolean))];}
function extractSelectedOptionId(payload){if(!payload||typeof payload!=='object')return null;return payload.selectedOptionId??payload.selected_option_id??payload.optionId??payload.option_id??payload.answer_option_id??payload.choiceId??payload.choice_id??null;}

function createD28RuntimeService({query,randomUUID,env=process.env,logger=console,timers=globalThis}={}){
  if(typeof query!=='function'||typeof randomUUID!=='function')throw new TypeError('D28 runtime service requires query() and randomUUID().');
  const repository=createD28Repository({query,randomUUID});
  const base=createD28Service({repository,env});
  const active=new Map();
  const ownerRelease=resolveOwnerReleaseAuthorization(env);
  let analyticsRunning=false,analyticsTimer=null,retentionTimer=null;
  const json=v=>JSON.stringify(v??null);
  const now=()=>new Date();
  const pseudo=id=>crypto.createHmac('sha256',requireAnalyticsPseudonymSecret(env)).update(String(id)).digest('hex').slice(0,40);
  const prepMaterial=p=>p?.material_delta?.material===true||p?.material_delta?.changed===true||Object.keys(p?.material_delta||{}).some(k=>!['material','changed'].includes(k));
  const candidateAttempt=p=>['Candidate','Pre-Lock Ready'].includes(String(p?.maturity_target||''));

  async function assertReady(){requireAnalyticsPseudonymSecret(env);await repository.assertReady();const {rows}=await query("select to_regclass('teaching_runtime.d28_item_analytics_events') analytics_events");if(!rows?.[0]?.analytics_events){const e=new Error('D28 analytics event schema is not installed.');e.code='TEACHING_D28_ANALYTICS_EVENT_SCHEMA_MISSING';throw e;}return true;}
  async function pplState(workspaceId){const {rows}=await query(`select count(*) filter(where provenance->>'scheduledReview'='true')::int scheduled_reviews,count(*) filter(where provenance->>'candidateAttempt'='true')::int candidates,coalesce(sum(model_calls),0)::int model_calls,coalesce(sum(total_tokens),0)::bigint total_tokens,coalesce(sum(estimated_cost_microunits),0)::bigint estimated_cost,count(*) filter(where material_noop=true)::int material_noops from teaching_runtime.d28_ppl_budget_usage where workspace_id=$1`,[workspaceId]);const r=rows?.[0]||{};return Object.freeze({policyVersion:base.policies.ppl.version,scheduledReviews:Number(r.scheduled_reviews||0),candidates:Number(r.candidates||0),inFlight:Number(active.get(workspaceId)||0),modelCalls:Number(r.model_calls||0),totalTokens:Number(r.total_tokens||0),estimatedCostMicrounits:Number(r.estimated_cost||0),materialNoops:Number(r.material_noops||0)});}
  async function insertPplUsage({workspaceId,workspaceVersion,routePosture,decision,materialNoop=false,modelCalls=0,totalTokens=0,estimatedCostMicrounits=null,latencyMs=null,provenance={}}){await query(`insert into teaching_runtime.d28_ppl_budget_usage(usage_id,workspace_id,workspace_version,policy_version,route_posture,disposition,material_noop,model_calls,total_tokens,estimated_cost_microunits,latency_ms,provenance,created_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::jsonb,now())`,[randomUUID(),workspaceId,Number(workspaceVersion)||1,base.policies.ppl.version,routePosture||null,decision,materialNoop,Number(modelCalls||0),Number(totalTokens||0),estimatedCostMicrounits==null?null:Number(estimatedCostMicrounits),latencyMs==null?null:Number(latencyMs),json(redactOperationalMetadata(provenance))]);}
  async function governPplInvocation({invocation}={}){const p=invocation?.preparation;if(!p)return null;const workspaceId=String(p.workspace_ref),state=await pplState(workspaceId),routeQualified=invocation?.route_control?.qualificationStatus==='QUALIFIED'&&invocation?.route_control?.productionAuthorized===true,ownerReleaseAuthorized=ownerRelease.enabled===true,scheduledReview=p.repair_attempt!==1,candidate=candidateAttempt(p),materialChange=prepMaterial(p),decision=decidePplExecution({materialChange,unresolvedDefect:(p.finding_refs||[]).length>0,routePosture:p.route_posture,routeQualified,ownerReleaseAuthorized,currentStage:p.maturity_target==='Pre-Lock Ready'?'FINALIZATION':'EARLY',state,policy:base.policies.ppl,delta:{scheduledReviews:scheduledReview?1:0,candidates:candidate?1:0,modelCalls:2,inFlight:1}});const provenance=buildPplProvenance({triggerRef:p.correlation_id,authoritativeInputVersions:Object.entries(p.authoritative_input_bundle||{}).map(([k,v])=>`${k}:${typeof v==='object'?JSON.stringify(v):String(v)}`),workspaceVersion:p.workspace_version,artifactVersion:p.previous_artifact?.version||null,findingVersions:p.finding_refs||[],routePosture:p.route_posture,validationOutcome:'PRE_EXECUTION_GOVERNANCE'});await insertPplUsage({workspaceId,workspaceVersion:p.workspace_version,routePosture:p.route_posture,decision:decision.disposition,materialNoop:decision.disposition==='NO_OP_NO_MATERIAL_CHANGE',modelCalls:decision.modelCallAllowed?1:0,provenance:{...provenance,scheduledReview,repairAttempt:p.repair_attempt||0,candidateAttempt:candidate,maturity:p.maturity,maturityTarget:p.maturity_target,reviewPurpose:p.review_purpose,empiricallyQualified:routeQualified,authorizationBasis:decision.authorizationBasis||null,ownerReleaseException:decision.authorizationBasis==='D31_OWNER_RELEASE_EXCEPTION'}});if(!decision.modelCallAllowed){const e=new Error(`PPL model execution held by D28: ${decision.disposition}`);e.code=decision.code||`TEACHING_D28_PPL_${decision.disposition}`;e.status=503;throw e;}active.set(workspaceId,Number(active.get(workspaceId)||0)+1);return Object.freeze({workspaceId,workspaceVersion:p.workspace_version,routePosture:p.route_posture,preparation:p,decision});}
  async function completePplInvocation(lease,{modelMetadata={},validationOutcome=null,staleResult=false,finalHandoffRef=null}={}){if(!lease)return;const m=modelMetadata||{},provenance=buildPplProvenance({triggerRef:lease.preparation.correlation_id,authoritativeInputVersions:Object.entries(lease.preparation.authoritative_input_bundle||{}).map(([k,v])=>`${k}:${typeof v==='object'?JSON.stringify(v):String(v)}`),workspaceVersion:lease.workspaceVersion,artifactVersion:lease.preparation.previous_artifact?.version||null,findingVersions:lease.preparation.finding_refs||[],routePosture:lease.routePosture,provider:m.provider,model:m.modelIdentifier,routeKey:m.routeKey,retryCount:m.retryCount,fallbackDepth:m.fallbackDepth,validationOutcome,staleResult,totalTokens:m.totalTokens,estimatedCostMicrounits:m.estimatedCostMicrounits,latencyMs:m.latencyMs,finalHandoffRef});await insertPplUsage({workspaceId:lease.workspaceId,workspaceVersion:lease.workspaceVersion,routePosture:lease.routePosture,decision:'EXECUTION_COMPLETED',modelCalls:Math.max(0,Math.min(1,Number(m.validationRetryCount)||0)),totalTokens:m.totalTokens||0,estimatedCostMicrounits:m.estimatedCostMicrounits,latencyMs:m.latencyMs,provenance:{...provenance,completion:true}}).catch(e=>logger?.warn?.('[KIWI Teaching D28] PPL completion telemetry failed',{code:e?.code}));const n=Math.max(0,Number(active.get(lease.workspaceId)||1)-1);if(n)active.set(lease.workspaceId,n);else active.delete(lease.workspaceId);}
  function releasePplInvocation(lease){if(!lease)return;const n=Math.max(0,Number(active.get(lease.workspaceId)||1)-1);if(n)active.set(lease.workspaceId,n);else active.delete(lease.workspaceId);}

  const optionOrder=extractOptionOrder;
  const selected=extractSelectedOptionId;
  async function candidates(limit=1000){const {rows=[]}=await query(`with selected_runs as (select distinct on (r.assessment_result_id,r.package_item_id) r.assessment_result_id,r.package_item_id,r.marking_run_id from public.teaching_marking_runs r where r.package_item_id is not null and r.run_status='ACCEPTED' order by r.assessment_result_id,r.package_item_id,r.created_at desc),item_scores as (select sr.assessment_result_id,sr.package_item_id,sum(j.proposed_credit)::numeric item_score,sum(j.criterion_max_marks)::numeric item_max from selected_runs sr join public.teaching_marking_criterion_judgments j on j.marking_run_id=sr.marking_run_id group by sr.assessment_result_id,sr.package_item_id),latest_response as (select distinct on (r.assessment_attempt_id,r.package_item_id) r.assessment_attempt_id,r.package_item_id,r.renderer_payload,r.response_state,r.accepted_at from public.teaching_assessment_responses r order by r.assessment_attempt_id,r.package_item_id,r.response_version desc) select ar.assessment_result_id,ar.result_version,ar.assessment_id,ar.assessment_attempt_id,ar.assessment_package_id,ar.raw_earned_marks package_score,ar.raw_max_marks package_max,a.policy_version_at_start,a.started_at,a.finalized_at,p.version_no package_version,p.assessment_blueprint_id,b.version_no blueprint_version,pi.package_item_id,pi.candidate_version_id,pi.item_hash,pi.slot_id,pi.response_family,pi.intended_marks,cv.choice_set_contract,cv.public_item_payload,lr.renderer_payload,lr.response_state,lr.accepted_at,s.item_score,s.item_max from public.teaching_assessment_results ar join public.teaching_assessment_attempts a on a.assessment_attempt_id=ar.assessment_attempt_id join public.teaching_assessment_packages p on p.assessment_package_id=ar.assessment_package_id join public.teaching_assessment_blueprints b on b.assessment_blueprint_id=p.assessment_blueprint_id join public.teaching_assessment_package_items pi on pi.assessment_package_id=p.assessment_package_id join public.teaching_assessment_candidate_versions cv on cv.candidate_version_id=pi.candidate_version_id left join latest_response lr on lr.assessment_attempt_id=a.assessment_attempt_id and lr.package_item_id=pi.package_item_id left join item_scores s on s.assessment_result_id=ar.assessment_result_id and s.package_item_id=pi.package_item_id where ar.raw_earned_marks is not null and ar.raw_max_marks is not null and ar.marking_state in ('PROVISIONAL','MODERATED') and p.package_state='LOCKED' and a.attempt_state in ('SUBMITTED','EXPIRED') and pi.item_state='ACTIVE' order by coalesce(a.finalized_at,a.updated_at),pi.ordinal limit $1`,[Math.max(1,Math.min(5000,Number(limit)||1000))]);return rows;}
  async function upsertEvent(r){const order=optionOrder(r.choice_set_contract,r.public_item_payload),sel=selected(r.renderer_payload),score=r.item_score==null?null:Number(r.item_score),max=r.item_max==null?Number(r.intended_marks):Number(r.item_max),omitted=!r.renderer_payload||r.response_state==='OMITTED'||(sel==null&&['MCQ','MULTIPLE_CHOICE','SINGLE_CHOICE'].includes(String(r.response_family||'').toUpperCase())),admin=pseudo(r.assessment_attempt_id),key=`${admin}:${r.package_item_id}:${r.item_hash}`;const {rows=[]}=await query(`insert into teaching_runtime.d28_item_analytics_events(item_event_id,administration_key,assessment_result_id,assessment_result_version,assessment_id,assessment_package_id,package_version,assessment_blueprint_id,blueprint_version,package_item_id,candidate_version_id,item_hash,slot_id,response_family,locked_option_order,selected_option_id,item_score,item_max,total_score_without_item,package_score,package_max,omitted,administration_context,method_version,occurred_at,idempotency_key) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15::jsonb,$16,$17,$18,$19,$20,$21,$22,$23::jsonb,$24,$25,$26) on conflict(idempotency_key) do update set assessment_result_id=excluded.assessment_result_id,assessment_result_version=excluded.assessment_result_version,item_score=excluded.item_score,item_max=excluded.item_max,total_score_without_item=excluded.total_score_without_item,package_score=excluded.package_score,package_max=excluded.package_max,omitted=excluded.omitted,administration_context=excluded.administration_context,occurred_at=excluded.occurred_at where excluded.assessment_result_version>teaching_runtime.d28_item_analytics_events.assessment_result_version returning assessment_package_id`,[randomUUID(),admin,r.assessment_result_id,Math.max(1,Number(r.result_version)||1),r.assessment_id,r.assessment_package_id,Number(r.package_version),r.assessment_blueprint_id,Number(r.blueprint_version||0),r.package_item_id,r.candidate_version_id,r.item_hash,r.slot_id,r.response_family,json(order),sel==null?null:String(sel),score,max,score==null?null:Math.max(0,Number(r.package_score)-score),Number(r.package_score),Number(r.package_max),omitted,json({policyVersionAtStart:r.policy_version_at_start,startedAt:r.started_at,finalizedAt:r.finalized_at,lockedOptionOrder:true}),base.policies.itemAnalytics.version,r.finalized_at||r.accepted_at||now().toISOString(),key]);return rows?.[0]?.assessment_package_id||null;}
  async function analyzeStoredPackage(packageId){const {rows=[]}=await query(`select * from teaching_runtime.d28_item_analytics_events where assessment_package_id=$1 order by package_item_id,occurred_at,item_event_id`,[packageId]);if(!rows.length)return null;const byItem=new Map();for(const e of rows){const k=String(e.package_item_id);if(!byItem.has(k))byItem.set(k,[]);byItem.get(k).push(e);}const first=rows[0],items=[];for(const events of byItem.values()){const e=events[0],full=new Set(events.filter(x=>x.selected_option_id&&x.item_score!=null&&x.item_max!=null&&Number(x.item_score)>=Number(x.item_max)).map(x=>String(x.selected_option_id))),order=Array.isArray(e.locked_option_order)?e.locked_option_order:[];items.push({item:{assessmentPackageId:e.assessment_package_id,packageVersion:e.package_version,packageItemId:e.package_item_id,candidateVersionId:e.candidate_version_id,slotId:e.slot_id,assessmentBlueprintId:e.assessment_blueprint_id,blueprintVersion:e.blueprint_version,itemHash:e.item_hash,responseFamily:e.response_family,maxMarks:Number(e.item_max||1),choiceSet:order.map(id=>({optionId:String(id),keyed:full.has(String(id))}))},administrations:events.map(x=>({included:true,invalidated:false,itemScore:x.item_score,totalScoreWithoutItem:x.total_score_without_item,omitted:x.omitted,responseState:x.omitted?'OMITTED':'SAVED',rendererPayload:{selectedOptionId:x.selected_option_id}}))});}return base.runItemAnalytics({packageRef:{assessmentId:first.assessment_id,assessmentPackageId:first.assessment_package_id,packageVersion:first.package_version,assessmentBlueprintId:first.assessment_blueprint_id,blueprintVersion:first.blueprint_version},items,administrationContext:{source:'D17_D20_AUTHORITATIVE_POST_ADMIN',privacy:'PSEUDONYMOUS_MINIMIZED',resultVersionAware:true}});}
  async function runAnalyticsSweep(limit=1000){if(analyticsRunning)return Object.freeze({skipped:true,reason:'ALREADY_RUNNING'});analyticsRunning=true;try{const rows=await candidates(limit),changed=new Set();for(const r of rows){const packageId=await upsertEvent(r);if(packageId)changed.add(packageId);}let runs=0;for(const packageId of changed){await analyzeStoredPackage(packageId);runs++;}return Object.freeze({candidateRows:rows.length,changedPackages:changed.size,analyticsRuns:runs,automaticAcademicMutations:0});}finally{analyticsRunning=false;}}
  async function visibilityControls(studentId,artifactType,artifactIds=[]){const ids=[...new Set((artifactIds||[]).map(String).filter(Boolean))];if(!ids.length)return new Map();const {rows=[]}=await query(`select artifact_id,visibility_state,reason_code from teaching_runtime.d28_artifact_visibility_controls where student_id=$1 and artifact_type=$2 and artifact_id=any($3::text[])`,[String(studentId),String(artifactType).toUpperCase(),ids]);return new Map(rows.map(r=>[String(r.artifact_id),r]));}
  async function projectStudyReviewSet(user,reviewSet={}){const studentId=String(user?.id||'');if(!studentId)return reviewSet;const refs=Array.isArray(reviewSet.references)?reviewSet.references:[];for(const ref of refs){if(ref?.status!=='CARD_MISSING')continue;await repository.createVisibilityControl({studentId,artifactType:'CARD_REFERENCE',artifactId:String(ref.referenceId),courseId:ref.courseId||null,subjectId:ref.subjectId||null,visibilityState:'SOURCE_UNAVAILABLE',reasonCode:'SOURCE_CARD_UNAVAILABLE',sourceOwner:'KIWI_STUDY',sourceVersion:ref.referencedVersion||null}).catch(()=>{});}const controls=await visibilityControls(studentId,'CARD_REFERENCE',refs.map(r=>r.referenceId));const visible=refs.filter(ref=>ref?.status!=='CARD_MISSING'&&!controls.has(String(ref.referenceId)));return Object.freeze({...reviewSet,references:Object.freeze(visible),suppressedReferenceCount:refs.length-visible.length,sourceUnavailableSuppressed:true,academicHistoryDeleted:false});}
  async function projectClassroomSnapshot(user,classId,snapshot={}){const studentId=String(user?.id||'');if(!studentId||!snapshot?.studyNote)return snapshot;const controls=await visibilityControls(studentId,'STUDY_PACK',[String(classId)]);if(!controls.has(String(classId)))return snapshot;return Object.freeze({...snapshot,studyNote:null,studyPackAvailability:'SUPPRESSED',studyPackDismissalAffectsAcademicHistory:false});}
  async function runRetentionCleanup(){const p=base.policies.retention;const {rows}=await query(`with e as (delete from teaching_runtime.d28_operational_events where occurred_at<now()-($1::text||' days')::interval returning 1),q as (delete from teaching_runtime.d28_quality_sample_refs where created_at<now()-($2::text||' days')::interval returning 1),c as (delete from teaching_runtime.d28_ai_response_cache where expires_at<=now() returning 1) select (select count(*) from e)::int operational_events,(select count(*) from q)::int quality_refs,(select count(*) from c)::int cache_rows`,[String(p.operationalEventDays),String(p.qualitySampleReferenceDays)]);const counts=rows?.[0]||{};if(Object.values(counts).some(Number))await repository.recordRetentionAction({policyVersion:p.version,artifactType:'D28_OPERATIONAL_BATCH',artifactId:`retention:${now().toISOString().slice(0,10)}`,actionKind:'POLICY_EXPIRY_CLEANUP',preservedAcademicLineage:true,reasonCode:'D28_RETENTION_WINDOW_EXPIRED'});return Object.freeze({...counts,academicHistoryDeleted:false});}
  function start(){if(!analyticsTimer){analyticsTimer=timers.setInterval?.(()=>runAnalyticsSweep().catch(e=>logger?.warn?.('[KIWI Teaching D28] analytics sweep failed',{code:e?.code})),15*60*1000)||null;analyticsTimer?.unref?.();timers.setImmediate?.(()=>runAnalyticsSweep().catch(()=>null));}if(!retentionTimer){retentionTimer=timers.setInterval?.(()=>runRetentionCleanup().catch(e=>logger?.warn?.('[KIWI Teaching D28] retention cleanup failed',{code:e?.code})),24*60*60*1000)||null;retentionTimer?.unref?.();}return base.status();}
  function stop(){if(analyticsTimer&&timers.clearInterval)timers.clearInterval(analyticsTimer);if(retentionTimer&&timers.clearInterval)timers.clearInterval(retentionTimer);analyticsTimer=null;retentionTimer=null;active.clear();return true;}
  return Object.freeze({...base,repository,assertReady,governPplInvocation,completePplInvocation,releasePplInvocation,runAnalyticsSweep,runRetentionCleanup,visibilityControls,projectStudyReviewSet,projectClassroomSnapshot,start,stop});
}
module.exports={createD28RuntimeService,requireAnalyticsPseudonymSecret,extractOptionOrder,extractSelectedOptionId};
