'use strict';
const {boundedText}=require('./contracts');
const SECRET_KEY_RE=/(secret|password|passwd|token|authorization|cookie|api[_-]?key|credential|private[_-]?key|service[_-]?role)/i;
const REASONING_KEY_RE=/(chain[_-]?of[_-]?thought|hidden[_-]?reasoning|hidden[_-]?validation[_-]?trace|scratchpad|thinking[_-]?trace|reasoning[_-]?content)/i;
const PROTECTED_KEY_RE=/(protected[_-]?(payload|content|marking)|answer[_-]?key|mark[_-]?scheme|rubric[_-]?secret|solution[_-]?material)/i;
const INJECTION_RE=/(ignore\s+(all\s+)?(previous|prior|system)\s+instructions|system\s+prompt|developer\s+message|reveal\s+(the\s+)?(prompt|answer|secret)|act\s+as\s+(system|developer)|<\s*script|javascript\s*:|data\s*:\s*text\/html)/i;
const ALLOWED_UPLOAD_TYPES=Object.freeze(new Set(['application/pdf','text/plain','text/markdown','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.presentationml.presentation','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','image/png','image/jpeg','image/webp']));
function sanitizeFreeText(value,{max=5000}={}){if(typeof value!=='string')throw Object.assign(new TypeError('Free text must be a string.'),{code:'TEACHING_D28_FREE_TEXT_INVALID'});const text=value.normalize('NFKC').replace(/\u0000/g,'').trim();if(text.length>max)throw Object.assign(new Error('Free text exceeds the allowed length.'),{code:'TEACHING_D28_FREE_TEXT_TOO_LARGE',status:413});return text;}
function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function safeRenderedText(value,opts){return escapeHtml(sanitizeFreeText(String(value??''),opts));}
function sanitizeOperationalMetadata(value,{depth=0,maxDepth=5,maxArray=30,maxKeys=40}={}){if(depth>maxDepth)return '[TRUNCATED]';if(value==null||typeof value==='boolean'||typeof value==='number')return value;if(typeof value==='string')return boundedText(value,500);if(Array.isArray(value))return Object.freeze(value.slice(0,maxArray).map(v=>sanitizeOperationalMetadata(v,{depth:depth+1,maxDepth,maxArray,maxKeys})));if(typeof value!=='object')return boundedText(value,160);const out={};for(const key of Object.keys(value).slice(0,maxKeys)){if(SECRET_KEY_RE.test(key)||REASONING_KEY_RE.test(key)||PROTECTED_KEY_RE.test(key)){out[key]='[REDACTED]';continue;}out[key]=sanitizeOperationalMetadata(value[key],{depth:depth+1,maxDepth,maxArray,maxKeys});}return Object.freeze(out);}
function assertNoProtectedOperationalPayload(value){const seen=new Set();function walk(v,path='root'){if(v==null||typeof v!=='object')return;if(seen.has(v))return;seen.add(v);for(const [k,x] of Object.entries(v)){if(SECRET_KEY_RE.test(k)||REASONING_KEY_RE.test(k)||PROTECTED_KEY_RE.test(k)){const e=new Error(`Sensitive field cannot enter D28 operational telemetry: ${path}.${k}`);e.code='TEACHING_D28_SENSITIVE_TELEMETRY_REJECTED';throw e;}walk(x,`${path}.${k}`);}}walk(value);return true;}
function classifyMaterialText(value){const text=sanitizeFreeText(String(value??''),{max:200000});return Object.freeze({text,injectionLike:INJECTION_RE.test(text),trustedInstruction:false,contentBoundary:'UNTRUSTED_COURSE_MATERIAL'});}
function validateUploadMetadata({mimeType,sizeBytes,fileName}={}){const type=String(mimeType||'').toLowerCase().trim();const size=Number(sizeBytes);const name=String(fileName||'').trim();if(!ALLOWED_UPLOAD_TYPES.has(type))throw Object.assign(new Error('Unsupported Teaching material file type.'),{code:'TEACHING_D28_UPLOAD_TYPE_REJECTED',status:415});if(!Number.isFinite(size)||size<=0||size>25*1024*1024)throw Object.assign(new Error('Teaching material file exceeds the 25 MiB upload limit or has invalid size.'),{code:'TEACHING_D28_UPLOAD_SIZE_REJECTED',status:413});if(!name||name.length>180||/[\/\u0000]/.test(name))throw Object.assign(new Error('Teaching material filename is invalid.'),{code:'TEACHING_D28_UPLOAD_NAME_REJECTED',status:422});return Object.freeze({mimeType:type,sizeBytes:size,fileName:name});}
function assertTrustedBackend(actor,{operation='privileged academic operation'}={}){if(actor?.trustedBackend===true||actor?.is_admin===true||actor?.isAdmin===true||actor?.supportRole==='academic-admin')return true;const e=new Error(`${operation} requires a trusted backend/admin context.`);e.code='TEACHING_D28_TRUSTED_BACKEND_REQUIRED';e.status=403;throw e;}
function assertStudentScope(actor,studentId){if(!actor?.id||String(actor.id)!==String(studentId)){const e=new Error('Cross-student Teaching access is forbidden.');e.code='TEACHING_D28_STUDENT_SCOPE_FORBIDDEN';e.status=403;throw e;}return true;}
module.exports={SECRET_KEY_RE,REASONING_KEY_RE,PROTECTED_KEY_RE,INJECTION_RE,ALLOWED_UPLOAD_TYPES,sanitizeFreeText,escapeHtml,safeRenderedText,sanitizeOperationalMetadata,assertNoProtectedOperationalPayload,classifyMaterialText,validateUploadMetadata,assertTrustedBackend,assertStudentScope};
