'use strict';
const crypto=require('node:crypto');const{TRUSTED_BACKEND_ACTIONS,PROHIBITED_OPERATIONAL_KEYS}=require('./contracts');
const BADKEY=/^(?:on[a-z]+|html|script|srcdoc|dangerouslysetinnerhtml)$/i,BADURI=/^\s*(?:javascript|vbscript|data\s*:\s*text\/html)/i;
const ALLOWED=Object.freeze({'application/pdf':['.pdf'],'text/plain':['.txt','.md'],'text/markdown':['.md'],'application/vnd.openxmlformats-officedocument.wordprocessingml.document':['.docx']});
function clean(v,max=20000){return String(v==null?'':v).replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g,'').slice(0,max)}
function sanitizeStructuredContent(v,{depth=0,maxDepth=12}={}){if(depth>maxDepth)throw Object.assign(new Error('Structured content exceeds the safe nesting limit.'),{code:'TEACHING_D28_CONTENT_DEPTH_EXCEEDED'});if(v==null||typeof v==='boolean'||typeof v==='number')return v;if(typeof v==='string'){const t=clean(v);if(BADURI.test(t))throw Object.assign(new Error('Unsafe URI scheme is not allowed.'),{code:'TEACHING_D28_UNSAFE_URI'});return t}if(Array.isArray(v))return v.slice(0,500).map(x=>sanitizeStructuredContent(x,{depth:depth+1,maxDepth}));if(typeof v!=='object')return clean(v);const out={};for(const[k0,x]of Object.entries(v).slice(0,500)){const k=clean(k0,120);if(!k||BADKEY.test(k))throw Object.assign(new Error(`Unsafe structured-content field: ${k||'unknown'}`),{code:'TEACHING_D28_UNSAFE_RENDER_FIELD'});out[k]=sanitizeStructuredContent(x,{depth:depth+1,maxDepth})}return Object.freeze(out)}
function ext(name){const n=clean(name,255).replace(/[/\\]/g,'_').trim().toLowerCase(),i=n.lastIndexOf('.');return i>=0?n.slice(i):''}
function validateMaterialUpload({filename,mimeType,sizeBytes,bytes=null},{maxBytes=10485760}={}){const name=clean(filename,255).replace(/[/\\]/g,'_').trim(),mime=clean(mimeType,150).toLowerCase(),size=Number(sizeBytes);if(!name||!ALLOWED[mime])throw Object.assign(new Error('Unsupported Teaching material type.'),{code:'TEACHING_D28_UPLOAD_TYPE_FORBIDDEN'});if(!Number.isFinite(size)||size<0||size>maxBytes)throw Object.assign(new Error('Teaching material size is outside the allowed limit.'),{code:'TEACHING_D28_UPLOAD_SIZE_FORBIDDEN'});if(!ALLOWED[mime].includes(ext(name)))throw Object.assign(new Error('File extension does not match the declared material type.'),{code:'TEACHING_D28_UPLOAD_EXTENSION_MISMATCH'});if(Buffer.isBuffer(bytes)&&bytes.length>=4&&mime==='application/pdf'&&bytes.subarray(0,5).toString('ascii')!=='%PDF-')throw Object.assign(new Error('File signature does not match the declared material type.'),{code:'TEACHING_D28_UPLOAD_SIGNATURE_MISMATCH'});if(Buffer.isBuffer(bytes)&&bytes.length>=4&&mime.includes('wordprocessingml')&&!(bytes[0]===0x50&&bytes[1]===0x4b))throw Object.assign(new Error('File signature does not match the declared material type.'),{code:'TEACHING_D28_UPLOAD_SIGNATURE_MISMATCH'});return Object.freeze({filename:name,mimeType:mime,sizeBytes:size,extension:ext(name)})}
function assertTrustedBackendAction(action,actor={}){const a=String(action||'').toUpperCase();if(!TRUSTED_BACKEND_ACTIONS.has(a)||actor.trustedBackend===true||actor.serviceRole===true||actor.role==='teaching_domain_service')return true;const e=new Error(`${a} requires a trusted backend context.`);e.code='TEACHING_D28_TRUSTED_BACKEND_REQUIRED';e.status=403;throw e}
function redactOperationalMetadata(v,{depth=0}={}){if(depth>8)return'[TRUNCATED]';if(v==null||typeof v==='number'||typeof v==='boolean')return v;if(typeof v==='string')return clean(v,1000);if(Array.isArray(v))return v.slice(0,100).map(x=>redactOperationalMetadata(x,{depth:depth+1}));if(typeof v!=='object')return clean(v,1000);const out={};for(const[k,x]of Object.entries(v).slice(0,100)){const lower=k.toLowerCase();out[k]=PROHIBITED_OPERATIONAL_KEYS.has(lower)||/(?:secret|password|authorization|cookie|chain.?of.?thought|hidden.?reason)/i.test(lower)?'[REDACTED]':redactOperationalMetadata(x,{depth:depth+1})}return Object.freeze(out)}
function opaqueStudentRef(id,secret){return id&&secret?crypto.createHmac('sha256',String(secret)).update(String(id)).digest('hex').slice(0,32):null}
function assertContextMinimized({allowedClasses=[],prohibitedClasses=[],context={}}={}){const a=new Set(allowedClasses.map(String)),p=new Set(prohibitedClasses.map(String));for(const k of Object.keys(context||{})){if(p.has(k))throw Object.assign(new Error(`Prohibited context class ${k} supplied.`),{code:'TEACHING_D28_CONTEXT_PROHIBITED'});if(a.size&&!a.has(k))throw Object.assign(new Error(`Unapproved context class ${k} supplied.`),{code:'TEACHING_D28_CONTEXT_NOT_ALLOWED'})}return true}
function protectedAssessmentContentAllowed({released=false,purpose='STUDENT_QUERY'}={}){return released||['PACKAGE_VALIDATION','FORMAL_MARKING','MODERATION','POST_EXPOSURE_REPAIR'].includes(String(purpose))}
module.exports={sanitizeStructuredContent,validateMaterialUpload,assertTrustedBackendAction,redactOperationalMetadata,opaqueStudentRef,assertContextMinimized,protectedAssessmentContentAllowed};
