Warning: truncated output (original token count: 256077)
Total output lines: 23463

// ════════════════════════════════════════════════════════════════════════════
//  KIWI BACKEND — Living Ecosystem Edition
//  MIGRATED: Firebase/Firestore → PostgreSQL (Supabase pg Pool)
//  Generated by: build_supabase_migration.js
//  Source: index.js (14,907 lines)
//  Schema:  schema.sql (31 tables: 29 main + 2 sub-collection)
//  Notes:   migration_notes.md
//
//  Key changes from source:
//    - firebase-admin removed; pg Pool added (DATABASE_URL env var)
//    - randomUUID() from node:crypto replaces Firestore auto-IDs
//    - FieldValue.increment → dynamic "field = field + $N" SQL
//    - Firestore batch writes → single DELETE / withTransaction()
//    - merge:true → INSERT ... ON CONFLICT DO UPDATE SET
//    - Chunking loops (findByDeckIds, findByCards, findBySubject) → ANY($1)
//    - 12 inline firestore calls in route handlers replaced with db.* calls
//    - notification_preferences update uses JSONB `||` merge (Section 4.7)
// ════════════════════════════════════════════════════════════════════════════
// ════════════════════════════════════════════════════════════════════════════
'use strict';
require('dotenv').config();
const path = require('path');
const express = require('express');
const compression = require('compression');
const cors = require('cors');
const cookieParser = require('cookie-parser');
const jwt = require('jsonwebtoken');
const bcrypt = require('bcryptjs');
const crypto = require('crypto');
const cron = require('node-cron');
// Gemini provider transport is centralized in services/ai/gemini-transport.js
// ── PostgreSQL (Supabase) — replaces Firebase Admin SDK ──────────────────────
// Connection via DATABASE_URL env var; ssl required for Supabase
const { Pool } = require('pg');
const { randomUUID } = require('crypto');
const { WebSocketServer } = require('ws');
const { createEcosystemV2 } = require('./ecosystem_v2');
const { buildTreeState } = require('./services/tree-state');
const { createAIRuntime } = require('./services/ai/runtime');
const { isAIAvailabilityError } = require('./services/ai/errors');
const { createShadowIntelligence, createReckoningEngine, createQuestionBank, createQuestionValidator, createAISemanticReviewer, createPreparationService, isAdaptiveReckoningQuestion, DELIVERY_E_RECKONING_CONFIG } = require('./services/reckoning');
const { finalizeKsSnapshot } = require('./services/reckoning/ks-outcome');
const { createTeachingRouter } = require('./teaching-backend');
const { createTeachingD05RuntimePlatform } = require('./teaching/runtime');
const { createTeachingEventSubscriberRegistry } = require('./teaching/events/dispatcher');
const { TEACHING_EVENTS } = require('./teaching/events/names');
const { createPreparationRuntimeRepository } = require('./teaching/repositories/preparation-runtime');
const { createPreparationPublishedEventHandlers, registerPreparationPublishedEventSubscribers } = require('./teaching/preparation/subscribers');
const { requireRuntimeSecret, optionalRuntimeSecret } = require('./services/runtime-secrets');

const DATABASE_URL = requireRuntimeSecret(process.env, 'DATABASE_URL', ['KIWI_DATABASE_URL']);

const pool = new Pool({
  connectionString: DATABASE_URL,
  ssl: { rejectUnauthorized: false },
  max: 15, // Balanced for Supabase session-mode — headroom for concurrent requests
  min: 2,  // Keep warm connections ready
  idleTimeoutMillis: 20000,
  connectionTimeoutMillis: 5000, // Fail fast rather than stall user
  statement_timeout: 25000,      // Kill runaway queries
});

// Thin query wrapper — pool.query returns { rows, rowCount }
const query = (text, params) => pool.query(text, params);

// KIWI AI Orchestrator runtime. All registered AI tasks route through this layer.
const _aiRuntime = createAIRuntime({
  query,
  randomUUID,
  env: process.env,
  fetchImpl: globalThis.fetch,
  logger: console,
});
const ai = _aiRuntime.orchestrator;

// KIWI Teaching D05 runtime platform. This composes the accepted D02
// authoritative due-event runtime with D05 orchestration persistence and the
// durable committed-domain event outbox. It owns no academic-domain truth.
const teachingAIRun = ai.run.bind(ai);
const teachingPublishedEvents = createTeachingEventSubscriberRegistry();
const teachingPreparationPublishedRepository = createPreparationRuntimeRepository({
  query,
  withTransaction,
  randomUUID,
});
const teachingPreparationPublishedHandlers = createPreparationPublishedEventHandlers({
  repository: teachingPreparationPublishedRepository,
});
registerPreparationPublishedEventSubscribers(
  teachingPublishedEvents,
  teachingPreparationPublishedHandlers
);
teachingPublishedEvents.register(TEACHING_EVENTS.REQUEST_DECIDED, {
  subscriberId: 'd10-request-decision-audit',
  handle: async (event) => Object.freeze({ accepted: true, requestId: event.aggregateId }),
});
teachingPublishedEvents.register(TEACHING_EVENTS.COURSE_ACTIVATED, {
  subscriberId: 'd10-course-activation-followup',
  handle: async (event) => Object.freeze({ accepted: true, courseId: event.aggregateId }),
});
const teachingRuntimePlatform = createTeachingD05RuntimePlatform({
  query,
  withTransaction,
  randomUUID,
  aiRun: teachingAIRun,
  eventPublisher: (event) => teachingPublishedEvents.publish(event),
  env: process.env,
  logger: console,
});

// Reckoning V2 Delivery B runs intelligence in SHADOW only. This object may
// persist risk/evidence telemetry, but it has no authority over legacy
// question count, access, scoring, lockout, or pass/fail behavior.
const reckoningShadow = createShadowIntelligence({
  query,
  randomUUID,
  logger: console,
});

// Transaction helper
async function withTransaction(fn) {
  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    const result = await fn(client);
    await client.query('COMMIT');
    return result;
  } catch (e) {
    await client.query('ROLLBACK');
    throw e;
  } finally {
    client.release();
  }
}

// Delivery E: V2 preparation and execution use the same centralized AI
// orchestrator as the rest of KIWI. Gemini writes questions; KIWI owns the plan,
// validation, evidence state, scheduling and outcome.
const adaptiveSemanticReview = createAISemanticReviewer({
  aiRun: (taskId, input, context) => ai.run(taskId, input, context),
});
const adaptiveQuestionValidator = createQuestionValidator({
  semanticReview: adaptiveSemanticReview,
});
const adaptiveQuestionBank = createQuestionBank({
  aiRun: (taskId, input, context) => ai.run(taskId, input, context),
  validator: adaptiveQuestionValidator,
});
function getReckoningGenerationConcurrencyState() {
  const traffic = _aiRuntime.trafficController.snapshot();
  const rawRouteScheduler = _aiRuntime.routeScheduler.snapshot();
  const plan = _aiRuntime.orchestrator.plan('RECKONING_CBT');

  // Only pressure on routes that RECKONING_CBT is actually allowed to use may
  // reduce Reckoning family fan-out. Background/Lite traffic must not make an
  // otherwise healthy Flash Reckoning unnecessarily serialize itself.
  const eligibleRouteKeys = new Set();
  const eligibleModelIds = new Set();
  for (const candidate of plan.candidates || []) {
    const slots = candidate.eligibleProjectSlots || [];
    if (!slots.length) continue;
    eligibleModelIds.add(candidate.modelId);
    for (const slotId of slots) {
      eligibleRouteKeys.add(`${slotId}::${candidate.modelId}`);
    }
  }

  const eligibleRoutes = (rawRouteScheduler.routes || []).filter(
    (route) => eligibleRouteKeys.has(`${route.projectSlot}::${route.modelId}`)
  );
  const eligibleModels = (rawRouteScheduler.models || []).filter(
    (model) => eligibleModelIds.has(model.modelId)
  );
  const maxInFlightPerRoute = Math.max(
    1,
    Number(rawRouteScheduler.maxInFlightPerRoute) || 1
  );
  const busyRouteCount = eligibleRoutes.filter(
    (route) => (Number(route.inFlight) || 0) >= maxInFlightPerRoute
  ).length;
  const pacedModelCount = eligibleModels.filter(
    (model) => (Number(model.waitMs) || 0) > 0
  ).length;

  const routeScheduler = Object.freeze({
    ...rawRouteScheduler,
    routes: Object.freeze(eligibleRoutes),
    models: Object.freeze(eligibleModels),
    eligibleRouteCount: eligibleRouteKeys.size,
    eligibleModelCount: eligibleModelIds.size,
  });

  return Object.freeze({
    ...traffic,
    routeScheduler,
    busyRouteCount,
    pacedModelCount,
    eligibleRouteCount: eligibleRouteKeys.size,
    eligibleModelCount: eligibleModelIds.size,
  });
}

const adaptivePreparationService = createPreparationService({
  questionBank: adaptiveQuestionBank,
  randomUUID,
  // Reckoning family generation now reacts to both global admission pressure
  // and Delivery A's route-level pacing/leases.
  getConcurrencyState: getReckoningGenerationConcurrencyState,
});

async function buildAdaptivePreparationInput({ session, userId }) {
  const subjectId = session?.subject_id;
  if (!subjectId) throw new Error('Reckoning subject is missing.');

  const decks = await db.decks.findBySubject(userId, subjectId);
  const deckIds = decks.map((deck) => deck.id);
  if (!deckIds.length) throw new Error('This subject has no decks for Reckoning.');

  const deckSet = new Set(deckIds);
  const allCards = await db.cards.findAllForUser(userId);
  const cards = allCards.filter((card) => {
    if (!deckSet.has(card.deck_id)) return false;
    const front = String(card.front_content || card.front || '').trim();
    const back = String(card.back_content || card.back || '').trim();
    return front.length >= 5 && back.length >= 5;
  });
  if (!cards.length) {
    throw new Error('Reckoning needs complete study cards before it can start.');
  }

  const cardIds = cards.map((card) => card.id);
  const states = await batchInitializeSeedlingStates(userId, cardIds);
  const activeBubbles = await db.masteryGoals.findActive(userId).catch(() => []);
  const bubbleCardIds = activeBubbles.flatMap((goal) => goal.card_ids || []);
  const nowMs = Date.now();
  const metricsByCardId = await reckoningShadow.loadMetrics(userId, cards, nowMs);
  const subjectExamDate = await getSubjectExamDate(userId, subjectId).catch(() => null);
  const examMs = subjectExamDate ? new Date(subjectExamDate).getTime() : NaN;
  const daysToExam = Number.isFinite(examMs)
    ? Math.floor((examMs - nowMs) / 86400000)
    : null;

  return {
    cards,
    states,
    bubbleCardIds,
    metricsByCardId,
    deckIds,
    context: { daysToExam },
    now: new Date(nowMs),
  };
}

const adaptiveReckoningEngine = createReckoningEngine({
  query,
  transaction: withTransaction,
  randomUUID,
  preparationService: adaptivePreparationService,
  preparationInputProvider: buildAdaptivePreparationInput,
  outcomeHandler: finalizeAdaptiveReckoningOutcome,
  getConcurrencyState: getReckoningGenerationConcurrencyState,
  logger: console,
});

// One in-process job per Reckoning. The database preparation claim remains the
// cross-instance authority, while this map prevents duplicate local launches.
const _reckoningPreparationJobs = new Map();
function _scheduleReckoningPreparation(reckoningId, userId) {
  const key = `${reckoningId}:${userId}`;
  const existing = _reckoningPreparationJobs.get(key);
  if (existing) return existing;

  const job = Promise.resolve()
    .then(() => adaptiveReckoningEngine.start({ reckoningId, userId }))
    .catch((error) => {
      console.warn('[KIWI RECKONING] background preparation failed', {
        reckoningId,
        userId,
        code: error?.code || null,
        message: String(error?.message || error).slice(0, 500),
      });
      throw error;
    })
    .finally(() => {
      _reckoningPreparationJobs.delete(key);
    });

  // The caller can attach its own completion handling; this catch prevents a
  // fire-and-forget trigger from becoming an unhandled rejection.
  job.catch(() => null);
  _reckoningPreparationJobs.set(key, job);
  return job;
}

function _runReckoningPreparationRecoverySweep() {
  if (
    !adaptiveReckoningEngine ||
    typeof adaptiveReckoningEngine.resumePendingPreparations !== 'function'
  ) {
    return;
  }
  Promise.resolve(
    adaptiveReckoningEngine.resumePendingPreparations({ limit: 2 })
  )
    .then((result) => {
      if (result?.launched > 0) {
        console.log('[KIWI RECKONING] durable recovery sweep launched', result);
      }
    })
    .catch((error) => {
      console.warn(
        '[KIWI RECKONING] durable recovery sweep failed:',
        String(error?.message || error).slice(0, 500)
      );
    });
}

// Start after normal boot/schema warm-up, then periodically reclaim only stale
// PREPARING work. Active preparation claims are excluded by the store query.
const _reckoningRecoveryFirstTimer = setTimeout(
  _runReckoningPreparationRecoverySweep,
  60000
);
_reckoningRecoveryFirstTimer.unref?.();
const _reckoningRecoveryInterval = setInterval(
  _runReckoningPreparationRecoverySweep,
  30000
);
_reckoningRecoveryInterval.unref?.();

// Ecosystem V2 owns session quality, permanent growth, fruit, vitality, streaks,
// and their idempotent reward ledger. Other services consume its committed result.
const ecosystemV2 = createEcosystemV2({ pool, query, randomUUID });

// ── Dynamic SQL builders ─────────────────────────────────────────────────────
// Used for tables where the route handler passes an arbitrary data spread.
// This is a structural necessity of SQL (explicit columns required) and is NOT
// a business-logic change. Preserves the exact Firestore .set(payload) semantics.

function _buildInsert(table, obj) {
  const keys = Object.keys(obj);
  const cols = keys.map(k => `"${k}"`).join(', ');
  const placeholders = keys.map((_, i) => `$${i + 1}`).join(', ');
  const vals = keys.map(k => {
    const v = obj[k];
    if (v !== null && typeof v === 'object' && !(v instanceof Date)) {
      return JSON.stringify(v);
    }
    return v;
  });
  return { text: `INSERT INTO ${table} (${cols}) VALUES (${placeholders})`, values: vals };
}

function _buildUpdate(table, whereCol, whereVal, obj, userId = null) {
  // Detects { increment: N } values and emits `"field" = "field" + $N` clauses.
  // This allows any db.X.update() call to receive FieldValue.increment-style objects.
  const setClauses = [];
  const vals = [];
  for (const [k, v] of Object.entries(obj)) {
    if (v !== null && typeof v === 'object' && !(v instanceof Date) && !Array.isArray(v) && v.increment !== undefined) {
      setClauses.push(`"${k}" = "${k}" + $${vals.length + 1}`);
      vals.push(v.increment);
    } else {
      const val = (v !== null && typeof v === 'object' && !(v instanceof Date))
        ? JSON.stringify(v) : v;
      setClauses.push(`"${k}" = $${vals.length + 1}`);
      vals.push(val);
    }
  }
  vals.push(whereVal);
  let whereClause = `WHERE "${whereCol}" = $${vals.length}`;
  // F-04 FIX: optional user_id scoping prevents IDOR on all update paths
  if (userId !== undefined && userId !== null) {
    vals.push(userId);
    whereClause += ` AND "user_id" = $${vals.length}`;
  }
  return {
    text: `UPDATE ${table} SET ${setClauses.join(', ')} ${whereClause}`,
    values: vals,
  };
}

function _buildUpsert(table, conflictCols, obj) {
  const keys = Object.keys(obj);
  const cols = keys.map(k => `"${k}"`).join(', ');
  const placeholders = keys.map((_, i) => `$${i + 1}`).join(', ');
  const conflict = Array.isArray(conflictCols) ? conflictCols.join(', ') : conflictCols;
  const updateCols = keys.filter(k => !conflictCols.includes(k));
  const setClauses = updateCols.map(k => `"${k}" = EXCLUDED."${k}"`).join(', ');
  const vals = keys.map(k => {
    const v = obj[k];
    if (v !== null && typeof v === 'object' && !(v instanceof Date)) {
      return JSON.stringify(v);
    }
    return v;
  });
  return {
    text: `INSERT INTO ${table} (${cols}) VALUES (${placeholders}) ON CONFLICT (${conflict}) DO UPDATE SET ${setClauses}`,
    values: vals,
  };
}

// ── INCREMENT builder — replaces FieldValue.increment ────────────────────────
// Detects { increment: N } objects in update payloads and emits
// "field" = "field" + $N SQL. Used in userStats.update and sessions.update.
function _buildIncrementUpdate(table, whereCol, whereVal, data) {
  const setClauses = [];
  const values = [];
  for (const [k, v] of Object.entries(data)) {
    if (v !== null && typeof v === 'object' && !(v instanceof Date) && !Array.isArray(v) && v.increment !== undefined) {
      setClauses.push(`"${k}" = "${k}" + $${values.length + 1}`);
      values.push(v.increment);
    } else {
      setClauses.push(`"${k}" = $${values.length + 1}`);
      const val = (v !== null && typeof v === 'object' && !Array.isArray(v) && !(v instanceof Date))
        ? JSON.stringify(v) : v;
      values.push(val);
    }
  }
  setClauses.push(`"updated_at" = NOW()`);
  values.push(whereVal);
  return {
    text: `UPDATE ${table} SET ${setClauses.join(', ')} WHERE "${whereCol}" = $${values.length} RETURNING *`,
    values,
    hasIncrements: data && Object.values(data).some(v =>
      v !== null && typeof v === 'object' && !(v instanceof Date) && !Array.isArray(v) && v.increment !== undefined
    ),
  };
}

// ════════════════════════════════════════════════════════════════════════════
//  INLINE DB LAYER (replaces firestore-db)

// ════════════════════════════════════════════════════════════════════════════

// ── KS Batch Queue ────────────────────────────────────────────────────────────
// Replaces per-review recomputeAndStoreCardState fire-and-forget.
// Cards accumulate here; a 60s cron drains them in a single pass.
const _ksQueue = new Map(); // key: `${userId}:${cardId}`
function queueKSRecompute(userId, cardId) {
  if (_ksQueue.size < 50000) _ksQueue.set(`${userId}:${cardId}`, { userId, cardId }); // F-11 FIX: cap unbounded growth
  // KS-CACHE: Best-effort invalidation — the 30s TTL means stale data is short-lived anyway
  invalidateKSCache(userId, null);
}

// ── Session Pagination Store ──────────────────────────────────────────────────
// Holds the full normalised card queue per active session.
// Cleared after 4 h (well beyond any realistic session length).
const _sessionQueues = new Map(); // sessionId → normalizedCards[]
const PAGE_SIZE = 20;

// ── WebSocket client registry ─────────────────────────────────────────────────
const _wsClients = new Map(); // userId (string) → Set<WebSocket>
function wsSend(userId, event, data) {
  const clients = _wsClients.get(String(userId));
  if (!clients) return;
  const msg = JSON.stringify({ event, data, ts: Date.now() });
  for (const ws of clients) {
    try { if (ws.readyState === 1) ws.send(msg); } catch (_) {}
  }
}

// ── In-memory job store — enables GET /api/jobs/:id polling fallback (Bug 2 fix) ──
// Jobs are ephemeral (WS-first); this store is the safety net when WS is slow/down.
// TTL: 10 min per entry. Cleaned up lazily on each write.
const _jobStore = new Map(); // jobId → { status, type, result?, error?, expiresAt }
function _jobStoreSet(jobId, data) {
  const expiresAt = Date.now() + 600_000; // 10-minute TTL
  _jobStore.set(jobId, { ...data, expiresAt });
  // Lazy cleanup of expired entries
  for (const [k, v] of _jobStore) {
    if (v.expiresAt < Date.now()) _jobStore.delete(k);
  }
  // ROOT FIX: Persist to PostgreSQL so polls survive server restarts / multi-instance deployments.
  // In-memory _jobStore is the fast path; DB is the durable fallback.
  query(
    `INSERT INTO background_jobs (id, status, type, result, error, expires_at)
     VALUES ($1, $2, $3, $4::jsonb, $5, NOW() + INTERVAL '10 minutes')
     ON CONFLICT (id) DO UPDATE SET
       status     = EXCLUDED.status,
       result     = EXCLUDED.result,
       error      = EXCLUDED.error,
       expires_at = EXCLUDED.expires_at`,
    [jobId, data.status, data.type,
     data.result ? JSON.stringify(data.result) : null,
     data.error || null]
  ).catch(() => {}); // fire-and-forget — never block the caller
}

// ════════════════════════════════════════════════════════════════════════════
//  INLINE DB LAYER (replaces firestore-db — migrated to PostgreSQL/pg)

// ════════════════════════════════════════════════════════════════════════════
// PostgreSQL NUMERIC columns arrive through node-postgres as strings by default.
// Normalize Mastery Goal rows at the data-access boundary so every Bubble
// service consumes numbers consistently rather than repeatedly coercing fields.
function _normalizeMasteryGoalRow(row) {
  if (!row) return row;
  const normalized = { ...row };
  const numericFields = [
    'current_ks',
    'target_ks',
    'required_ks_per_day',
    'actual_ks_velocity',
    'trajectory_gap',
    'final_ks_at_deadline',
  ];
  for (const field of numericFields) {
    if (normalized[field] == null || normalized[field] === '') continue;
    const value = Number(normalized[field]);
    if (Number.isFinite(value)) normalized[field] = value;
  }
  return normalized;
}

const db = {
// ── users ───────────────────────────────────────────────────────────────────
users: {
async findById(id) {
  const { rows } = await query('SELECT * FROM users WHERE id = $1 LIMIT 1', [id]);
  return rows[0] || null;
},
async findByUsernameOrEmail(username, email) {
  const { rows } = await query(
    'SELECT * FROM users WHERE username = $1 OR email = $2 LIMIT 1',
    [username, email]
  );
  return rows[0] || null;
},
async findByEmail(email) {
  const { rows } = await query(
    'SELECT * FROM users WHERE LOWER(email) = LOWER($1) LIMIT 1',
    [email]
  );
  return rows[0] || null;
},
async findByEmailWithStats(email) {
  const { rows } = await query('SELECT * FROM users WHERE email = $1 LIMIT 1', [email]);
  if (!rows[0]) return null;
  const user = rows[0];
  const stats = await db.userStats.get(user.id);
  return { ...user, stats };
},
async create(data) {
  const id = data.id || randomUUID();
  const now = new Date();
  const payload = { ...data, id, created_at: now, updated_at: now };
  const q = _buildInsert('users', payload);
  await query(q.text, q.values);
  return { id, ...payload };
},
async update(id, data) {
  // Fix #38: eliminate post-write re-fetch; return computed payload
  const payload = { ...data, updated_at: new Date() };
  const q = _buildUpdate('users', 'id', id, payload);
  await query(q.text, q.values);
  return { id, ...payload };
},
async delete(id) {
  await query('DELETE FROM users WHERE id = $1', [id]);
  return true;
},
async findAll() {
  const { rows } = await query('SELECT * FROM users ORDER BY created_at DESC');
  return rows;
},
},
// ── user_stats ──────────────────────────────────────────────────────────────
userStats: {
async get(userId) {
  const { rows } = await query('SELECT * FROM user_stats WHERE user_id = $1', [userId]);
  return rows[0] ? { userId: rows[0].user_id, ...rows[0] } : null;
},
async create(userId) {
  const payload = {
    user_id: userId,
    total_xp: 0,
    current_level: 1,
    xp_in_current_level: 0,
    current_streak: 0,
    longest_streak: 0,
    streak_grace_used: false,
    tree_health: 100,
    tree_stage: 1,
    total_cards_reviewed: 0,
    total_cards_mastered: 0,
    total_study_minutes: 0,
    total_sessions_completed: 0,
    total_exams_completed: 0,
    last_study_date: null,
    seedlings_balance: 0,
    streak_shields_held: 0,
    streak_shields_earned: 0,
    knowledge_score_global: 0,
    last_login_at: null,
    created_at: new Date(),
  };
  await query(
    `INSERT INTO user_stats (user_id, total_xp, current_level, xp_in_current_level,
      current_streak, longest_streak, streak_grace_used, tree_health, tree_stage,
      total_cards_reviewed, total_cards_mastered, total_study_minutes,
      total_sessions_completed, total_exams_completed, last_study_date,
      seedlings_balance, streak_shields_held, streak_shields_earned,
      knowledge_score_global, last_login_at, created_at)
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21)`,
    [userId, 0, 1, 0, 0, 0, false, 100, 1, 0, 0, 0, 0, 0, null, 0, 0, 0, 0, null, payload.created_at]
  );
  return payload;
},
async update(userId, data) {
  // Fix #38: conditional RETURNING * — only re-fetch when { increment: N } is used
  const built = _buildIncrementUpdate('user_stats', 'user_id', userId, data);
  const { rows } = await query(built.text, built.values);
  return rows[0] ? { userId, ...rows[0] } : { userId, ...data };
},
async leaderboard(limit = 20, offset = 0) {
  const { rows } = await query(
    'SELECT * FROM user_stats ORDER BY total_xp DESC LIMIT $1 OFFSET $2',
    [limit, offset]
  );
  return rows.map(r => ({ userId: r.user_id, ...r }));
},
async countWithMoreXP(totalXP) {
  const { rows } = await query(
    'SELECT COUNT(*) AS count FROM user_stats WHERE total_xp > $1',
    [totalXP]
  );
  return parseInt(rows[0]?.count || '0', 10);
},
async findAll() {
  const { rows } = await query('SELECT * FROM user_stats');
  return rows.map(r => ({ userId: r.user_id, ...r }));
},
},
// ── refresh_tokens ──────────────────────────────────────────────────────────
refreshTokens: {
async create(userId, tokenHash, expiresAt) {
  await query(
    `INSERT INTO refresh_tokens (token_hash, user_id, expires_at, created_at)
     VALUES ($1, $2, $3, NOW())
     ON CONFLICT (token_hash) DO UPDATE SET
       user_id = EXCLUDED.user_id,
       expires_at = EXCLUDED.expires_at,
       created_at = NOW()`,
    [tokenHash, userId, expiresAt]
  );
  return true;
},
async findByHash(hash, userId) {
  const { rows } = await query(
    'SELECT * FROM refresh_tokens WHERE token_hash = $1 AND user_id = $2 LIMIT 1',
    [hash, userId]
  );
  return rows[0] || null;
},
async deleteByHash(hash) {
  await query('DELETE FROM refresh_tokens WHERE token_hash = $1', [hash]);
  return true;
},
async deleteByUserId(userId) {
  // Firestore batch → single DELETE
  await query('DELETE FROM refresh_tokens WHERE user_id = $1', [userId]);
  return true;
},
},
// ── subjects ───────────────────────────────────────────────────────────────
subjects: {
async findById(id) {
  const { rows } = await query('SELECT * FROM subjects WHERE id = $1 LIMIT 1', [id]);
  return rows[0] || null;
},
async findManyWithDecks(userId) {
  const { rows: subjects } = await query(
    'SELECT * FROM subjects WHERE user_id = $1 ORDER BY created_at ASC',
    [userId]
  );
  const { rows: decks } = await query(
    'SELECT * FROM decks WHERE user_id = $1',
    [userId]
  );
  return subjects.map((s) => {
    const sDecks = decks.filter((d) => d.subject_id === s.id);
    // BUGFIX-2: Some older subjects were stored with JSON-encoded name fields
    // e.g. name = '{"name":"Physics","color":"#2d6a4f","icon":"📚"}'
    // Normalize here so every caller gets a plain string name.
    let normalizedName = s.name || '';
    if (normalizedName.trim().startsWith('{')) {
      try {
        const parsed = JSON.parse(normalizedName);
        if (parsed && parsed.name) normalizedName = parsed.name;
      } catch (_) {}
    }
    return {
      ...s,
      name: normalizedName,
      deck_count: sDecks.length,
      total_cards: sDecks.reduce((sum, d) => sum + (d.card_count || 0), 0),
      decks: sDecks,
    };
  });
},
async getCorpusForUser(userId, subjectId) {
  const { rows: subjectRows } = await query('SELECT * FROM subjects WHERE id = $1 AND user_id = $2 LIMIT 1', [subjectId, userId]);
  const subject = subjectRows[0];
  if (!subject) return null;
  const { rows: decks } = await query('SELECT * FROM decks WHERE user_id = $1 AND subject_id = $2 ORDER BY created_at ASC,id ASC', [userId, subjectId]);
  const deckIds = decks.map((deck) => deck.id);
  const { rows: cards } = deckIds.length
    ? await query('SELECT * FROM cards WHERE user_id = $1 AND deck_id = ANY($2::text[]) ORDER BY created_at ASC,id ASC', [userId, deckIds])
    : { rows: [] };
  return { subject, decks, cards };
},
async create(userId, data) {
  const id = randomUUID();
  // Use an explicit column list so the query never references columns that
  // may not exist in the migrated schema (e.g. updated_at).
  // DB columns are "color" and "icon" (not color_hex / emoji — confirmed from live logs)
  const cols = ['id', 'user_id', 'name', 'color', 'icon', 'created_at'];
  const colorVal = data.color || data.color_hex || '#4F46E5';
  const iconVal  = data.icon  || data.emoji      || '📚';
  const vals = [id, userId, data.name, colorVal, iconVal, new Date()];
  if (data.exam_date != null) { cols.push('exam_date'); vals.push(data.exam_date); }
  if (data.test_date != null) { cols.push('test_date'); vals.push(data.test_date); }
  const placeholders = vals.map((_, i) => `$${i + 1}`).join(', ');
  const { rows: [subject] } = await query(
    `INSERT INTO subjects (${cols.join(', ')}) VALUES (${placeholders}) RETURNING *`,
    vals
  );
  return subject || { id, user_id: userId, ...data };
},
async update(userId, id, data) {
  // Fix #38: eliminate post-write re-fetch
  const payload = { ...data, updated_at: new Date() };
  const q = _buildUpdate('subjects', 'id', id, payload, userId);
  await query(q.text, q.values);
  return { id, ...payload };
},
async delete(userId, id) {
  // Cascade: wipe dependent rows before removing the subject itself
  await query('DELETE FROM card_states WHERE user_id = $1 AND card_id IN (SELECT id FROM cards WHERE user_id = $1 AND deck_id IN (SELECT id FROM decks WHERE user_id = $1 AND subject_id = $2))', [userId, id]);
  await query('DELETE FROM knowledge_scores WHERE user_id = $1 AND subject_id = $2', [userId, id]);
  await query('DELETE FROM exam_questions WHERE user_id = $1 AND exam_session_id IN (SELECT id FROM exam_sessions WHERE user_id = $1 AND subject_id = $2)', [userId, id]);
  await query('DELETE FROM exam_sessions WHERE user_id = $1 AND subject_id = $2', [userId, id]);
  await query('DELETE FROM cards WHERE user_id = $1 AND deck_id IN (SELECT id FROM decks WHERE user_id = $1 AND subject_id = $2)', [userId, id]);
  await query('DELETE FROM decks WHERE user_id = $1 AND subject_id = $2', [userId, id]);
  await query('DELETE FROM subjects WHERE id = $1 AND user_id = $2', [id, userId]);
  return true;
},
},
// ── topics ──────────────────────────────────────────────────────────────────
topics: {
async findMany(userId, subjectId) {
  const { rows } = await query(
    'SELECT * FROM topics WHERE user_id = $1 AND subject_id = $2',
    [userId, subjectId]
  );
  return rows;
},
async create(userId, subjectId, name) {
  const id = randomUUID();
  const payload = { user_id: userId, subject_id: subjectId, name, created_at: new Date() };
  await query(
    'INSERT INTO topics (id, user_id, subject_id, name, created_at) VALUES ($1,$2,$3,$4,$5)',
    [id, userId, subjectId, name, payload.created_at]
  );
  return { id, ...payload };
},
},
// ── decks ───────────────────────────────────────────────────────────────────
decks: {
async findMany(userId, filters = {}) {
  let sql = 'SELECT * FROM decks WHERE user_id = $1';
  const vals = [userId];
  if (filters.subject_id) { sql += ` AND subject_id = $${vals.length + 1}`; vals.push(filters.subject_id); }
  if (filters.topic_id)   { sql += ` AND topic_id = $${vals.length + 1}`;   vals.push(filters.topic_id); }
  const { rows } = await query(sql, vals);
  return { decks: rows, total: rows.length };
},
async create(userId, data) {
  const id = randomUUID();
  // Explicit column list avoids referencing columns absent from the migrated schema.
  const cols = ['id', 'user_id', 'name', 'created_at'];
  const vals = [id, userId, data.name, new Date()];
  if (data.subject_id != null) { cols.push('subject_id'); vals.push(data.subject_id); }
  if (data.topic_id   != null) { cols.push('topic_id');   vals.push(data.topic_id);   }
  const placeholders = vals.map((_, i) => `$${i + 1}`).join(', ');
  const { rows: [deck] } = await query(
    `INSERT INTO decks (${cols.join(', ')}) VALUES (${placeholders}) RETURNING *`,
    vals
  );
  return deck || { id, user_id: userId, ...data };
},
async findByIdFull(userId, id) {
  const { rows: [deck] } = await query(
    'SELECT * FROM decks WHERE id = $1 AND user_id = $2 LIMIT 1',
    [id, userId]
  );
  if (!deck) return null;
  const { rows: cards } = await query(
    'SELECT * FROM cards WHERE deck_id = $1',
    [id]
  );
  deck.cards = cards;
  return deck;
},
async findById(userId, id) {
  const { rows } = await query(
    'SELECT * FROM decks WHERE id = $1 AND user_id = $2 LIMIT 1',
    [id, userId]
  );
  return rows[0] || null;
},
async update(userId, id, data) {
  // Fix #38: eliminate post-write re-fetch
  const payload = { ...data, updated_at: new Date() };
  const q = _buildUpdate('decks', 'id', id, payload, userId);
  await query(q.text, q.values);
  return { id, ...payload };
},
async delete(userId, id) {
  await query('DELETE FROM decks WHERE id = $1 AND user_id = $2', [id, userId]);
  return true;
},
async findBySubject(userId, subjectId) {
  const { rows } = await query(
    'SELECT * FROM decks WHERE user_id = $1 AND subject_id = $2',
    [userId, subjectId]
  );
  return rows;
},
async findBySubjectWithCards(userId, subjectId) {
  // Fix #55: 1 findAllForUser read replaces N sequential per-deck queries
  const decks = await this.findBySubject(userId, subjectId);
  if (decks.length === 0) return decks;
  const allCards = await db.cards.findAllForUser(userId);
  const deckIdSet = new Set(decks.map(d => d.id));
  const cardsByDeck = {};
  for (const c of allCards.filter(c => deckIdSet.has(c.deck_id))) {
    if (!cardsByDeck[c.deck_id]) cardsByDeck[c.deck_id] = [];
    cardsByDeck[c.deck_id].push(c);
  }
  for (const deck of decks) {
    deck.cards = cardsByDeck[deck.id] || [];
  }
  return decks;
},
async count(userId, filters = {}) {
  let sql = 'SELECT COUNT(*) AS count FROM decks WHERE user_id = $1';
  const vals = [userId];
  if (filters.is_public !== undefined) { sql += ` AND is_public = $${vals.length + 1}`; vals.push(filters.is_public); }
  const { rows } = await query(sql, vals);
  return parseInt(rows[0]?.count || '0', 10);
},
},
// ── cards ───────────────────────────────────────────────────────────────────
cards: {
async findById(userId, id) {
  const { rows } = await query(
    'SELECT * FROM cards WHERE id = $1 AND user_id = $2 LIMIT 1',
    [id, userId]
  );
  return rows[0] || null;
},
async findByIds(userId, cardIds) {
  if (!cardIds || cardIds.length === 0) return [];
  const { rows } = await query(
    'SELECT * FROM cards WHERE user_id = $1 AND id = ANY($2::text[])',
    [userId, cardIds]
  );
  return rows;
},
async findMany(userId, filters = {}, { page = 1, limit = 50 } = {}) {
  // Fix #46: use COUNT for total; avoid loading all cards to count
  let baseSQL = 'FROM cards WHERE user_id = $1';
  const vals = [userId];
  if (filters.deck_id) { baseSQL += ` AND deck_id = $${vals.length + 1}`; vals.push(filters.deck_id); }
  if (filters.stage !== undefined) { baseSQL += ` AND stage = $${vals.length + 1}`; vals.push(filters.stage); }
  const { rows: [{ count }] } = await query(`SELECT COUNT(*) AS count ${baseSQL}`, vals);
  const total = parseInt(count || '0', 10);
  const offset = (page - 1) * limit;
  const valsPage = [...vals, limit, offset];
  const { rows: cards } = await query(
    `SELECT * ${baseSQL} ORDER BY created_at ASC LIMIT $${valsPage.length - 1} OFFSET $${valsPage.length}`,
    valsPage
  );
  return { cards, total, page, total_pages: Math.ceil(total / limit) };
},
async create(userId, data) {
  const id = randomUUID();
  const payload = {
    ...data,
    id,
    user_id: userId,
    stage: data.stage || 1,
    interval_days: data.interval_days || 1,
    easiness_factor: data.easiness_factor || 2.5,
    repetition_count: data.repetition_count || 0,
    next_review_at: data.next_review_at || new Date(),
    created_at: new Date(),
    updated_at: new Date(),
  };
  const q = _buildInsert('cards', payload);
  await query(q.text, q.values);
  return { id, ...payload };
},
async createMany(userId, deckId, cardsData) {
  // Firestore batch → single transaction
  return withTransaction(async (client) => {
    const created = [];
    for (const c of cardsData) {
      const id = randomUUID();
      const payload = {
        id,
        user_id: userId,
        deck_id: deckId,
        stage: 1,
        interval_days: 1,
        easiness_factor: 2.5,
        repetition_count: 0,
        next_review_at: new Date(),
        created_at: new Date(),
        updated_at: new Date(),
        ...c,
      };
      const q = _buildInsert('cards', payload);
      await client.query(q.text, q.values);
      created.push({ id, ...payload });
    }
    return created;
  });
},
async update(userId, id, data) {
  // Fix #38: eliminate post-write re-fetch
  const payload = { ...data, updated_at: new Date() };
  const q = _buildUpdate('cards', 'id', id, payload, userId);
  await query(q.text, q.values);
  return { id, ...payload };
},
async delete(userId, id) {
  await query('DELETE FROM cards WHERE id = $1 AND user_id = $2', [id, userId]);
  return true;
},
async countByDeck(userId, deckId) {
  const { rows } = await query(
    'SELECT COUNT(*) AS count FROM cards WHERE user_id = $1 AND deck_id = $2',
    [userId, deckId]
  );
  return parseInt(rows[0]?.count || '0', 10);
},
async findAllForUser(userId) {
  const { rows } = await query('SELECT * FROM cards WHERE user_id = $1', [userId]);
  return rows;
},
async findByDeck(userId, deckId) {
  const { rows } = await query(
    'SELECT * FROM cards WHERE user_id = $1 AND deck_id = $2',
    [userId, deckId]
  );
  return rows;
},
async findByDeckIds(userId, deckIds) {
  // Fix #30 + collapse chunking: ANY($1) replaces chunked IN queries
  if (!deckIds || deckIds.length === 0) return [];
  const { rows } = await query(
    'SELECT * FROM cards WHERE user_id = $1 AND deck_id = ANY($2::text[])',
    [userId, deckIds]
  );
  return rows;
},
async countMastered(userId, sinceDate) {
  let sql = 'SELECT COUNT(*) AS count FROM cards WHERE user_id = $1 AND stage = 5';
  const vals = [userId];
  if (sinceDate) { sql += ` AND last_reviewed_at >= $${vals.length + 1}`; vals.push(sinceDate); }
  const { rows } = await query(sql, vals);
  return parseInt(rows[0]?.count || '0', 10);
},
},
// ── review_logs ─────────────────────────────────────────────────────────────
reviewLogs: {
async create(userId, data) {
  const id = randomUUID();
  const payload = { ...data, id, user_id: userId, created_at: new Date() };
  const q = _buildInsert('review_logs', payload);
  await query(q.text, q.values);
  return { id, ...payload };
},
async findByCards(userId, cardIds) {
  // Fix #36 + collapse chunking: ANY($1) replaces chunked IN queries
  if (!cardIds || cardIds.length === 0) return [];
  const { rows } = await query(
    'SELECT * FROM review_logs WHERE user_id = $1 AND card_id = ANY($2::text[])',
    [userId, cardIds]
  );
  return rows;
},
async findByUser(userId, sinceDate) {
  const { rows } = await query(
    'SELECT * FROM review_logs WHERE user_id = $1 AND reviewed_at >= $2',
    [userId, sinceDate]
  );
  return rows;
},
async count(userId, filters = {}) {
  let sql = 'SELECT COUNT(*) AS count FROM review_logs WHERE user_id = $1';
  const vals = [userId];
  if (filters.reviewed_at_gte) { sql += ` AND reviewed_at >= $${vals.length + 1}`; vals.push(filters.reviewed_at_gte); }
  const { rows } = await query(sql, vals);
  return parseInt(rows[0]?.count || '0', 10);
},
},
// ── sessions ────────────────────────────────────────────────────────────────
sessions: {
async create(userId, deckId, startedAt) {
  const id = randomUUID();
  const payload = {
    id,
    user_id: userId,
    deck_id: deckId,
    started_at: startedAt,
    ended_at: null,
    duration_seconds: 0,
    cards_reviewed: 0,
    cards_again: 0,
    cards_hard: 0,
    cards_good: 0,
    cards_easy: 0,
    accuracy_pct: 0,
    xp_earned: 0,
    session_completed: false,
    seed_survived: false,
    focus_breaks: 0,
    focus_seed_stage: 'Dormant',
    fruiting_achieved: false,
    created_at: new Date(),
  };
  await query(
    `INSERT INTO sessions (id, user_id, deck_id, started_at, ended_at, duration_seconds,
      cards_reviewed, cards_again, cards_hard, cards_good, cards_easy, accuracy_pct,
      xp_earned, session_completed, seed_survived, focus_breaks, focus_seed_stage,
      fruiting_achieved, created_at)
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19)`,
    [id, userId, deckId, startedAt, null, 0, 0, 0, 0, 0, 0, 0, 0, false, false, 0, 'Dormant', false, payload.created_at]
  );
  return { id, ...payload };
},
async findById(userId, id) {
  const { rows } = await query(
    'SELECT * FROM sessions WHERE id = $1 AND user_id = $2 LIMIT 1',
    [id, userId]
  );
  return rows[0] || null;
},
async findByIdFull(userId, id) {
  const { rows: [session] } = await query(
    'SELECT * FROM sessions WHERE id = $1 AND user_id = $2 LIMIT 1',
    [id, userId]
  );
  if (!session) return null;
  if (session.deck_id) {
    const { rows: [deck] } = await query('SELECT * FROM decks WHERE id = $1', [session.deck_id]);
    if (deck) session.deck = deck;
  }
  return session;
},
async update(userId, id, data) {
  // Fix #38: conditional RETURNING * — only re-fetch when { increment: N } is used
  const built = _buildIncrementUpdate('sessions', 'id', id, data);
  const { rows } = await query(built.text, built.values);
  return rows[0] ? { id, ...rows[0] } : { id, ...data };
},
async findMany(userId, filters = {}, { limit = 20, offset = 0 } = {}) {
  // Fix #47: use COUNT for accurate total
  let baseSQL = 'FROM sessions WHERE user_id = $1';
  const vals = [userId];
  if (filters.session_completed !== undefined) {
    baseSQL += ` AND session_completed = $${vals.length + 1}`; vals.push(filters.session_completed);
  }
  if (filters.deck_id) { baseSQL += ` AND deck_id = $${vals.length + 1}`; vals.push(filters.deck_id); }
  if (filters.started_at_gte) { baseSQL += ` AND started_at >= $${vals.length + 1}`; vals.push(filters.started_at_gte); }
  const { rows: [{ count }] } = await query(`SELECT COUNT(*) AS count ${baseSQL}`, vals);
  const valsPage = [...vals, limit, offset];
  const { rows: sessions } = await query(
    `SELECT * ${baseSQL} ORDER BY started_at DESC LIMIT $${valsPage.length - 1} OFFSET $${valsPage.length}`,
    valsPage
  );
  return { sessions, total: parseInt(count || '0', 10) };
},
async findBySubject(userId, subjectId, sinceDate) {
  // Fix #37 + collapse chunking: JOIN replaces deck-chunked IN queries
  let sql = `SELECT s.* FROM sessions s
    JOIN decks d ON s.deck_id = d.id
    WHERE s.user_id = $1 AND d.subject_id = $2`;
  const vals = [userId, subjectId];
  if (sinceDate) { sql += ` AND s.started_at >= $${vals.length + 1}`; vals.push(sinceDate); }
  const { rows } = await query(sql, vals);
  return rows;
},
async count(userId, filters = {}) {
  let sql = 'SELECT COUNT(*) AS count FROM sessions WHERE user_id = $1';
  const vals = [userId];
  if (filters.session_completed !== undefined) {
    sql += ` AND session_completed = $${vals.length + 1}`; vals.push(filters.session_completed);
  }
  if (filters.started_at_gte) { sql += ` AND started_at >= $${vals.length + 1}`; vals.push(filters.started_at_gte); }
  const { rows } = await query(sql, vals);
  return parseInt(rows[0]?.count || '0', 10);
},
},
// ── exam_sessions ───────────────────────────────────────────────────────────
examSessions: {
async create(userId, data) {
  const id = randomUUID();
  const payload = {
    ...data,
    id,
    user_id: userId,
    // Production schema keeps started_at NOT NULL. Status is authoritative for
    // whether an exam has actually started; /start and Reckoning activation
    // overwrite this timestamp with the real activation time.
    started_at: new Date(),
    is_reckoning: data.is_reckoning || false,
    status: data.status || 'pending',
    created_at: new Date(),
  };
  const q = _buildInsert('exam_sessions', payload);
  await query(q.text, q.values);
  return { id, ...payload };
},
async update(userId, id, data) {
  // Scope exam writes to the authenticated owner.
  const payload = { ...data, updated_at: new Date() };
  const q = _buildUpdate('exam_sessions', 'id', id, payload, userId);
  const result = await query(q.text, q.values);
  return result.rowCount > 0 ? { id, ...payload } : null;
},
async findByIdWithQuestions(userId, id) {
  const { rows: [exam] } = await query(
    'SELECT * FROM exam_sessions WHERE id = $1 AND user_id = $2 LIMIT 1',
    [id, userId]
  );
  if (!exam) return null;
  const { rows: questions } = await query(
    'SELECT * FROM exam_questions WHERE exam_session_id = $1 AND user_id = $2',
    [id, userId]
  );
  exam.questions = questions;
  return exam;
},
async findMany(userId, filters = {}, { limit = 20, offset = 0 } = {}) {
  // JOIN with subjects so every row carries subject_name — fixes UUID display in exam history
  let sql = `SELECT es.*, s.name AS subject_name FROM exam_sessions es
             LEFT JOIN subjects s ON es.subject_id = s.id
             WHERE es.user_id = $1`;
  const vals = [userId];
  if (filters.status) { sql += ` AND es.status = $${vals.length + 1}`; vals.push(filters.status); }
  if (filters.started_at_gte) { sql += ` AND es.started_at >= $${vals.length + 1}`; vals.push(filters.started_at_gte); }
  vals.push(limit, offset);
  sql += ` ORDER BY es.created_at DESC LIMIT $${vals.length - 1} OFFSET $${vals.length}`;
  const { rows } = await query(sql, vals);
  // Normalise JSON-encoded subject names (legacy migration artefact)
  return rows.map(r => {
    let name = r.subject_name || '';
    if (name.trim().startsWith('{')) {
      try { const p = JSON.parse(name); if (p?.name) name = p.name; } catch (_) {}
    }
    return { ...r, subject_name: name || null };
  });
},
// FIX: Add missing delete method — called by background exam generation on parse failure
async delete(userId, id) {
  await query('DELETE FROM exam_questions WHERE exam_session_id = $1 AND user_id = $2', [id, userId]);
  await query('DELETE FROM exam_sessions WHERE id = $1 AND user_id = $2', [id, userId]);
  return true;
},
},
// ── exam_questions ──────────────────────────────────────────────────────────
examQuestions: {
async create(userId, examSessionId, data) {
  const id = randomUUID();
  const payload = {
    ...data,
    id,
    user_id: userId,
    exam_session_id: examSessionId,
    created_at: new Date(),
  };
  const q = _buildInsert('exam_questions', payload);
  await query(q.text, q.values);
  return { id, ...payload };
},
async findByNumber(userId, examSessionId, questionNumber) {
  const { rows } = await query(
    `SELECT * FROM exam_questions WHERE user_id = $1 AND exam_session_id = $2
     AND question_number = $3 LIMIT 1`,
    [userId, examSessionId, questionNumber]
  );
  return rows[0] || null;
},
async findById(userId, id) {
  const { rows } = await query(
    'SELECT * FROM exam_questions WHERE id = $1 AND user_id = $2 LIMIT 1',
    [id, userId]
  );
  return rows[0] |…231077 tokens truncated… PRIMARY KEY,
      user_id text,
      subject_id text,
      status text DEFAULT 'triggered',
      activation_announced_at timestamptz,
      created_at timestamptz DEFAULT NOW(),
      updated_at timestamptz DEFAULT NOW()
    )`,
    `CREATE TABLE IF NOT EXISTS chronicle_entries (
      id text PRIMARY KEY,
      user_id text,
      week_start text,
      summary text,
      data jsonb,
      created_at timestamptz DEFAULT NOW()
    )`,
    `CREATE TABLE IF NOT EXISTS almanac_entries (
      id text PRIMARY KEY,
      user_id text,
      entry_code text,
      unlocked boolean DEFAULT false,
      unlocked_at timestamptz,
      narrative text,
      created_at timestamptz DEFAULT NOW()
    )`,
    `CREATE TABLE IF NOT EXISTS user_persona (
      id text PRIMARY KEY,
      user_id text,
      assigned_week_start text,
      persona_type text,
      traits jsonb,
      created_at timestamptz DEFAULT NOW()
    )`,
    `CREATE TABLE IF NOT EXISTS daily_ritual_cache (
      id text PRIMARY KEY,
      user_id text,
      type text,
      date text,
      data jsonb,
      updated_at timestamptz DEFAULT NOW()
    )`,
    `CREATE TABLE IF NOT EXISTS seedling_transactions (
      id text PRIMARY KEY,
      user_id text,
      type text,
      amount integer DEFAULT 0,
      reason text,
      created_at timestamptz DEFAULT NOW()
    )`,
    `CREATE TABLE IF NOT EXISTS mastery_goals (
      id text PRIMARY KEY,
      user_id text,
      subject_id text,
      name text,
      card_ids jsonb DEFAULT '[]',
      cross_bubble_card_ids jsonb DEFAULT '[]',
      deck_ids jsonb DEFAULT '[]',
      test_date timestamptz,
      exam_date timestamptz,
      deadline_editable boolean DEFAULT true,
      status text DEFAULT 'dormant',
      phase text DEFAULT 'SEEDING',
      phase_entered_at timestamptz,
      phase_history jsonb DEFAULT '[]',
      current_ks numeric DEFAULT 0,
      target_ks numeric DEFAULT 100,
      required_ks_per_day numeric DEFAULT 0,
      actual_ks_velocity numeric DEFAULT 0,
      trajectory_gap numeric DEFAULT 0,
      trajectory_status text DEFAULT 'ON_TRACK',
      daily_contract_cards integer DEFAULT 0,
      daily_contract_breakdown jsonb DEFAULT '{}',
      daily_contract_minutes integer DEFAULT 0,
      daily_contract_generated_at timestamptz,
      daily_contract_completed boolean DEFAULT false,
      daily_contract_consequence text,
      stall_response_active text,
      consecutive_low_velocity_days integer DEFAULT 0,
      velocity_samples jsonb DEFAULT '[]',
      last_recalculated_at timestamptz,
      completed_at timestamptz,
      learning_debt_card_count integer DEFAULT 0,
      seeding_early_stall_checked boolean DEFAULT false,
      autopsy_generated boolean DEFAULT false,
      autopsy_generated_at timestamptz,
      coverage_gap_active boolean DEFAULT false,
      created_at timestamptz DEFAULT NOW(),
      updated_at timestamptz DEFAULT NOW()
    )`,
    `CREATE TABLE IF NOT EXISTS goal_history (
      id text PRIMARY KEY,
      goal_id text,
      event_type text,
      data jsonb DEFAULT '{}',
      created_at timestamptz DEFAULT NOW()
    )`,
    `CREATE TABLE IF NOT EXISTS concept_clusters (
      id text PRIMARY KEY,
      goal_id text,
      name text,
      card_ids jsonb DEFAULT '[]',
      cluster_ks numeric DEFAULT 0,
      cluster_status text DEFAULT 'WEAK',
      identified_at timestamptz DEFAULT NOW(),
      last_ks_update timestamptz DEFAULT NOW(),
      updated_at timestamptz DEFAULT NOW()
    )`,
    `CREATE TABLE IF NOT EXISTS marketplace_items (
      id text PRIMARY KEY,
      item_code text UNIQUE,
      name text,
      description text,
      category text,
      gate1_condition jsonb,
      gate2_seedling_cost integer DEFAULT 0,
      purchase_limit integer,
      created_at timestamptz DEFAULT NOW()
    )`,
    `CREATE TABLE IF NOT EXISTS user_inventory (
      id text PRIMARY KEY,
      user_id text,
      item_code text,
      quantity integer DEFAULT 0,
      unlocked boolean DEFAULT false,
      acquired_at timestamptz,
      updated_at timestamptz DEFAULT NOW()
    )`,
  ];
  for (const sql of createTables) {
    try {
      await query(sql);
    } catch (e) {
      console.error('[KIWI] Create table failed:', e.message);
    }
  }

  const migrations = [
    // almanac_entries: chapter, name, unlock_condition were missing from initial schema
    `ALTER TABLE almanac_entries ADD COLUMN IF NOT EXISTS chapter integer`,
    `ALTER TABLE almanac_entries ADD COLUMN IF NOT EXISTS name text`,
    `ALTER TABLE almanac_entries ADD COLUMN IF NOT EXISTS unlock_condition jsonb`,
    `ALTER TABLE almanac_entries ADD COLUMN IF NOT EXISTS is_artifact boolean DEFAULT false`,
    `ALTER TABLE almanac_entries ADD COLUMN IF NOT EXISTS is_ai_generated boolean DEFAULT false`,

    // subjects: color + icon are in the explicit INSERT column list — their absence causes a hard error
    `ALTER TABLE subjects ADD COLUMN IF NOT EXISTS color text DEFAULT '#4F46E5'`,
    `ALTER TABLE subjects ADD COLUMN IF NOT EXISTS icon text DEFAULT '📚'`,
    `ALTER TABLE subjects ADD COLUMN IF NOT EXISTS exam_date timestamptz`,
    `ALTER TABLE subjects ADD COLUMN IF NOT EXISTS test_date timestamptz`,
    `ALTER TABLE subjects ADD COLUMN IF NOT EXISTS updated_at timestamptz`,
    `ALTER TABLE subjects ADD COLUMN IF NOT EXISTS status text DEFAULT 'active'`,
    `ALTER TABLE subjects ADD COLUMN IF NOT EXISTS archived boolean DEFAULT false`,
    `ALTER TABLE subjects ADD COLUMN IF NOT EXISTS archived_at timestamptz`,

    // users: extended columns used by _safeUserCreate, cron jobs, and settings routes
    `ALTER TABLE users ADD COLUMN IF NOT EXISTS full_name text DEFAULT ''`,
    `ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url text DEFAULT ''`,
    `ALTER TABLE users ADD COLUMN IF NOT EXISTS bio text DEFAULT ''`,
    `ALTER TABLE users ADD COLUMN IF NOT EXISTS role text DEFAULT 'user'`,
    `ALTER TABLE users ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true`,
    `ALTER TABLE users ADD COLUMN IF NOT EXISTS is_guest boolean DEFAULT false`,
    `ALTER TABLE users ADD COLUMN IF NOT EXISTS guest_expires_at timestamptz`,
    `ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_at timestamptz`,
    `ALTER TABLE users ADD COLUMN IF NOT EXISTS previous_login_at timestamptz`,
    `ALTER TABLE users ADD COLUMN IF NOT EXISTS telegram_link_token text`,
    `ALTER TABLE users ADD COLUMN IF NOT EXISTS telegram_chat_id text`,
    `ALTER TABLE users ADD COLUMN IF NOT EXISTS notification_preferences jsonb DEFAULT '{"email":true,"telegram":false}'`,
    `ALTER TABLE users ADD COLUMN IF NOT EXISTS theme text`,
    `ALTER TABLE users ADD COLUMN IF NOT EXISTS exam_reminder_days integer`,
    `ALTER TABLE users ADD COLUMN IF NOT EXISTS is_blocked boolean DEFAULT false`,
    `ALTER TABLE users ADD COLUMN IF NOT EXISTS blocked_reason text`,

    // user_stats: updated_at required by _buildIncrementUpdate (always appended to SET clause)
    `ALTER TABLE user_stats ADD COLUMN IF NOT EXISTS updated_at timestamptz`,
    `ALTER TABLE user_stats ADD COLUMN IF NOT EXISTS study_mode text DEFAULT 'normal'`,
    `ALTER TABLE user_stats ADD COLUMN IF NOT EXISTS streak_milestones_earned jsonb DEFAULT '[]'`,

    // sessions: updated_at required by _buildIncrementUpdate
    `ALTER TABLE sessions ADD COLUMN IF NOT EXISTS updated_at timestamptz`,
    // sessions: ks_delta written by /study/end so progress history shows real KS change
    `ALTER TABLE sessions ADD COLUMN IF NOT EXISTS ks_delta numeric DEFAULT 0`,

    // decks: extra columns referenced in create/update calls
    `ALTER TABLE decks ADD COLUMN IF NOT EXISTS card_count integer DEFAULT 0`,
    `ALTER TABLE decks ADD COLUMN IF NOT EXISTS is_public boolean DEFAULT false`,
    `ALTER TABLE decks ADD COLUMN IF NOT EXISTS description text`,
    `ALTER TABLE decks ADD COLUMN IF NOT EXISTS updated_at timestamptz`,

    // cards: archive expansion and review tracking
    `ALTER TABLE cards ADD COLUMN IF NOT EXISTS archived boolean DEFAULT false`,
    `ALTER TABLE cards ADD COLUMN IF NOT EXISTS review_count integer DEFAULT 0`,
    // cards: canonical content columns — DB uses front_content/back_content not front/back
    `ALTER TABLE cards ADD COLUMN IF NOT EXISTS front_content text`,
    `ALTER TABLE cards ADD COLUMN IF NOT EXISTS back_content text`,

    // subject_stats: analytics columns written by persistKnowledgeScore, cron, and Biome
    `ALTER TABLE subject_stats ADD COLUMN IF NOT EXISTS knowledge_score numeric DEFAULT 0`,
    `ALTER TABLE subject_stats ADD COLUMN IF NOT EXISTS previous_week_ks numeric`,
    `ALTER TABLE subject_stats ADD COLUMN IF NOT EXISTS previous_week_ks_recorded_at timestamptz`,
    `ALTER TABLE subject_stats ADD COLUMN IF NOT EXISTS last_studied_at timestamptz`,
    `ALTER TABLE subject_stats ADD COLUMN IF NOT EXISTS last_study_date timestamptz`,
    `ALTER TABLE subject_stats ADD COLUMN IF NOT EXISTS zone_state text DEFAULT 'Dormant'`,
    `ALTER TABLE subject_stats ADD COLUMN IF NOT EXISTS last_zone_state text`,
    `ALTER TABLE subject_stats ADD COLUMN IF NOT EXISTS fruit_count integer DEFAULT 0`,
    `ALTER TABLE subject_stats ADD COLUMN IF NOT EXISTS archived boolean DEFAULT false`,
    `ALTER TABLE subject_stats ADD COLUMN IF NOT EXISTS archived_at timestamptz`,
    `ALTER TABLE subject_stats ADD COLUMN IF NOT EXISTS was_neglected_then_resumed boolean DEFAULT false`,

    // exam_sessions: is_reckoning (P1.7 migration note), scoring, and timing fields
    `ALTER TABLE exam_sessions ADD COLUMN IF NOT EXISTS is_reckoning boolean DEFAULT false`,
    `ALTER TABLE exam_sessions ADD COLUMN IF NOT EXISTS updated_at timestamptz`,
    `ALTER TABLE exam_sessions ADD COLUMN IF NOT EXISTS subject_id text`,
    `ALTER TABLE exam_sessions ADD COLUMN IF NOT EXISTS score_pct numeric`,
    `ALTER TABLE exam_sessions ADD COLUMN IF NOT EXISTS question_count integer DEFAULT 0`,
    `ALTER TABLE exam_sessions ADD COLUMN IF NOT EXISTS correct_answers integer DEFAULT 0`,
    `ALTER TABLE exam_sessions ADD COLUMN IF NOT EXISTS total_questions integer DEFAULT 0`,
    `ALTER TABLE exam_sessions ADD COLUMN IF NOT EXISTS duration_seconds integer DEFAULT 0`,
    `ALTER TABLE exam_sessions ADD COLUMN IF NOT EXISTS completed_at timestamptz`,
    `ALTER TABLE exam_sessions ADD COLUMN IF NOT EXISTS time_limit_seconds integer DEFAULT 1800`,
    `ALTER TABLE exam_sessions ADD COLUMN IF NOT EXISTS card_range text DEFAULT 'all'`,
    `ALTER TABLE exam_sessions ADD COLUMN IF NOT EXISTS difficulty_level text DEFAULT NULL`,
    `DO $$ BEGIN
       IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'exam_sessions_difficulty_level_check') THEN
         ALTER TABLE exam_sessions ADD CONSTRAINT exam_sessions_difficulty_level_check
         CHECK (difficulty_level IS NULL OR difficulty_level IN ('easy','hard','very_hard','hell'));
       END IF;
     END $$`,
    `ALTER TABLE exam_sessions ADD COLUMN IF NOT EXISTS ended_early boolean DEFAULT false`,
    `ALTER TABLE exam_sessions ADD COLUMN IF NOT EXISTS timed_out boolean DEFAULT false`,
    // Persist exact before/after snapshots; NULL delta means historical change is unknown.
    `ALTER TABLE exam_sessions ADD COLUMN IF NOT EXISTS ks_delta numeric`,
    `ALTER TABLE exam_sessions ALTER COLUMN ks_delta DROP DEFAULT`,
    `ALTER TABLE exam_sessions ADD COLUMN IF NOT EXISTS ks_before numeric`,
    `ALTER TABLE exam_sessions ADD COLUMN IF NOT EXISTS ks_after numeric`,
    `ALTER TABLE exam_sessions ADD COLUMN IF NOT EXISTS ks_processed_at timestamptz`,

    // reckoning_sessions: fields referenced in brain router and lockout middleware
    `ALTER TABLE reckoning_sessions ADD COLUMN IF NOT EXISTS subject_name text`,
    `ALTER TABLE reckoning_sessions ADD COLUMN IF NOT EXISTS pressure_score integer DEFAULT 0`,
    `ALTER TABLE reckoning_sessions ADD COLUMN IF NOT EXISTS flagged_card_count integer DEFAULT 0`,
    `ALTER TABLE reckoning_sessions ADD COLUMN IF NOT EXISTS question_count integer DEFAULT 0`,
    `ALTER TABLE reckoning_sessions ADD COLUMN IF NOT EXISTS was_deferred boolean DEFAULT false`,
    `ALTER TABLE reckoning_sessions ADD COLUMN IF NOT EXISTS deferred_until timestamptz`,
    `ALTER TABLE reckoning_sessions ADD COLUMN IF NOT EXISTS deferral_used boolean DEFAULT false`,
    `ALTER TABLE reckoning_sessions ADD COLUMN IF NOT EXISTS debrief_text text`,
    `ALTER TABLE reckoning_sessions ADD COLUMN IF NOT EXISTS score_pct numeric`,
    `ALTER TABLE reckoning_sessions ADD COLUMN IF NOT EXISTS activation_announced_at timestamptz`,
    `ALTER TABLE reckoning_sessions ADD COLUMN IF NOT EXISTS completed_at timestamptz`,
    `ALTER TABLE reckoning_sessions ADD COLUMN IF NOT EXISTS failure_count integer NOT NULL DEFAULT 0`,
    `ALTER TABLE reckoning_sessions ADD COLUMN IF NOT EXISTS last_failure_exam_id text`,
    `ALTER TABLE reckoning_sessions ADD COLUMN IF NOT EXISTS failsafe_released_at timestamptz`,
    `ALTER TABLE reckoning_sessions ADD COLUMN IF NOT EXISTS failsafe_penalty_ks_before numeric`,
    `ALTER TABLE reckoning_sessions ADD COLUMN IF NOT EXISTS failsafe_penalty_ks_after numeric`,
    `ALTER TABLE reckoning_sessions ADD COLUMN IF NOT EXISTS failsafe_claimed_at timestamptz`,
    // Keep the Reckoning state machine synchronized with every terminal state.
    // In particular, the sixth-failure circuit breaker must be allowed to persist
    // failsafe_released or reconciliation will loop forever and lock the account.
    `ALTER TABLE reckoning_sessions DROP CONSTRAINT IF EXISTS reckoning_sessions_state_machine_ck`,
    `ALTER TABLE reckoning_sessions
       ADD CONSTRAINT reckoning_sessions_state_machine_ck
       CHECK (
         (
           status = 'triggered'
           AND exam_session_id IS NULL
           AND deferred_until IS NULL
         )
         OR (
           status = 'deferred'
           AND exam_session_id IS NULL
           AND deferred_until IS NOT NULL
           AND deferral_used = true
         )
         OR (
           status = 'in_progress'
           AND exam_session_id IS NOT NULL
           AND deferred_until IS NULL
         )
         OR (
           status = 'completed'
           AND deferred_until IS NULL
           AND completed_at IS NOT NULL
           AND score_pct IS NOT NULL
           AND score_pct >= 70
         )
         OR (
           status = 'failsafe_released'
           AND exam_session_id IS NULL
           AND deferred_until IS NULL
           AND completed_at IS NOT NULL
           AND failsafe_released_at IS NOT NULL
         )
       )`,
    `ALTER TABLE card_states ADD COLUMN IF NOT EXISTS reckoning_penalty_factor numeric NOT NULL DEFAULT 1`,
    `ALTER TABLE card_states ADD COLUMN IF NOT EXISTS reckoning_penalty_applied_at timestamptz`,
    `ALTER TABLE card_states DROP CONSTRAINT IF EXISTS card_states_reckoning_penalty_factor_check`,
    `ALTER TABLE card_states
       ADD CONSTRAINT card_states_reckoning_penalty_factor_check
       CHECK (reckoning_penalty_factor >= 0 AND reckoning_penalty_factor <= 1)`,

    // Legacy Bubble tables are unused by the current service. Keep them inaccessible
    // through PostgREST instead of leaving public-schema tables without RLS.
    `ALTER TABLE IF EXISTS public.mastery_clusters ENABLE ROW LEVEL SECURITY`,
    `ALTER TABLE IF EXISTS public.bubble_sessions ENABLE ROW LEVEL SECURITY`,

    // mastery_goals: bubble trajectory, contract streak, rescue and stall tracking
    `ALTER TABLE mastery_goals ADD COLUMN IF NOT EXISTS contract_streak_current integer DEFAULT 0`,
    `ALTER TABLE mastery_goals ADD COLUMN IF NOT EXISTS contract_streak_best integer DEFAULT 0`,
    `ALTER TABLE mastery_goals ADD COLUMN IF NOT EXISTS daily_contract_miss_consequence text`,
    `ALTER TABLE mastery_goals ADD COLUMN IF NOT EXISTS rescue_eligible boolean DEFAULT false`,
    `ALTER TABLE mastery_goals ADD COLUMN IF NOT EXISTS rescue_active boolean DEFAULT false`,
    `ALTER TABLE mastery_goals ADD COLUMN IF NOT EXISTS rescue_mode_entered_at timestamptz`,
    `ALTER TABLE mastery_goals ADD COLUMN IF NOT EXISTS stall_active boolean DEFAULT false`,
    `ALTER TABLE mastery_goals ADD COLUMN IF NOT EXISTS stall_cause text`,
    `ALTER TABLE mastery_goals ADD COLUMN IF NOT EXISTS stall_detected_at timestamptz`,
    `ALTER TABLE mastery_goals ADD COLUMN IF NOT EXISTS stall_resolved_at timestamptz`,
    `ALTER TABLE mastery_goals ADD COLUMN IF NOT EXISTS test_date_gate_passed boolean DEFAULT false`,
    `ALTER TABLE mastery_goals ADD COLUMN IF NOT EXISTS test_date_gate_failed boolean DEFAULT false`,
    `ALTER TABLE mastery_goals ADD COLUMN IF NOT EXISTS gate_fail_message text`,
    `ALTER TABLE mastery_goals ADD COLUMN IF NOT EXISTS projected_completion_date timestamptz`,
    `ALTER TABLE mastery_goals ADD COLUMN IF NOT EXISTS projected_best_case timestamptz`,
    `ALTER TABLE mastery_goals ADD COLUMN IF NOT EXISTS projected_minimum_viable timestamptz`,
    `ALTER TABLE mastery_goals ADD COLUMN IF NOT EXISTS last_ks_snapshot_at timestamptz`,
    `ALTER TABLE mastery_goals ADD COLUMN IF NOT EXISTS final_ks_at_deadline numeric`,
    `ALTER TABLE mastery_goals ADD COLUMN IF NOT EXISTS archived_at timestamptz`,

    // achievements: extra columns missing from initial schema
    `ALTER TABLE achievements ADD COLUMN IF NOT EXISTS icon_emoji text`,
    `ALTER TABLE achievements ADD COLUMN IF NOT EXISTS is_secret boolean DEFAULT false`,
    `ALTER TABLE achievements ADD COLUMN IF NOT EXISTS is_timed boolean DEFAULT false`,
    `ALTER TABLE achievements ADD COLUMN IF NOT EXISTS condition jsonb`,
    `ALTER TABLE achievements ADD COLUMN IF NOT EXISTS xp_reward integer DEFAULT 0`,
    `ALTER TABLE achievements ADD COLUMN IF NOT EXISTS category text`,

    // community_decks: catalog and marketplace fields
    `ALTER TABLE community_decks ADD COLUMN IF NOT EXISTS is_featured boolean DEFAULT false`,
    `ALTER TABLE community_decks ADD COLUMN IF NOT EXISTS author_id text`,
    `ALTER TABLE community_decks ADD COLUMN IF NOT EXISTS author_name text`,
    `ALTER TABLE community_decks ADD COLUMN IF NOT EXISTS subject_hint text`,
    `ALTER TABLE community_decks ADD COLUMN IF NOT EXISTS card_count integer DEFAULT 0`,
    `ALTER TABLE community_decks ADD COLUMN IF NOT EXISTS average_rating numeric DEFAULT 0`,
    `ALTER TABLE community_decks ADD COLUMN IF NOT EXISTS clone_count integer DEFAULT 0`,
    `ALTER TABLE community_decks ADD COLUMN IF NOT EXISTS tags jsonb DEFAULT '[]'`,
    `ALTER TABLE community_decks ADD COLUMN IF NOT EXISTS sample_cards jsonb DEFAULT '[]'`,
    `ALTER TABLE community_decks ADD COLUMN IF NOT EXISTS description text`,
    `ALTER TABLE community_decks ADD COLUMN IF NOT EXISTS title text`,
    `ALTER TABLE community_decks ADD COLUMN IF NOT EXISTS is_public boolean DEFAULT true`,
    `ALTER TABLE community_decks ADD COLUMN IF NOT EXISTS subject text`,
    `ALTER TABLE community_decks ADD COLUMN IF NOT EXISTS likes integer DEFAULT 0`,
    `ALTER TABLE community_decks ADD COLUMN IF NOT EXISTS downloads integer DEFAULT 0`,
    `ALTER TABLE community_decks ADD COLUMN IF NOT EXISTS group_name text`,
    // Remove hardcoded KIWI Team seed decks — library is user-populated only
    `DELETE FROM community_decks WHERE author_name = 'KIWI Team' AND original_deck_id IS NULL`,
    // DB-FIX: exam_questions needs card_id for SRS feedback linkage (Issue #1 fix)
    `ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS card_id text`,
    // DB-FIX: background_jobs table for job polling fallback
    `CREATE TABLE IF NOT EXISTS background_jobs (
      id          TEXT        PRIMARY KEY,
      status      TEXT        NOT NULL DEFAULT 'pending',
      type        TEXT        NOT NULL,
      result      JSONB,
      error       TEXT,
      expires_at  TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '10 minutes'),
      created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )`,
    `CREATE INDEX IF NOT EXISTS idx_background_jobs_expires ON background_jobs(expires_at)`,
    // FSRS-4.5 + latency modulation columns
    `ALTER TABLE cards ADD COLUMN IF NOT EXISTS fsrs_stability numeric DEFAULT NULL`,
    `ALTER TABLE cards ADD COLUMN IF NOT EXISTS fsrs_difficulty numeric DEFAULT NULL`,
    `ALTER TABLE cards ADD COLUMN IF NOT EXISTS avg_response_time_ms numeric DEFAULT NULL`,
    `ALTER TABLE review_logs ADD COLUMN IF NOT EXISTS fsrs_stability_after numeric DEFAULT NULL`,
  ];
  for (const sql of migrations) {
    try {
      await query(sql);
    } catch (e) {
      console.error('[KIWI] Migration failed:', sql, e.message);
    }
  }
  await ecosystemV2.migrate();
  console.log('[KIWI] ✅ Schema migrations + Ecosystem V2 applied');
}

// ════════════════════════════════════════════════════════════════════════════
//  BREVO (SENDINBLUE) EMAIL SERVICE — CEE-style with daily reset & auto-fallback

// ════════════════════════════════════════════════════════════════════════════
function buildBrevoPool() {
  const senderEmail = process.env.BREVO_SENDER_EMAIL;
  if (!senderEmail) {
    console.warn('[KIWI] BREVO_SENDER_EMAIL env var is not set — emails will not be sent.');
    return []; // empty pool; sendBrevoEmail will skip gracefully
  }
  const accts = [];
  if (process.env.BREVO_API_KEY) {
    accts.push({ key: process.env.BREVO_API_KEY.trim(), from: senderEmail, sentToday: 0, lastResetDate: '' });
  }
  for (let i = 2; i <= 15; i++) {
    const k = process.env[`BREVO_API_KEY_${i}`];
    if (k && k.trim()) accts.push({ key: k.trim(), from: senderEmail, sentToday: 0, lastResetDate: '' });
  }
  return accts;
}
const _brevoAccounts = buildBrevoPool();

function _brevoResetIfNewDay(acct) {
  const today = new Date().toISOString().split('T')[0];
  if (acct.lastResetDate !== today) { acct.sentToday = 0; acct.lastResetDate = today; }
}

function _pickBrevoAccount() {
  for (const acct of _brevoAccounts) {
    _brevoResetIfNewDay(acct);
    if (acct.sentToday < 295) return acct;
  }
  return null;
}

async function _sendViaBrevo(acct, toEmail, subject, htmlContent) {
  try {
    const res = await fetch('https://api.brevo.com/v3/smtp/email', {
      method: 'POST',
      headers: { 'api-key': acct.key, 'Content-Type': 'application/json', 'Accept': 'application/json' },
      body: JSON.stringify({
        sender: { name: 'KIWI Study', email: acct.from },
        to: [{ email: toEmail }],
        subject,
        htmlContent,
      }),
    });
    if (res.status === 201 || res.status === 200 || res.status === 202) {
      acct.sentToday++;
      return { success: true };
    }
    let errMsg = `Brevo HTTP ${res.status}`;
    try { const b = await res.json(); errMsg = b.message || b.error || errMsg; } catch (_) {}
    if (res.status === 429) acct.sentToday = 300;
    return { success: false, error: errMsg };
  } catch (e) {
    return { success: false, error: e.message };
  }
}

async function sendBrevoEmail(toEmail, templateName, params = {}) {
  if (_brevoAccounts.length === 0) {
    console.warn(`[KIWI] No Brevo API keys configured. Would have sent "${templateName}" to ${toEmail}. Set BREVO_API_KEY env var to enable emails.`);
    return false;
  }
  // Resolve app URL once — works on Render (APP_URL), Replit (REPLIT_DOMAINS), or local dev
  const appUrl = process.env.APP_URL
    || (process.env.REPLIT_DOMAINS ? 'https://' + process.env.REPLIT_DOMAINS.split(',')[0].trim() : '')
    || 'https://kiwi.app';
  params = { ...params, appUrl };
  const templates = {
    welcome: {
      subject: 'Welcome to KIWI 🥝',
      htmlContent: `<html><body><h1>Welcome to KIWI</h1><p>Hi ${params.name || 'Learner'},</p><p>Your spaced-repetition journey begins now. Start by adding a subject and creating your first deck.</p></body></html>`,
    },
    exam_result: {
      subject: 'Your KIWI Exam Results',
      htmlContent: `<html><body><h1>Exam Complete</h1><p>Subject: ${params.subjectName || 'Study Session'}</p><p>Score: ${params.scorePct || 0}%</p><p>${params.passed ? 'You passed! 🎉' : 'Keep practicing — mastery takes time.'}</p></body></html>`,
    },
    streak_danger: {
      subject: '⚠️ KIWI Streak in Danger',
      htmlContent: `<html><body><h1>Streak Alert</h1><p>Your ${params.streak || 0}-day streak is about to break. Do today's review to keep it alive!</p></body></html>`,
    },
    streak_broken: {
      subject: 'KIWI Streak Broken',
      htmlContent: `<html><body><h1>Streak Reset</h1><p>Your ${params.streak || 0}-day streak has ended. Every ending is a new beginning — start again today.</p></body></html>`,
    },
    weekly_digest: {
      subject: 'Your Weekly KIWI Chronicle 🥝',
      htmlContent: `<html><body style="background:#030d0b;color:#dff2eb;font-family:sans-serif;padding:24px;">
<h1 style="color:#52b788;">🥝 Your Week in KIWI</h1>
<p>Hi ${params.name || 'Learner'},</p>
<p>Here's what you accomplished this week:</p>
<table style="border-collapse:collapse;width:100%;max-width:400px;margin:16px 0;">
  <tr><td style="padding:8px 0;border-bottom:1px solid #1b4332;">📚 Reviews completed</td><td style="padding:8px 0;border-bottom:1px solid #1b4332;text-align:right;"><strong>${params.reviews || 0}</strong></td></tr>
  <tr><td style="padding:8px 0;border-bottom:1px solid #1b4332;">📝 Exams taken</td><td style="padding:8px 0;border-bottom:1px solid #1b4332;text-align:right;"><strong>${params.exams || 0}</strong></td></tr>
  <tr><td style="padding:8px 0;">📈 Knowledge score change</td><td style="padding:8px 0;text-align:right;"><strong>${params.ksDelta >= 0 ? '+' : ''}${params.ksDelta || 0}%</strong></td></tr>
</table>
${params.streak > 0 ? `<p>🔥 Current streak: <strong>${params.streak} days</strong> — keep it going!</p>` : ''}
<p><a href="${params.appUrl}" style="background:#2d6a4f;color:#dff2eb;padding:10px 20px;border-radius:8px;text-decoration:none;display:inline-block;margin-top:8px;">Open KIWI →</a></p>
<p style="color:#4a7a65;font-size:12px;margin-top:24px;">You are receiving this weekly digest because you have email notifications enabled. Turn off in Settings → Notifications.</p>
</body></html>`,
    },
    contact_form: {
      subject: `[KIWI Contact] Message from ${params.name || 'Unknown'} <${params.email || ''}>`,
      htmlContent: `<html><body style="font-family:sans-serif;padding:24px;">
<h2>New Contact Form Submission</h2>
<p><strong>From:</strong> ${params.name || 'Unknown'} &lt;${params.email || 'no email'}&gt;</p>
<p><strong>Received:</strong> ${params.received_at || new Date().toISOString()}</p>
<hr style="border:1px solid #ccc;margin:16px 0;"/>
<p><strong>Message:</strong></p>
<p style="white-space:pre-wrap;">${params.message || '(no message)'}</p>
</body></html>`,
    },
    daily_login_reminder: {
      subject: params.slot === 'afternoon'
        ? `⏰ Still time to study today, ${params.name || 'Learner'}!`
        : `☀️ Your KIWI cards are ready, ${params.name || 'Learner'}!`,
      htmlContent: `<html><body style="background:#030d0b;color:#dff2eb;font-family:sans-serif;padding:24px;">
<h1 style="color:#52b788;">🥝 KIWI</h1>
<p>Hi ${params.name || 'Learner'},</p>
${params.slot === 'afternoon'
  ? `<p>The afternoon is still yours. ${params.streak > 0 ? `Your <strong>${params.streak}-day streak</strong> is on the line — a quick review is all it takes.` : 'Start a new streak today with even 5 minutes of review.'}</p>`
  : `<p>Good morning! Your spaced-repetition cards are due today. ${params.streak > 0 ? `You're on a <strong>${params.streak}-day streak</strong> — keep it alive!` : 'Start your first streak today!'}</p>`
}
<p><a href="${params.appUrl}" style="background:#2d6a4f;color:#dff2eb;padding:10px 20px;border-radius:8px;text-decoration:none;display:inline-block;margin-top:8px;">Open KIWI →</a></p>
<p style="color:#4a7a65;font-size:12px;margin-top:24px;">You are receiving this because you have login reminders enabled. Turn off in Settings → Notifications.</p>
</body></html>`,
    },
  };
  const tpl = templates[templateName] || templates.welcome;
  const acct = _pickBrevoAccount();
  if (!acct) {
    console.error('[KIWI] All Brevo accounts exhausted for today.');
    return false;
  }
  const result = await _sendViaBrevo(acct, toEmail, tpl.subject, tpl.htmlContent);
  // Auto-fallback if first account hit daily limit
  if (!result.success && (result.error || '').toLowerCase().includes('limit')) {
    const fallback = _pickBrevoAccount();
    if (fallback && fallback !== acct) {
      console.warn(`[KIWI] Brevo account hit limit — retrying with fallback`);
      const r2 = await _sendViaBrevo(fallback, toEmail, tpl.subject, tpl.htmlContent);
      return r2.success;
    }
  }
  if (!result.success) console.error('[KIWI] Brevo send failed:', result.error);
  return result.success;
}
async function sendEmailNotification(userId, templateName, params = {}) {
  try {
    const user = await db.users.findById(userId);
    if (!user) return;
    const prefs = user.notification_preferences || {};
    if (prefs.email === false) return;
    if (!user.email) return;
    await sendBrevoEmail(user.email, templateName, params);
  } catch (e) {
    console.error('[KIWI] Email notification failed:', e.message);
  }
}

async function startServer() {
try {
await runSchemaMigrations();
try {
  await _aiRuntime.initialize();
} catch (e) {
  console.error('[KIWI AI] Orchestrator initialization failed; AI requests paused and automatic recovery scheduled:', e.message);
}

try {
  await teachingRuntimePlatform.initialize();
  teachingRuntimePlatform.start();
  console.log('[KIWI Teaching] D05 runtime initialized; due-event and durable outbox workers started.');
} catch (e) {
  // Fail closed: never substitute an in-memory/browser academic-time or event
  // owner. Until domain subscribers exist, an unexpected outbox event also
  // remains durable/retryable rather than being marked published to nowhere.
  console.error(
    '[KIWI Teaching] D05 runtime unavailable; Teaching due/outbox execution remains fail-closed:',
    e.message
  );
}
try {
  await teachingRouter.assertD07Ready();
  console.log('[KIWI Teaching] D07 Course Intake runtime verified; authoritative schema is ready.');
} catch (e) {
  console.error('[KIWI Teaching] D07 Course Intake runtime unavailable; Course setup remains fail-closed:', e.message);
}
try {
  await teachingRouter.assertD08Ready();
  console.log('[KIWI Teaching] D08 Course Plan/Coverage runtime verified; authoritative schema is ready.');
} catch (e) {
  console.error('[KIWI Teaching] D08 Course Plan/Coverage runtime unavailable; Stage 2 review remains fail-closed:', e.message);
}
try {
  await teachingRouter.assertD09Ready();
  console.log('[KIWI Teaching] D09 Semester/Scheduling runtime verified; Scheduler schema is ready.');
} catch (e) {
  console.error('[KIWI Teaching] D09 Semester/Scheduling runtime unavailable; Stage 4/5 remains fail-closed:', e.message);
}
try {
  await teachingRouter.assertD10Ready();
  console.log('[KIWI Teaching] D10 Course Lifecycle/Request runtime verified; activation and formal Requests are ready.');
} catch (e) {
  console.error('[KIWI Teaching] D10 Course Lifecycle/Request runtime unavailable; activation/Requests remain fail-closed:', e.message);
}
try {
  await teachingRouter.assertD11Ready();
  console.log('[KIWI Teaching] D11 Lesson Blueprint/Controller runtime verified; deterministic Class control is ready and model routes remain D30-held.');
} catch (e) {
  console.error('[KIWI Teaching] D11 Lesson Blueprint/Controller runtime unavailable; Class control remains fail-closed:', e.message);
}
try {
  await teachingRouter.assertD12Ready();
  console.log('[KIWI Teaching] D12 Response Evaluation/Pedagogy runtime verified; durable response/event contracts are ready and model routes remain D30-held.');
} catch (e) {
  console.error('[KIWI Teaching] D12 Response Evaluation/Pedagogy runtime unavailable; D12 response interpretation remains fail-closed:', e.message);
}
try {
  await teachingRouter.assertD13Ready();
  console.log('[KIWI Teaching] D13 Student Knowledge Model runtime verified; deterministic evidence/state contracts are ready and TPF-09/TPF-19 routes remain D30-held.');
} catch (e) {
  console.error('[KIWI Teaching] D13 Student Knowledge Model runtime unavailable; SKM mutation remains fail-closed:', e.message);
}
try {
  await teachingRouter.assertD14Ready();
  console.log('[KIWI Teaching] D14 Classroom artifacts verified; TPF-19/TPF-20 routes and Study Pack publication remain held.');
} catch (e) {
  console.error('[KIWI Teaching] D14 Classroom artifacts unavailable; Classroom artifact routes remain fail-closed:', e.message);
}
// Seed functions are best-effort — missing tables should never crash the server
try { await seedAchievements(); } catch(e) { console.warn('[KIWI] Achievement seeding skipped:', e.message); }
try { await db.marketplaceItems.seed(); } catch(e) { console.warn('[KIWI] Marketplace seeding skipped:', e.message); }
// seedCommunityDecks removed — community library is user-populated only
console.log(`[KIWI] ✅ Startup seeding complete (non-fatal errors may appear above if DB tables are missing)`);


    // ════════════════════════════════════════════════════════════════════════════
    //  TELEGRAM BOT INTEGRATION

    // ════════════════════════════════════════════════════════════════════════════
    const TELEGRAM_BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN;
    async function sendTelegramMessage(chatId, text) {
      if (!TELEGRAM_BOT_TOKEN || !chatId) return false;
      try {
        const url = `https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage`;
        const res = await fetch(url, {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify({ chat_id: chatId, text, parse_mode: 'Markdown' }),
        });
        return res.ok;
      } catch (e) {
        console.error('[KIWI] Telegram send failed:', e.message);
        return false;
      }
    }
    async function sendTelegramExamResult(userId, subjectId, scorePct, passed) {
      try {
        const user = await db.users.findById(userId);
        if (!user) return;
        const prefs = user.notification_preferences || {};
        if (prefs.telegram === false) return;
        if (!user.telegram_chat_id) return;
        const subject = await db.subjects.findById(subjectId).catch(() => null);
        const subjName = subject?.name || 'Study Session';
        const status = passed ? '✅ PASSED' : '❌ Did not pass';
        await sendTelegramMessage(
          user.telegram_chat_id,
          `*Exam Result: ${subjName}*\nScore: *${scorePct}%*\nStatus: ${status}`
        );
      } catch (e) {
        console.error('[KIWI] Telegram exam notify failed:', e.message);
      }
    }
    async function sendTelegramDailyReminder(userId) {
      try {
        const user = await db.users.findById(userId);
        if (!user) return;
        const prefs = user.notification_preferences || {};
        if (prefs.telegram === false) return;
        if (!user.telegram_chat_id) return;
        await sendTelegramMessage(
          user.telegram_chat_id,
          `🥝 *KIWI Daily Reminder*\nYour cards are waiting. Keep the streak alive!`
        );
      } catch (e) {
        console.error('[KIWI] Telegram reminder failed:', e.message);
      }
    }
    // Telegram webhook handler
    async function handleTelegramWebhook(body) {
      const msg = body.message;
      if (!msg || !msg.text) return;
      const chatId = msg.chat.id;
      const text = msg.text.trim();
      const cmd = text.split(' ')[0].toLowerCase();
      // Link telegram to user on /start
      if (cmd === '/start') {
        // Check if user exists with this chat_id
        const { rows: _existingRows } = await query(
          'SELECT id FROM users WHERE telegram_chat_id = $1 LIMIT 1',
          [String(chatId)]
        );
        if (_existingRows.length > 0) {
          return sendTelegramMessage(
            chatId,
            'Welcome back to KIWI 🥝! Your account is already linked. Use /status, /streak, or /due.'
          );
        }
        // Try to match by start token if provided
        const token = text.split(' ')[1];
        if (token) {
          const { rows: _tokenRows } = await query(
            'SELECT id FROM users WHERE telegram_link_token = $1 LIMIT 1',
            [token]
          );
          if (_tokenRows.length > 0) {
            const userId = _tokenRows[0].id;
            await db.users.update(userId, { telegram_chat_id: String(chatId) });
            return sendTelegramMessage(
              chatId,
              '✅ KIWI account linked successfully! Use /status, /streak, or /due.'
            );
          }
        }
        return sendTelegramMessage(
          chatId,
          'Welcome to KIWI 🥝!\nTo link your account, visit Settings in the app and copy your Telegram link token, then send:\n/start '
        );
      }
      // Find user by chat_id
      const { rows: _chatRows } = await query(
        'SELECT * FROM users WHERE telegram_chat_id = $1 LIMIT 1',
        [String(chatId)]
      );
      if (_chatRows.length === 0) {
        return sendTelegramMessage(
          chatId,
          'Account not linked. Visit the app Settings → Notifications to connect Telegram.'
        );
      }
      const userId = _chatRows[0].id;
      const user = _chatRows[0];
      if (cmd === '/status') {
        const stats = await db.userStats.get(userId).catch(() => ({}));
        const streak = stats?.current_streak || 0;
        const seeds = stats?.seedlings_balance || 0; // BUG 5 FIX: correct field name
        return sendTelegramMessage(
          chatId,
          `🥝 *KIWI Status*\nStreak: *${streak}* days\nSeedlings: *${seeds}*`
        );
      }
      if (cmd === '/streak') {
        const stats = await db.userStats.get(userId).catch(() => ({}));
        const streak = stats?.current_streak || 0;
        const longest = stats?.longest_streak || 0;
        return sendTelegramMessage(
          chatId,
          `🔥 *Streak*\nCurrent: *${streak}* days\nLongest: *${longest}* days`
        );
      }
      if (cmd === '/due') {
        // Fix #54: 1 findAllForUser read instead of N per-deck Firestore queries
        const today = new Date().toISOString().slice(0, 10);
        const allCards = await db.cards.findAllForUser(userId);
        const totalDue = allCards.filter(c => !c.due || c.due <= today).length;
        return sendTelegramMessage(chatId, `📚 *Due Cards*\nTotal due today: *${totalDue}*`);
      }
      if (cmd === '/help') {
        return sendTelegramMessage(
          chatId,
          `🥝 *KIWI Bot Commands*\n/status — Overview\n/streak — Streak info\n/due — Cards due today\n/help — This message`
        );
      }
      return sendTelegramMessage(chatId, 'Unknown command. Try /help');
    }

    // ════════════════════════════════════════════════════════════════════════════
    //  INPUT VALIDATION MIDDLEWARE

    // ════════════════════════════════════════════════════════════════════════════
    function validatePayload(schema) {
      return (req, res, next) => {
        const errors = [];
        for (const [key, rules] of Object.entries(schema)) {
          const val = req.body[key];
          if (rules.required && (val === undefined || val === null)) {
            errors.push(`${key} is required`);
            continue;
          }
          if (val !== undefined && val !== null) {
            if (rules.type === 'string' && typeof val !== 'string')
              errors.push(`${key} must be a string`);
            if (rules.type === 'number' && typeof val !== 'number')
              errors.push(`${key} must be a number`);
            if (rules.type === 'boolean' && typeof val !== 'boolean')
              errors.push(`${key} must be a boolean`);
            if (rules.type === 'array' && !Array.isArray(val))
              errors.push(`${key} must be an array`);
            if (rules.enum && !rules.enum.includes(val))
              errors.push(`${key} must be one of ${rules.enum.join(', ')}`);
            if (rules.minLength !== undefined && String(val).length < rules.minLength)
              errors.push(`${key} must be at least ${rules.minLength} characters`);
            if (rules.maxLength !== undefined && String(val).length > rules.maxLength)
              errors.push(`${key} must be at most ${rules.maxLength} characters`);
            if (rules.pattern && !rules.pattern.test(String(val)))
              errors.push(`${key} format is invalid`);
          }
        }
        if (errors.length > 0) {
          return res.status(400).json({ error: 'Validation failed', details: errors });
        }
        next();
      };
    }
    // Telegram webhook endpoint
    app.post('/telegramWebhook', async (req, res) => {
      try {
        await handleTelegramWebhook(req.body);
        res.sendStatus(200);
      } catch (e) {
        console.error('[KIWI] Telegram webhook error:', e.message);
        res.sendStatus(200); // Always return 200 to Telegram
      }
    });
    // Notification preferences endpoint
    app.post('/api/settings/notifications', authenticate, async (req, res) => {
      try {
        const { email, telegram } = req.body;
        // Section 4.7: JSONB dot-notation update → jsonb `||` merge
        const patch = {};
        if (typeof email === 'boolean') patch.email = email;
        if (typeof telegram === 'boolean') patch.telegram = telegram;
        await query(
          `UPDATE users SET notification_preferences = notification_preferences || $1::jsonb, updated_at = NOW() WHERE id = $2`,
          [JSON.stringify(patch), req.user.id]
        );
        res.json({ success: true, preferences: { email, telegram } });
      } catch (e) {
        res.status(500).json({ error: 'Failed to update preferences', details: e.message });
      }
    });

    // ── TEST: Send test email to authenticated user ──────────────────────────────
    app.post('/api/notifications/test-email', authenticate, async (req, res) => {
      try {
        const user = await db.users.findById(req.user.id);
        if (!user) return res.status(404).json({ error: 'User not found' });
        if (!user.email) return res.status(400).json({ error: 'No email address on account' });
        if (_brevoAccounts.length === 0) {
          return res.status(503).json({ error: 'Email service not configured (BREVO_API_KEY missing)' });
        }
        await sendBrevoEmail(user.email, 'welcome', { name: user.username || 'Learner' });
        res.json({ success: true, message: `Test email sent to ${user.email}` });
      } catch (e) {
        res.status(500).json({ error: 'Test email failed', details: e.message });
      }
    });

    // ── TEST: Send test Telegram message to authenticated user ───────────────────
    app.post('/api/notifications/test-telegram', authenticate, async (req, res) => {
      try {
        const user = await db.users.findById(req.user.id);
        if (!user) return res.status(404).json({ error: 'User not found' });
        if (!user.telegram_chat_id) {
          return res.status(400).json({
            error: 'Telegram not linked',
            hint: `Start a chat with the bot and send: /start ${user.telegram_link_token || '<your token>'}`,
          });
        }
        const ok = await sendTelegramMessage(
          user.telegram_chat_id,
          `🥝 *KIWI Test Notification*\nTelegram is working. Your notifications are connected!`
        );
        if (!ok) return res.status(503).json({ error: 'Telegram send failed — check TELEGRAM_BOT_TOKEN' });
        res.json({ success: true, message: 'Test Telegram message sent.' });
      } catch (e) {
        res.status(500).json({ error: 'Test Telegram failed', details: e.message });
      }
    });

    // ── ADMIN: Auto-set Telegram webhook URL ─────────────────────────────────────
    app.post('/api/admin/set-webhook', authenticate, async (req, res) => {
      try {
        const _adminUser = await db.users.findById(req.user.id);
        if (!_adminUser || _adminUser.role !== 'admin') {
          return res.status(403).json({ error: 'Admin only' });
        }
        if (!TELEGRAM_BOT_TOKEN) {
          return res.status(400).json({ error: 'TELEGRAM_BOT_TOKEN not configured on server' });
        }
        // Build webhook URL from request headers (Railway sets x-forwarded-host)
        const host = req.headers['x-forwarded-host'] || req.headers.host || 'localhost';
        const proto = req.headers['x-forwarded-proto'] || (host.includes('localhost') ? 'http' : 'https');
        const webhookUrl = `${proto}://${host}/telegramWebhook`;
        const tgRes = await fetch(`https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/setWebhook`, {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify({ url: webhookUrl, allowed_updates: ['message'] }),
        });
        const tgData = await tgRes.json();
        if (tgData.ok) {
          console.log(`[KIWI] Telegram webhook set to: ${webhookUrl}`);
          res.json({ success: true, webhook_url: webhookUrl, telegram_response: tgData });
        } else {
          res.status(400).json({ error: 'Telegram rejected webhook', details: tgData.description, attempted_url: webhookUrl });
        }
      } catch (e) {
        res.status(500).json({ error: 'Set webhook failed', details: e.message });
      }
    });

    // ── Error handling — registered last so all routes above are matched first ──
    app.use((req, res) => {
      res.status(404).json({ error: 'Not found', path: req.path });
    });
    app.use((err, req, res, next) => {
      console.error('[KIWI ERROR]', err);
      res.status(err.status || 500).json({ error: err.message || 'Internal server error' });
    });

    // ── Ensure background_jobs table exists (idempotent — runs on every startup) ──
    // This table backs the DB-fallback job polling and survives server restarts.
    await pool.query(`
      CREATE TABLE IF NOT EXISTS background_jobs (
        id          TEXT        PRIMARY KEY,
        status      TEXT        NOT NULL DEFAULT 'pending',
        type        TEXT        NOT NULL,
        result      JSONB,
        error       TEXT,
        expires_at  TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '10 minutes'),
        created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `).catch(e => console.warn('[KIWI] background_jobs table creation skipped:', e.message));
    // Clean up expired jobs older than 1 hour (fire-and-forget, best-effort)
    pool.query(`DELETE FROM background_jobs WHERE expires_at < NOW() - INTERVAL '1 hour'`).catch(() => {});

    // Run startup recovery before accepting requests
    ensureKSDeltaColumn().catch(e => console.error('[KIWI] Column migration failed:', e.message));
    ensureCommunityDeckAuthorColumn().catch(e => console.error('[KIWI] community_decks author_name migration failed:', e.message));
    recoverInterruptedExams().catch(e => console.error('[KIWI] Startup recovery failed:', e.message));

    const _httpServer = app.listen(PORT, () => {
      console.log(`[KIWI] 🥝 Living Ecosystem backend running on port ${PORT}`);
      console.log(`[KIWI] Environment: ${process.env.NODE_ENV || 'development'}`);
      startSelfHealthPing();
    });
    // ── WebSocket server ──────────────────────────────────────────────────────
    const _wss = new WebSocketServer({ server: _httpServer });
    _wss.on('connection', (ws, req) => {
      let _wsUserId = null;
      try {
        const _url = new URL(req.url, 'http://localhost');
        const _tok = _url.searchParams.get('token');
        if (!_tok) { ws.close(4001, 'Unauthorized'); return; }
        const _dec = jwt.verify(_tok, JWT_SECRET);
        _wsUserId = String(_dec.id || _dec.userId || _dec.sub || '');
        if (!_wsUserId) { ws.close(4001, 'Unauthorized'); return; }
        if (!_wsClients.has(_wsUserId)) _wsClients.set(_wsUserId, new Set());
        _wsClients.get(_wsUserId).add(ws);
        ws.send(JSON.stringify({ event: 'connected', data: { userId: _wsUserId }, ts: Date.now() }));
        console.log(`[KIWI WS] User ${_wsUserId} connected`);
      } catch (_e) { ws.close(4001, 'Unauthorized'); return; }
      ws.on('close', () => {
        if (_wsUserId) {
          const _set = _wsClients.get(_wsUserId);
          if (_set) { _set.delete(ws); if (_set.size === 0) _wsClients.delete(_wsUserId); }
        }
      });
      ws.on('error', () => { try { ws.close(); } catch (_) {} });
    });
    console.log('[KIWI WS] WebSocket server ready');

} catch (e) {
console.error('[KIWI] Failed to start server:', e);
process.exit(1);
}
}
startServer();
