'use strict';

const D20_CONTRACT_VERSION='d20.marking-gradebook.v1';
const TPF15=Object.freeze({family:'TPF-15',version:'1.0',sha256:'a088a74f044082abb126952939bc3fe627b273b1cfea166833fae87afbc8dcdb'});
const TPF16=Object.freeze({family:'TPF-16',version:'1.0',sha256:'278c45b97de8ceff9e6307543bea1072d51d244ccf21b7b16ca8a98d3c5daeda'});
const DEFAULT_CATEGORY_WEIGHTS=Object.freeze({CLASSWORK:0.10,HOMEWORK:0.05,IMPROMPTU:0.10,SCHEDULED_TEST:0.15,MID_SEMESTER:0.20,FINAL_EXAMINATION:0.40});
const RESULT_LIFECYCLE=Object.freeze(['MARKING','MODERATING','PROVISIONAL','MODERATED','RELEASED','APPEALABLE','FINALIZED']);
const REVIEW_STATES=Object.freeze(new Set(['ordinary','borderline','rubric_precision_gap','material_ambiguity','possible_rubric_defect','possible_item_defect','insufficient_marking_context','moderation_required']));
const SATISFACTION=Object.freeze(new Set(['full','partial','none','unable_to_judge']));
const FORBIDDEN_MARKING_CONTEXT_KEYS=Object.freeze(new Set([
  'student_identity','student_name','demographics','attendance','attendance_history','teacher_personality','personality','previous_gpa','gpa','peer_performance','effort_history','current_course_total','course_total','grade_boundary_position','desired_progression_outcome','integrity_suspicion','integrity_telemetry','behavior_history','unrelated_grades','prior_grades','scheduling_behavior','student_reputation'
]));
const FORBIDDEN_MODEL_OUTPUT_KEYS=Object.freeze(new Set(['official_total','official_mark','official_grade','gradebook_write','gradebook_entry','course_score','topic_score','gpa','progression_outcome','finalize_assessment','rounding_result','category_weight']));

function fail(message,code='TEACHING_D20_CONTRACT_INVALID',status=409,details=null){const e=new Error(message);e.code=code;e.status=status;if(details)e.details=details;throw e;}
function asObject(v){return v&&typeof v==='object'&&!Array.isArray(v)?v:{};}
function asArray(v){return Array.isArray(v)?v:[];}
function upper(v){return String(v||'').trim().toUpperCase();}
function number(v,label){const n=Number(v);if(!Number.isFinite(n))fail(`${label} must be a finite number.`,'TEACHING_D20_NUMBER_INVALID',400,{label,value:v});return n;}
function clamp(n,min,max){return Math.max(min,Math.min(max,n));}
function normalizedText(v){return String(v??'').trim().replace(/\s+/g,' ');}
function canonicalSymbolic(v){return normalizedText(v).toLowerCase().replace(/\s+/g,'').replace(/×/g,'*').replace(/÷/g,'/').replace(/[−–—]/g,'-');}
function stableUnique(values){return [...new Set(asArray(values).map(String).filter(Boolean))].sort();}

function categoryForAssessment(type,sourceLineage={}){
  const t=upper(type);
  if(t==='CLASSWORK')return 'CLASSWORK';
  if(t==='IMPROMPTU_TEST')return 'IMPROMPTU';
  if(t==='SCHEDULED_TEST')return 'SCHEDULED_TEST';
  if(t==='MID_SEMESTER')return 'MID_SEMESTER';
  if(t==='FINAL_EXAMINATION')return 'FINAL_EXAMINATION';
  if(t==='MAKE_UP'){
    const source=upper(sourceLineage?.make_up?.source_assessment_type||sourceLineage?.source_assessment_type||sourceLineage?.d19_make_up?.source_assessment_type);
    if(!source)fail('Make-Up Gradebook category requires source Assessment type lineage.','TEACHING_D20_MAKE_UP_CATEGORY_LINEAGE_REQUIRED');
    return categoryForAssessment(source,sourceLineage);
  }
  if(['DIAGNOSTIC','VERIFICATION'].includes(t))return null;
  if(t==='RESIT')fail('Resit grade policy remains owned by D21.','TEACHING_D20_RESIT_D21_OWNER',409,{owner:'D21'});
  fail('Assessment type has no D20 Gradebook category.','TEACHING_D20_CATEGORY_UNKNOWN',400,{assessmentType:type});
}

function normalizeWeights(input={}){
  const raw=asObject(input);const source={...DEFAULT_CATEGORY_WEIGHTS,...raw};
  if(Object.prototype.hasOwnProperty.call(raw,'FINAL')&&!Object.prototype.hasOwnProperty.call(raw,'FINAL_EXAMINATION'))source.FINAL_EXAMINATION=raw.FINAL;
  const out={};let sum=0;
  for(const key of Object.keys(DEFAULT_CATEGORY_WEIGHTS)){const n=number(source[key],`category weight ${key}`);if(n<0||n>1)fail('Category weight must be between 0 and 1.','TEACHING_D20_CATEGORY_WEIGHT_INVALID',400,{key,n});out[key]=n;sum+=n;}
  if(Math.abs(sum-1)>1e-9)fail('Grading Policy category weights must sum to 1.','TEACHING_D20_CATEGORY_WEIGHTS_NOT_100',400,{sum});
  return Object.freeze(out);
}
function normalizeRoundingPolicy(input={}){
  const p=asObject(input),mode=upper(p.mode||'NONE');
  if(mode==='NONE')return Object.freeze({mode:'NONE'});
  const decimals=Number.isInteger(p.decimals)?p.decimals:0;
  if(decimals<0||decimals>4)fail('Rounding decimals must be 0-4.','TEACHING_D20_ROUNDING_INVALID',400);
  if(!['HALF_UP','FLOOR','CEIL','TRUNCATE'].includes(mode))fail('Unsupported rounding mode.','TEACHING_D20_ROUNDING_INVALID',400,{mode});
  return Object.freeze({mode,decimals});
}
function roundConfigured(value,policy={}){const n=number(value,'rounding value'),p=normalizeRoundingPolicy(policy);if(p.mode==='NONE')return n;const factor=10**p.decimals,x=n*factor;let y;if(p.mode==='FLOOR')y=Math.floor(x);else if(p.mode==='CEIL')y=Math.ceil(x);else if(p.mode==='TRUNCATE')y=Math.trunc(x);else y=Math.round(x+Number.EPSILON);return y/factor;}

function defaultPolicy({categoryWeights=null,roundingPolicy=null,gradeScalePolicy=null,topicEvidencePolicy=null,essentialOutcomePolicy=null,moderationPolicy=null,appealPolicy=null}={}){
  return Object.freeze({
    contract_version:D20_CONTRACT_VERSION,
    category_weights:normalizeWeights(categoryWeights||{}),
    rounding_policy:normalizeRoundingPolicy(roundingPolicy||{mode:'NONE'}),
    grade_scale_policy:Object.freeze({scale:'KIWI_PERCENTAGE_100_V1',percentage_range:{min:0,max:100},letter_grade:null,grade_point:null,...asObject(gradeScalePolicy)}),
    topic_evidence_policy:Object.freeze({minimum_grade_contributing_events:null,minimum_distinct_assessment_contexts:null,minimum_separate_academic_occasions:null,controlled_independent_evidence_required:null,insufficient_state:'PROVISIONAL_INSUFFICIENT_EVIDENCE',single_small_item_can_finalize_major_topic:false,...asObject(topicEvidencePolicy)}),
    essential_outcome_policy:Object.freeze({...asObject(essentialOutcomePolicy)}),
    moderation_policy:Object.freeze({mid_semester_constructed_response_requires_independent_moderation:true,final_exam_constructed_response_requires_independent_moderation:true,blind_first_pass_required:true,unresolved_material_disagreement_behavior:'REVIEW_NEEDED_NO_FINALIZATION',...asObject(moderationPolicy)}),
    appeal_policy:Object.freeze({default_review_direction:null,repeat_requires_new_authorized_ground:true,...asObject(appealPolicy)}),
  });
}

function assertNoForbiddenContext(value,path='context'){
  if(Array.isArray(value)){value.forEach((v,i)=>assertNoForbiddenContext(v,`${path}[${i}]`));return true;}
  if(!value||typeof value!=='object')return true;
  for(const [k,v] of Object.entries(value)){const key=String(k).toLowerCase();if(FORBIDDEN_MARKING_CONTEXT_KEYS.has(key))fail('Formal marker context contains forbidden student/history context.','TEACHING_D20_T4_CONTEXT_FORBIDDEN',400,{path:`${path}.${k}`});assertNoForbiddenContext(v,`${path}.${k}`);}return true;
}
function markingContextAllowlist(input={}){
  const x=asObject(input);assertNoForbiddenContext(x);
  return Object.freeze({task:asObject(x.task),locked_rubric:asObject(x.locked_rubric),submitted_response:x.submitted_response??null,permitted_source_context:asObject(x.permitted_source_context),necessary_course_context:asObject(x.necessary_course_context),deterministic_checker_outputs:asObject(x.deterministic_checker_outputs),item_validity:asObject(x.item_validity),accessibility_interpretation:asObject(x.accessibility_interpretation),evaluation_purpose:String(x.evaluation_purpose||'graded_candidate'),provenance_refs:Object.freeze(stableUnique(x.provenance_refs))});
}

function extractObjectiveSpec(item){const p=asObject(item?.protected_marking_payload||item?.protectedPayload||item?.marking||{});const pub=asObject(item?.public_item_payload||item?.publicPayload||{});const family=upper(item?.response_family||item?.responseFamily||pub.response_family||p.response_family);return {p,pub,family};}
function responseValue(response){const r=response?.renderer_payload??response?.rendererPayload??response;if(r&&typeof r==='object'){for(const k of ['answer','value','selected','selection','response','text','code'])if(Object.prototype.hasOwnProperty.call(r,k))return r[k];}return r;}
function markMcq(spec,response,maxMarks){const expected=spec.p.correct_answer??spec.p.answer_key??spec.p.correctAnswer??spec.p.correct_option;const accepted=asArray(spec.p.correct_answers).length?asArray(spec.p.correct_answers):[expected];if(accepted.every(v=>v==null))fail('Objective item has no locked answer key.','TEACHING_D20_OBJECTIVE_KEY_MISSING');const actual=responseValue(response);const ok=accepted.map(v=>normalizedText(v)).includes(normalizedText(actual));return {earned:ok?maxMarks:0,max:maxMarks,method:'EXACT_KEY',detail:{correct:ok}};}
function markNumeric(spec,response,maxMarks){const target=number(spec.p.correct_value??spec.p.numeric_answer??spec.p.answer,'numeric answer key'),actual=Number(responseValue(response));if(!Number.isFinite(actual))return {earned:0,max:maxMarks,method:'NUMERIC_TOLERANCE',detail:{correct:false,reason:'NON_NUMERIC_RESPONSE'}};const absTol=Math.max(0,Number(spec.p.absolute_tolerance??spec.p.tolerance??0)||0),relTol=Math.max(0,Number(spec.p.relative_tolerance??0)||0),limit=Math.max(absTol,Math.abs(target)*relTol),ok=Math.abs(actual-target)<=limit+1e-12;return {earned:ok?maxMarks:0,max:maxMarks,method:'NUMERIC_TOLERANCE',detail:{correct:ok,target,tolerance:limit}};}
function markSymbolic(spec,response,maxMarks){const accepted=asArray(spec.p.accepted_forms||spec.p.acceptable_answers||spec.p.correct_answers);if(!accepted.length&&spec.p.answer!=null)accepted.push(spec.p.answer);if(!accepted.length)fail('Symbolic item has no locked accepted forms.','TEACHING_D20_OBJECTIVE_KEY_MISSING');const actual=canonicalSymbolic(responseValue(response)),ok=accepted.map(canonicalSymbolic).includes(actual);return {earned:ok?maxMarks:0,max:maxMarks,method:'SYMBOLIC_CANONICAL_MATCH',detail:{correct:ok}};}
function markStructured(spec,response,maxMarks){const expected=asObject(spec.p.expected_structure||spec.p.answer_structure);const actual=asObject(responseValue(response));const keys=Object.keys(expected);if(!keys.length)fail('Structured objective item lacks expected structure.','TEACHING_D20_OBJECTIVE_KEY_MISSING');const correct=keys.filter(k=>canonicalSymbolic(actual[k])===canonicalSymbolic(expected[k]));const per=maxMarks/keys.length;return {earned:correct.length*per,max:maxMarks,method:'STRUCTURED_FIELD_MATCH',detail:{correct_fields:correct,total_fields:keys.length}};}
function markCodeTests(spec,response,maxMarks){const tests=asArray(spec.p.test_results||spec.p.test_cases);const submitted=asObject(response?.deterministic_test_results||response?.test_results);if(!tests.length)fail('Code objective marking requires locked reliable test cases.','TEACHING_D20_CODE_TESTS_MISSING');if(!submitted||!Array.isArray(submitted.results))fail('Code test results must come from the trusted deterministic runner.','TEACHING_D20_TRUSTED_TEST_RESULTS_REQUIRED');const byId=new Map(submitted.results.map(r=>[String(r.test_id||r.id),Boolean(r.passed)]));let total=0,earned=0;for(const t of tests){const id=String(t.test_id||t.id||'');const w=Math.max(0,Number(t.weight??1)||0);total+=w;if(byId.get(id)===true)earned+=w;}if(total<=0)fail('Code tests have no positive scoring weight.','TEACHING_D20_CODE_TEST_WEIGHT_INVALID');return {earned:maxMarks*(earned/total),max:maxMarks,method:'TRUSTED_CODE_TESTS',detail:{passed_weight:earned,total_weight:total}};}
function deterministicMarkObjective(item,response){const {p,family}=extractObjectiveSpec(item),maxMarks=number(item?.intended_marks??item?.intendedMarks??p.max_marks??p.maxMarks,'item max marks');if(maxMarks<=0)fail('Item max marks must be positive.','TEACHING_D20_ITEM_MAX_INVALID');let result;if(['MCQ','MULTIPLE_CHOICE','SINGLE_CHOICE'].includes(family))result=markMcq({p},response,maxMarks);else if(['NUMERIC','NUMBER','NUMERIC_RESPONSE'].includes(family))result=markNumeric({p},response,maxMarks);else if(['SYMBOLIC','SYMBOLIC_RESPONSE'].includes(family))result=markSymbolic({p},response,maxMarks);else if(['STRUCTURED_OBJECTIVE','STRUCTURED'].includes(family))result=markStructured({p},response,maxMarks);else if(['CODE_TESTS','CODE_OBJECTIVE','PROGRAMMING_TESTS'].includes(family))result=markCodeTests({p},response,maxMarks);else return Object.freeze({resolved:false,reason:'INTERPRETIVE_MARKING_REQUIRED',responseFamily:family,max:maxMarks});return Object.freeze({resolved:true,responseFamily:family,earned:clamp(result.earned,0,maxMarks),max:maxMarks,method:result.method,detail:Object.freeze(result.detail||{})});}

function rubricCriteria(rubric){return asArray(rubric?.criteria||rubric?.rubric_contract?.criteria||rubric?.rubricContract?.criteria);}
function criterionMap(rubric){return new Map(rubricCriteria(rubric).map(c=>[String(c.criterion_id||c.criterionId),c]));}
function assertModelOutputNoAuthority(value,path='output'){if(Array.isArray(value)){value.forEach((v,i)=>assertModelOutputNoAuthority(v,`${path}[${i}]`));return true;}if(!value||typeof value!=='object')return true;for(const [k,v] of Object.entries(value)){if(FORBIDDEN_MODEL_OUTPUT_KEYS.has(String(k).toLowerCase()))fail('Model output attempted an authoritative Gradebook/total decision.','TEACHING_D20_MODEL_AUTHORITY_EXCEEDED',422,{path:`${path}.${k}`});assertModelOutputNoAuthority(v,`${path}.${k}`);}return true;}
function validateCriterionJudgments(output,rubric,{requireFamily='TPF-15'}={}){assertModelOutputNoAuthority(output);if(String(output?.family||requireFamily)!==requireFamily)fail('Marking output prompt family mismatch.','TEACHING_D20_PROMPT_FAMILY_MISMATCH',422);if(output?.review_state&&!REVIEW_STATES.has(String(output.review_state)))fail('Unknown marking review state.','TEACHING_D20_REVIEW_STATE_INVALID',422,{reviewState:output.review_state});const map=criterionMap(rubric),seen=new Set(),normalized=[];for(const j of asArray(output?.criterion_judgments)){const id=String(j?.criterion_id||'');const c=map.get(id);if(!c)fail('Model returned a criterion outside the locked rubric.','TEACHING_D20_CRITERION_OUT_OF_SCOPE',422,{criterionId:id});if(seen.has(id))fail('Duplicate criterion judgment.','TEACHING_D20_CRITERION_DUPLICATE',422,{criterionId:id});seen.add(id);const max=number(c.criterion_max_marks??c.criterionMaxMarks,'criterion max marks'),credit=j.proposed_credit==null?null:number(j.proposed_credit,'proposed credit');if(credit!=null&&(credit<0||credit>max))fail('Criterion credit is outside locked bounds.','TEACHING_D20_CRITERION_CREDIT_OUT_OF_BOUNDS',422,{criterionId:id,credit,max});const sat=String(j.satisfaction||'unable_to_judge');if(!SATISFACTION.has(sat))fail('Criterion satisfaction is invalid.','TEACHING_D20_CRITERION_SATISFACTION_INVALID',422,{criterionId:id});const precision=String(c.credit_precision||'exact_points');if(precision==='ranged_band'&&credit!=null&&!c.within_band_selection_rule)fail('Exact credit cannot be invented inside an unruled ranged band.','TEACHING_D20_RUBRIC_PRECISION_GAP',409,{criterionId:id});normalized.push(Object.freeze({criterion_id:id,criterion_max_marks:max,proposed_credit:credit,proposed_band_id:j.proposed_band_id||null,supported_credit_range:j.supported_credit_range||null,satisfaction:sat,evidence_refs:Object.freeze(stableUnique(j.evidence_refs)),evidence_summary:String(j.evidence_summary||'').slice(0,2000),review_state:String(j.review_state||output.review_state||'ordinary'),confidence:String(j.confidence||'low'),alternative_valid_route_used:Boolean(j.alternative_valid_route_used),follow_through_applied:Boolean(j.follow_through_applied),defect_flags:Object.freeze(asArray(j.defect_flags||output.defect_flags).slice(0,20))}));}return Object.freeze(normalized);}
function deterministicAggregateCriteria(judgments,rubric,{roundingPolicy={mode:'NONE'}}={}){const map=criterionMap(rubric),rows=asArray(judgments);let earned=0,max=0;for(const c of map.values())max+=number(c.criterion_max_marks??c.criterionMaxMarks,'criterion max marks');for(const j of rows){if(j.proposed_credit==null)fail('Cannot aggregate unresolved criterion credit.','TEACHING_D20_UNRESOLVED_CREDIT');earned+=number(j.proposed_credit,'criterion credit');}for(const cap of asArray(rubric?.global_caps_or_dependencies)){if(cap?.type==='MAX_TOTAL'&&Number.isFinite(Number(cap.max_marks)))earned=Math.min(earned,Number(cap.max_marks));}earned=clamp(earned,0,max);return Object.freeze({earned:roundConfigured(earned,roundingPolicy),max:roundConfigured(max,roundingPolicy),percentage:max>0?roundConfigured(earned/max*100,roundingPolicy):0});}

function withinCategoryWeights(entries){const active=asArray(entries).filter(e=>upper(e.entry_state)!=='INVALIDATED');if(!active.length)return new Map();const explicit=active.every(e=>Number.isFinite(Number(e.explicit_within_category_weight)));if(explicit){const total=active.reduce((s,e)=>s+Number(e.explicit_within_category_weight),0);if(total<=0)fail('Within-category explicit weights must have positive total.','TEACHING_D20_WITHIN_CATEGORY_WEIGHT_INVALID');return new Map(active.map(e=>[String(e.source_ref),Number(e.explicit_within_category_weight)/total]));}const equal=1/active.length;return new Map(active.map(e=>[String(e.source_ref),equal]));}
function calculateCategoryLedger(entries,weights,roundingPolicy){const grouped=new Map();for(const e of asArray(entries).filter(x=>upper(x.entry_state)!=='INVALIDATED')){const key=upper(e.category_key);if(!grouped.has(key))grouped.set(key,[]);grouped.get(key).push(e);}const breakdown={};let course=0;for(const [key,rows] of grouped){const budget=Number(weights[key]??0),w=withinCategoryWeights(rows);let pct=0;for(const e of rows)pct+=(Number(e.raw_percentage)||0)*(w.get(String(e.source_ref))||0);const contribution=pct*budget;breakdown[key]={category_weight:budget,category_percentage:roundConfigured(pct,roundingPolicy),course_contribution:roundConfigured(contribution,roundingPolicy),entry_count:rows.length};course+=contribution;}return Object.freeze({score_percentage:roundConfigured(course,roundingPolicy),category_breakdown:Object.freeze(breakdown)});}
function calculateCourseScore(entries,policy){const p=policy?.category_weights?policy:defaultPolicy(policy);return calculateCategoryLedger(entries,p.category_weights,p.rounding_policy);}
function configuredThreshold(value){return value!=null&&Number.isFinite(Number(value))?Number(value):null;}
function topicScore(entries,policy,{topicId,essentialOutcomes=[]}={}){const p=policy?.category_weights?policy:defaultPolicy(policy),rows=asArray(entries).filter(e=>asArray(e.topic_ids).map(String).includes(String(topicId))&&upper(e.entry_state)!=='INVALIDATED'),ep=p.topic_evidence_policy||{},contexts=new Set(rows.map(e=>String(e.category_key))),occasions=new Set(rows.map(e=>String(e.academic_occasion_ref||e.source_ref))),controlled=rows.some(e=>Boolean(e.controlled_independent));const minEvents=configuredThreshold(ep.minimum_grade_contributing_events),minContexts=configuredThreshold(ep.minimum_distinct_assessment_contexts),minOccasions=configuredThreshold(ep.minimum_separate_academic_occasions),controlledRule=typeof ep.controlled_independent_evidence_required==='boolean'?ep.controlled_independent_evidence_required:null;const sufficiencyConfigured=[minEvents,minContexts,minOccasions,controlledRule].some(v=>v!==null);const sufficient=sufficiencyConfigured&&(minEvents===null||rows.length>=minEvents)&&(minContexts===null||contexts.size>=minContexts)&&(minOccasions===null||occasions.size>=minOccasions)&&(controlledRule!==true||controlled);const ledger=rows.length?calculateCategoryLedger(rows,p.category_weights,p.rounding_policy):{score_percentage:null,category_breakdown:{}};const flags=asArray(essentialOutcomes).map(o=>({outcome_ref:String(o.outcome_ref||o.id),threshold:Number(o.threshold),met:ledger.score_percentage==null?null:ledger.score_percentage>=Number(o.threshold)}));return Object.freeze({score_percentage:ledger.score_percentage,score_state:sufficient?'FINALIZED':String(ep.insufficient_state||'PROVISIONAL_INSUFFICIENT_EVIDENCE'),evidence_count:rows.length,distinct_context_count:contexts.size,distinct_occasion_count:occasions.size,controlled_independent_present:controlled,category_breakdown:ledger.category_breakdown,essential_outcome_flags:Object.freeze(flags),sufficiency_policy_configured:sufficiencyConfigured});}

function moderationRequired({assessmentType,hasConstructedResponse,policy,reviewState='ordinary'}={}){const type=upper(assessmentType),p=asObject(policy);if(['borderline','rubric_precision_gap','material_ambiguity','possible_rubric_defect','possible_item_defect','moderation_required'].includes(String(reviewState)))return true;if(!hasConstructedResponse)return false;if(type==='MID_SEMESTER'&&p.mid_semester_constructed_response_requires_independent_moderation!==false)return true;if(type==='FINAL_EXAMINATION'&&p.final_exam_constructed_response_requires_independent_moderation!==false)return true;return false;}
function compareIndependentJudgments(original,independent,{materialCreditDelta=0}={}){const a=new Map(asArray(original).map(j=>[String(j.criterion_id),j])),b=new Map(asArray(independent).map(j=>[String(j.criterion_id),j]));const comparisons=[];let material=false;for(const [id,oj] of a){const ij=b.get(id);if(!ij){comparisons.push({criterion_id:id,classification:'review_not_possible_fairly'});material=true;continue;}if(oj.proposed_credit==null||ij.proposed_credit==null){comparisons.push({criterion_id:id,classification:'rubric_precision_unresolved'});material=true;continue;}const delta=Number(ij.proposed_credit)-Number(oj.proposed_credit),classification=Math.abs(delta)<=Number(materialCreditDelta)?'agreement_same_credit':'material_credit_disagreement';if(classification==='material_credit_disagreement')material=true;comparisons.push({criterion_id:id,original_credit:Number(oj.proposed_credit),independent_credit:Number(ij.proposed_credit),delta,classification});}return Object.freeze({material_disagreement:material,comparisons:Object.freeze(comparisons)});}
function applyReviewDirection({originalCredit,reviewedCredit,policy}){const o=number(originalCredit,'original credit'),r=number(reviewedCredit,'reviewed credit'),p=String(policy||'').trim();if(!p)fail('Appeal review direction must come from an explicit configured policy.','TEACHING_D20_REVIEW_DIRECTION_REQUIRED',409);if(p==='upward_only')return Math.max(o,r);if(p==='retain_or_escalate'||p==='retain_or_escalate_only')return o;if(p==='two_way')return r;fail('Unknown review-direction policy.','TEACHING_D20_REVIEW_DIRECTION_INVALID',400,{policy});}

module.exports={D20_CONTRACT_VERSION,TPF15,TPF16,DEFAULT_CATEGORY_WEIGHTS,RESULT_LIFECYCLE,FORBIDDEN_MARKING_CONTEXT_KEYS,fail,asObject,asArray,upper,stableUnique,categoryForAssessment,normalizeWeights,normalizeRoundingPolicy,roundConfigured,defaultPolicy,assertNoForbiddenContext,markingContextAllowlist,deterministicMarkObjective,rubricCriteria,validateCriterionJudgments,deterministicAggregateCriteria,calculateCourseScore,topicScore,moderationRequired,compareIndependentJudgments,applyReviewDirection};