'use strict';
const {OUTCOMES,PASS_STATES,assertCoursePolicyComplete,finite,upper,asArray,stableUnique}=require('./contracts');
function coverageStatus(row){if(row.excluded_at)return'EXCLUDED';if(row.instructionally_complete_at)return'INSTRUCTIONALLY_COMPLETE';if(row.validated_prior_knowledge_at)return'VALIDATED_PRIOR_KNOWLEDGE';if(row.taught_at)return'TAUGHT';if(row.planned_at)return'PLANNED';if(row.mapped_at)return'MAPPED';return'FOUND';}
function isRequired(unit){return unit?.metadata?.required!==false&&unit?.metadata?.optional!==true;}
function unresolvedEssentialFlags(snapshot){const flags=[...asArray(snapshot.courseResult?.essential_outcome_flags),...asArray(snapshot.topicScores).flatMap(t=>asArray(t.essential_outcome_flags))];return flags.filter(flag=>typeof flag==='string'?/(FAIL|UNMET|REMEDIATION_REQUIRED)/i.test(flag):flag&&(flag.met===false||['FAIL','UNMET','REMEDIATION_REQUIRED'].includes(upper(flag.status))));}
function certificationCheck(snapshot,rawPolicy={}){
  const policy=assertCoursePolicyComplete(rawPolicy),blockers=[],warnings=[];const coverage=asArray(snapshot.coverage),units=asArray(snapshot.learningUnits),assessments=asArray(snapshot.assessments),results=asArray(snapshot.assessmentResults),result=snapshot.courseResult||null;
  const byUnit=new Map(),rank={FOUND:1,MAPPED:2,PLANNED:3,TAUGHT:4,VALIDATED_PRIOR_KNOWLEDGE:4,INSTRUCTIONALLY_COMPLETE:5,EXCLUDED:9};for(const row of coverage){if(!row.learning_unit_id)continue;const s=coverageStatus(row),prev=byUnit.get(String(row.learning_unit_id));if((rank[s]||0)>(rank[prev]||0))byUnit.set(String(row.learning_unit_id),s);}
  const required=units.filter(isRequired),incomplete=required.filter(u=>!['TAUGHT','VALIDATED_PRIOR_KNOWLEDGE','INSTRUCTIONALLY_COMPLETE','EXCLUDED'].includes(byUnit.get(String(u.learning_unit_id)))).map(u=>String(u.learning_unit_id));if(policy.certification.requireAllRequiredLearningUnits&&incomplete.length)blockers.push({code:'REQUIRED_COVERAGE_INCOMPLETE',learningUnitIds:incomplete});
  if(!result||finite(result.score_percentage)==null)blockers.push({code:'COURSE_GRADEBOOK_RESULT_MISSING'});
  const requiredTopicIds=stableUnique(required.map(u=>u.topic_id)),latestTopic=new Map();for(const t of asArray(snapshot.topicScores)){const k=String(t.topic_id||'');if(!k)continue;const p=latestTopic.get(k);if(!p||Number(t.version_no||0)>=Number(p.version_no||0))latestTopic.set(k,t);}
  const insufficientTopics=[];if(policy.certification.requireTrustworthyTopicEvidence){for(const topicId of requiredTopicIds){const t=latestTopic.get(topicId);if(!t||upper(t.score_state)!=='FINALIZED')insufficientTopics.push(topicId);}if(insufficientTopics.length)blockers.push({code:'TRUSTWORTHY_EVIDENCE_INSUFFICIENT',topicIds:insufficientTopics});}
  const requiredTypes=new Set(policy.certification.requiredAssessmentTypes),requiredAssessments=assessments.filter(a=>a.source_lineage?.required_for_completion===true||requiredTypes.has(upper(a.assessment_type))),byAssessment=new Map(results.map(r=>[String(r.assessment_id),r])),missing=[],unresolved=[];for(const a of requiredAssessments){const r=byAssessment.get(String(a.assessment_id));if(!r){missing.push(String(a.assessment_id));continue;}if(r.review_blocked||upper(r.release_state)!=='FINALIZED')unresolved.push(String(a.assessment_id));}if(missing.length)blockers.push({code:'REQUIRED_ASSESSMENT_MISSING',assessmentIds:missing});if(policy.certification.requireFinalizedRequiredAssessments&&unresolved.length)blockers.push({code:'REQUIRED_ASSESSMENT_UNRESOLVED',assessmentIds:unresolved});
  const openAppeals=asArray(snapshot.openAppeals);if(openAppeals.length)blockers.push({code:'UNRESOLVED_GRADE_APPEAL',appealIds:openAppeals.map(a=>a.grade_appeal_id)});const invalidAttempts=asArray(snapshot.invalidAssessmentAttempts);if(invalidAttempts.length)blockers.push({code:'UNRESOLVED_ASSESSMENT_VALIDITY',attemptIds:invalidAttempts.map(a=>a.assessment_attempt_id)});const integrityIssues=asArray(snapshot.unresolvedIntegrityIssues);if(integrityIssues.length)blockers.push({code:'UNRESOLVED_INTEGRITY_STATE',integrityRefs:integrityIssues.map(x=>x.integrity_review_id||x.submission_id||x.assignment_id).filter(Boolean)});
  if(policy.certification.terminalFloor!=null){const terminals=assessments.filter(a=>['FINAL_EXAMINATION','FINAL','TERMINAL_EXAMINATION'].includes(upper(a.assessment_type))),scores=terminals.map(a=>finite(byAssessment.get(String(a.assessment_id))?.raw_percentage)).filter(v=>v!=null);if(terminals.length&&!scores.length)blockers.push({code:'TERMINAL_FLOOR_UNVERIFIABLE'});else if(scores.length&&Math.max(...scores)<policy.certification.terminalFloor)blockers.push({code:'TERMINAL_FLOOR_NOT_MET',floor:policy.certification.terminalFloor,best:Math.max(...scores)});}
  const essential=unresolvedEssentialFlags(snapshot);if(essential.length)warnings.push({code:'ESSENTIAL_OUTCOMES_UNRESOLVED',flags:essential});const score=finite(result?.score_percentage),scorePass=score!=null&&score>=policy.certification.passThreshold;
  return Object.freeze({eligibleForAcademicOutcome:blockers.length===0,blockers:Object.freeze(blockers),warnings:Object.freeze(warnings),incompleteRequiredLearningUnitIds:Object.freeze(incomplete),insufficientTopicIds:Object.freeze(insufficientTopics),unresolvedEssential:Object.freeze(essential),courseScore:score,passThreshold:policy.certification.passThreshold,scorePass});
}
function weaknessProfile(snapshot,certification){const latest=new Map();for(const row of asArray(snapshot.topicScores)){const k=String(row.topic_id||row.learning_unit_id||'');if(!k)continue;const p=latest.get(k);if(!p||Number(row.version_no||0)>=Number(p.version_no||0))latest.set(k,row);}const weak=[...latest.values()].filter(row=>{const score=finite(row.score_percentage??row.score),state=upper(row.score_state||row.result_state),flag=asArray(row.essential_outcome_flags).some(f=>f?.met===false||['FAIL','UNMET','REMEDIATION_REQUIRED'].includes(upper(f?.status||f)));return flag||state.includes('FAIL')||(score!=null&&score<certification.passThreshold);});const critical=weak.filter(r=>asArray(r.essential_outcome_flags).some(f=>f?.met===false||['FAIL','UNMET'].includes(upper(f?.status||f)))||r.critical===true);return Object.freeze({weakCount:weak.length,criticalWeakCount:critical.length,weakRefs:Object.freeze(stableUnique(weak.map(r=>r.learning_unit_id||r.topic_id))),criticalWeakRefs:Object.freeze(stableUnique(critical.map(r=>r.learning_unit_id||r.topic_id)))});}
function determineProgressionOutcome(snapshot,rawPolicy={},history={}){const policy=assertCoursePolicyComplete(rawPolicy),certification=certificationCheck(snapshot,rawPolicy),weakness=weaknessProfile(snapshot,certification);if(!certification.eligibleForAcademicOutcome)return Object.freeze({outcome:OUTCOMES.INCOMPLETE,certification,weakness,reasonCodes:Object.freeze(certification.blockers.map(b=>b.code))});const essentialGap=(certification.unresolvedEssential.length>0||weakness.criticalWeakCount>0)&&history.verifiedRemediation!==true,total=Math.max(1,asArray(snapshot.learningUnits).filter(isRequired).length),ratio=weakness.weakCount/total,used=Number(history.standardResitAttemptsUsed||0);let outcome,reasons=[];if(certification.scorePass&&!essentialGap){outcome=OUTCOMES.CLEAN_PASS;reasons=['COURSE_REQUIREMENTS_MET'];}else if(certification.scorePass&&essentialGap){outcome=OUTCOMES.PASS_REMEDIATION_REQUIRED;reasons=['PASS_WITH_ESSENTIAL_OR_PREREQUISITE_GAP'];}else if(history.reasonableRecoveryFailed===true){outcome=OUTCOMES.REPEAT_REQUIRED;reasons=['FAILED_REASONABLE_RECOVERY'];}else if(ratio>=policy.pathways.systemicGapRatio||weakness.weakCount>=policy.pathways.distributedGapMinUnits){outcome=OUTCOMES.RECOVERY_REQUIRED;reasons=['DISTRIBUTED_OR_SYSTEMIC_WEAKNESS'];}else if(used>=policy.resit.maxStandardResits){outcome=OUTCOMES.RECOVERY_REQUIRED;reasons=['STANDARD_RESIT_ALLOWANCE_EXHAUSTED'];}else{outcome=OUTCOMES.RESIT_REQUIRED;reasons=['NARROW_RECOVERABLE_FAILURE_PATTERN'];}return Object.freeze({outcome,certification,weakness,reasonCodes:Object.freeze(reasons)});}
function prerequisiteDestinationDecision({courseOutcome,prerequisiteFindings=[],policy={}}={}){const p=assertCoursePolicyComplete(policy),unmet=asArray(prerequisiteFindings).filter(x=>x&&x.ready===false);return Object.freeze({courseOutcome,destinationReady:unmet.length===0,remediationRequired:p.pathways.prerequisiteDestinationRemediation&&unmet.length>0,blockingPrerequisiteRefs:Object.freeze(stableUnique(unmet.map(x=>x.prerequisite_learning_unit_id||x.learningUnitId||x.ref))),changesCourseMark:false,independentCoursesUnaffected:true});}
function freshKnowledgeReady(currentStates=[],baselineVersions={}){const findings=asArray(currentStates).map(s=>{const ref=String(s.learning_unit_id),before=Number(baselineVersions?.[ref]||0),now=Number(s.version_no||0),state=upper(s.durable_state||s.knowledge_state||s.state),overlays=asArray(s.overlays).map(upper),ready=now>before&&PASS_STATES.has(state)&&!overlays.includes('BLOCKED');return {learningUnitId:ref,beforeVersion:before,currentVersion:now,state,ready};});return Object.freeze({ready:findings.length>0&&findings.every(f=>f.ready),findings:Object.freeze(findings)});}
module.exports={coverageStatus,certificationCheck,weaknessProfile,determineProgressionOutcome,prerequisiteDestinationDecision,freshKnowledgeReady};
