'use strict';
function getCapability(id){return require('../capability-registry').getCapability(id);}
const {TPF17,TPF19,fail,asArray,asObject}=require('./contracts');
const CAPABILITIES=Object.freeze({
  essential:'teaching.progression.essential_learning_outcome_verification_interpretation',
  readiness:'teaching.progression.certification_readiness_synthesis',
  remediation:'teaching.progression.targeted_remediation_plan_generation',
  resit:'teaching.progression.resit_preparation_plan_generation',
  targetedVerification:'teaching.progression.targeted_verification_design_instead_of_whole_resit',
  recovery:'teaching.progression.recovery_programme_generation',
  repeat:'teaching.progression.repeat_course_diagnostic_compression_plan',
  narrative:'teaching.progression.final_academic_narrative_generation',
  explanation:'teaching.progression.progression_explanation_generation',
});
const MODES=Object.freeze({essential:'essential_outcome_evidence_interpretation',readiness:'certification_readiness_synthesis',remediation:'targeted_remediation_plan',resit:'resit_preparation_plan',targetedVerification:'targeted_verification_proposal',recovery:'recovery_programme_plan',repeat:'repeat_course_compression_plan',narrative:'final_academic_narrative',explanation:'progression_explanation'});
const FORBIDDEN_OUTPUT=new Set(['official_grade','official_mark','gradebook_write','gradebook_entry','gpa','gpa_value','progression_outcome','progression_eligibility','resit_eligibility','course_attempt','course_attempt_mutation','schedule_commit','assessment_package_lock','authoritative_commit']);
function familyFor(capability){return capability.prompt_family_id==='TPF-19'?TPF19:TPF17;}
function validateOutput(output,{family}){if(!output||typeof output!=='object'||Array.isArray(output))return {ok:false,reason:'TEACHING_D21_AI_OUTPUT_INVALID'};for(const key of Object.keys(output))if(FORBIDDEN_OUTPUT.has(String(key).toLowerCase()))return {ok:false,reason:'TEACHING_D21_AI_AUTHORITY_EXCEEDED',details:{field:key}};if(family.family==='TPF-17'){const plan=asObject(output.pathway_plan||output.plan);if(!Object.keys(plan).length)return {ok:false,reason:'TEACHING_D21_TPF17_PATHWAY_PLAN_REQUIRED'};if(plan.changes_progression_outcome===true||plan.commits_eligibility===true||plan.mutates_gradebook===true)return {ok:false,reason:'TEACHING_D21_TPF17_AUTHORITY_EXCEEDED'};if(plan.preserves_original_marks_and_history===false)return {ok:false,reason:'TEACHING_D21_TPF17_HISTORY_PRESERVATION_REQUIRED'};}if(family.family==='TPF-19'){if(output.changes_marks===true||output.changes_progression===true)return {ok:false,reason:'TEACHING_D21_TPF19_MUTATION_FORBIDDEN'};}return {ok:true,value:output};}
function makeRequest({capabilityId,taskMode,studentId,aggregateId,stateVersion,academicInput={},requestKey}){const capability=getCapability(capabilityId),family=familyFor(capability);if(!['TPF-17','TPF-19'].includes(capability.prompt_family_id))throw fail('D21 capability is not bound to TPF-17/TPF-19.','TEACHING_D21_PROMPT_BINDING_INVALID',500,{capabilityId,family:capability.prompt_family_id});return {trigger:{type:'workflow_continuation',ref:`d21:${aggregateId}:${taskMode}`,source:'teaching.d21',actor_id:studentId},capabilityId,declaredAuthorityLevel:capability.authority_ceiling,idempotencyKey:String(requestKey),correlationId:String(requestKey),stateReference:{aggregate_type:'PROGRESSION_PATHWAY',aggregate_id:String(aggregateId),state_version:String(stateVersion??0)},preconditions:{progression_owner_external:true,gradebook_owner_external:true,skm_owner_external:true,current_state_revalidation_required:true},provenanceRefs:asArray(academicInput.provenance_refs),resultContract:{output_schema_id:`d21.${taskMode}`,output_schema_version:'1',validator_ids:['schema','domain','authority','current-state']},taskMode,directive:{bounded_actions:family.family==='TPF-17'?['prepare or refine a non-authoritative repair/verification plan']:['translate normalized authoritative facts for the student'],allowed_operations:family.family==='TPF-17'?['planning','prioritization','bounded explanation','uncertainty']:['translation','summary','status distinction'],prohibited_operations:['commit progression outcome','commit resit eligibility','write Gradebook','calculate official GPA','create Course Attempt','lock Assessment Package','select provider/model'],downstream_handoff:{type:family.family==='TPF-17'?'d21_progression_owner_revalidation':'presentation_only',commit_owner_boundary:capability.authoritative_owner_boundary}},contextSpec:{authoritative_refs:asArray(academicInput.provenance_refs).map(ref=>({ref})),provenance_refs:[],untrusted_refs:[],context_kind:family.family==='TPF-17'?'d21_progression_planning':'d21_academic_translation',access_purpose:taskMode,forbidden_context:['hidden_chain_of_thought','unrelated_student_history','personality','peer_performance']},academicInput:{...academicInput,prompt_contract:{family:family.family,version:family.version,sha256:family.sha256}},outputSchema:{id:`d21.${taskMode}`,version:'1',validate:async output=>validateOutput(output,{family})},schemaValidator:async output=>validateOutput(output,{family}),domainValidator:async output=>validateOutput(output,{family}),provenanceValidator:async()=>({ok:true}),commit:false,capabilityPromptFamily:family.family};}
function createD21Intelligence({orchestrator}={}){if(!orchestrator||typeof orchestrator.execute!=='function')return null;const run=(key,args)=>orchestrator.execute(makeRequest({...args,capabilityId:CAPABILITIES[key],taskMode:MODES[key]}));return Object.freeze({CAPABILITIES,prepareRemediation:a=>run('remediation',a),prepareResit:a=>run('resit',a),prepareTargetedVerification:a=>run('targetedVerification',a),prepareRecovery:a=>run('recovery',a),prepareRepeat:a=>run('repeat',a),interpretEssential:a=>run('essential',a),synthesizeReadiness:a=>run('readiness',a),finalNarrative:a=>run('narrative',a),explain:a=>run('explanation',a)});}
module.exports={CAPABILITIES,MODES,makeRequest,validateOutput,createD21Intelligence};
