'use strict';
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function page(title,body){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><style>:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#090c10;color:#f5f7f9;font:16px/1.55 ui-sans-serif,system-ui;padding:clamp(18px,4vw,54px)}main{max-width:1050px;margin:auto}.hero{padding:clamp(24px,5vw,56px);border:1px solid #2a313b;border-radius:28px;background:radial-gradient(circle at 90% 0%,rgba(111,210,255,.16),transparent 35%),linear-gradient(145deg,#111720,#0c1016)}.eyebrow{text-transform:uppercase;letter-spacing:.14em;font-size:.75rem;color:#a9bacd}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:16px;margin-top:18px}.card{border:1px solid #252d37;border-radius:20px;padding:20px;background:#0f141b}.truth{border-left:3px solid currentColor;padding-left:12px;color:#cbd5df}.status{font-weight:750;font-size:1.08rem}.muted{color:#9ba9b8}ul{padding-left:1.2rem}a,button{font:inherit}dl{display:grid;grid-template-columns:max-content 1fr;gap:6px 14px}dd{margin:0}@media(max-width:540px){body{padding:12px}.hero{border-radius:20px;padding:22px}}</style></head><body><main>${body}</main></body></html>`;}
function shell(kind,title,lede,body){return `<section class="hero" data-pathway="${esc(kind)}" aria-labelledby="${esc(kind)}-title"><p class="eyebrow">Academic pathway</p><h1 id="${esc(kind)}-title">${esc(title)}</h1><p>${esc(lede)}</p><div class="grid">${body}</div></section>`;}
function refs(items,label){const a=Array.isArray(items)?items:[];return `<article class="card"><h2>${esc(label)}</h2>${a.length?`<ul>${a.map(v=>`<li>${esc(v)}</li>`).join('')}</ul>`:'<p class="muted">No additional items are listed.</p>'}</article>`;}
function renderRemediation(p={}){return page('Remediation',shell('remediation','Remediation','Your official Course mark remains unchanged. This pathway repairs a specific essential or prerequisite gap before progression is cleared.',refs(p.required_learning_unit_refs,'Repair focus')+`<article class="card"><h2>Record protection</h2><p class="truth">Remediation can establish readiness; it never rewrites the historical Gradebook result.</p></article>`));}
function renderResit(p={}){return page('Resit',shell('resit','Resit preparation','Preparation must be completed before a fresh equivalent formal resit can be attempted. The original Assessment Result remains in history.',refs(p.required_learning_unit_refs,'Preparation focus')+`<article class="card"><h2>Current state</h2><p class="status">${esc(p.pathway_state||'ACTIVE')}</p><p class="truth">A valid resit may replace the failed component for Course-score recalculation under the locked policy; it does not delete the original result.</p></article>`));}
function renderRecovery(p={}){return page('Recovery Programme',shell('recovery','Recovery Programme','A broader weakness pattern requires structured repair before controlled verification.',refs(p.required_learning_unit_refs,'Recovery focus')+`<article class="card"><h2>What happens next</h2><p>KIWI prepares and refines the repair plan, then the Progression Engine rechecks authoritative evidence before verification eligibility.</p></article>`));}
function renderRepeatSetup(p={}){return page('Repeat setup',shell('repeat','Whole-Course Repeat','A repeat starts a new linked academic Course Attempt. Prior grades remain historical while prior learning evidence may help compress already-secure material after a fresh diagnostic.',`<article class="card"><h2>Lineage</h2><dl><dt>Prior attempt</dt><dd>${esc(p.source_attempt_id||'Preserved')}</dd><dt>New attempt</dt><dd>${esc(p.attempt_id||'Created when repeat begins')}</dd></dl></article><article class="card"><h2>Reset boundary</h2><p class="truth">Academic attempt resets. Pedagogical history does not.</p></article>`));}
function renderIncomplete(o={}){const blockers=o.certification_snapshot?.blockers||o.certification?.blockers||[];return page('Course Incomplete',shell('incomplete','Course Incomplete','Incomplete is not Fail. KIWI cannot issue a final academic outcome while required coverage, evidence, assessment, appeal, or validity state remains unresolved.',refs(blockers.map(b=>b.code),'What remains')+`<article class="card"><h2>Academic meaning</h2><p class="truth">No failing judgment is inferred from missing or unresolved evidence.</p></article>`));}
function renderSemesterRecord(model={}){const courses=Array.isArray(model.courses)?model.courses:[];return page('Semester Record',`<section class="hero" aria-labelledby="record-title"><p class="eyebrow">Authoritative projection</p><h1 id="record-title">Semester Record</h1><p>${model.gpa?.gpa_value!=null?`Current GPA: <strong>${esc(model.gpa.gpa_value)}</strong>`:'GPA is not available until the configured academic rules and required Course results are complete.'}</p><div class="grid">${courses.map(c=>`<article class="card"><h2>${esc(c.title||'Course')}</h2><p class="status">${esc(c.progression_outcome||'Outcome pending')}</p>${c.score_percentage!=null?`<p>Official Course score: ${esc(c.score_percentage)}%</p>`:''}${c.academic_credits!=null?`<p>Academic credits: ${esc(c.academic_credits)}</p>`:''}<p class="muted">Attempt ${esc(c.attempt_no||1)} · ${esc(c.attempt_kind||'INITIAL')}</p></article>`).join('')}</div></section>`);}
function renderCourseProgression(model={}){const latest=model.latestOutcome||{},pathways=model.pathways||[],active=[...pathways].reverse().find(p=>!['VERIFIED','FAILED','CANCELLED','SUPERSEDED'].includes(p.pathway_state));if(latest.outcome==='INCOMPLETE')return renderIncomplete(latest);if(active?.pathway_type==='REMEDIATION')return renderRemediation(active);if(['RESIT_PREPARATION','TARGETED_VERIFICATION'].includes(active?.pathway_type))return renderResit(active);if(active?.pathway_type==='RECOVERY')return renderRecovery(active);if(active?.pathway_type==='REPEAT')return renderRepeatSetup(active);return page('Course progression',`<section class="hero"><p class="eyebrow">Official progression</p><h1>${esc(latest.outcome||'Outcome pending')}</h1><p class="truth">Course score is owned by D20 Gradebook. This surface only projects the D21 progression consequence.</p></section>`);}
module.exports={renderRemediation,renderResit,renderRecovery,renderRepeatSetup,renderIncomplete,renderSemesterRecord,renderCourseProgression};
