'use strict';
// Explicit structural shapes for coordinator internal artifacts. Functional
// acceptance still requires D12/D11 state/source/exposure checks at commit.
const {object,string,list,bool,enumeration,exact,claim,fail}=require('./contracts');
function fields(v,required,optional,name){object(v,name);for(const k of required)if(!Object.hasOwn(v,k))fail('CLASSROOM_FIELD_REQUIRED',name+'.'+k);for(const k of Object.keys(v))if(![...required,...optional,'basis','evidence_refs'].includes(k))fail('CLASSROOM_FIELD_UNKNOWN',name+'.'+k);claim(v,name);}
function strings(v,keys){for(const k of keys)string(v[k],k);}
function arrays(v,keys){for(const k of keys)list(v[k],k);}
function validateInternalArtifacts(a){
 if(a.progress){const v=a.progress;fields(v,['current_position','confirmed_delivered','unfinished','waiting_state','strategy_history','return_anchor'],[],'progress');strings(v,['current_position','return_anchor']);arrays(v,['confirmed_delivered','unfinished','strategy_history']);enumeration(v.waiting_state,['none','response','interpretation','directive'],'waiting_state');}
 if(a.continuity){const v=a.continuity;fields(v,['record_or_summary','source_links','demonstrated_evidence','unresolved_questions','unfinished_essentials','assistance_given','follow_up'],[],'continuity');strings(v,['record_or_summary']);arrays(v,['source_links','demonstrated_evidence','unresolved_questions','unfinished_essentials','assistance_given']);v.demonstrated_evidence.forEach(e=>{fields(e,['claim','limits'],[],'demonstrated_evidence');strings(e,['claim','limits']);});exact(v.follow_up,['confirmed','proposed'],'follow_up');arrays(v.follow_up,['confirmed','proposed']);}
 if(a.replan_request){const v=a.replan_request;fields(v,['current_position','actual_completion','blocker','evidence','attempts_made','remaining_time','unresolved_commitments','required_decision'],[],'replan_request');strings(v,['current_position','blocker','required_decision']);arrays(v,['evidence','attempts_made','unresolved_commitments']);if(v.remaining_time!==null&&(!Number.isFinite(v.remaining_time)||v.remaining_time<0))fail('CLASSROOM_REPLAN_TIME_INVALID');}
 if(a.assessment_guidance){const v=a.assessment_guidance;fields(v,['actual_coverage','objectives','evidence_needs','exposure_and_assistance','intended_independence','constraints','required_handoff'],[],'assessment_guidance');arrays(v,['objectives','evidence_needs','constraints']);strings(v,['required_handoff']);object(v.exposure_and_assistance,'exposure_and_assistance');}
 if(a.response_interpretation){const v=a.response_interpretation;fields(v,['task_ref','response_ref','criterion_ref','feedback_points','item_validity','judgments','components','errors','hypotheses','attempt_context','supports','does_not_establish','next_evidence_need'],['private','learning_stage'],'interpretation');strings(v,['task_ref','response_ref','criterion_ref']);arrays(v,['feedback_points','errors','hypotheses','supports','does_not_establish']);exact(v.item_validity,['findings','negative_attribution_protection'],'item_validity');arrays(v.item_validity,['findings']);bool(v.item_validity.negative_attribution_protection,'negative_attribution_protection');exact(v.judgments,['correctness','conceptual_support','reasoning','completeness','alignment','independence','evidence_sufficiency'],'judgments');
  enumeration(v.judgments.correctness,['correct','incorrect','partial','indeterminate','not_applicable'],'correctness');for(const k of ['conceptual_support','reasoning','completeness','alignment','independence','evidence_sufficiency'])enumeration(v.judgments[k],['supported','not_established','partial','indeterminate','not_applicable'],'judgments.'+k);
  exact(v.components,['supported','missing','incorrect','indeterminate'],'components');arrays(v.components,['supported','missing','incorrect','indeterminate']);v.errors.forEach(e=>{exact(e,['location','significance','kind','uncertainty'],'error');strings(e,['location','significance','uncertainty']);enumeration(e.kind,['local execution','conceptual'],'error.kind');});v.hypotheses.forEach(h=>{fields(h,['type','alternatives','confidence'],[],'hypothesis');enumeration(h.type,['misconception','prerequisite'],'hypothesis.type');arrays(h,['alternatives']);enumeration(h.confidence,['high','medium','low','indeterminate'],'confidence');});exact(v.attempt_context,['attempts','self_correction','assistance','accommodations','contamination'],'attempt_context');arrays(v.attempt_context,['attempts','accommodations']);object(v.attempt_context.assistance,'assistance');
  if(v.private){exact(v.private,['expected_solution_or_criteria','acceptable_alternatives'],'interpretation.private');arrays(v.private,['acceptable_alternatives']);}
  if(v.learning_stage){exact(v.learning_stage,['descriptor','state'],'learning_stage');enumeration(v.learning_stage.descriptor,['demonstration','guided','independent_familiar','independent_varied','method_selection','delayed_retrieval','integration_transfer','unknown','not_applicable'],'learning_stage.descriptor');enumeration(v.learning_stage.state,['supported','not_established','indeterminate'],'learning_stage.state');}
 }
 if(a.scaffolding){const v=a.scaffolding;fields(v,['target_ref','strategy','student_facing','private','assistance_level','validation_status','lineage_refs'],[],'scaffolding');strings(v,['target_ref','strategy']);exact(v.student_facing,['example','steps'],'scaffolding.student_facing');arrays(v.student_facing,['steps']);string(v.student_facing.example,'example');exact(v.private,['expected_result','validation_note'],'scaffolding.private');strings(v.private,['validation_note']);enumeration(v.assistance_level,require('../d12/contracts').ASSISTANCE_LEVELS,'assistance_level');enumeration(v.validation_status,['self-checked','validated candidate','requires validation'],'validation_status');arrays(v,['lineage_refs']);}
 if(a.diagnostic_specification){const v=a.diagnostic_specification;fields(v,['purpose','targets','opportunities','private','non_graded','inference_ceiling'],[],'diagnostic');strings(v,['purpose','inference_ceiling']);arrays(v,['targets','opportunities']);if(v.non_graded!==true)fail('CLASSROOM_DIAGNOSTIC_MUST_BE_NONGRADED');exact(v.private,['critical_criteria'],'diagnostic.private');arrays(v.private,['critical_criteria']);}
 if(a.scheduling)list(a.scheduling,'scheduling').forEach(v=>{fields(v,['message_refs','boundary_ref','requested_handling','confirmation_needed'],[],'scheduling');arrays(v,['message_refs']);strings(v,['boundary_ref','confirmation_needed']);enumeration(v.requested_handling,['boundary','unit','closure','follow_up_proposal'],'requested_handling');});
 return a;
}
module.exports={validateInternalArtifacts};
