'use strict';
// Candidate-only contracts. These validators never publish or mutate D11/D12.
const {ASSISTANCE_LEVELS}=require('../d12/contracts');
const VERSION='classroom-contracts.v1';
const AUTHOR_MODES=Object.freeze(['pre_class_lesson_blueprint','core_optional_selection','adaptive_reserve_allocation','purposeful_retrieval_selection','live_lesson_replan','lateness_replan','lesson_closure_analysis','rolling_planning_horizon','homework_design_generate','homework_to_next_lesson_synthesis']);
const COORDINATOR_MODES=Object.freeze(['prepare_guidance','coordinate_lesson','handle_message','design_check','interpret_response','close_class','prepare_continuity','guide_assessment']);
const PRESENTER_MODES=Object.freeze(['natural_teacher_instruction','teacher_question_or_probe','permitted_hint_wording','example_or_analogy_generation','teacher_self_correction','teacher_source_grounding_selection','outside_class_course_qa','interaction_style_realization','evidence_based_praise','challenge_accountability_communication','context_sensitive_register_humor','board_instructional_content']);
const COORDINATOR_FIELDS=Object.freeze(['request_ref','task_mode','input_state_reference','status','review_required','artifacts','next_action','runtime_requests','issues']);
const ACTIONS=Object.freeze(['continue','slow down','pause','clarify','change example or representation','move to practice','defer optional depth','request replanning','prepare closure','focused probe','clarification','hint','missing step','new example','representation change','misconception repair','guided practice','independent attempt','further verification','answer message','request clarification','wait']);
const TIMINGS=Object.freeze(['immediately','at a suitable teaching pause','at the end of class']);
const BASIS=Object.freeze(['explicit fact','supported inference','proposal','unresolved']);
const AUTHOR_STATUSES=Object.freeze(['policy_block','state_conflict','insufficient_context','infeasible_within_time','workload_validation_required','validation_needed','ok']);
const PRESENTER_STATUSES=Object.freeze(['policy_block','directive_conflict','insufficient_context','source_conflict','correction_required','validation_needed','handoff_required','ok']);
const PROHIBITED_KEYS=new Set(['official_mark','official_grade','mastery_state','knowledge_state','attendance_outcome','progression_outcome','inferred_emotion','student_intent','durable_state_committed']);
function fail(code,path=''){const e=new Error(code+(path?': '+path:''));e.code=code;e.fieldPath=path;throw e;}
function object(v,p){if(!v||typeof v!=='object'||Array.isArray(v))fail('CLASSROOM_OBJECT_REQUIRED',p);return v;}
function string(v,p){if(typeof v!=='string'||!v.trim())fail('CLASSROOM_STRING_REQUIRED',p);return v;}
function list(v,p){if(!Array.isArray(v))fail('CLASSROOM_ARRAY_REQUIRED',p);return v;}
function bool(v,p){if(typeof v!=='boolean')fail('CLASSROOM_BOOLEAN_REQUIRED',p);return v;}
function enumeration(v,values,p){if(!values.includes(v))fail('CLASSROOM_ENUM_INVALID',p);return v;}
function exact(v,fields,p){object(v,p);for(const f of fields)if(!Object.hasOwn(v,f))fail('CLASSROOM_FIELD_REQUIRED',p+'.'+f);for(const f of Object.keys(v))if(!fields.includes(f))fail('CLASSROOM_FIELD_UNKNOWN',p+'.'+f);return v;}
function noAuthority(v,p='',depth=0){if(depth>30)fail('CLASSROOM_NESTING_LIMIT',p);if(Array.isArray(v)){v.forEach((x,i)=>noAuthority(x,p+'.'+i,depth+1));return;}if(v&&typeof v==='object')for(const[k,x]of Object.entries(v)){if(PROHIBITED_KEYS.has(k))fail('CLASSROOM_AUTHORITY_EXCEEDED',p+'.'+k);noAuthority(x,p+'.'+k,depth+1);}}
function claim(v,p){object(v,p);enumeration(v.basis,BASIS,p+'.basis');list(v.evidence_refs,p+'.evidence_refs').forEach(r=>string(r,p+'.evidence_refs'));}
function versionRef(v,{kind=null}={}){exact(v,['kind','id','version','anchor'],'reference');enumeration(v.kind,['chapter','chapter_unit','source_element','course_learning_unit','plan','guide','portion','task','criterion','message','board','closure','response','interpretation'],'reference.kind');string(v.id,'reference.id');string(v.version,'reference.version');if(v.anchor!==null)string(v.anchor,'reference.anchor');if(kind&&v.kind!==kind)fail('CLASSROOM_REFERENCE_KIND_MISMATCH');return v;}
function resolveAnchor(ref,chapter){versionRef(ref);if(!['chapter','chapter_unit','source_element'].includes(ref.kind)||ref.id!==chapter.id||ref.version!==chapter.version)fail('CLASSROOM_REFERENCE_VERSION_MISMATCH');if(ref.kind==='chapter'&&ref.anchor!==null)fail('CLASSROOM_REFERENCE_KIND_MISMATCH');if(ref.kind==='chapter_unit'&&!chapter.units.some(u=>ref.anchor===u.anchor))fail('CLASSROOM_ANCHOR_UNRESOLVED');if(ref.kind==='source_element'&&!chapter.units.some(u=>u.elements.some(e=>e.anchor===ref.anchor)))fail('CLASSROOM_ANCHOR_UNRESOLVED');return ref;}
function validateChapter(c){
 exact(c,['id','version','scope_ref','title','completeness','validation','units','continuation','prior_version','remaps'],'chapter');
 string(c.id,'chapter.id');string(c.version,'chapter.version');string(c.scope_ref,'chapter.scope_ref');string(c.title,'chapter.title');
 enumeration(c.completeness,['complete','partial','blocked'],'chapter.completeness');enumeration(c.validation,['candidate','checked','validated','validation_needed'],'chapter.validation');
 const anchors=new Set();const units=list(c.units,'chapter.units');
 if(c.completeness==='complete'&&!units.length)fail('CLASSROOM_EMPTY_COMPLETE_CHAPTER');
 units.forEach(u=>{exact(u,['anchor','title','objective_refs','prerequisite_refs','designation','treatment','elements'],'unit');string(u.anchor,'unit.anchor');if(anchors.has(u.anchor))fail('CLASSROOM_DUPLICATE_ANCHOR');anchors.add(u.anchor);string(u.title,'unit.title');list(u.objective_refs,'unit.objective_refs').forEach(r=>versionRef(r,{kind:'course_learning_unit'}));list(u.prerequisite_refs,'unit.prerequisite_refs').forEach(r=>versionRef(r,{kind:'course_learning_unit'}));enumeration(u.designation,['essential','supporting','optional_depth'],'unit.designation');enumeration(u.treatment,['scheduled','support','deferred'],'unit.treatment');if(!list(u.elements,'unit.elements').length)fail('CLASSROOM_EMPTY_UNIT');u.elements.forEach(e=>{exact(e,['anchor','type','text','asset_ref','alt_text','source_refs'],'element');string(e.anchor,'element.anchor');if(!e.anchor.startsWith(u.anchor+'.')||anchors.has(e.anchor))fail('CLASSROOM_ELEMENT_ANCHOR_INVALID');anchors.add(e.anchor);enumeration(e.type,['paragraph','equation','diagram','example','code','passage'],'element.type');string(e.text,'element.text');list(e.source_refs,'element.source_refs').forEach(r=>string(r,'element.source_ref'));if(e.type==='diagram')string(e.alt_text,'element.alt_text');if(e.asset_ref!==null)versionRef(e.asset_ref,{kind:'board'});});});
 list(c.remaps,'chapter.remaps').forEach(r=>{exact(r,['prior_version','from','to','reason'],'remap');string(r.prior_version,'remap.prior_version');string(r.from,'remap.from');string(r.reason,'remap.reason');list(r.to,'remap.to').forEach(a=>{if(!anchors.has(a))fail('CLASSROOM_REMAP_TARGET_UNKNOWN');});});
 if(c.completeness==='partial'){exact(c.continuation,['candidate_id','candidate_version','last_complete_unit','remaining_units','preserved_hashes','next_task'],'continuation');if(c.continuation.candidate_id!==c.id||c.continuation.candidate_version!==c.version)fail('CLASSROOM_CONTINUATION_VERSION_MISMATCH');if(!anchors.has(c.continuation.last_complete_unit))fail('CLASSROOM_CONTINUATION_ANCHOR_UNKNOWN');if(!list(c.continuation.remaining_units,'continuation.remaining_units').length)fail('CLASSROOM_CONTINUATION_REMAINDER_REQUIRED');object(c.continuation.preserved_hashes,'continuation.preserved_hashes');string(c.continuation.next_task,'continuation.next_task');for(const u of units)if(!/^[a-f0-9]{64}$/.test(c.continuation.preserved_hashes[u.anchor]||''))fail('CLASSROOM_CONTINUATION_HASH_REQUIRED');}
 else if(c.continuation!==null)fail('CLASSROOM_CONTINUATION_ON_NONPARTIAL');
 noAuthority(c);return c;
}
function validatePlan(p,chapter){
 exact(p,['id','version','chapter_ref','objectives','phases','time_ledger','remediation_branches','carry_forward'],'plan');string(p.id,'plan.id');string(p.version,'plan.version');resolveAnchor(p.chapter_ref,chapter);
 list(p.objectives,'plan.objectives').forEach(o=>{exact(o,['ref','priority','completion_standard'],'objective');versionRef(o.ref,{kind:'course_learning_unit'});enumeration(o.priority,['core','secondary','optional_enrichment'],'objective.priority');string(o.completion_standard,'objective.completion_standard');});
 const phases=list(p.phases,'plan.phases');phases.forEach(p=>{exact(p,['purpose','source_refs','minutes','kind'],'phase');string(p.purpose,'phase.purpose');list(p.source_refs,'phase.source_refs').forEach(r=>resolveAnchor(r,chapter));enumeration(p.kind,['instruction','interaction','break','assessment','closure'],'phase.kind');if(typeof p.minutes!=='number'||!Number.isFinite(p.minutes)||p.minutes<0)fail('CLASSROOM_PLAN_DURATION_INVALID');});
 exact(p.time_ledger,['usable_minutes','reserve_minutes','accounting_basis'],'time_ledger');string(p.time_ledger.accounting_basis,'time_ledger.accounting_basis');for(const k of ['usable_minutes','reserve_minutes'])if(typeof p.time_ledger[k]!=='number'||!Number.isFinite(p.time_ledger[k])||p.time_ledger[k]<0)fail('CLASSROOM_TIME_LEDGER_INVALID');if(phases.reduce((s,p)=>s+p.minutes,0)+p.time_ledger.reserve_minutes>p.time_ledger.usable_minutes)fail('CLASSROOM_PLAN_INFEASIBLE');
 list(p.remediation_branches,'plan.remediation_branches').forEach(b=>{exact(b,['blocker','strategy_requirement','budget','return_evidence','carry_forward_condition'],'branch');for(const k of Object.keys(b))string(b[k],'branch.'+k);});list(p.carry_forward,'plan.carry_forward');return p;
}
const MODE_ARTIFACTS=Object.freeze({prepare_guidance:['explanation_guides','pedagogical_profile','scaffolding'],coordinate_lesson:['progress','replan_request'],handle_message:['message_dispositions','progress','replan_request','scheduling'],design_check:['checks','progress','replan_request','diagnostic_specification'],interpret_response:['response_interpretation','progress','replan_request'],close_class:['continuity','progress','replan_request'],prepare_continuity:['continuity'],guide_assessment:['assessment_guidance']});
function exactDisposition(x){const required=['message_ref','classification','question_or_unit_ref','disposition','reason','response_timing','grouping_refs','acknowledgement_status','reply_delivery_status','difficulty_resolution','basis','evidence_refs'];const optional=['confirmed_queue_state','requested_queue_transition','remaining_need'];object(x,'disposition');for(const k of required)if(!Object.hasOwn(x,k))fail('CLASSROOM_FIELD_REQUIRED','disposition.'+k);for(const k of Object.keys(x))if(![...required,...optional].includes(k))fail('CLASSROOM_FIELD_UNKNOWN','disposition.'+k);string(x.reason,'disposition.reason');list(x.grouping_refs,'grouping_refs');}
function validateDemand(v){exact(v,['familiarity','method_cueing','representation_demand','integration_demand','retention_timing'],'task_demand');enumeration(v.familiarity,['exact_reuse','near_reuse','familiar_family','fresh_equivalent','new_representation','new_context_same_construct','integrated','unknown'],'familiarity');enumeration(v.method_cueing,['explicit','partial','none','not_applicable'],'method_cueing');enumeration(v.representation_demand,['same_representation','alternate_familiar_representation','new_legitimate_representation','cross_representation_connection','not_applicable'],'representation_demand');enumeration(v.integration_demand,['isolated_construct','multi_step_same_construct','combine_eligible_constructs','embedded_in_broader_problem','not_applicable'],'integration_demand');enumeration(v.retention_timing,['immediate','same_session_later','spaced','delayed','not_applicable'],'retention_timing');return v;}
function validateCoordinator(v,{mode=v?.task_mode,messageRefs=[],chapter=null,confirmedAcknowledgements=[],confirmedReplies=[],resolvedDifficulties=[]}={}){
 exact(v,COORDINATOR_FIELDS,'coordinator');noAuthority(v);enumeration(v.task_mode,COORDINATOR_MODES,'task_mode');if(v.task_mode!==mode)fail('CLASSROOM_MODE_MISMATCH');enumeration(v.status,['complete','partial','blocked'],'status');bool(v.review_required,'review_required');if(v.request_ref!==null)string(v.request_ref,'request_ref');if(v.input_state_reference!==null)string(v.input_state_reference,'input_state_reference');
 list(v.issues,'issues').forEach(i=>{exact(i,['type','scope','evidence_or_missing_input','consequence','owner','can_safely_continue'],'issue');enumeration(i.type,['insufficient context','contract conflict','stale state','source conflict','invalid item','missing evaluation criteria','modality limit','validation needed','policy restriction','action failure','missing confirmation','replanning needed'],'issue.type');for(const k of ['scope','evidence_or_missing_input','consequence'])string(i[k],'issue.'+k);bool(i.can_safely_continue,'issue.can_safely_continue');});
 if(v.status!=='complete'&&!v.issues.length)fail('CLASSROOM_INCOMPLETE_WITHOUT_ISSUE');if(v.status==='blocked'&&v.next_action!==null)fail('CLASSROOM_BLOCKED_ACTION');
 object(v.artifacts,'artifacts');const legacy=v.artifacts.legacy_consumer;if(legacy){require('./legacy-consumer-adapter').assertValidatedExtension(legacy,mode);if(v.status==='complete'&&legacy.payload.status&&legacy.payload.status!=='ok')fail('CLASSROOM_LEGACY_COMPLETION_INFLATED');}if(v.status==='complete'){const primary={prepare_guidance:['explanation_guides','pedagogical_profile','scaffolding'],coordinate_lesson:['progress'],handle_message:['message_dispositions'],design_check:['checks','diagnostic_specification'],interpret_response:['response_interpretation'],close_class:['continuity','progress'],prepare_continuity:['continuity'],guide_assessment:['assessment_guidance']}[mode];if(!legacy&&!primary.some(k=>Object.hasOwn(v.artifacts,k)))fail('CLASSROOM_PRIMARY_ARTIFACT_REQUIRED');}for(const k of Object.keys(v.artifacts))if(k!=='legacy_consumer'&&!MODE_ARTIFACTS[mode].includes(k))fail('CLASSROOM_ARTIFACT_MODE_MISMATCH',k);
 const d=v.artifacts.message_dispositions;if(d){const seen=new Set();list(d,'message_dispositions').forEach(x=>{exactDisposition(x);claim(x,'disposition');string(x.message_ref,'message_ref');if(seen.has(x.message_ref)||!messageRefs.includes(x.message_ref))fail('CLASSROOM_MESSAGE_IDENTITY_MISMATCH');seen.add(x.message_ref);enumeration(x.classification,['question about the material','clarification request','expression of confusion','response to a teacher question','relevant contribution or connection','message needing clarification or respectful redirection'],'classification');enumeration(x.disposition,['answer','queue','request clarification','combine with related questions','redirect respectfully','preserve for follow-up'],'disposition');enumeration(x.response_timing,TIMINGS,'response_timing');enumeration(x.acknowledgement_status,['confirmed','requested'],'acknowledgement_status');enumeration(x.reply_delivery_status,['not_delivered','delivery_requested','delivered_confirmed','failed','unknown'],'reply_delivery_status');enumeration(x.difficulty_resolution,['unresolved','not_established','resolved','not_applicable'],'difficulty_resolution');if(x.acknowledgement_status==='confirmed'&&!confirmedAcknowledgements.includes(x.message_ref))fail('CLASSROOM_ACK_CONFIRMATION_REQUIRED');if(x.reply_delivery_status==='delivered_confirmed'&&!confirmedReplies.includes(x.message_ref))fail('CLASSROOM_REPLY_CONFIRMATION_REQUIRED');if(x.difficulty_resolution==='resolved'&&!resolvedDifficulties.includes(x.message_ref))fail('CLASSROOM_RESOLUTION_EVIDENCE_REQUIRED');if(x.confirmed_queue_state==='answered'&&!confirmedReplies.includes(x.message_ref))fail('CLASSROOM_ANSWER_CONFIRMATION_REQUIRED');for(const f of ['confirmed_queue_state','requested_queue_transition'])if(x[f]!=null)enumeration(x[f],['waiting','ready','needing clarification','answered','unresolved at closure'],f);});if(v.status==='complete'&&seen.size!==messageRefs.length)fail('CLASSROOM_MESSAGE_DISPOSITION_MISSING');}
 if(mode==='handle_message'&&messageRefs.length&&v.status==='complete'&&!d)fail('CLASSROOM_MESSAGE_DISPOSITION_MISSING');
 if(v.artifacts.pedagogical_profile){const {validatePedagogyProfile}=require('../d12/contracts');validatePedagogyProfile(v.artifacts.pedagogical_profile);claim(v.artifacts.pedagogical_profile,'profile');}
 if(v.artifacts.explanation_guides){const g=v.artifacts.explanation_guides;claim(g,'guides');list(g.covered_refs,'covered_refs');list(g.uncovered_refs,'uncovered_refs');if(chapter){if(g.source_version!==chapter.version)fail('CLASSROOM_GUIDE_VERSION_MISMATCH');g.covered_refs.forEach(r=>resolveAnchor(r,chapter));}list(g.teaching_units,'teaching_units').forEach(u=>{string(u.unit_ref,'unit_ref');list(u.source_elements,'source_elements');list(u.passages,'passages').forEach(p=>{claim(p,'passage');for(const k of ['passage_ref','meaning','intended_understanding','expand_when','stop_when'])string(p[k],k);for(const k of ['terms','reasoning','representations','likely_confusion','essential','optional_expansion','pauses','connections','interaction_or_check_refs'])list(p[k],k);});});}
 if(v.artifacts.checks)list(v.artifacts.checks,'checks').forEach(c=>{exact(c,['decision_question','target_objective','intended_evidence_claim','candidate_ref','student_facing','private','lineage_exposure_reuse','task_demand','permitted_assistance','response_form','response_window_requirements','inference_ceiling','sufficiency_condition','stopping_condition','validation_status','basis','evidence_refs'],'check');claim(c,'check');exact(c.student_facing,['question'],'check.student_facing');exact(c.private,['expected_solution_or_criteria','acceptable_alternatives'],'check.private');list(c.private.acceptable_alternatives,'acceptable_alternatives');validateDemand(c.task_demand);for(const k of ['decision_question','target_objective','intended_evidence_claim','inference_ceiling','sufficiency_condition','stopping_condition','response_form'])string(c[k],k);string(c.student_facing?.question,'student_facing.question');object(c.private,'check.private');if(c.expected_solution_or_criteria!==undefined)fail('CLASSROOM_PRIVATE_CRITERIA_LEAK');if(c.private.expected_solution_or_criteria==null)fail('CLASSROOM_CRITERIA_REQUIRED');enumeration(c.validation_status,['validated candidate','self-checked','requires validation'],'validation_status');if(c.validation_status==='requires validation'&&v.next_action!==null)fail('CLASSROOM_UNVALIDATED_CHECK_RELEASE');});
 if(v.next_action!==null){const a=v.next_action;exact(a,['action','targets','purpose','reason','basis','evidence_refs','timing','preconditions','assistance_limits','response_waiting_constraints','presenter_guidance','completion_signal','resume_at','fallback',...(Object.hasOwn(a,'conditional_follow_up')?['conditional_follow_up']:[])],'next_action');claim(a,'next_action');enumeration(a.action,ACTIONS,'action');enumeration(a.timing,TIMINGS,'timing');object(a.targets,'targets');for(const k of ['purpose','reason','completion_signal','resume_at','fallback'])string(a[k],k);list(a.preconditions,'preconditions');object(a.presenter_guidance,'presenter_guidance');}
 require('./artifact-shapes').validateInternalArtifacts(v.artifacts);
 list(v.runtime_requests,'runtime_requests').forEach(r=>{exact(r,['ref','action','owner','target_refs','preconditions','confirmation_needed'],'runtime_request');for(const k of ['ref','action','owner','confirmation_needed'])string(r[k],k);list(r.target_refs,'target_refs');list(r.preconditions,'preconditions');});return v;
}
const DIRECTIVE_FIELDS=Object.freeze(['academic_mode','instructional_purpose','approved_action','target_competence_or_question','allowed_interaction_kinds','assistance_ceiling','current_assistance_state','evidence_intent','restrictions','expected_student_action','current_learning_stage','presentation_span','response_budget','source_refs','board_refs','task_ref','time_constraints','response_window','resume_at','accepted_evaluation']);
function validateDirective(d){
 exact(d,DIRECTIVE_FIELDS,'directive');enumeration(d.academic_mode,['teaching','guided practice','independent practice','homework','classwork','controlled assessment','examination','outside-class Q&A'],'academic_mode');enumeration(d.approved_action,['explain','probe','hint','example','analogy','wait','challenge','correct teacher','clarify source','explain with the Board','transition','answer outside class','acknowledge'],'approved_action');for(const k of ['instructional_purpose','target_competence_or_question','resume_at'])string(d[k],k);for(const k of ['allowed_interaction_kinds','restrictions','presentation_span','source_refs','board_refs'])list(d[k],k);enumeration(d.assistance_ceiling,ASSISTANCE_LEVELS,'assistance_ceiling');enumeration(d.current_assistance_state,ASSISTANCE_LEVELS,'current_assistance_state');if(ASSISTANCE_LEVELS.indexOf(d.current_assistance_state)>ASSISTANCE_LEVELS.indexOf(d.assistance_ceiling))fail('CLASSROOM_ASSISTANCE_CEILING_EXCEEDED');enumeration(d.evidence_intent,['instruction_only','practice','independent_evidence','formal_measurement','none'],'evidence_intent');enumeration(d.expected_student_action,['answer','reasoning','prediction','selection','explanation','attempt','readiness','none'],'expected_student_action');enumeration(d.current_learning_stage,['demonstration','guided','independent_familiar','independent_varied','method_selection','delayed_retrieval','integration_transfer','unknown','not_applicable'],'current_learning_stage');if(!Number.isSafeInteger(d.response_budget)||d.response_budget<=0)fail('CLASSROOM_RESPONSE_BUDGET_REQUIRED');object(d.time_constraints,'time_constraints');return d;
}
const ACTION_MAP=Object.freeze({'continue':'explain','answer message':'explain','clarify':'explain','clarification':'explain','missing step':'explain','misconception repair':'explain','focused probe':'probe','independent attempt':'probe','further verification':'probe','request clarification':'probe','hint':'hint','new example':'example','representation change':'explain','change example or representation':'explain','guided practice':'explain','prepare closure':'transition','wait':'wait'});
function bindDirective(decision,binding){
 enumeration(decision.action,ACTIONS,'action');if(!ACTION_MAP[decision.action])return {kind:'engine_action',action:decision.action,directive:null};
 const d={...binding,approved_action:ACTION_MAP[decision.action]};validateDirective(d);
 if(d.response_window?.state==='OPEN'&&decision.action!=='wait'&&!(binding.task_ref&&decision.targets?.task_ref===binding.task_ref&&['answer message','request clarification','hint','clarification','clarify','missing step'].includes(decision.action)))fail('CLASSROOM_OPEN_WINDOW_UNRELATED_MOVE');
 if(binding.accepted_evaluation!==null){const a=binding.accepted_evaluation;exact(a,['receipt_id','task_ref','criterion_ref','source_version','assistance_version','state_reference','accepted'],'acceptance');if(a.accepted!==true||a.task_ref!==binding.task_ref)fail('CLASSROOM_FEEDBACK_NOT_ACCEPTED');for(const k of ['receipt_id','criterion_ref','source_version','assistance_version','state_reference'])string(a[k],k);}
 return {kind:'presenter',directive:d};
}
function projectPortion(p){return {id:p.id,sequence:p.sequence,teacher_message:p.teacher_message,source_refs:p.source_refs.map(r=>({...versionRef(r)})),board_refs:[...p.board_refs],task_ref:p.task_ref,boundary:p.boundary,correction_of:p.correction_of};}
function projectChapter(c){validateChapter(c);if(c.completeness!=='complete'||c.validation!=='validated')fail('CLASSROOM_CHAPTER_NOT_PUBLIC_READY');return {id:c.id,version:c.version,title:c.title,units:c.units.map(u=>({anchor:u.anchor,title:u.title,reading_status:u.treatment==='deferred'?'DEFERRED':u.designation==='optional_depth'?'OPTIONAL':'AVAILABLE',elements:u.elements.map(e=>({anchor:e.anchor,type:e.type,text:e.text,asset_ref:e.asset_ref,alt_text:e.alt_text,source_refs:[...e.source_refs]}))})),remaps:c.remaps.map(r=>({prior_version:r.prior_version,from:r.from,to:[...r.to],reason:r.reason}))};}
function schemaDescriptor(role,mode,validate){const modes=role==='coordinator'?COORDINATOR_MODES:role==='author'?AUTHOR_MODES:role==='presenter'?PRESENTER_MODES:null;if(!modes?.includes(mode))fail('CLASSROOM_MODE_UNKNOWN');return Object.freeze({id:'classroom.'+role+'.'+mode,version:VERSION,uncertainty_states:['INSUFFICIENT_EVIDENCE','UNRESOLVED_CONFLICT','REVIEW_NEEDED'],review_needed_field:'review_required',declared_fields:role==='coordinator'?COORDINATOR_FIELDS:[],state_bearing_fields:['status'],student_facing_field:null,validate});}
module.exports={VERSION,AUTHOR_MODES,COORDINATOR_MODES,PRESENTER_MODES,COORDINATOR_FIELDS,AUTHOR_STATUSES,PRESENTER_STATUSES,ACTIONS,TIMINGS,BASIS,DIRECTIVE_FIELDS,MODE_ARTIFACTS,ACTION_MAP,fail,object,string,list,bool,enumeration,exact,noAuthority,claim,versionRef,resolveAnchor,validateChapter,validatePlan,validateCoordinator,validateDirective,bindDirective,projectPortion,projectChapter,schemaDescriptor};
