'use strict';
// Model-visible structural projection of the closed runtime validators. It
// describes fields, never creates policy values or authorizes publication.
const c=require('./contracts');
const {D11_BLUEPRINT_OUTPUT_FORMAT}=require('../d11/blueprint-output-contract');
const reference={kind:'chapter|chapter_unit|source_element|course_learning_unit|plan|guide|portion|task|criterion|message|board|closure|response|interpretation',id:'nonempty string',version:'nonempty string',anchor:'string|null; exact registered anchor'};
const chapter={id:'string',version:'string',scope_ref:'string',title:'string',completeness:'complete|partial|blocked',validation:'candidate|checked|validated|validation_needed',units:[{anchor:'string',title:'string',objective_refs:[reference],prerequisite_refs:[reference],designation:'essential|supporting|optional_depth',treatment:'scheduled|support|deferred',elements:[{anchor:'unit anchor + . + stable element suffix',type:'paragraph|equation|diagram|example|code|passage',text:'substantial source-grounded content',asset_ref:'board version reference|null',alt_text:'string|null; required for diagram',source_refs:['source identifiers']}]}],continuation:'null except partial: {candidate_id,candidate_version,last_complete_unit,remaining_units[],preserved_hashes:{unitAnchor:sha256},next_task}',prior_version:'string|null',remaps:[{prior_version:'string',from:'prior anchor',to:['current anchors; [] for explicit retirement'],reason:'string'}]};
const plan={id:'string',version:'string',chapter_ref:reference,objectives:[{ref:reference,priority:'core|secondary|optional_enrichment',completion_standard:'string'}],phases:[{purpose:'string',source_refs:[reference],minutes:'nonnegative finite number from adopted time budget',kind:'instruction|interaction|break|assessment|closure'}],time_ledger:{usable_minutes:'adopted usable duration',reserve_minutes:'adopted D11 reserve',accounting_basis:'string'},remediation_branches:[{blocker:'string',strategy_requirement:'string',budget:'string',return_evidence:'string',carry_forward_condition:'string'}],carry_forward:['bounded proposals']};
const guide={basis:c.BASIS,evidence_refs:['actual evidence identifiers'],source_version:'chapter version',covered_refs:[reference],uncovered_refs:[reference],teaching_units:[{unit_ref:'exact chapter unit anchor',source_elements:['exact source element anchors'],passages:[{basis:c.BASIS,evidence_refs:['actual evidence identifiers'],passage_ref:'source element anchor',meaning:'string',intended_understanding:'string',expand_when:'string',stop_when:'string',terms:[],reasoning:[],representations:[],likely_confusion:[],essential:[],optional_expansion:[],pauses:[],connections:[],interaction_or_check_refs:[]}]}]};
function classroomOutputFormat(role,mode,context={}) {
 const common={version:c.VERSION,role,mode,priority:'Return only the closed runtime JSON envelope described here. Runtime format takes precedence over generic examples in the candidate body. Every required field is present; artifact keys are limited to this mode. No official outcomes or committed-state claims.',reference,claims:{basis:c.BASIS,evidence_refs:['actual evidence identifiers']}};
 if(role==='author')return {...common,required_fields:['task_mode','input_state_reference','status','review_required','review_reasons','completion','provenance','artifacts','handoff'],task_mode:mode,status:c.AUTHOR_STATUSES,review_required:'boolean',review_reasons:[],completion:'map of requested artifact key to complete|partial|blocked|not_requested',provenance:{},handoff:[],allowed_artifacts:require('./mode-schemas').AUTHOR_BLOCKS[mode],artifact_formats:{chapter,unit_map:[reference],teaching_plan:plan,controller_blueprint:{...D11_BLUEPRINT_OUTPUT_FORMAT,placement:'artifacts.controller_blueprint; return retained D11 object here, within the classroom author envelope'},learning_trajectory:{current_stage:'demonstration|guided|independent_familiar|independent_varied|method_selection|delayed_retrieval|integration_transfer|unknown|not_applicable',evidence_goals:[],next_stage_requirements:[]},preparation_update:{dependency_refs:[],required_stages:[],pending_artifacts:[]},homework_proposal:{assign:'boolean proposal only',purpose:'string',student_tasks:[],private:{}},closure_or_replan:{preserved_work:[],carry_forward:[],current_position:'string'}}};
 if(role==='coordinator')return {...common,required_fields:c.COORDINATOR_FIELDS,task_mode:mode,status:['complete','partial','blocked'],review_required:'boolean',request_ref:'string|null',input_state_reference:'string|null',next_action:'null during preparation; live directive proposal must satisfy registered action contract',runtime_requests:[],issues:[{type:'registered issue type',scope:'string',evidence_or_missing_input:'string',consequence:'string',owner:'owner identifier',can_safely_continue:'boolean'}],allowed_artifacts:[...c.MODE_ARTIFACTS[mode],...(context.legacyRequest?['legacy_consumer']:[])],artifact_formats:{explanation_guides:guide,continuity:{basis:c.BASIS,evidence_refs:[],record_or_summary:'string',source_links:[],demonstrated_evidence:[{basis:c.BASIS,evidence_refs:[],claim:'bounded claim',limits:'string'}],unresolved_questions:[],unfinished_essentials:[],assistance_given:[],follow_up:{confirmed:[],proposed:[]}},legacy_consumer:context.legacyRequest?{payload:{declared_fields:context.legacyRequest.outputSchema.declared_fields,contract:'Exact original caller schema and validators; server owns envelope identity, acceptance and hash'}}:null},internal_artifact_shape_contract:require('node:fs').readFileSync(require.resolve('./artifact-shapes'),'utf8'),live_decision_contract:require('node:fs').readFileSync(require.resolve('./contracts'),'utf8')};
 return {...common,required_fields:require('./mode-schemas').PRESENTER_FIELDS,task_mode:mode,status:c.PRESENTER_STATUSES,input_state_reference:'string|null',review_required:'boolean',provenance:{},interaction:{instructional_purpose:'string',portions:[{id:'stable string',sequence:'1-based consecutive integer',teacher_message:'natural source-grounded teaching',source_refs:[reference],board_refs:[],task_ref:'string|null',boundary:'reading_boundary|suitable_teaching_pause',publication_dependencies:[],wait_requirement:'none|student_response|evaluation|new_directive',resume_at:'exact current anchor',expected_student_action:'string|null',correction_of:'string|null'}],silence:'boolean',expects_student_response:'boolean',expected_response_kind:'string|null',preparation_completion:'complete|partial|blocked',stop_reason:'string|null'},board:[{id:'string',operation:'add|highlight|reveal|annotate|compare|clear|restore; supplied supported operations only',type:'text|equations|worked_steps|code|sources|graph|data|comparison|diagram|student_work_annotation',content:'D14 block-specific content object',target_ref:'version reference|null',depends_on:[]}],policy:{academic_mode:'exact directive.academic_mode',approved_action:'exact directive.approved_action',assistance_ceiling:'exact directive.assistance_ceiling'},content_integrity:{validation_status:'checked|validation_needed|not_applicable',checkable_content_generated:'boolean'},teacher_correction:{},continuity:{},uncertainties:[],handoff:[]};
}
module.exports={classroomOutputFormat};
