'use strict';

const { randomUUID } = require('node:crypto');

function optional(name) { try { return require(name); } catch { return null; } }
const defaultParsers = Object.freeze({ pdf:optional('pdf-parse'), docx:optional('mammoth'), pptx:optional('officeparser') });
const MAX_TEXT = 80_000;
const CHUNK_SIZE = 12_000;

function chunks(text) { const out=[]; for(let i=0;i<text.length;i+=CHUNK_SIZE)out.push(text.slice(i,i+CHUNK_SIZE)); return out; }
function stripMarkdown(text) { return text.replace(/^#{1,6}\s+/gm,'').replace(/\*\*([^*]+)\*\*/g,'$1').replace(/__([^_]+)__/g,'$1').replace(/\*([^*]+)\*/g,'$1').replace(/_([^_]+)_/g,'$1').replace(/~~([^~]+)~~/g,'$1').replace(/`{1,3}[^`]*`{1,3}/g,'').replace(/\[([^\]]+)\]\([^)]+\)/g,'$1').replace(/^\s*[-*+]\s+/gm,'').replace(/^\s*\d+\.\s+/gm,''); }
function bounded(text) { return String(text||'').trim().slice(0,MAX_TEXT); }
function fail(res,status,error,details) { return res.status(status).json(details?{error,details}:{error}); }

function createStudyImportRouter({ express, db, generateFlashcards, parseFlashcards, extractFromImage, generateCBTQuestions, parseCBTResponse, estimateCBTCount, batchInitializeSeedlingStates, persistKnowledgeScore, checkAIRateLimit, jobStoreSet, wsSend, parsers=defaultParsers }={}) {
  if(!express||!db||!generateFlashcards||!parseFlashcards||!batchInitializeSeedlingStates)throw new TypeError('Study import router dependencies are required.');
  const router=express.Router();
  async function persist(userId,deckId,cardsData,source,{recalculate=false}={}) { const created=await db.cards.createMany(userId,deckId,cardsData); await db.decks.update(userId,deckId,{card_count:{increment:created.length}}); await batchInitializeSeedlingStates(userId,created.map(card=>card.id)); if(recalculate){const deck=await db.decks.findById(userId,deckId).catch(()=>null);if(deck?.subject_id)await persistKnowledgeScore(userId,deck.subject_id).catch(error=>console.error('[KIWI] KS recalculation:',error.message));} return {cards:created,count:created.length,source}; }
  async function fromText(text,hint,{fallback=false}={}) { const cards=[];for(const chunk of chunks(text)){try{cards.push(...parseFlashcards(await generateFlashcards(chunk,hint)));}catch(error){if(!fallback)throw error;const lines=chunk.split('\n').filter(line=>line.trim().length>10);for(let i=0;i<lines.length-1;i+=2)cards.push({front_content:lines[i].trim(),back_content:lines[i+1].trim()});}}return cards; }
  async function cbt(text,source,res){const count=estimateCBTCount(text),questions=parseCBTResponse(await generateCBTQuestions(text,count),null,[]);if(!questions.length)return fail(res,422,'AI could not generate CBT questions from this content');return res.status(200).json({questions,count:questions.length,source});}
  async function extractDocument(kind,base64){if(kind==='txt'||kind==='md')return Buffer.from(base64,'base64').toString('utf8');if(kind==='pdf'){if(!parsers.pdf)throw Object.assign(new Error('PDF parsing is not available.'),{status:503});return (await parsers.pdf(Buffer.from(base64,'base64')))?.text||'';}if(kind==='docx'){if(!parsers.docx)throw Object.assign(new Error('DOCX parsing is not available.'),{status:503});return (await parsers.docx.extractRawText({buffer:Buffer.from(base64,'base64')}))?.value||'';}if(kind==='pptx'){if(!parsers.pptx)throw Object.assign(new Error('PPTX parsing is not available.'),{status:503});const buffer=Buffer.from(base64,'base64');if(buffer.length>20*1024*1024)throw Object.assign(new Error('PPTX is too large. Maximum upload size is 20 MB.'),{status:413});const ast=await parsers.pptx.parseOffice(buffer,{fileType:'pptx',decompressionLimits:{maxUncompressedBytes:64*1024*1024,maxZipEntries:5000,maxTableCells:250000}});return (await ast.to('text',{includeImages:false,textConfig:{preserveLayout:false,renderNotes:true}}))?.value||'';}throw new Error('Unsupported document type.');}

  router.post('/ai',async(req,res)=>{try{const {deck_id,notes,subject_hint=''}=req.body;if(!deck_id||!notes)return fail(res,400,'deck_id and notes required');const deck=await db.decks.findById(req.user.id,deck_id).catch(()=>null),subjectId=deck?.subject_id||null,jobId=randomUUID(),userId=req.user.id;jobStoreSet(jobId,{status:'pending',type:'note_generation'});res.status(202).json({job_id:jobId,deck_id,subject_id:subjectId,status:'generating'});setImmediate(async()=>{try{const parsed=parseFlashcards(await generateFlashcards(notes,subject_hint));if(!parsed.length)throw new Error('Could not parse flashcards from AI response');const result=await persist(userId,deck_id,parsed.map(card=>({...card,ai_summary:''})),'ai');result.deck_id=deck_id;result.subject_id=subjectId;result.suggest_bubble=subjectId!==null&&result.count>=5;jobStoreSet(jobId,{status:'done',type:'note_generation',result});wsSend(userId,'job_done',{job_id:jobId,type:'note_generation',result});}catch(error){jobStoreSet(jobId,{status:'failed',type:'note_generation',error:error.message});wsSend(userId,'job_failed',{job_id:jobId,type:'note_generation',error:error.message});}});}catch(error){fail(res,500,'AI import failed',error.message);}});
  router.post('/text',async(req,res)=>{try{const {deck_id,text,format='qa_pairs',delimiter='::'}=req.body;if(!deck_id||!text)return fail(res,400,'deck_id and text required');const cards=[];for(const line of text.split('\n').filter(x=>x.trim())){const parts=format==='csv'?line.split(','):line.split(delimiter);if(parts[0]&&parts[1])cards.push({front_content:parts[0].trim(),back_content:parts.slice(1).join(format==='csv'?',':delimiter).trim()});}if(!cards.length)return fail(res,422,'No valid cards found in text');res.status(201).json(await persist(req.user.id,deck_id,cards,'text'));}catch(error){fail(res,500,'Text import failed',error.message);}});
  router.post('/image',async(req,res)=>{try{const {deck_id,image_base64,mime_type='image/jpeg'}=req.body;if(!deck_id||!image_base64)return fail(res,400,'deck_id and image_base64 required');const extracted=await extractFromImage(Buffer.from(image_base64,'base64'),mime_type);let cards=[];try{const parsed=JSON.parse(extracted);if(Array.isArray(parsed))cards=parsed.map(item=>({front_content:item.front||item.question||'',back_content:item.back||item.answer||''})).filter(card=>card.front_content&&card.back_content);}catch{for(const line of extracted.split('\n').filter(x=>x.includes(':')||x.includes('—'))){const parts=line.split(/[:—]/);if(parts.length>=2)cards.push({front_content:parts[0].trim(),back_content:parts.slice(1).join(' — ').trim()});}}if(!cards.length)return fail(res,422,'Could not extract cards from image');res.status(201).json(await persist(req.user.id,deck_id,cards,'image'));}catch(error){fail(res,500,'Image import failed',error.message);}});

  for(const kind of ['pdf','docx','txt','md','pptx'])router.post(`/${kind}`,async(req,res)=>{try{const base64=req.body[`${kind}_base64`],{deck_id,mode='flashcard',subject_hint=''}=req.body;if(!base64)return fail(res,400,`${kind}_base64 is required`);if(mode!=='cbt'&&!deck_id)return fail(res,400,'deck_id is required for flashcard mode');let text=bounded(await extractDocument(kind,base64));if(kind==='md')text=bounded(stripMarkdown(text));if(!text)return fail(res,422,kind==='md'?'No usable text in markdown file':`No usable text extracted from ${kind.toUpperCase()}`);if(mode==='cbt')return cbt(text,kind,res);const cards=await fromText(text,subject_hint,{fallback:kind==='pdf'||kind==='docx'});if(!cards.length)return fail(res,422,`AI could not generate cards from this ${kind==='pptx'?'presentation':'content'}`);res.status(201).json(await persist(req.user.id,deck_id,cards,kind,{recalculate:kind==='docx'}));}catch(error){fail(res,error.status||500,`${kind.toUpperCase()} import failed`,error.status?undefined:error.message);}});

  router.post('/quizlet',async(req,res)=>{try{const {deck_id,text,url}=req.body;if(!deck_id||(!text&&!url))return fail(res,400,'deck_id and either text or url required');if(url&&checkAIRateLimit(req.user.id,'quizlet_import',5,86400000))return fail(res,429,'Rate limit: max 5 Quizlet URL imports per day');let cards=[];if(url){const html=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0'},signal:AbortSignal.timeout(10000)}).then(response=>response.text());const match=html.match(/"setData"\s*:\s*({[\s\S]?})\s*[,}]/);if(match){const data=JSON.parse(match[1]),terms=data.terms||data.studiableItems||[];cards=terms.map(term=>({front_content:term.word||term.term||term.sides?.[0]?.label||'',back_content:term.definition||term.sides?.[1]?.label||''})).filter(card=>card.front_content&&card.back_content);}}else{for(const line of text.split('\n').filter(x=>x.trim())){let parts=line.split('\t');if(parts.length<2)parts=line.split(/[—–]/);if(parts.length>=2)cards.push({front_content:parts[0].trim(),back_content:parts.slice(1).join(' — ').trim()});}}if(!cards.length)return fail(res,422,'No valid Quizlet cards found');res.status(201).json(await persist(req.user.id,deck_id,cards,url?'quizlet_url':'quizlet_text',{recalculate:true}));}catch(error){fail(res,500,'Quizlet import failed',error.message);}});
  return router;
}

module.exports={createStudyImportRouter,stripMarkdown,bounded,chunks};
