'use strict';

const RECKONING_ENGINE = Object.freeze({
  NAME: 'reckoning-v2',
  ENGINE_VERSION: 2,
  ARCHITECTURE_VERSION: 1,
  STATUS: 'SCAFFOLD',
});

const SESSION_PHASES = Object.freeze({
  PREPARING: 'PREPARING',
  ACTIVE: 'ACTIVE',
  FINALIZING: 'FINALIZING',
  COMPLETE: 'COMPLETE',
});

const QUESTION_ROLES = Object.freeze({
  DIAGNOSTIC: 'DIAGNOSTIC',
  CONTROL: 'CONTROL',
  CHALLENGE: 'CHALLENGE',
  CONFIRMATION: 'CONFIRMATION',
});

const EVIDENCE_STATUSES = Object.freeze({
  UNTESTED: 'UNTESTED',
  PROVISIONAL: 'PROVISIONAL',
  CHALLENGE_REQUIRED: 'CHALLENGE_REQUIRED',
  CONFIRMATION_REQUIRED: 'CONFIRMATION_REQUIRED',
  RECOVERED: 'RECOVERED',
  UNRESOLVED: 'UNRESOLVED',
  INVALIDATED: 'INVALIDATED',
});

const RISK_LEVELS = Object.freeze({
  CRITICAL: 'CRITICAL',
  HIGH: 'HIGH',
  SUPPORTING: 'SUPPORTING',
});

module.exports = {
  RECKONING_ENGINE,
  SESSION_PHASES,
  QUESTION_ROLES,
  EVIDENCE_STATUSES,
  RISK_LEVELS,
};
