'use strict';
const test=require('node:test'),assert=require('node:assert/strict');const {randomUUID}=require('node:crypto');
const {integrationConfig,assertNonProductionDatabase,createIntegrationPool}=require('./test-db');
const {fixture}=require('../fixtures/classroom-database');const f=require('../fixtures/classroom-remodel-academic');const {fixturePolicy}=require('../fixtures/classroom-presentation-policy');
const {connectionString,projectRef,skipReason:skip}=integrationConfig('Classroom durable presentation');
async function harness(run,{concurrent=false}={}){assertNonProductionDatabase({connectionString,projectRef});const local=['localhost','127.0.0.1','::1'].includes(new URL(connectionString).hostname);const pool=new (require('pg').Pool)({connectionString,ssl:local?false:{rejectUnauthorized:false},max:concurrent?4:1}),client=await pool.connect();await client.query('BEGIN');let seq=0,committed=false;
 const withTransaction=async fn=>{if(committed){const tx=await pool.connect();try{await tx.query('BEGIN');const result=await fn(tx);await tx.query('COMMIT');return result;}catch(error){await tx.query('ROLLBACK');throw error;}finally{tx.release();}}const name='presentation_'+(++seq);await client.query('SAVEPOINT '+name);try{const result=await fn(client);await client.query('RELEASE SAVEPOINT '+name);return result;}catch(error){await client.query('ROLLBACK TO SAVEPOINT '+name);await client.query('RELEASE SAVEPOINT '+name);throw error;}};
 const query=(...args)=>committed?pool.query(...args):client.query(...args);
 try{const ids=await fixture(client);await query("update public.teaching_classes set scheduled_start_at=now()-interval '1 minute',scheduled_end_at=now()+interval '1 hour' where class_id=$1",[ids.classId]);
  const academic=require('../../../teaching/repositories/classroom-academic-artifacts').createClassroomAcademicRepository({query,withTransaction,randomUUID});
  const base={...ids,expectedScheduleVersion:1,expectedPlanVersion:1};const artifacts={};
  for(const kind of ['chapter','plan','guide','opening']){const context=kind==='chapter'?{requiredUnits:['U01']}:{chapter:f.chapter(),essentialAnchors:['U01.E01'],directive:f.directive(),supportedBoardOperations:[]};const dependencies=Object.values(artifacts).map(a=>({kind:a.artifact_kind,ref:a.logical_id,version:a.logical_version,artifactId:a.artifact_version_id}));const a=await academic.saveCandidate({...base,kind,operationKey:kind,logicalId:kind+'1',logicalVersion:'1',payload:f[kind](),producer:f.producer(kind),context,dependencies});await academic.recordValidation({studentId:ids.studentId,artifactId:a.artifact_version_id,receipt:{accepted:true,independent:true,routeQualified:true,reviewId:'FIXTURE_NOT_PROVIDER',contentHash:a.content_sha256}});artifacts[kind]=a;}
  await academic.bindReady({...base,blueprintId:ids.blueprint,chapterId:artifacts.chapter.artifact_version_id,planId:artifacts.plan.artifact_version_id,guideId:artifacts.guide.artifact_version_id,openingId:artifacts.opening.artifact_version_id,receipt:{ready:true,delivery1GatePassed:true,routesQualified:true,pplReady:true,evidenceKind:'FIXTURE'}});
  const sessionId=ids.classId+'-session';await query("insert into public.teaching_class_sessions(class_session_id,student_id,class_id,course_id,course_plan_id,lesson_blueprint_id,lifecycle_state,instructional_substate,state_version,started_at,classroom_engine,classroom_chapter_artifact_id,classroom_binding_version) values($1,$2,$3,$4,$5,$6,'ACTIVE','INSTRUCTION',1,now(),'CLASSROOM_V1',$7,1)",[sessionId,ids.studentId,ids.classId,ids.course,ids.coursePlanId,ids.blueprint,artifacts.chapter.artifact_version_id]);
  const d11Repository=require('../../../teaching/repositories/d11-lesson-controller').createD11LessonControllerRepository({query,withTransaction,randomUUID});
  const d14Repository=require('../../../teaching/repositories/d14-classroom').createD14ClassroomRepository({query,withTransaction,randomUUID,d11Repository});
  const dueEventStore=require('../../../teaching/runtime/postgres-event-store').createPostgresTeachingEventStore({query,randomUUID});
  const outboxStore=require('../../../teaching/runtime/postgres-outbox-store').createPostgresTeachingOutboxStore({query,randomUUID});
  const repository=require('../../../teaching/repositories/classroom-presentation').createClassroomPresentationRepository({query,withTransaction,randomUUID,d14Repository,dueEventStore,outboxStore});
  await repository.initialize({studentId:ids.studentId,classId:ids.classId,policy:fixturePolicy(),pace:'normal'});
  const read=()=>repository.read(ids.studentId,ids.classId,{snapshot:true});
  const args=(snapshot,extra)=>({schemaVersion:'classroom-domain.v1',sessionId,operationKey:randomUUID(),expectedControllerVersion:snapshot.controller_version,expectedDeliveryVersion:snapshot.delivery_version,deliveryEpoch:snapshot.delivery_epoch,controlEpoch:snapshot.control_epoch,clientId:'first',...extra});
  const accept=async output=>repository.acceptSequence({studentId:ids.studentId,classId:ids.classId,operationKey:randomUUID(),output:output||f.opening(),directive:f.directive(),expected:await repository.capture(ids.studentId,ids.classId),types:['text']});
  if(concurrent){await client.query('COMMIT');committed=true;}
  await run({ids,sessionId,query,withTransaction,repository,read,args,accept,d14Repository,dueEventStore});
 }finally{if(!committed)await client.query('ROLLBACK');client.release();await pool.end();}}
test('presentation tables enforce service-only RLS and immutable private content',{skip},async()=>harness(async({query,repository,accept})=>{
 const tables=(await query("select c.relname,c.relrowsecurity,has_table_privilege('authenticated',c.oid,'SELECT') browser_read from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in ('teaching_classroom_delivery','teaching_classroom_sequences','teaching_classroom_portions','teaching_classroom_conversation','teaching_classroom_delivery_receipts','teaching_classroom_delivery_commands')")).rows;assert.equal(tables.length,6);assert.ok(tables.every(t=>t.relrowsecurity&&!t.browser_read));await accept();await assert.rejects(()=>repository.command('other','missing',{}));
}));
test('publication is durable and private until released; receipts, reload, duplicate due and takeover preserve one effect',{skip},async()=>harness(async h=>{
 const {ids,repository,read,args,accept,query,dueEventStore}=h;const output=f.opening();output.interaction.portions.push({...f.clone(output.interaction.portions[0]),id:'portion2',sequence:2,teacher_message:'Now retain the stated conditions when applying this relationship.'});await accept(output);
 assert.equal((await read()).conversation.length,0);assert.equal((await read()).released_portions.length,0);
 const claim=await repository.command(ids.studentId,ids.classId,args(await read(),{intent:'claim'}));assert.ok(claim.leaseToken);
 const event=(await dueEventStore.claimDue({workerId:'fixture-worker',now:new Date(),leaseMs:60000})).find(e=>e.event_type==='teaching.classroom.portion_release_due'&&e.payload.class_id===h.ids.classId);assert.ok(event);
 const first=await repository.release(ids.studentId,ids.classId,{event});assert.equal(first.released,true);assert.equal((await repository.release(ids.studentId,ids.classId,{event})).released,false);
 let snapshot=await read();assert.equal(snapshot.conversation.length,1);assert.equal(snapshot.position.last_render_confirmed,0);assert.equal(snapshot.capabilities.messages,false);
 const receipt=args(snapshot,{portionId:first.portionId,leaseToken:claim.leaseToken,renderState:'accessible_ready',active:true,representationReady:true,readyAssetIds:[]});
 assert.equal((await repository.receipt(ids.studentId,ids.classId,receipt)).masteryEstablished,false);assert.equal((await repository.receipt(ids.studentId,ids.classId,receipt)).replay,true);
 await query('select pg_sleep(0.03)');assert.equal((await repository.release(ids.studentId,ids.classId,{event})).reason,'STALE_DUE_PORTION');
 snapshot=await read();const takeover=await repository.command(ids.studentId,ids.classId,args(snapshot,{intent:'takeover',clientId:'second'}));assert.equal(takeover.controlEpoch,2);
 await assert.rejects(async()=>repository.command(ids.studentId,ids.classId,args(await read(),{intent:'pause',leaseToken:claim.leaseToken})),{code:'CLASSROOM_CLIENT_LEASE_STALE'});
 assert.equal((await repository.release(ids.studentId,ids.classId)).released,true);
 assert.equal((await query('select count(*)::int n from public.teaching_teacher_communications where class_session_id=$1',[h.sessionId])).rows[0].n,2);
 assert.equal((await read()).conversation.length,2);const delta=await repository.read(ids.studentId,ids.classId,{after:1});assert.equal(delta.events.length,1);assert.equal(delta.events[0].sequence,2);
 await assert.rejects(()=>repository.read(ids.studentId,ids.classId,{after:99}),{code:'CLASSROOM_CURSOR_RESET_REQUIRED'});
}));
test('atomic D14 failure rolls back conversation, portion publication and outbox',{skip},async()=>harness(async h=>{
 await h.accept();await h.repository.command(h.ids.studentId,h.ids.classId,h.args(await h.read(),{intent:'claim'}));const original=h.d14Repository.publishTeacherTurnUsing;
 // Repository object is frozen; inject a wrapper in a second engine over the same state.
 const failing=require('../../../teaching/repositories/classroom-presentation').createClassroomPresentationRepository({query:h.query,withTransaction:h.withTransaction,randomUUID,dueEventStore:h.dueEventStore,outboxStore:{appendUsing:()=>{throw new Error('crash-before-commit');}},d14Repository:{publishTeacherTurnUsing:original}});
 await assert.rejects(()=>failing.release(h.ids.studentId,h.ids.classId),/crash-before-commit/);assert.equal((await h.read()).conversation.length,0);assert.equal((await h.query('select count(*)::int n from public.teaching_teacher_communications where class_session_id=$1',[h.sessionId])).rows[0].n,0);assert.equal((await h.repository.release(h.ids.studentId,h.ids.classId)).released,true);
}));
test('protected transition fences generation, clears public history and invalidates pending portions',{skip},async()=>harness(async h=>{
 const expected=await h.repository.capture(h.ids.studentId,h.ids.classId);await h.accept();await h.query("update public.teaching_class_sessions set instructional_substate='ASSESSMENT',state_version=state_version+1 where class_session_id=$1",[h.sessionId]);
 assert.equal((await h.repository.acceptSequence({studentId:h.ids.studentId,classId:h.ids.classId,operationKey:'late',output:f.opening(),directive:f.directive(),expected})).accepted,false);
 const snapshot=await h.read();assert.equal(snapshot.chapter_ref,null);assert.equal(snapshot.position.resume_anchor,null);assert.deepEqual(snapshot.conversation,[]);assert.equal(snapshot.delivery_state,'RECOVERING');assert.equal((await h.repository.release(h.ids.studentId,h.ids.classId)).released,false);
 assert.equal((await h.query("select count(*)::int n from public.teaching_classroom_portions where session_id=$1 and status='SUPERSEDED'",[h.sessionId])).rows[0].n,1);
}));
test('paused authoritative end invalidates teaching without changing D11 lifecycle',{skip},async()=>harness(async h=>{
 await h.accept();const claim=await h.repository.command(h.ids.studentId,h.ids.classId,h.args(await h.read(),{intent:'claim'}));await h.repository.command(h.ids.studentId,h.ids.classId,h.args(await h.read(),{intent:'pause',leaseToken:claim.leaseToken}));
 await h.query("update public.teaching_classes set scheduled_end_at=clock_timestamp()-interval '1 second' where class_id=$1",[h.ids.classId]);const snapshot=await h.read();assert.equal(snapshot.delivery_state,'CLOSING');assert.equal(snapshot.capabilities.presentation,false);assert.equal((await h.query('select lifecycle_state from public.teaching_class_sessions where class_session_id=$1',[h.sessionId])).rows[0].lifecycle_state,'ACTIVE');
}));
test('independent PostgreSQL transactions serialize competing releases and duplicate receipts',{skip},async()=>harness(async h=>{
 await h.accept();const claim=await h.repository.command(h.ids.studentId,h.ids.classId,h.args(await h.read(),{intent:'claim'}));
 const results=await Promise.all([h.repository.release(h.ids.studentId,h.ids.classId),h.repository.release(h.ids.studentId,h.ids.classId)]);assert.equal(results.filter(r=>r.released).length,1);
 const first=results.find(r=>r.released),snapshot=await h.read(),input=h.args(snapshot,{leaseToken:claim.leaseToken,portionId:first.portionId,renderState:'accessible_ready',active:true,representationReady:true,readyAssetIds:[]});
 const receipts=await Promise.all([h.repository.receipt(h.ids.studentId,h.ids.classId,input),h.repository.receipt(h.ids.studentId,h.ids.classId,input)]);assert.equal(receipts.filter(r=>r.replay).length,1);
 assert.equal((await h.query('select count(*)::int n from public.teaching_classroom_delivery_receipts where session_id=$1',[h.sessionId])).rows[0].n,1);assert.equal((await h.query('select count(*)::int n from public.teaching_teacher_communications where class_session_id=$1',[h.sessionId])).rows[0].n,1);
 // This uniquely named committed fixture is retained in CI's disposable database;
 // immutable provenance is never deleted or weakened for test cleanup.
},{concurrent:true}));
test('expired/hidden clients cannot confirm or progress; takeover restores uncertainty without resetting dwell',{skip},async()=>harness(async h=>{
 await h.accept();const claim=await h.repository.command(h.ids.studentId,h.ids.classId,h.args(await h.read(),{intent:'claim'}));const first=await h.repository.release(h.ids.studentId,h.ids.classId);const snapshot=await h.read(),input=h.args(snapshot,{leaseToken:claim.leaseToken,portionId:first.portionId,renderState:'accessible_ready',active:false,representationReady:true,readyAssetIds:[]});
 await assert.rejects(()=>h.repository.receipt(h.ids.studentId,h.ids.classId,input),{code:'CLASSROOM_RENDER_NOT_READY'});assert.equal((await h.read()).position.last_render_confirmed,0);
 await h.query("update public.teaching_classroom_delivery set lease_expires_at=clock_timestamp()-interval '1 second' where session_id=$1",[h.sessionId]);await assert.rejects(()=>h.repository.receipt(h.ids.studentId,h.ids.classId,{...input,active:true}),{code:'CLASSROOM_CLIENT_LEASE_STALE'});
 const takeover=await h.repository.command(h.ids.studentId,h.ids.classId,h.args(await h.read(),{intent:'claim',clientId:'second'}));const recovered=h.args(await h.read(),{clientId:'second',leaseToken:takeover.leaseToken,portionId:first.portionId,renderState:'accessible_ready',active:true,representationReady:true,readyAssetIds:[]});await h.repository.receipt(h.ids.studentId,h.ids.classId,recovered);assert.equal((await h.read()).position.last_render_confirmed,1);
}));
test('missing essential diagram holds publication; explicit text replacement has real Board anchors',{skip},async()=>harness(async h=>{
 const expected=await h.repository.capture(h.ids.studentId,h.ids.classId),output=f.opening(),assetId='missing-essential-fixture';output.board=[{id:'board1',operation:'add',type:'diagram',content:{src:'/api/teaching/classes/'+encodeURIComponent(h.ids.classId)+'/classroom/assets/'+assetId,assetId,alt:'Force and acceleration directions'},target_ref:null,depends_on:[]}];output.interaction.portions[0].board_refs=['board1'];
 await h.repository.acceptSequence({studentId:h.ids.studentId,classId:h.ids.classId,operationKey:'essential',output,directive:f.directive(),expected,types:['diagram'],assets:[assetId]});await h.repository.command(h.ids.studentId,h.ids.classId,h.args(await h.read(),{intent:'claim'}));assert.equal((await h.repository.release(h.ids.studentId,h.ids.classId)).reason,'ESSENTIAL_ASSET_NOT_READY');assert.equal((await h.read()).conversation.length,0);
 await h.repository.invalidate(h.ids.studentId,h.ids.classId,'EXPLICIT_SOURCE_GROUNDED_TEXT_REPLACEMENT');await h.accept();assert.equal((await h.repository.release(h.ids.studentId,h.ids.classId)).released,true);const refs=(await h.read()).released_portions[0].content.board_refs;assert.equal(refs.length,1);assert.equal(refs[0].kind,'board');assert.equal((await h.query('select count(*)::int n from public.teaching_board_items where board_item_id=$1',[refs[0].id])).rows[0].n,1);
}));
test('private sequence, policy pin and committed Board identities reject mutation in PostgreSQL',{skip},async()=>harness(async h=>{
 await h.accept();await assert.rejects(()=>h.withTransaction(tx=>tx.query("update public.teaching_classroom_sequences set payload='{}' where session_id=$1",[h.sessionId])),/IMMUTABLE/);await assert.rejects(()=>h.withTransaction(tx=>tx.query("update public.teaching_classroom_delivery set policy_version='changed' where session_id=$1",[h.sessionId])),/PIN_IMMUTABLE/);
 await h.repository.command(h.ids.studentId,h.ids.classId,h.args(await h.read(),{intent:'claim'}));const first=await h.repository.release(h.ids.studentId,h.ids.classId);await assert.rejects(()=>h.withTransaction(tx=>tx.query("update public.teaching_classroom_portions set board_item_ids='[]',status='CONFIRMED' where portion_id=$1",[first.portionId])),/PUBLICATION_IMMUTABLE/);
}));
test('authenticated HTTP snapshot, lease, receipt and SSE exercise the real persisted release path',{skip},async()=>harness(async h=>{
 const app=require('express')();app.use(require('express').json());app.use((req,res,next)=>{if(req.headers.authorization!=='Bearer fixture-owner')return res.status(401).json({code:'UNAUTHORIZED'});req.user={id:h.ids.studentId};next();});
 const service=require('../../../teaching/classroom-remodel/presentation-service').createClassroomPresentationService({repository:h.repository});require('../../../teaching/classroom-remodel/presentation-routes').mountClassroomPresentationRoutes(app,{service,reauthenticate:async()=>true});
 const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));const base='http://127.0.0.1:'+server.address().port+'/classes/'+h.ids.classId+'/classroom/',headers={Authorization:'Bearer fixture-owner','Content-Type':'application/json'};
 try{
  await h.accept();assert.equal((await fetch(base+'session')).status,401);const snapshot=await (await fetch(base+'session',{headers})).json();assert.equal(snapshot.released_portions.length,0);
  const claim=await (await fetch(base+'client-lease',{method:'POST',headers,body:JSON.stringify(h.args(snapshot,{intent:'claim'}))})).json();assert.ok(claim.leaseToken);
  const event=(await h.dueEventStore.claimDue({workerId:'connected-http-fixture',now:new Date(),leaseMs:60000})).find(e=>e.event_type==='teaching.classroom.portion_release_due'&&e.payload.class_id===h.ids.classId);const released=await h.repository.release(h.ids.studentId,h.ids.classId,{event});assert.equal(released.released,true);
  const published=await (await fetch(base+'session',{headers})).json();assert.equal(published.conversation[0].text,f.opening().interaction.portions[0].teacher_message);assert.ok(published.released_portions[0].content.board_refs[0].id);
  const receipt=h.args(published,{leaseToken:claim.leaseToken,portionId:released.portionId,renderState:'accessible_ready',active:true,representationReady:true,readyAssetIds:[]});const accepted=await (await fetch(base+'delivery-receipts',{method:'POST',headers,body:JSON.stringify(receipt)})).json();assert.equal(accepted.semantics,'APPLICATION_RENDER_ONLY');assert.equal((await h.read()).position.last_render_confirmed,1);
  const stream=await fetch(base+'stream?after=0',{headers}),reader=stream.body.getReader(),decoder=new TextDecoder();let text='';while(!text.includes('classroom_delta'))text+=decoder.decode((await reader.read()).value);assert.ok(text.includes(f.opening().interaction.portions[0].teacher_message));assert.doesNotMatch(text,/presentation_span|assistance_ceiling|leaseToken/);await reader.cancel();
 }finally{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}
}));
