'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto');
const {integrationConfig}=require('./test-db');const {skipReason:skip}=integrationConfig('Classroom response windows');
const {harness}=require('../fixtures/classroom-presentation-database'),{taskPolicy}=require('../fixtures/classroom-task-policy');
const f=require('../fixtures/classroom-remodel-academic'),tf=require('../fixtures/classroom-tasks');const {hash}=require('../../../teaching/classroom-remodel/academic-artifacts');
const run=fn=>{const policy=taskPolicy();policy.fields.taskDurations.value={short_text:10000};return harness(fn,{policy,learningUnit:true});};
async function question(h,{parts=1}={}){const r=tf.setup(h),p=tf.proposal(h.ids.learningUnit),targetRef={kind:'course_learning_unit',id:h.ids.learningUnit,version:'1',anchor:null};const designed=await r.design({studentId:h.ids.studentId,classId:h.ids.classId,operationKey:randomUUID(),proposal:p,targetRef,validation:tf.validation(p),expected:await h.repository.capture(h.ids.studentId,h.ids.classId)});const task=designed.task;
 const directive={...f.directive(),approved_action:'probe',target_competence_or_question:h.ids.learningUnit,task_ref:task.id,assistance_ceiling:'conceptual',evidence_intent:'practice',expected_student_action:'explanation',response_window:task.window};
 const output=f.opening();output.task_mode='teacher_question_or_probe';output.policy.approved_action='probe';output.policy.assistance_ceiling='conceptual';output.interaction.expects_student_response=true;output.interaction.expected_response_kind='text';Object.assign(output.interaction.portions[0],{teacher_message:task.public_question.text,task_ref:task.id,wait_requirement:'student_response',expected_student_action:'explanation'});
 if(parts===2){const final={...output.interaction.portions[0],id:'question-final',sequence:2};output.interaction.portions[0].teacher_message='Read the source condition before answering.';output.interaction.portions[0].wait_requirement='none';output.interaction.portions.push(final);}
 await h.repository.acceptSequence({studentId:h.ids.studentId,classId:h.ids.classId,operationKey:randomUUID(),expected:await h.repository.capture(h.ids.studentId,h.ids.classId),output,directive,types:['text'],classroomTaskId:task.id});return {r,task};}
async function open(h){const q=await question(h),lease=await h.repository.command(h.ids.studentId,h.ids.classId,h.args(await h.read(),{intent:'claim'})),release=await h.repository.release(h.ids.studentId,h.ids.classId);assert.equal(release.released,true);assert.equal((await h.read()).active_task,null);await h.repository.receipt(h.ids.studentId,h.ids.classId,h.args(await h.read(),{portionId:release.portionId,leaseToken:lease.leaseToken,renderState:'accessible_ready',active:true,representationReady:true,readyAssetIds:[]}));const snapshot=await h.read();const window=snapshot.active_task.window;return {...q,window,body:{schemaVersion:'classroom-tasks.v1',sessionId:h.sessionId,operationKey:randomUUID(),taskId:q.task.id,taskVersion:q.task.version,windowId:window.id,windowVersion:window.version,text:'A net force changes velocity.'}};}
test('complete task render opens an absolute window; response retry captures one admission and visible response with no charge',{skip},()=>run(async h=>{const q=await open(h);assert.equal(q.window.state,'OPEN');const first=await q.r.submit(h.ids.studentId,h.ids.classId,q.body),second=await q.r.submit(h.ids.studentId,h.ids.classId,q.body);assert.equal(second.response_id,first.response_id);assert.equal(second.replay,true);assert.equal(first.charged,false);assert.equal((await h.read()).conversation.at(-1).id,first.response_id);assert.equal((await h.query('select count(*)::int n from public.teaching_classroom_task_admissions where session_id=$1',[h.sessionId])).rows[0].n,1);assert.equal((await h.repository.release(h.ids.studentId,h.ids.classId)).released,false);assert.equal(JSON.stringify((await h.read()).active_task).includes('expected_solution'),false);}));
test('extension retries preserve the same deadline; expiry records no response without producing an incorrect evaluation',{skip},()=>run(async h=>{const q=await open(h),input={schemaVersion:q.body.schemaVersion,sessionId:h.sessionId,operationKey:randomUUID(),taskId:q.task.id,windowId:q.window.id,windowVersion:q.window.version};const first=await q.r.extend(h.ids.studentId,h.ids.classId,input),again=await q.r.extend(h.ids.studentId,h.ids.classId,input);assert.equal(again.window.deadline_at,first.window.deadline_at);await h.query("update public.teaching_classroom_task_windows set opened_at=clock_timestamp()-interval '2 seconds',deadline_at=clock_timestamp()-interval '1 second' where window_id=$1",[q.window.id]);await h.read();assert.equal((await h.query('select state from public.teaching_classroom_task_windows where window_id=$1',[q.window.id])).rows[0].state,'EXPIRED_NO_RESPONSE');assert.equal((await h.query('select count(*)::int n from public.teaching_response_evaluations where class_session_id=$1',[h.sessionId])).rows[0].n,0);await assert.rejects(()=>q.r.submit(h.ids.studentId,h.ids.classId,q.body),{code:'CLASSROOM_TASK_WINDOW_CONFLICT'});}));
test('accepted immutable work is evaluated after closure without reopening Class or publishing feedback',{skip},()=>run(async h=>{const q=await open(h),accepted=await q.r.submit(h.ids.studentId,h.ids.classId,q.body);await h.query("update public.teaching_class_sessions set lifecycle_state='CLOSED',state_version=state_version+1 where class_session_id=$1",[h.sessionId]);const claim=await q.r.claimEvaluation(h.ids.studentId,h.ids.classId,accepted.admission_id);assert.ok(claim.token);const output=tf.interpretation(q.task,accepted.response_id),adapted=require('../../../teaching/classroom-remodel/task-contracts').interpretation(output,{task:q.task,exposure:claim.exposure,responseId:accepted.response_id,demand:claim.context.design.artifacts.checks[0].task_demand,stateReference:claim.context.design.input_state_reference});const receipt={accepted:true,ownerRef:'FIXTURE_EVALUATION_OWNER',admissionId:accepted.admission_id,contextHash:hash(claim.context),outputHash:hash(adapted.evaluation),executionId:'FIXTURE_EXECUTION'};const before=(await h.read()).cursor;const result=await q.r.commitEvaluation(h.ids.studentId,h.ids.classId,claim,output,receipt);assert.equal(result.afterClosure,true);assert.equal(result.livePublication,false);assert.equal(result.officialOutcome,false);assert.equal((await h.read()).cursor,before);assert.equal((await h.query('select lifecycle_state from public.teaching_class_sessions where class_session_id=$1',[h.sessionId])).rows[0].lifecycle_state,'CLOSED');}));
test('simultaneous response submissions admit one identity and replay the same operation without double capture',{skip},async()=>{const policy=taskPolicy();policy.fields.taskDurations.value={short_text:30000};return harness(async h=>{const q=await open(h);const same=await Promise.all([q.r.submit(h.ids.studentId,h.ids.classId,q.body),q.r.submit(h.ids.studentId,h.ids.classId,q.body)]);assert.equal(same[0].response_id,same[1].response_id);assert.equal((await h.query('select count(*)::int n from public.teaching_student_responses where class_session_id=$1',[h.sessionId])).rows[0].n,1);await assert.rejects(()=>q.r.submit(h.ids.studentId,h.ids.classId,{...q.body,operationKey:randomUUID()}),{code:'CLASSROOM_TASK_WINDOW_CONFLICT'});},{policy,learningUnit:true,concurrent:true});});
test('response rollback cannot leave partial work when durable event scheduling fails',{skip},()=>run(async h=>{const q=await open(h),emit=h.repository.emitUsing;h.repository.emitUsing=async()=>{throw Error('durable scheduling fault');};await assert.rejects(()=>q.r.submit(h.ids.studentId,h.ids.classId,q.body),/durable scheduling fault/);h.repository.emitUsing=emit;assert.equal((await h.query('select count(*)::int n from public.teaching_student_responses where class_session_id=$1',[h.sessionId])).rows[0].n,0);assert.equal((await h.read()).active_task.window.state,'OPEN');assert.equal((await h.read()).conversation.filter(e=>e.role==='student').length,0);}));
test('evaluation lease fencing rejects a timed-out worker and retains adopted retry state',{skip},()=>run(async h=>{const q=await open(h),accepted=await q.r.submit(h.ids.studentId,h.ids.classId,q.body),claim=await q.r.claimEvaluation(h.ids.studentId,h.ids.classId,accepted.admission_id);await q.r.failEvaluation(h.ids.studentId,h.ids.classId,claim,'FIXTURE_PROVIDER_FAILURE');const state=(await h.query('select state,lease_token from public.teaching_classroom_task_evaluation_jobs where admission_id=$1',[accepted.admission_id])).rows[0];assert.equal(state.state,'RETRY');assert.equal(state.lease_token,null);await assert.rejects(()=>q.r.commitEvaluation(h.ids.studentId,h.ids.classId,claim,tf.interpretation(q.task,accepted.response_id),{}),{code:'CLASSROOM_TASK_EVALUATION_LEASE_STALE'});assert.equal((await h.query('select count(*)::int n from public.teaching_response_evaluations where class_session_id=$1',[h.sessionId])).rows[0].n,0);}));
test('protected takeover hides an accepted task and rejects further submissions without deleting admitted work',{skip},()=>run(async h=>{const q=await open(h),accepted=await q.r.submit(h.ids.studentId,h.ids.classId,q.body);await h.query("update public.teaching_class_sessions set instructional_substate='ASSESSMENT',state_version=state_version+1 where class_session_id=$1",[h.sessionId]);const snapshot=await h.read();assert.equal(snapshot.active_task,null);assert.equal(snapshot.capabilities.tasks,false);assert.deepEqual(snapshot.conversation,[]);await assert.rejects(()=>q.r.submit(h.ids.studentId,h.ids.classId,{...q.body,operationKey:randomUUID()}),{code:'CLASSROOM_TASK_RESPONSE_RESTRICTED'});assert.equal((await h.query('select response_id from public.teaching_classroom_task_admissions where admission_id=$1',[accepted.admission_id])).rows[0].response_id,accepted.response_id);}));
async function reviewedTurn(h,q,kind='assistance',level='attention'){
 const ready=await q.r.handlingContext(h.ids.studentId,h.ids.classId,{taskId:q.task.id});const output=f.opening();output.interaction.portions[0].task_ref=q.task.id;output.interaction.portions[0].teacher_message=kind==='feedback'?'You identified acceleration. This response does not establish mastery.':'Focus on how velocity changes, including direction.';output.policy.assistance_ceiling='conceptual';output.policy.approved_action=kind==='feedback'?'acknowledge':'hint';
 const directive={...f.directive(),task_ref:q.task.id,assistance_ceiling:'conceptual',current_assistance_state:level,approved_action:output.policy.approved_action,response_window:ready.task.window,evidence_intent:'instruction_only'};
 if(kind==='feedback')directive.accepted_evaluation={receipt_id:hash(ready.job.acceptance_receipt),task_ref:q.task.id,criterion_ref:'criterion:'+q.task.private.criterion_ref.id+'@1',source_version:'1',assistance_version:'fixture-exposure',state_reference:'fixture@1',accepted:true};
 const receipt={accepted:true,independent:true,ownerRef:'FIXTURE_TURN_REVIEW',executionId:'FIXTURE_TURN_EXECUTION',contentHash:hash({output,directive}),taskId:q.task.id,taskVersion:q.task.version,authorityHash:hash(ready.expected.authority),evaluationId:ready.job?.evaluation_id};
 await q.r.acceptTurn({studentId:h.ids.studentId,classId:h.ids.classId,taskId:q.task.id,operationKey:randomUUID(),kind,output,directive,assistanceLevel:level,receipt,expected:ready.expected});
 await h.repository.acceptSequence({studentId:h.ids.studentId,classId:h.ids.classId,operationKey:randomUUID(),output,directive,expected:await h.repository.capture(h.ids.studentId,h.ids.classId),types:['text'],classroomTaskId:q.task.id});
 return {output,directive};
}
async function confirmNext(h){const release=await h.repository.release(h.ids.studentId,h.ids.classId);assert.equal(release.released,true);const d=(await h.query('select * from public.teaching_classroom_delivery where session_id=$1',[h.sessionId])).rows[0];const lease=await h.repository.command(h.ids.studentId,h.ids.classId,h.args(await h.read(),{intent:'takeover'}));await h.repository.receipt(h.ids.studentId,h.ids.classId,h.args(await h.read(),{portionId:release.portionId,leaseToken:lease.leaseToken,renderState:'accessible_ready',active:true,representationReady:true,readyAssetIds:[]}));return d;}
test('task help is free and preserves the deadline; exposure separates released and accessible assistance',{skip},()=>run(async h=>{const q=await open(h),body={...q.body,operationKey:randomUUID(),kind:'help',text:'Help with this question'};const accepted=await q.r.support(h.ids.studentId,h.ids.classId,body),replay=await q.r.support(h.ids.studentId,h.ids.classId,body);assert.equal(accepted.charged,false);assert.equal(replay.request_id,accepted.request_id);await reviewedTurn(h,q);assert.equal((await h.read()).active_task.window.deadline_at,q.window.deadline_at);await confirmNext(h);assert.equal((await h.read()).active_task.window.deadline_at,q.window.deadline_at);const receipt=await q.r.submit(h.ids.studentId,h.ids.classId,q.body);const claim=await q.r.claimEvaluation(h.ids.studentId,h.ids.classId,receipt.admission_id);assert.equal(claim.exposure.released_assistance_level,'attention');assert.equal(claim.exposure.events.some(e=>e.stage==='released'),true);assert.equal(claim.exposure.events.some(e=>e.stage==='accessible'),true);}));
test('accepted interpretation has one bounded action and reviewed feedback completes handling only after render',{skip},()=>run(async h=>{const q=await open(h),accepted=await q.r.submit(h.ids.studentId,h.ids.classId,q.body),claim=await q.r.claimEvaluation(h.ids.studentId,h.ids.classId,accepted.admission_id),output=tf.interpretation(q.task,accepted.response_id),adapted=require('../../../teaching/classroom-remodel/task-contracts').interpretation(output,{task:q.task,exposure:claim.exposure,responseId:accepted.response_id,demand:claim.context.design.artifacts.checks[0].task_demand,stateReference:claim.context.design.input_state_reference});await q.r.commitEvaluation(h.ids.studentId,h.ids.classId,claim,output,{accepted:true,ownerRef:'FIXTURE_EVAL_OWNER',admissionId:accepted.admission_id,contextHash:hash(claim.context),outputHash:hash(adapted.evaluation),executionId:'FIXTURE_EVAL'});await reviewedTurn(h,q,'feedback','none');assert.equal((await h.read()).active_task.window.state,'RESPONSE_ACCEPTED');await confirmNext(h);assert.equal((await h.read()).active_task,null);const turn=(await h.query("select * from public.teaching_classroom_task_turns where session_id=$1 and kind='feedback'",[h.sessionId])).rows[0];assert.equal(turn.state,'CONFIRMED');assert.equal(typeof turn.selected_action.action,'string');assert.equal(turn.selected_action.officialOutcome,false);}));
test('unreviewed help and help exceeding the ceiling cannot create a publishable turn',{skip},()=>run(async h=>{const q=await open(h),ready=await q.r.handlingContext(h.ids.studentId,h.ids.classId,{taskId:q.task.id});await assert.rejects(()=>q.r.acceptTurn({studentId:h.ids.studentId,classId:h.ids.classId,taskId:q.task.id,operationKey:randomUUID(),kind:'assistance',output:f.opening(),directive:f.directive(),receipt:{accepted:false},expected:ready.expected}),{code:'CLASSROOM_TASK_TURN_REVIEW_REQUIRED'});await assert.rejects(()=>reviewedTurn(h,q,'assistance','worked_example'),/ceiling/i);assert.equal((await h.query('select count(*)::int n from public.teaching_classroom_task_turns where session_id=$1',[h.sessionId])).rows[0].n,0);}));
function revisions(h){const d12=require('../../../teaching/repositories/d12-response-pedagogy').createD12ResponsePedagogyRepository({query:h.query,withTransaction:h.withTransaction,randomUUID,d11Repository:h.d11Repository});const r=require('../../../teaching/repositories/classroom-revisions').createClassroomRevisionRepository({presentationRepository:h.repository,d11Repository:h.d11Repository,d12Repository:d12,randomUUID});h.repository.connectRevisions(r);return r;}
test('explicit correction retains original/successor history, invalidates prepared output and requests evidence-owner recheck',{skip},()=>run(async h=>{
 const q=await open(h),r=revisions(h),original=(await h.query("select portion_id from public.teaching_classroom_portions where session_id=$1 and status='CONFIRMED'",[h.sessionId])).rows[0];const output=f.opening();output.task_mode='teacher_self_correction';output.policy.approved_action='correct teacher';output.interaction.portions[0].teacher_message='Correction: net force changes velocity; motion itself does not require a continuing net force.';output.interaction.portions[0].correction_of={kind:'portion',id:original.portion_id,version:'1',anchor:null};output.teacher_correction={result:'teacher_error_confirmed',board_repair_needed:false,requires_chapter_revision:false};const directive={...f.directive(),approved_action:'correct teacher'},expected=await h.repository.capture(h.ids.studentId,h.ids.classId);const challenge=require('../fixtures/classroom-messages').setup(h);const message=await challenge.repository.admit(h.ids.studentId,h.ids.classId,challenge.body('This teaching claim may be wrong',{intent:'correction_report'}));const receipt={accepted:true,independent:true,messageId:message.message_id,ownerRef:'FIXTURE_SOURCE_OWNER',executionId:'FIXTURE_CORRECTION',contentHash:hash({originalPortionId:original.portion_id,output,directive}),authorityHash:hash(expected.authority)};const corrected=await r.correction({studentId:h.ids.studentId,classId:h.ids.classId,operationKey:randomUUID(),originalPortionId:original.portion_id,output,directive,receipt,expected});await h.repository.acceptSequence({studentId:h.ids.studentId,classId:h.ids.classId,operationKey:randomUUID(),output,directive,expected:await h.repository.capture(h.ids.studentId,h.ids.classId),types:['text'],classroomRevisionId:corrected.revisionId});await confirmNext(h);const event=(await h.read()).conversation.at(-1);assert.equal(event.type,'correction');assert.ok(event.source_refs.some(ref=>ref.kind==='portion'&&ref.id===original.portion_id));assert.equal((await h.query('select count(*)::int n from public.teaching_evidence_recheck_handoffs where class_session_id=$1',[h.sessionId])).rows[0].n,1);assert.equal((await h.read()).active_task.window.deadline_at,q.window.deadline_at);const handled=(await h.query('select state,release_hold from public.teaching_classroom_message_queue where message_id=$1',[message.message_id])).rows[0];assert.equal(handled.state,'answered');assert.equal(handled.release_hold,false);
}));
test('TPF-05 remainder is applied through D11 atomically without resetting accepted work, chapter or response deadline',{skip},()=>run(async h=>{
 const q=await open(h),r=revisions(h),state=await r.context(h.ids.studentId,h.ids.classId),plan=f.plan();plan.id='remaining-plan';plan.version='2';plan.objectives[0].ref.id=h.ids.learningUnit;const chapter=f.chapter();chapter.units[0].objective_refs[0].id=h.ids.learningUnit;const artifact=await h.academic.saveCandidate({...h.ids,expectedScheduleVersion:1,expectedPlanVersion:1,kind:'plan',operationKey:randomUUID(),logicalId:plan.id,logicalVersion:plan.version,payload:plan,producer:f.producer('plan'),context:{chapter},dependencies:[]});await h.academic.recordValidation({studentId:h.ids.studentId,artifactId:artifact.artifact_version_id,receipt:{accepted:true,independent:true,routeQualified:true,reviewId:'FIXTURE_REPLAN_PLAN',contentHash:artifact.content_sha256}});
 const blueprint={status:'OK',objectives:[{id:'remaining-objective',learning_unit_ref:h.ids.learningUnit,label:'Explain the relationship',criticality:'CORE'}],segments:[{id:'remaining-segment',objective_refs:['remaining-objective'],planned_minutes:10,minimum_safe_minutes:5,criticality:'CORE'}],adaptive_reserve_minutes:7,prerequisite_checks:[],likely_misconceptions:[],examples:[],guided_work:[],independent_evidence_opportunities:[],remediation_branches:[],homework_candidates:[]};const author={task_mode:'live_lesson_replan',input_state_reference:'fixture@1',status:'ok',review_required:false,review_reasons:[],completion:{teaching_plan:'complete',closure_or_replan:'complete',controller_blueprint:'complete'},provenance:{},artifacts:{teaching_plan:plan,controller_blueprint:blueprint,closure_or_replan:{preserved_work:state.work.confirmed,carry_forward:state.work.unresolved,current_position:state.position}},handoff:[]};const receipt={accepted:true,independent:true,ownerRef:'FIXTURE_D11_OWNER',executionId:'FIXTURE_TPF05',contentHash:hash({author,planArtifactId:artifact.artifact_version_id,work:state.work}),authorityHash:hash(state.expected.authority),reservePolicyAdoptionRef:'FIXTURE_D11_RESERVE'};const result=await r.replan({studentId:h.ids.studentId,classId:h.ids.classId,operationKey:randomUUID(),author,planArtifactId:artifact.artifact_version_id,receipt,expected:state.expected,work:state.work,reservePolicy:require('../../../teaching/d11/contracts').DEFAULT_ADAPTIVE_RESERVE_POLICY});assert.equal(result.completedWorkPreserved,true);const snapshot=await h.read();assert.equal(snapshot.chapter_ref.id,'chapter1');assert.equal(snapshot.active_task.window.deadline_at,q.window.deadline_at);assert.ok(snapshot.delivery_epoch>state.expected.deliveryEpoch);assert.equal((await h.query("select count(*)::int n from public.teaching_classroom_portions where session_id=$1 and status='CONFIRMED'",[h.sessionId])).rows[0].n,state.work.confirmed.length);assert.equal((await h.repository.capture(h.ids.studentId,h.ids.classId)).held,undefined);
}));
test('task responses, support and extensions remain available after conversational allowance exhaustion',{skip},()=>run(async h=>{
 const q=await open(h),messages=require('../fixtures/classroom-messages').setup(h);await messages.repository.admit(h.ids.studentId,h.ids.classId,messages.body('First question'));await messages.repository.admit(h.ids.studentId,h.ids.classId,messages.body('Second question'));await assert.rejects(()=>messages.repository.admit(h.ids.studentId,h.ids.classId,messages.body('Beyond quota')),{code:'CLASSROOM_MESSAGE_ALLOWANCE_EXHAUSTED'});
 const support=await q.r.support(h.ids.studentId,h.ids.classId,{...q.body,operationKey:randomUUID(),kind:'clarification',text:'Please clarify the requested response'});assert.equal(support.charged,false);const extension=await q.r.extend(h.ids.studentId,h.ids.classId,{schemaVersion:q.body.schemaVersion,sessionId:h.sessionId,operationKey:randomUUID(),taskId:q.task.id,windowId:q.window.id,windowVersion:q.window.version});assert.equal(extension.charged,false);assert.equal((await q.r.submit(h.ids.studentId,h.ids.classId,{...q.body,windowVersion:extension.window.version})).charged,false);assert.equal((await h.query('select count(*)::int n from public.teaching_classroom_allowance_charges where session_id=$1',[h.sessionId])).rows[0].n,2);
}));
test('unresolved source conflict holds delivery; explicit accepted successor resolves the hold without erasing history',{skip},()=>run(async h=>{
 const q=await open(h),r=revisions(h),original=(await h.query("select portion_id from public.teaching_classroom_portions where session_id=$1 and status='CONFIRMED'",[h.sessionId])).rows[0].portion_id;
 async function correct(result){const output=f.opening();output.task_mode='teacher_self_correction';output.policy.approved_action='correct teacher';output.interaction.portions[0].correction_of={kind:'portion',id:original,version:'1',anchor:null};output.teacher_correction={result,board_repair_needed:false,requires_chapter_revision:false};const directive={...f.directive(),approved_action:'correct teacher'},expected=await h.repository.capture(h.ids.studentId,h.ids.classId);return {output,directive,result:await r.correction({studentId:h.ids.studentId,classId:h.ids.classId,operationKey:randomUUID(),originalPortionId:original,output,directive,expected,receipt:{accepted:true,independent:true,ownerRef:'FIXTURE_SOURCE_OWNER',executionId:randomUUID(),contentHash:hash({originalPortionId:original,output,directive}),authorityHash:hash(expected.authority)}})};}
 await correct('unresolved');assert.equal((await h.repository.release(h.ids.studentId,h.ids.classId)).released,false);const fixed=await correct('teacher_error_confirmed');await h.repository.acceptSequence({studentId:h.ids.studentId,classId:h.ids.classId,operationKey:randomUUID(),output:fixed.output,directive:fixed.directive,expected:await h.repository.capture(h.ids.studentId,h.ids.classId),types:['text'],classroomRevisionId:fixed.result.revisionId});await confirmNext(h);const states=(await h.query('select state from public.teaching_classroom_revisions where session_id=$1 order by created_at',[h.sessionId])).rows.map(r=>r.state);assert.deepEqual(states.sort(),['CONFIRMED','SUPERSEDED']);assert.equal((await h.read()).active_task.window.deadline_at,q.window.deadline_at);
}));
test('an accepted academic-source correction holds future delivery for the chapter owner rather than publishing unvalidated prose',{skip},()=>run(async h=>{
 await open(h);const r=revisions(h),original=(await h.query("select portion_id from public.teaching_classroom_portions where session_id=$1 and status='CONFIRMED'",[h.sessionId])).rows[0].portion_id,output=f.opening(),directive={...f.directive(),approved_action:'correct teacher'},expected=await h.repository.capture(h.ids.studentId,h.ids.classId);output.teacher_correction={result:'teacher_error_confirmed',requires_chapter_revision:true};const result=await r.correction({studentId:h.ids.studentId,classId:h.ids.classId,operationKey:randomUUID(),originalPortionId:original,output,directive,expected,receipt:{accepted:true,independent:true,ownerRef:'FIXTURE_SOURCE_OWNER',executionId:randomUUID(),contentHash:hash({originalPortionId:original,output,directive}),authorityHash:hash(expected.authority)}});assert.equal(result.held,true);assert.equal((await h.repository.release(h.ids.studentId,h.ids.classId)).released,false);assert.equal((await h.read()).chapter_ref.version,'1');assert.equal((await h.query('select state from public.teaching_classroom_revisions where revision_id=$1',[result.revisionId])).rows[0].state,'HELD');
}));
test('a multipart question cannot open its response clock on a partial render receipt',{skip},()=>run(async h=>{
 const q=await question(h,{parts:2}),lease=await h.repository.command(h.ids.studentId,h.ids.classId,h.args(await h.read(),{intent:'claim'}));async function deliver(){const released=await h.repository.release(h.ids.studentId,h.ids.classId);assert.equal(released.released,true);await h.repository.receipt(h.ids.studentId,h.ids.classId,h.args(await h.read(),{portionId:released.portionId,leaseToken:lease.leaseToken,renderState:'accessible_ready',active:true,representationReady:true,readyAssetIds:[]}));}
 await deliver();assert.equal((await h.read()).active_task,null);assert.equal((await h.query('select state from public.teaching_classroom_task_windows where task_id=$1',[q.task.id])).rows[0].state,'PENDING_DELIVERY');await h.query('update public.teaching_classroom_delivery set next_release_at=clock_timestamp() where session_id=$1',[h.sessionId]);await deliver();assert.equal((await h.read()).active_task.window.state,'OPEN');
}));
test('Board correction adds a linked successor while retaining the original owned Board object',{skip},()=>run(async h=>{
 await open(h);const r=revisions(h),original=(await h.query("select portion_id,board_item_ids from public.teaching_classroom_portions where session_id=$1 and status='CONFIRMED'",[h.sessionId])).rows[0],oldBoard=original.board_item_ids[0],output=f.opening();output.task_mode='teacher_self_correction';output.policy.approved_action='correct teacher';output.interaction.portions[0].correction_of={kind:'portion',id:original.portion_id,version:'1',anchor:null};output.interaction.portions[0].board_refs=['repair'];output.board=[{id:'repair',operation:'add',type:'text',content:{text:'Correction: net force changes velocity.'},target_ref:{kind:'board',id:oldBoard,version:'1',anchor:null},depends_on:[]}];output.teacher_correction={result:'teacher_error_confirmed',board_repair_needed:true,requires_chapter_revision:false};const directive={...f.directive(),approved_action:'correct teacher'},expected=await h.repository.capture(h.ids.studentId,h.ids.classId),receipt={accepted:true,independent:true,ownerRef:'FIXTURE_BOARD_SOURCE_OWNER',executionId:randomUUID(),contentHash:hash({originalPortionId:original.portion_id,output,directive}),authorityHash:hash(expected.authority)};const accepted=await r.correction({studentId:h.ids.studentId,classId:h.ids.classId,operationKey:randomUUID(),originalPortionId:original.portion_id,output,directive,receipt,expected});await h.repository.acceptSequence({studentId:h.ids.studentId,classId:h.ids.classId,operationKey:randomUUID(),output,directive,expected:await h.repository.capture(h.ids.studentId,h.ids.classId),types:['text'],classroomRevisionId:accepted.revisionId});await confirmNext(h);const snapshot=await h.read();assert.ok(snapshot.conversation.at(-1).source_refs.some(ref=>ref.kind==='board'&&ref.id===oldBoard));const newBoard=snapshot.released_portions.at(-1).content.board_refs[0].id;assert.notEqual(newBoard,oldBoard);assert.equal((await h.query('select count(*)::int n from public.teaching_board_items where board_item_id=any($1::text[])',[[oldBoard,newBoard]])).rows[0].n,2);
}));
