'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {PRODUCTION_PROJECT_REF,assertNonProductionDatabase,integrationConfig,createIntegrationPool}=require('./test-db');
const {connectionString:url,projectRef:ref,skipReason:skip}=integrationConfig('D17');
const tables=['teaching_assessments','teaching_assessment_blueprints','teaching_assessment_eligibility_entries','teaching_assessment_candidates','teaching_assessment_candidate_versions','teaching_assessment_validations','teaching_assessment_packages','teaching_assessment_package_items','teaching_assessment_attempts','teaching_assessment_attempt_events','teaching_assessment_responses','teaching_assessment_item_challenges','teaching_assessment_invalidations','teaching_assessment_contamination_events','teaching_assessment_ppl_workspaces'];

test('D17 integration guard refuses production',()=>{assert.throws(()=>assertNonProductionDatabase({connectionString:'postgresql://x@localhost/x',projectRef:PRODUCTION_PROJECT_REF}),/production/);});

test('D17 schema exists and RLS is enabled',{skip},async()=>{assertNonProductionDatabase({connectionString:url,projectRef:ref});const pool=createIntegrationPool(url);try{const {rows}=await pool.query("select c.relname,c.relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname=any($1::text[]) and c.relkind='r'",[tables]);assert.equal(rows.length,tables.length);for(const row of rows)assert.equal(row.relrowsecurity,true,row.relname);}finally{await pool.end();}});

test('D17 browser roles have no direct table grants',{skip},async()=>{const pool=createIntegrationPool(url);try{const {rows}=await pool.query("select table_name,grantee,privilege_type from information_schema.role_table_grants where table_schema='public' and table_name=any($1::text[]) and grantee in ('anon','authenticated')",[tables]);assert.deepEqual(rows,[]);}finally{await pool.end();}});

test('D17 protected and evidence tables are append-only for service_role',{skip},async()=>{const appendOnly=['teaching_assessment_blueprints','teaching_assessment_eligibility_entries','teaching_assessment_candidate_versions','teaching_assessment_validations','teaching_assessment_attempt_events','teaching_assessment_responses','teaching_assessment_invalidations'];const pool=createIntegrationPool(url);try{const {rows}=await pool.query("select table_name,privilege_type from information_schema.role_table_grants where table_schema='public' and table_name=any($1::text[]) and grantee='service_role' and privilege_type in ('UPDATE','DELETE','TRUNCATE')",[appendOnly]);assert.deepEqual(rows,[]);}finally{await pool.end();}});

test('D17 contamination evidence has narrow governed resolution instead of general mutability',{skip},async()=>{const pool=createIntegrationPool(url);try{const columns=await pool.query("select column_name from information_schema.columns where table_schema='public' and table_name='teaching_assessment_contamination_events' and column_name in ('resolved_at','resolution_ref') order by column_name");assert.deepEqual(columns.rows.map(r=>r.column_name),['resolution_ref','resolved_at']);const trigger=await pool.query("select tgname from pg_trigger where tgrelid='public.teaching_assessment_contamination_events'::regclass and not tgisinternal and tgname='teaching_d17_contamination_resolution_guard'");assert.equal(trigger.rows.length,1);const grants=await pool.query("select privilege_type from information_schema.role_table_grants where table_schema='public' and table_name='teaching_assessment_contamination_events' and grantee='service_role' order by privilege_type");assert.deepEqual(grants.rows.map(r=>r.privilege_type),['INSERT','SELECT','UPDATE']);}finally{await pool.end();}});

test('D17 one-active-attempt and idempotency indexes are installed',{skip},async()=>{const pool=createIntegrationPool(url);try{const {rows}=await pool.query("select indexname,indexdef from pg_indexes where schemaname='public' and indexname in ('teaching_assessment_attempts_one_active_uidx','teaching_assessment_responses_idempotency_uidx','teaching_assessment_eligibility_snapshot_uidx','teaching_assessment_packages_locked_hash_uidx')");assert.equal(rows.length,4);assert.match(rows.find(r=>r.indexname==='teaching_assessment_attempts_one_active_uidx').indexdef,/WHERE \(attempt_state = 'ACTIVE'/i);}finally{await pool.end();}});

test('D17 shared Integrity Session Guard accepts formal Assessment Attempt owner',{skip},async()=>{const pool=createIntegrationPool(url);try{const {rows}=await pool.query("select pg_get_constraintdef(oid) definition from pg_constraint where conrelid='public.kiwi_integrity_sessions'::regclass and conname='kiwi_integrity_sessions_owner_type_check'");assert.equal(rows.length,1);assert.match(rows[0].definition,/TEACHING_ASSESSMENT_ATTEMPT/);}finally{await pool.end();}});

test('D17 database enforces independent validation and no-system-defect student penalty',{skip},async()=>{const pool=createIntegrationPool(url);try{const {rows}=await pool.query("select conname,pg_get_constraintdef(oid) definition from pg_constraint where conname in ('teaching_assessment_validations_independent_check','teaching_assessment_invalidations_no_penalty_check') order by conname");assert.equal(rows.length,2);assert.match(rows.map(r=>r.definition).join(' '),/independent_from_generation = true/i);assert.match(rows.map(r=>r.definition).join(' '),/student_penalty_allowed = false/i);}finally{await pool.end();}});
