'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {PRODUCTION_PROJECT_REF,assertNonProductionDatabase,integrationConfig,createIntegrationPool}=require('./test-db');
const {connectionString:url,projectRef:ref,skipReason:skip}=integrationConfig('D17');
const tables=['teaching_assessments','teaching_assessment_blueprints','teaching_assessment_eligibility_entries','teaching_assessment_candidates','teaching_assessment_candidate_versions','teaching_assessment_validations','teaching_assessment_packages','teaching_assessment_package_items','teaching_assessment_attempts','teaching_assessment_attempt_events','teaching_assessment_responses','teaching_assessment_item_challenges','teaching_assessment_invalidations','teaching_assessment_contamination_events','teaching_assessment_ppl_workspaces'];

test('D17 integration guard refuses production',()=>{assert.throws(()=>assertNonProductionDatabase({connectionString:'postgresql://x@localhost/x',projectRef:PRODUCTION_PROJECT_REF}),/production/);});

test('D17 schema exists and RLS is enabled',{skip},async()=>{assertNonProductionDatabase({connectionString:url,projectRef:ref});const pool=createIntegrationPool(url);try{const {rows}=await pool.query("select c.relname,c.relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname=any($1::text[]) and c.relkind='r'",[tables]);assert.equal(rows.length,tables.length);for(const row of rows)assert.equal(row.relrowsecurity,true,row.relname);}finally{await pool.end();}});

test('D17 browser roles have no direct table grants',{skip},async()=>{const pool=createIntegrationPool(url);try{const {rows}=await pool.query("select table_name,grantee,privilege_type from information_schema.role_table_grants where table_schema='public' and table_name=any($1::text[]) and grantee in ('anon','authenticated')",[tables]);assert.deepEqual(rows,[]);}finally{await pool.end();}});

test('D17 protected and evidence tables are append-only for service_role',{skip},async()=>{const appendOnly=['teaching_assessment_blueprints','teaching_assessment_eligibility_entries','teaching_assessment_candidate_versions','teaching_assessment_validations','teaching_assessment_attempt_events','teaching_assessment_responses','teaching_assessment_invalidations'];const pool=createIntegrationPool(url);try{const {rows}=await pool.query("select table_name,privilege_type from information_schema.role_table_grants where table_schema='public' and table_name=any($1::text[]) and grantee='service_role' and privilege_type in ('UPDATE','DELETE','TRUNCATE')",[appendOnly]);assert.deepEqual(rows,[]);}finally{await pool.end();}});

test('D17 contamination evidence has narrow governed resolution instead of general mutability',{skip},async()=>{const pool=createIntegrationPool(url);try{const columns=await pool.query("select column_name from information_schema.columns where table_schema='public' and table_name='teaching_assessment_contamination_events' and column_name in ('resolved_at','resolution_ref') order by column_name");assert.deepEqual(columns.rows.map(r=>r.column_name),['resolution_ref','resolved_at']);const trigger=await pool.query("select tgname from pg_trigger where tgrelid='public.teaching_assessment_contamination_events'::regclass and not tgisinternal and tgname='teaching_d17_contamination_resolution_guard'");assert.equal(trigger.rows.length,1);const grants=await pool.query("select privilege_type from information_schema.role_table_grants where table_schema='public' and table_name='teaching_assessment_contamination_events' and grantee='service_role' order by privilege_type");assert.deepEqual(grants.rows.map(r=>r.privilege_type),['INSERT','SELECT','UPDATE']);}finally{await pool.end();}});

test('D17 one-active-attempt and idempotency indexes are installed',{skip},async()=>{const pool=createIntegrationPool(url);try{const {rows}=await pool.query("select indexname,indexdef from pg_indexes where schemaname='public' and indexname in ('teaching_assessment_attempts_one_active_uidx','teaching_assessment_responses_idempotency_uidx','teaching_assessment_eligibility_snapshot_uidx','teaching_assessment_packages_locked_hash_uidx')");assert.equal(rows.length,4);assert.match(rows.find(r=>r.indexname==='teaching_assessment_attempts_one_active_uidx').indexdef,/WHERE \(attempt_state = 'ACTIVE'/i);}finally{await pool.end();}});

test('D17 shared Integrity Session Guard accepts formal Assessment Attempt owner',{skip},async()=>{const pool=createIntegrationPool(url);try{const {rows}=await pool.query("select pg_get_constraintdef(oid) definition from pg_constraint where conrelid='public.kiwi_integrity_sessions'::regclass and conname='kiwi_integrity_sessions_owner_type_check'");assert.equal(rows.length,1);assert.match(rows[0].definition,/TEACHING_ASSESSMENT_ATTEMPT/);}finally{await pool.end();}});

test('D17 database enforces independent validation and no-system-defect student penalty',{skip},async()=>{const pool=createIntegrationPool(url);try{const {rows}=await pool.query("select conname,pg_get_constraintdef(oid) definition from pg_constraint where conname in ('teaching_assessment_validations_independent_check','teaching_assessment_invalidations_no_penalty_check') order by conname");assert.equal(rows.length,2);assert.match(rows.map(r=>r.definition).join(' '),/independent_from_generation = true/i);assert.match(rows.map(r=>r.definition).join(' '),/student_penalty_allowed = false/i);}finally{await pool.end();}});

test('D17 canonical state guards replace provisional Integration vocabularies',{skip},async()=>{const pool=createIntegrationPool(url);try{const names=['teaching_assessments_definition_state_check','teaching_assessment_blueprints_maturity_check','teaching_assessment_blueprints_timer_model_check','teaching_assessment_eligibility_entries_basis_check','teaching_assessment_candidates_candidate_state_check','teaching_assessment_validations_outcome_check','teaching_assessment_packages_package_state_check','teaching_assessment_packages_locked_complete_check','teaching_assessment_attempts_attempt_state_check','teaching_assessment_attempts_result_state_check','teaching_assessment_package_items_item_state_check'];const {rows}=await pool.query("select conname,pg_get_constraintdef(oid) definition from pg_constraint where conname=any($1::text[]) order by conname",[names]);assert.equal(rows.length,names.length);const defs=Object.fromEntries(rows.map(r=>[r.conname,r.definition]));assert.match(defs.teaching_assessments_definition_state_check,/PLANNED/);assert.match(defs.teaching_assessment_blueprints_maturity_check,/PRE_LOCK_READY/);assert.match(defs.teaching_assessment_blueprints_timer_model_check,/PER_QUESTION_EXPLICIT_SKILL/);assert.match(defs.teaching_assessment_eligibility_entries_basis_check,/EXPLICIT_ASSUMED_PREREQUISITE/);assert.match(defs.teaching_assessment_candidates_candidate_state_check,/VALIDATION_PENDING/);assert.match(defs.teaching_assessment_candidates_candidate_state_check,/VALIDATED/);assert.match(defs.teaching_assessment_validations_outcome_check,/REVIEW_REQUIRED/);assert.match(defs.teaching_assessment_packages_package_state_check,/ASSEMBLING/);assert.match(defs.teaching_assessment_packages_locked_complete_check,/locked_at IS NOT NULL/i);assert.match(defs.teaching_assessment_attempts_attempt_state_check,/SUBMITTED/);assert.match(defs.teaching_assessment_attempts_attempt_state_check,/EXPIRED/);assert.match(defs.teaching_assessment_attempts_result_state_check,/AWAITING_MARKING/);assert.match(defs.teaching_assessment_package_items_item_state_check,/RETIRED_AS_CLEAN_EVIDENCE/);const legacy=await pool.query("select conname from pg_constraint where conname in ('teaching_assessment_eligibility_entries_eligibility_basis_check','teaching_assessment_contamination_events_action_check','teaching_assessments_assessment_type_check','teaching_assessments_check','teaching_assessment_packages_check') order by conname");assert.deepEqual(legacy.rows,[]);}finally{await pool.end();}});

test('D17 canonical package freeze guard replaces abandoned prototype guards',{skip},async()=>{const pool=createIntegrationPool(url);try{const legacyTriggers=await pool.query("select tgname from pg_trigger where not tgisinternal and tgname in ('teaching_d17_locked_package_update_guard','teaching_d17_package_item_insert_guard','teaching_d17_package_item_update_guard','teaching_d17_package_item_delete_guard') order by tgname");assert.deepEqual(legacyTriggers.rows,[]);const legacyFunctions=await pool.query("select p.proname from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('teaching_d17_guard_locked_package_update','teaching_d17_guard_package_item_mutation') order by p.proname");assert.deepEqual(legacyFunctions.rows,[]);const trigger=await pool.query("select pg_get_triggerdef(t.oid,true) definition,p.proconfig from pg_trigger t join pg_proc p on p.oid=t.tgfoid where t.tgrelid='public.teaching_assessment_package_items'::regclass and t.tgname='teaching_d17_locked_package_item_guard' and not t.tgisinternal");assert.equal(trigger.rows.length,1);assert.match(trigger.rows[0].definition,/INSERT/);assert.match(trigger.rows[0].definition,/UPDATE/);assert.match(trigger.rows[0].definition,/DELETE/);assert.ok((trigger.rows[0].proconfig||[]).some(v=>String(v).replace(/\s/g,'')==='search_path=pg_catalog,public'));const funcs=await pool.query("select p.proname,p.proconfig from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('teaching_d17_guard_locked_package','teaching_d17_guard_locked_package_item','teaching_d17_guard_contamination_resolution','teaching_d17_reject_append_only_mutation') order by p.proname");assert.equal(funcs.rows.length,4);for(const row of funcs.rows)assert.ok((row.proconfig||[]).some(v=>String(v).replace(/\s/g,'')==='search_path=pg_catalog,public'),row.proname);}finally{await pool.end();}});


test('D17 canonical foreign keys are complete and preserve delete semantics',{skip},async()=>{const pool=createIntegrationPool(url);try{const {rows}=await pool.query("select c.confdeltype,count(*)::int n from pg_constraint c join pg_class t on t.oid=c.conrelid where t.relnamespace='public'::regnamespace and t.relname=any($1::text[]) and c.contype='f' group by c.confdeltype order by c.confdeltype",[tables]);assert.deepEqual(rows,[{confdeltype:'a',n:3},{confdeltype:'c',n:37},{confdeltype:'n',n:1},{confdeltype:'r',n:7}]);const critical=await pool.query("select c.conname,pg_get_constraintdef(c.oid) definition from pg_constraint c where c.conname in ('d17_eligibility_learning_unit_fk','d17_eligibility_course_plan_fk','d17_eligibility_coverage_fk','d17_packages_blueprint_fk','d17_package_items_candidate_version_fk','d17_attempts_package_fk','d17_responses_package_item_fk','d17_item_challenges_package_item_fk') order by c.conname");assert.equal(critical.rows.length,8);const joined=critical.rows.map(r=>r.definition).join(' ');assert.match(joined,/ON DELETE SET NULL/);assert.match(joined,/ON DELETE RESTRICT/);}finally{await pool.end();}});

test('D17 schema has no exact duplicate indexes or provisional unique constraints',{skip},async()=>{const pool=createIntegrationPool(url);try{const dup=await pool.query("select t.relname table_name,i.indisunique,i.indkey::text indkey,coalesce(pg_get_expr(i.indpred,i.indrelid),'') predicate,count(*)::int n from pg_index i join pg_class x on x.oid=i.indexrelid join pg_class t on t.oid=i.indrelid where t.relname=any($1::text[]) and i.indisvalid and i.indisready group by t.relname,i.indisunique,i.indkey::text,coalesce(pg_get_expr(i.indpred,i.indrelid),'') having count(*)>1 order by t.relname",[tables]);assert.deepEqual(dup.rows,[]);const provisional=await pool.query("select c.conname from pg_constraint c join pg_class t on t.oid=c.conrelid where t.relnamespace='public'::regnamespace and t.relname=any($1::text[]) and c.conname in ('teaching_assessment_package_i_assessment_package_id_slot_id_key','teaching_assessments_student_id_assessment_id_key') order by c.conname",[tables]);assert.deepEqual(provisional.rows,[]);}finally{await pool.end();}});

test('D17 every foreign key has a leading covering index',{skip},async()=>{const pool=createIntegrationPool(url);try{const {rows}=await pool.query("with d17_tables as (select oid,relname from pg_class where relnamespace='public'::regnamespace and relkind='r' and relname=any($1::text[])), fks as (select c.conname,c.conrelid,c.conkey,t.relname table_name from pg_constraint c join d17_tables t on t.oid=c.conrelid where c.contype='f') select table_name,conname from fks f where not exists(select 1 from pg_index i where i.indrelid=f.conrelid and i.indisvalid and i.indisready and (i.indkey::smallint[])[0:cardinality(f.conkey)-1]=f.conkey) order by table_name,conname",[tables]);assert.deepEqual(rows,[]);}finally{await pool.end();}});
