'use strict';

const test=require('node:test');
const assert=require('node:assert/strict');
const {PRODUCTION_PROJECT_REF,assertNonProductionDatabase,integrationConfig,createIntegrationPool}=require('./test-db');
const {connectionString:url,projectRef:ref,skipReason:skip}=integrationConfig('D20');

const tables=[
  'teaching_grading_policies','teaching_assessment_results','teaching_marking_runs',
  'teaching_marking_criterion_judgments','teaching_grade_appeals','teaching_gradebook_entries',
  'teaching_topic_score_snapshots','teaching_course_result_snapshots','teaching_grade_change_audit',
];

test('D20 integration guard refuses production',()=>{assert.throws(()=>assertNonProductionDatabase({connectionString:'postgresql://x@localhost/x',projectRef:PRODUCTION_PROJECT_REF}),/production/);});

test('D20 authoritative tables exist with RLS enabled',{skip},async()=>{assertNonProductionDatabase({connectionString:url,projectRef:ref});const pool=createIntegrationPool(url);try{const {rows}=await pool.query("select c.relname,c.relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname=any($1::text[]) and c.relkind='r' order by c.relname",[tables]);assert.equal(rows.length,tables.length);for(const row of rows)assert.equal(row.relrowsecurity,true,row.relname);}finally{await pool.end();}});

test('D20 browser roles have no direct authoritative grants',{skip},async()=>{const pool=createIntegrationPool(url);try{const {rows}=await pool.query("select table_name,grantee,privilege_type from information_schema.role_table_grants where table_schema='public' and table_name=any($1::text[]) and grantee in ('anon','authenticated')",[tables]);assert.deepEqual(rows,[]);}finally{await pool.end();}});

test('D20 append-only academic evidence is protected by database triggers',{skip},async()=>{const pool=createIntegrationPool(url);try{const expected=['teaching_marking_runs','teaching_marking_criterion_judgments','teaching_gradebook_entries','teaching_topic_score_snapshots','teaching_course_result_snapshots','teaching_grade_change_audit'];const {rows}=await pool.query("select c.relname table_name,t.tgname,pg_get_triggerdef(t.oid,true) definition from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname=any($1::text[]) and not t.tgisinternal and t.tgname like 'd20_append_only_%' order by c.relname",[expected]);assert.equal(rows.length,expected.length);for(const row of rows){assert.match(row.definition,/UPDATE/);assert.match(row.definition,/DELETE/);}}finally{await pool.end();}});

test('D20 graded work cannot begin without locked Course Grading Policy',{skip},async()=>{const pool=createIntegrationPool(url);try{const names=['teaching_d20_assessment_policy_gate','teaching_d20_assignment_policy_gate','teaching_d20_attempt_policy_gate'];const {rows}=await pool.query("select tgname,pg_get_triggerdef(oid,true) definition from pg_trigger where not tgisinternal and tgname=any($1::text[]) order by tgname",[names]);assert.equal(rows.length,names.length);assert.match(rows.map(r=>r.definition).join(' '),/teaching_d20_require_locked_grading_policy/);assert.match(rows.map(r=>r.definition).join(' '),/teaching_d20_require_policy_before_attempt/);}finally{await pool.end();}});

test('D20 appeal direction is governed by policy-at-event rather than request/model input',{skip},async()=>{const pool=createIntegrationPool(url);try{const names=['teaching_d20_grading_policy_appeal_direction','teaching_d20_appeal_policy_gate'];const {rows}=await pool.query("select tgname,pg_get_triggerdef(oid,true) definition from pg_trigger where not tgisinternal and tgname=any($1::text[]) order by tgname",[names]);assert.equal(rows.length,2);assert.match(rows.map(r=>r.definition).join(' '),/guard_policy_appeal_direction/);assert.match(rows.map(r=>r.definition).join(' '),/require_configured_appeal_direction/);}finally{await pool.end();}});

test('D20 Assessment Gradebook lineage is explicit and database-filled',{skip},async()=>{const pool=createIntegrationPool(url);try{const columns=await pool.query("select column_name from information_schema.columns where table_schema='public' and table_name='teaching_gradebook_entries' and column_name in ('source_result_id','source_assessment_id','source_assessment_attempt_id','source_assessment_package_id') order by column_name");assert.deepEqual(columns.rows.map(r=>r.column_name),['source_assessment_attempt_id','source_assessment_id','source_assessment_package_id','source_result_id']);const trigger=await pool.query("select tgname from pg_trigger where tgrelid='public.teaching_gradebook_entries'::regclass and not tgisinternal and tgname='teaching_d20_gradebook_assessment_lineage_trg'");assert.equal(trigger.rows.length,1);}finally{await pool.end();}});

test('D20 result and appeal source identity cannot be silently rewritten',{skip},async()=>{const pool=createIntegrationPool(url);try{const names=['teaching_d20_result_identity_guard','teaching_d20_appeal_identity_guard'];const {rows}=await pool.query("select tgname,pg_get_triggerdef(oid,true) definition from pg_trigger where not tgisinternal and tgname=any($1::text[]) order by tgname",[names]);assert.equal(rows.length,2);assert.match(rows[0].definition+rows[1].definition,/guard_appeal_identity|guard_result_identity/);}finally{await pool.end();}});

test('D20 service-role mutation grants are narrow',{skip},async()=>{const pool=createIntegrationPool(url);try{const {rows}=await pool.query("select table_name,privilege_type from information_schema.role_table_grants where table_schema='public' and table_name=any($1::text[]) and grantee='service_role' and privilege_type in ('UPDATE','DELETE','TRUNCATE') order by table_name,privilege_type",[tables]);assert.deepEqual(rows,[{table_name:'teaching_assessment_results',privilege_type:'UPDATE'},{table_name:'teaching_grade_appeals',privilege_type:'UPDATE'}]);}finally{await pool.end();}});

test('D20 key idempotency and lineage indexes exist',{skip},async()=>{const pool=createIntegrationPool(url);try{const names=['teaching_grading_policies_idempotency_uidx','teaching_marking_runs_idempotency_uidx','teaching_gradebook_entries_idempotency_uidx','teaching_grade_appeals_idempotency_uidx','teaching_topic_score_snapshots_idempotency_uidx','teaching_course_result_snapshots_idempotency_uidx','teaching_grade_change_audit_idempotency_uidx','teaching_gradebook_entries_assessment_result_lineage_idx'];const {rows}=await pool.query("select indexname from pg_indexes where schemaname='public' and indexname=any($1::text[]) order by indexname",[names]);assert.deepEqual(rows.map(r=>r.indexname),[...names].sort());}finally{await pool.end();}});
