'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {PRODUCTION_PROJECT_REF,assertNonProductionDatabase,integrationConfig,createIntegrationPool}=require('./test-db');
const {connectionString:url,projectRef:ref,skipReason:skip}=integrationConfig('D21');
const tables=['teaching_course_attempts','teaching_progression_policies','teaching_progression_outcomes','teaching_progression_pathways','teaching_progression_pathway_steps','teaching_semester_gpa_snapshots'];

test('D21 integration guard refuses production',()=>{assert.throws(()=>assertNonProductionDatabase({connectionString:'postgresql://x@localhost/x',projectRef:PRODUCTION_PROJECT_REF}),/production/);});

test('D21 authoritative tables exist with RLS and no browser grants',{skip},async()=>{const pool=createIntegrationPool(url);try{const {rows}=await pool.query("select c.relname,c.relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname=any($1::text[]) and c.relkind='r' order by c.relname",[tables]);assert.equal(rows.length,tables.length);for(const row of rows)assert.equal(row.relrowsecurity,true,row.relname);const grants=await pool.query("select table_name,grantee,privilege_type from information_schema.role_table_grants where table_schema='public' and table_name=any($1::text[]) and grantee in('anon','authenticated')",[tables]);assert.deepEqual(grants.rows,[]);}finally{await pool.end();}});

test('D21 attempt, policy, outcome, step and GPA truth are append-only',{skip},async()=>{const pool=createIntegrationPool(url);try{const names=['d21_course_attempts_append_only','d21_progression_policies_append_only','d21_progression_outcomes_append_only','d21_pathway_steps_append_only','d21_semester_gpa_append_only'];const {rows}=await pool.query("select tgname,pg_get_triggerdef(oid,true) definition from pg_trigger where not tgisinternal and tgname=any($1::text[]) order by tgname",[names]);assert.equal(rows.length,names.length);for(const r of rows){assert.match(r.definition,/UPDATE/);assert.match(r.definition,/DELETE/);}}finally{await pool.end();}});

test('D21 progression outcome carries exact D20 source lineage and immutable digest',{skip},async()=>{const pool=createIntegrationPool(url);try{const expected=['progression_policy_id','progression_policy_version','source_course_result_id','source_course_result_version','source_gradebook_entry_ids','source_state_digest','supersedes_outcome_id'];const {rows}=await pool.query("select column_name from information_schema.columns where table_schema='public' and table_name='teaching_progression_outcomes' and column_name=any($1::text[]) order by column_name",[expected]);assert.deepEqual(rows.map(r=>r.column_name),[...expected].sort());}finally{await pool.end();}});

test('D21 repeat attempts preserve linked history without embedding Gradebook truth',{skip},async()=>{const pool=createIntegrationPool(url);try{const expected=['root_course_id','source_course_id','source_attempt_id','source_progression_outcome_id','prior_pedagogical_history_ref'];const cols=await pool.query("select column_name from information_schema.columns where table_schema='public' and table_name='teaching_course_attempts' and column_name=any($1::text[]) order by column_name",[expected]);assert.deepEqual(cols.rows.map(r=>r.column_name),[...expected].sort());const gradeCols=await pool.query("select column_name from information_schema.columns where table_schema='public' and table_name='teaching_course_attempts' and column_name like '%grade%'");assert.deepEqual(gradeCols.rows,[]);}finally{await pool.end();}});

test('D21 pathways alone have service-role UPDATE and guard immutable academic identity',{skip},async()=>{const pool=createIntegrationPool(url);try{const {rows}=await pool.query("select table_name,privilege_type from information_schema.role_table_grants where table_schema='public' and table_name=any($1::text[]) and grantee='service_role' and privilege_type in('UPDATE','DELETE','TRUNCATE') order by table_name,privilege_type",[tables]);assert.deepEqual(rows,[{table_name:'teaching_progression_pathways',privilege_type:'UPDATE'}]);const guard=await pool.query("select tgname from pg_trigger where tgrelid='public.teaching_progression_pathways'::regclass and not tgisinternal and tgname='d21_pathway_identity_guard'");assert.equal(guard.rows.length,1);}finally{await pool.end();}});

test('D21 PPL target is unique and pathway stores the workspace reference',{skip},async()=>{const pool=createIntegrationPool(url);try{const idx=await pool.query("select indexname from pg_indexes where schemaname='teaching_preparation' and indexname='teaching_d21_ppl_pathway_workspace_uidx'");assert.equal(idx.rows.length,1);const col=await pool.query("select column_name from information_schema.columns where table_schema='public' and table_name='teaching_progression_pathways' and column_name='preparation_workspace_ref'");assert.equal(col.rows.length,1);}finally{await pool.end();}});

test('D21 idempotency and version indexes exist',{skip},async()=>{const pool=createIntegrationPool(url);try{const names=['teaching_course_attempts_idempotency_uidx','teaching_progression_policies_idempotency_uidx','teaching_progression_outcomes_idempotency_uidx','teaching_progression_outcomes_source_digest_uidx','teaching_progression_pathways_idempotency_uidx','teaching_progression_pathway_steps_idempotency_uidx','teaching_semester_gpa_snapshots_idempotency_uidx','teaching_semester_gpa_snapshots_source_digest_uidx'];const {rows}=await pool.query("select indexname from pg_indexes where indexname=any($1::text[]) order by indexname",[names]);assert.deepEqual(rows.map(r=>r.indexname),[...names].sort());}finally{await pool.end();}});
