'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {PRODUCTION_PROJECT_REF,assertNonProductionDatabase,integrationConfig,createIntegrationPool}=require('./test-db');
const {connectionString:url,projectRef:ref,skipReason:skip}=integrationConfig('D22');
const tables=['teaching_teacher_identity_versions','teaching_teacher_familiarity_states'];

test('D22 integration guard refuses production',()=>{assert.throws(()=>assertNonProductionDatabase({connectionString:'postgresql://x@localhost/x',projectRef:PRODUCTION_PROJECT_REF}),/production/);});

test('D22 authoritative version/familiarity tables exist with RLS and browser read-only access',{skip},async()=>{const pool=createIntegrationPool(url);try{const {rows}=await pool.query("select c.relname,c.relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname=any($1::text[]) and c.relkind='r' order by c.relname",[tables]);assert.equal(rows.length,tables.length);for(const row of rows)assert.equal(row.relrowsecurity,true,row.relname);const grants=await pool.query("select table_name,privilege_type from information_schema.role_table_grants where table_schema='public' and table_name=any($1::text[]) and grantee='authenticated' order by table_name,privilege_type",[tables]);assert.deepEqual(grants.rows,[{table_name:'teaching_teacher_familiarity_states',privilege_type:'SELECT'},{table_name:'teaching_teacher_identity_versions',privilege_type:'SELECT'}]);}finally{await pool.end();}});

test('D22 identity and familiarity history are append-only',{skip},async()=>{const pool=createIntegrationPool(url);try{const names=['teaching_teacher_identity_versions_immutable','teaching_teacher_familiarity_states_immutable'];const {rows}=await pool.query("select tgname,pg_get_triggerdef(oid,true) definition from pg_trigger where not tgisinternal and tgname=any($1::text[]) order by tgname",[names]);assert.equal(rows.length,2);for(const row of rows){assert.match(row.definition,/UPDATE/);assert.match(row.definition,/DELETE/);}}finally{await pool.end();}});

test('D22 version schema stores structured style traits but no subject/performance personality inputs',{skip},async()=>{const pool=createIntegrationPool(url);try{const wanted=['teacher_identity_id','version_no','style_envelope_schema_version','warmth','directness','formality','expressiveness','humor_frequency','encouragement_intensity','challenge_style','accountability_style','conversationality','presentation_metadata','generation_mode','broad_style_preference','influence_trace','prompt_family_id','prompt_family_version','prompt_sha256'];const cols=await pool.query("select column_name from information_schema.columns where table_schema='public' and table_name='teaching_teacher_identity_versions' order by ordinal_position");const names=cols.rows.map(r=>r.column_name);for(const name of wanted)assert.ok(names.includes(name),name);for(const forbidden of ['subject_id','course_subject','grade','mark','performance','gender'])assert.equal(names.includes(forbidden),false,forbidden);}finally{await pool.end();}});

test('D22 familiarity is assignment-scoped authoritative state, not embedded course-age inference',{skip},async()=>{const pool=createIntegrationPool(url);try{const cols=await pool.query("select column_name from information_schema.columns where table_schema='public' and table_name='teaching_teacher_familiarity_states' order by ordinal_position");const names=cols.rows.map(r=>r.column_name);assert.ok(names.includes('teacher_assignment_id'));assert.ok(names.includes('familiarity_level'));assert.ok(names.includes('source_kind'));assert.equal(names.includes('message_count'),false);assert.equal(names.includes('course_age'),false);}finally{await pool.end();}});

test('D22 service_role has SELECT/INSERT only on append-only D22 truth',{skip},async()=>{const pool=createIntegrationPool(url);try{const {rows}=await pool.query("select table_name,privilege_type from information_schema.role_table_grants where table_schema='public' and table_name=any($1::text[]) and grantee='service_role' order by table_name,privilege_type",[tables]);assert.deepEqual(rows,[{table_name:'teaching_teacher_familiarity_states',privilege_type:'INSERT'},{table_name:'teaching_teacher_familiarity_states',privilege_type:'SELECT'},{table_name:'teaching_teacher_identity_versions',privilege_type:'INSERT'},{table_name:'teaching_teacher_identity_versions',privilege_type:'SELECT'}]);}finally{await pool.end();}});

test('D22 retains D10 formal Teacher Change lineage rather than introducing a second request owner',{skip},async()=>{const pool=createIntegrationPool(url);try{const request=await pool.query("select check_clause from information_schema.check_constraints where constraint_name in (select constraint_name from information_schema.constraint_column_usage where table_schema='public' and table_name='teaching_requests' and column_name='request_type')");assert.ok(request.rows.some(r=>String(r.check_clause).includes('TEACHER_CHANGE')));const cols=await pool.query("select column_name from information_schema.columns where table_schema='public' and table_name='teaching_course_teacher_assignments' and column_name in('source_request_id','supersedes_teacher_assignment_id') order by column_name");assert.deepEqual(cols.rows.map(r=>r.column_name),['source_request_id','supersedes_teacher_assignment_id']);}finally{await pool.end();}});
