'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const c=require('../../../teaching/classroom-remodel/task-contracts');
const {taskPolicy}=require('../fixtures/classroom-task-policy');
const window=()=>({id:'window',version:1,state:'PENDING_DELIVERY',duration_ms:1000,opened_at:null,deadline_at:null,activation_receipt_id:null,class_end_at:'2026-10-10T16:00:00.000Z',extension_count:0});
test('pending task opens only on actual render receipt and retains a committed absolute deadline',()=>{const t={window:window()};assert.throws(()=>c.openWindow(t,{now:'2026-10-10T15:00:00Z',classEnd:t.window.class_end_at}),{code:'CLASSROOM_TASK_RENDER_RECEIPT_REQUIRED'});const w=c.openWindow(t,{now:'2026-10-10T15:00:00Z',classEnd:t.window.class_end_at,receiptId:'receipt'});assert.equal(w.state,'OPEN');assert.equal(w.deadline_at,'2026-10-10T15:00:01.000Z');assert.equal(w.activation_receipt_id,'receipt');});
test('insufficient fair time cancels a pending question as a system outcome rather than a wrong answer',()=>{const t={window:window()};const w=c.openWindow(t,{now:'2026-10-10T15:59:59.500Z',classEnd:t.window.class_end_at,receiptId:'receipt'});assert.equal(w.state,'CANCELLED_SYSTEM');assert.equal(w.reason,'INSUFFICIENT_FAIR_RESPONSE_TIME');assert.equal(w.opened_at,null);});
test('extensions are adopted bounded changes to the same window and never exceed Class end',()=>{const w=c.openWindow({window:window()},{now:'2026-10-10T15:00:00Z',classEnd:'2026-10-10T16:00:00Z',receiptId:'receipt'});const ext=c.extendWindow(w,taskPolicy(),{now:'2026-10-10T15:00:00.500Z',classEnd:'2026-10-10T15:00:01.200Z'});assert.equal(ext.id,w.id);assert.equal(ext.deadline_at,'2026-10-10T15:00:01.200Z');assert.throws(()=>c.extendWindow(ext,taskPolicy(),{now:'2026-10-10T15:00:00.600Z',classEnd:ext.class_end_at}),{code:'CLASSROOM_TASK_EXTENSION_EXHAUSTED'});assert.throws(()=>c.extendWindow(w,taskPolicy(),{now:w.deadline_at,classEnd:w.class_end_at}),{code:'CLASSROOM_TASK_EXTENSION_INELIGIBLE'});});
test('missing owner-adopted policy holds tasks and browser authority fields cannot enter a response',()=>{assert.throws(()=>c.policy({version:'missing',fields:{}}),{code:'CLASSROOM_TASK_POLICY_MISSING'});const s={schemaVersion:c.VERSION,sessionId:'session',operationKey:'key',taskId:'task',taskVersion:'1',windowId:'window',windowVersion:2,text:'My reasoning'};assert.equal(c.submission(s),s);assert.throws(()=>c.submission({...s,submittedAt:'2026-10-10T15:00:00Z'}),{code:'CLASSROOM_TASK_SUBMISSION_INVALID'});assert.throws(()=>c.submission({...s,charged:false}),{code:'CLASSROOM_TASK_SUBMISSION_INVALID'});});
test('extension requests reject client-owned duration and deadlines',()=>{const input={schemaVersion:c.VERSION,sessionId:'s',operationKey:'o',taskId:'t',windowId:'w',windowVersion:2};assert.equal(c.extension(input),input);for(const field of ['deadline','durationMs','charged','submittedAt'])assert.throws(()=>c.extension({...input,[field]:1}),{code:'CLASSROOM_TASK_EXTENSION_INVALID'});assert.throws(()=>c.extendWindow({...window(),state:'OPEN',deadline_at:'invalid'},taskPolicy(),{now:'invalid',classEnd:'invalid'}),{code:'CLASSROOM_TASK_EXTENSION_INELIGIBLE'});});
test('late-review policy remains held until its independent route exists',()=>{const p=taskPolicy();p.fields.lateSubmissionPolicy.value='separate_authorized_review';assert.throws(()=>c.policy(p),{code:'CLASSROOM_TASK_LATE_REVIEW_ROUTE_HELD'});});
const f=require('../fixtures/classroom-remodel-academic'),tf=require('../fixtures/classroom-tasks');
function designed(){const p=tf.proposal();return c.check(p,{chapter:f.chapter(),targetRef:{kind:'course_learning_unit',id:'lu1',version:'1',anchor:null},validation:tf.validation(p),policy:taskPolicy(),sessionId:'s',classEnd:window().class_end_at,taskId:'t',windowId:'w',criterionId:'criterion'}).task;}
test('task design requires explicitly authorized evidence intent and independent validation',()=>{const p=tf.proposal(),args={chapter:f.chapter(),targetRef:{kind:'course_learning_unit',id:'lu1',version:'1',anchor:null},validation:tf.validation(p),policy:taskPolicy(),sessionId:'s',classEnd:window().class_end_at,taskId:'t',windowId:'w',criterionId:'criterion'};assert.equal(c.check(p,args).task.evidence_intent,'practice');assert.throws(()=>c.check(p,{...args,validation:{...args.validation,evidenceIntent:undefined}}),{code:'CLASSROOM_TASK_EVIDENCE_INTENT_NOT_AUTHORIZED'});assert.throws(()=>c.check(p,{...args,validation:{...args.validation,independent:false}}),{code:'CLASSROOM_TASK_INDEPENDENT_VALIDATION_REQUIRED'});});
test('canonical evaluation projects into D12 without discarding findings or upgrading independence',()=>{const task=designed(),output=tf.interpretation(task,'r');const result=c.interpretation(output,{task,responseId:'r',demand:tf.proposal().artifacts.checks[0].task_demand,stateReference:'fixture@1',exposure:{answer_or_method_exposed:true,uncertain_exposure:true,released_assistance_level:'none'}});assert.equal(result.evaluation.response_assessment.final_result_correctness,'correct');assert.equal(result.evaluation.response_assessment.evidence_sufficiency,'contaminated');assert.equal(result.evaluation.assistance_and_independence.independence_interpretation,'contaminated');assert.deepEqual(result.evaluation.canonical_interpretation,output.artifacts.response_interpretation);assert.equal(result.officialOutcome,false);});
test('incorrect work on an item needing protection cannot supply unrestricted negative evidence',()=>{const task=designed(),output=tf.interpretation(task,'r');output.artifacts.response_interpretation.item_validity.negative_attribution_protection=true;output.artifacts.response_interpretation.judgments.correctness='incorrect';output.artifacts.response_interpretation.judgments.evidence_sufficiency='supported';const result=c.interpretation(output,{task,responseId:'r',demand:tf.proposal().artifacts.checks[0].task_demand,stateReference:'fixture@1',exposure:{}});assert.equal(result.evaluation.item_validity.evidence_use_limit,'do_not_use_negative_evidence');assert.equal(result.evaluation.response_assessment.evidence_sufficiency,'insufficient');});
test('interpretation must refer to the exact admitted response and private criterion version',()=>{const task=designed(),args={task,responseId:'r',demand:tf.proposal().artifacts.checks[0].task_demand,stateReference:'fixture@1',exposure:{}};const output=tf.interpretation(task,'other');assert.throws(()=>c.interpretation(output,args),{code:'CLASSROOM_TASK_INTERPRETATION_TARGET_MISMATCH'});});
test('evaluation worker reviews immutable output before commit and handles a provider failure durably',async()=>{const task=designed(),responseId='r',context={task,response:{response_id:responseId},policy:taskPolicy(),design:tf.proposal()},claim={admissionId:'a',token:'token',context,exposure:{}};let committed=0,failed=0;const repository={claimEvaluation:async()=>claim,commitEvaluation:async(_s,_c,_claim,_output,receipt)=>{assert.equal(receipt.ownerRef,'reviewer');committed++;return {accepted:true};},failEvaluation:async()=>{failed++;}};const {createClassroomTaskService}=require('../../../teaching/classroom-remodel/task-service');const service=createClassroomTaskService({repository,coordinator:{interpret:async args=>{assert.equal(args.immutableContext,context);return tf.interpretation(task,responseId);}},reviewer:{accept:async args=>{assert.equal(args.evaluation.canonical_interpretation.task_ref,'task:t@1');return {ownerRef:'reviewer'};}}});assert.equal((await service.process({studentId:'s',classId:'c',admissionId:'a'})).accepted,true);assert.equal(committed,1);const broken=createClassroomTaskService({repository,coordinator:{interpret:async()=>{throw Object.assign(Error('provider failed'),{code:'PROVIDER_FAULT'});}},reviewer:{accept:async()=>{throw Error('must not review failed output');}}});assert.equal((await broken.process({studentId:'s',classId:'c',admissionId:'a'})).pending,true);assert.equal(failed,1);assert.equal(committed,1);});
test('one bounded action replaces a conflicting proposal and cannot increase help ceiling',()=>{const task=designed(),output=tf.interpretation(task,'r'),interpreted=c.interpretation(output,{task,responseId:'r',demand:tf.proposal().artifacts.checks[0].task_demand,stateReference:'fixture@1',exposure:{}});const actions=require('../../../teaching/classroom-remodel/task-actions');const selected=actions.select(interpreted.evaluation,{action:'hint'},{task});assert.equal(selected.action,'independent attempt');assert.equal(selected.proposed_action,'hint');assert.equal(selected.new_task_required,true);assert.throws(()=>actions.level('worked_example',task),/ceiling/i);assert.equal(actions.level('attention',task).proposed_level,'attention');});
test('task interpretation uses governed canonical candidate execution without changing active bindings',async()=>{
 const task=designed(),policy=taskPolicy(),responseId='r',output=tf.interpretation(task,responseId),context={classRow:{student_id:'s',class_id:'c',course_id:'course',course_lifecycle_state:'ACTIVE',course_state_version:1,schedule_version:1},session:{state_version:2,instructional_substate:'INSTRUCTION'},plan:{course_plan_id:'plan',version_no:1}};let request;
 const adapter=require('../../../teaching/classroom-remodel/task-intelligence').createClassroomTaskIntelligence({orchestrator:{execute:async args=>{request=args;await args.beforeAttempt();assert.equal((await args.schemaValidator(output)).ok,true);return {accepted:true,validatedResult:{output}};}},d11Repository:{getClassContext:async()=>context},requirementsReader:async()=>({version:'fixture',adoptionRef:'fixture',numericPolicy:{version:policy.version}})});
 const admission={task,response:{response_id:responseId},policy,sources:{chapter:f.chapter()},design:tf.proposal()};assert.equal(await adapter.coordinator.interpret({studentId:'s',classId:'c',admissionId:'a',token:'lease',immutableContext:admission,exposure:{}}),output);assert.equal(request.candidatePromptBinding.familyId,'TPF-21');assert.equal(request.taskMode,'interpret_response');assert.equal(request.candidatePromptBinding.runtimeAuthorized,false);assert.equal(request.commit,false);assert.equal(request.academicInput.immutable_admission,admission);assert.deepEqual(request.contextSpec.untrusted_refs,[{ref:'response:r'}]);
});
test('Presenter cannot receive feedback until an independent owner selects public findings',async()=>{
 const task=designed(),policy=taskPolicy(),ready={task,publicTask:{id:task.id},policy,expected:{authority:{version:'fixture'},deliveryEpoch:1},sources:{chapter:f.chapter()},job:{admission_id:'a',evaluation_id:'e',acceptance_receipt:{accepted:true},context_snapshot:{sources:{chapter:f.chapter()},response:{assistance_context:{}},design:tf.proposal()},selected_action:{action:'independent attempt',feedback_points:['private raw finding']}}};let generated=0;
 const service=require('../../../teaching/classroom-remodel/task-service').createClassroomTaskService({repository:{handlingContext:async()=>ready,loadTurn:async()=>null},turnProvider:{generate:async()=>{generated++;}},turnReviewer:{select:async()=>({publicContent:{feedbackPoints:[]},receipt:{accepted:false}}),accept:async()=>{}}});await assert.rejects(()=>service.prepareHandling({studentId:'s',classId:'c',taskId:task.id}),{code:'CLASSROOM_TASK_PUBLIC_SELECTION_REQUIRED'});assert.equal(generated,0);
});
test('fresh verification rejects cosmetic replacement before a new task can be committed',async()=>{
 const task=designed(),policy=taskPolicy();let committed=0;const ready={priorTask:task,admission:{},turn:{selected_action:{action:'independent attempt',new_task_required:true}},policy,expected:{authority:{},deliveryEpoch:1},sources:{chapter:f.chapter()}};
 const service=require('../../../teaching/classroom-remodel/task-service').createClassroomTaskService({repository:{actionContext:async()=>ready,design:async()=>{committed++;}},coordinator:{design:async()=>tf.proposal()},reviewer:{acceptDesign:async()=>({independent:true,variationOfTaskId:task.id,constructPreserved:true,cosmeticOnly:true,variationReviewRef:'not-approved'})},turnReviewer:{acceptQuestion:async()=>{}}});await assert.rejects(()=>service.adjust({studentId:'s',classId:'c',turnId:'t'}),{code:'CLASSROOM_FRESH_VARIATION_NOT_VALIDATED'});assert.equal(committed,0);
});
test('partial success and ambiguous evidence retain separate judgments rather than collapsing to incorrect',()=>{
 const task=designed();for(const correctness of ['partial','indeterminate']){const output=tf.interpretation(task,'r'),v=output.artifacts.response_interpretation;v.judgments.correctness=correctness;v.judgments.completeness='partial';v.components.missing=['Direction condition'];const result=c.interpretation(output,{task,responseId:'r',demand:tf.proposal().artifacts.checks[0].task_demand,stateReference:'fixture@1',exposure:{}});assert.equal(result.evaluation.response_assessment.final_result_correctness,correctness==='partial'?'partially_correct':'indeterminate');assert.equal(result.evaluation.response_assessment.completeness,'partial');assert.equal(result.evaluation.canonical_interpretation.components.supported.length,1);assert.deepEqual(result.evaluation.canonical_interpretation.components.missing,['Direction condition']);}
});
test('valid alternatives and local execution slips do not become unsupported misconception truth',()=>{
 const task=designed(),output=tf.interpretation(task,'r'),v=output.artifacts.response_interpretation;v.components.supported=['Equivalent acceleration explanation from the accepted alternative'];v.errors=[{location:'Final arithmetic step',significance:'Local to calculation',kind:'local execution',uncertainty:'No conceptual failure established'}];const result=c.interpretation(output,{task,responseId:'r',demand:tf.proposal().artifacts.checks[0].task_demand,stateReference:'fixture@1',exposure:{}});assert.equal(result.evaluation.response_assessment.final_result_correctness,'correct');assert.equal(result.evaluation.error_analysis[0].type,'procedural_slip');assert.equal(result.evaluation.misconception.status,'none_supported');assert.deepEqual(result.evaluation.canonical_interpretation,v);
});
test('misconception and prerequisite hypotheses preserve alternative explanations and evidence limits',()=>{
 const task=designed(),output=tf.interpretation(task,'r');output.artifacts.response_interpretation.hypotheses=[{basis:'proposal',evidence_refs:['response:r'],type:'misconception',alternatives:['Wording ambiguity','Local omission'],confidence:'low'},{basis:'unresolved',evidence_refs:['response:r'],type:'prerequisite',alternatives:['Prerequisite not yet observed'],confidence:'indeterminate'}];const result=c.interpretation(output,{task,responseId:'r',demand:tf.proposal().artifacts.checks[0].task_demand,stateReference:'fixture@1',exposure:{}});assert.equal(result.evaluation.misconception.status,'indeterminate');assert.equal(result.evaluation.prerequisite.status,'investigation_needed');assert.equal(result.evaluation.prerequisite.prerequisite_ref,null);assert.deepEqual(result.evaluation.misconception.alternative_explanations,['Wording ambiguity','Local omission']);assert.equal(result.officialOutcome,false);
});
test('authorized accommodation context is retained without changing observed correctness or inventing independence',()=>{
 const task=designed(),output=tf.interpretation(task,'r'),v=output.artifacts.response_interpretation;v.attempt_context.accommodations=['Authorized screen reader; target construct unchanged'];const result=c.interpretation(output,{task,responseId:'r',demand:tf.proposal().artifacts.checks[0].task_demand,stateReference:'fixture@1',exposure:{answer_or_method_exposed:false,uncertain_exposure:false,released_assistance_level:'none'}});assert.equal(result.evaluation.response_assessment.final_result_correctness,'correct');assert.equal(result.evaluation.response_assessment.reasoning_or_method,'valid');assert.equal(result.evaluation.assistance_and_independence.independence_interpretation,'unknown');assert.deepEqual(result.evaluation.canonical_interpretation.attempt_context.accommodations,v.attempt_context.accommodations);
});
