'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {createClassroomPresentationService}=require('../../../teaching/classroom-remodel/presentation-service');
const {assertPresentationPolicy,dwell}=require('../../../teaching/classroom-remodel/presentation-policy');
const {fixturePolicy}=require('../fixtures/classroom-presentation-policy');const f=require('../fixtures/classroom-remodel-academic');
const input={schemaVersion:'classroom-domain.v1',sessionId:'s',operationKey:'op',expectedControllerVersion:1,expectedDeliveryVersion:1,deliveryEpoch:1,controlEpoch:0,clientId:'client',intent:'claim'};
test('presentation refuses unadopted policy; dwell uses adopted types and pace only',()=>{const p=fixturePolicy();assertPresentationPolicy(p);assert.equal(dwell(p,'normal',['diagram']),20);assert.equal(dwell(p,'slow',['text']),20);assert.throws(()=>dwell(p,'normal',['unknown']));delete p.fields.clientLeaseMs;assert.throws(()=>assertPresentationPolicy(p));});
test('public commands preserve authenticated owner and reject private/unsupported input',async()=>{let call;const s=createClassroomPresentationService({repository:{command:async(...args)=>{call=args;return {accepted:true};}}});await s.lease({id:'owned'},'class',input);assert.equal(call[0],'owned');assert.equal(call[1],'class');assert.throws(()=>s.lease({id:'owned'},'class',{...input,studentId:'other'}),{code:'CLASSROOM_COMMAND_INVALID'});assert.throws(()=>s.control({id:'owned'},'class',input),{code:'CLASSROOM_CONTROL_UNAVAILABLE'});assert.throws(()=>s.lease({id:'owned'},'class',{...input,deliveryEpoch:'1'}),{code:'CLASSROOM_COMMAND_INVALID'});assert.throws(()=>s.snapshot(null,'class'),{code:'CLASSROOM_OWNER_REQUIRED'});});
test('generation captures then runs outside repository and rejects stale output at acceptance',async()=>{const order=[],expected={policy:fixturePolicy(),authority:{controllerVersion:1}};const repository={capture:async()=>{order.push('capture');return expected;},preparationInputs:async()=>{order.push('inputs');return {chapter:f.chapter(),guide:f.guide()};},acceptSequence:async args=>{order.push('accept');assert.equal(args.expected,expected);return {accepted:false,reason:'STALE_GENERATION_AUTHORITY'};}};const s=createClassroomPresentationService({repository,presenter:{generate:async args=>{order.push('generate');assert.equal(args.retryLimit,0);return f.opening();}}});assert.equal((await s.prepareSpan({studentId:'s',classId:'c',operationKey:'o',directive:f.directive()})).accepted,false);assert.deepEqual(order,['capture','inputs','generate','accept']);});
test('missing qualified presenter is a scoped hold and never invokes persistence',async()=>{const s=createClassroomPresentationService({repository:{capture:()=>assert.fail()}});assert.equal((await s.prepareSpan({})).reason,'CLASSROOM_PRESENTER_ROUTE_HELD');});
test('provider stall returns a bounded unknown-outcome hold and never accepts late output',async()=>{const policy=fixturePolicy();policy.fields.generationTimeoutMs.value=5;let accepted=0;const s=createClassroomPresentationService({repository:{capture:async()=>({policy,authority:{}}),preparationInputs:async()=>({chapter:f.chapter(),guide:f.guide()}),acceptSequence:()=>accepted++},presenter:{generate:async args=>{assert.ok(args.signal);return new Promise(resolve=>setTimeout(()=>resolve(f.opening()),15));}}});const result=await s.prepareSpan({studentId:'s',classId:'c',operationKey:'o',directive:f.directive()});assert.equal(result.reason,'CLASSROOM_GENERATION_OUTCOME_UNKNOWN');await new Promise(resolve=>setTimeout(resolve,20));assert.equal(accepted,0);});
test('live Presenter adapter uses D14 controller context, durably accepts before D05 completion, and reconciles replay',async()=>{
 const policy=fixturePolicy();let request,cached=null;
 const context={classRow:{student_id:'s',class_id:'c',course_id:'course',course_lifecycle_state:'ACTIVE',course_state_version:1,schedule_version:1},session:{state_version:2,instructional_substate:'INSTRUCTION'},plan:{course_plan_id:'plan',version_no:1}};
 const repository={loadSequence:async()=>cached,acceptSequence:async args=>{cached=args.output;return {accepted:true};}};
 const adapter=require('../../../teaching/classroom-remodel/presentation-intelligence').createClassroomPresentationIntelligence({orchestrator:{execute:async args=>{request=args;await args.beforeAttempt();await assert.rejects(()=>args.beforeAttempt(),{code:'CLASSROOM_GENERATION_RETRY_BUDGET_EXHAUSTED'});const checked=await args.schemaValidator(f.opening());assert.equal(checked.ok,true);await args.provisionalResultSink({output:checked.value});return {accepted:true,validatedResult:{output:checked.value}};}},repository,d11Repository:{getClassContext:async()=>context},requirementsReader:async()=>({version:'fixture',adoptionRef:'fixture',numericPolicy:{version:policy.version}})});
 const args={studentId:'s',classId:'c',policy,expected:{authority:{},deliveryEpoch:1},operationKey:'operation',chapter:f.chapter(),guide:f.guide(),directive:f.directive()};
 await adapter.generate(args);assert.equal(request.stateReference.state_version,'2');assert.equal(request.candidatePromptBinding.familyId,'TPF-08');assert.equal(request.preparation,undefined);assert.equal(request.commit,false);assert.equal(request.generation.maxOutputTokens,policy.fields.generationBudget.value);assert.equal(request.academicInput.pinned_numeric_policy,policy);assert.equal((await adapter.generate(args)),cached);
 await assert.rejects(()=>adapter.generate({...args,policy:{version:'mismatch'}}),{code:'CLASSROOM_GENERATION_POLICY_HANDOFF_CONFLICT'});
});
test('presentation wire maps command safety fields and returns the canonical domain receipt',async()=>{
 const result={operationId:'op',sessionId:'s',accepted:true,applied:true,controllerVersion:1,deliveryVersion:2,deliveryEpoch:1,controlEpoch:1,serverTime:'2026-10-10T01:00:00Z',leaseToken:'private-owned-token'};
 const s=createClassroomPresentationService({repository:{command:async()=>result}});const response=await s.lease({id:'s'},'c',input);assert.equal(response.receipt.operation_id,'op');assert.equal(response.receipt.outcome,'applied');assert.equal(response.receipt.delivery_version,2);assert.equal(response.wire_schema_version,'classroom-presentation-wire.v1');
});
