'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {validateInput,assertPolicy,validateDisposition}=require('../../../teaching/classroom-remodel/message-contracts');
const {messagePolicy}=require('../fixtures/classroom-message-policy');const {proposal}=require('../fixtures/classroom-messages');const f=require('../fixtures/classroom-remodel-academic');
test('message policy requires adopted limits, units and independent worker recovery bounds',()=>{assertPolicy(messagePolicy());const p=messagePolicy();delete p.fields.messageRateWindowMs;assert.throws(()=>assertPolicy(p),{code:'CLASSROOM_MESSAGE_POLICY_MISSING'});const q=messagePolicy();delete q.fields.conversationalAllowance.unit;assert.throws(()=>assertPolicy(q),{code:'CLASSROOM_MESSAGE_POLICY_UNIT_MISSING'});});
test('client cannot claim teacher response or silently add authority fields',()=>{const b={schemaVersion:'classroom-messages.v1',sessionId:'s',operationKey:'k',content:'x',intent:'task_response'};assert.throws(()=>validateInput(b),{code:'CLASSROOM_MESSAGE_LANE_UNAVAILABLE'});assert.throws(()=>validateInput({...b,intent:'conversation',charged:false}),{code:'CLASSROOM_MESSAGE_INVALID'});});
test('routing keeps exact closed timing enum with compatible unit scheduling',()=>{const p=proposal('m',{kind:'unit',anchor:'U01'});assert.equal(validateDisposition(p,{messageId:'m',chapter:f.chapter()}).kind,'unit');p.artifacts.scheduling[0].boundary_ref='nonexistent';assert.throws(()=>validateDisposition(p,{messageId:'m',chapter:f.chapter()}),{code:'CLASSROOM_MESSAGE_UNIT_UNAVAILABLE'});});
test('proposal cannot claim delivered answer, resolved difficulty, task verdict or unsupported action',()=>{for(const patch of [{reply_delivery_status:'delivered_confirmed'},{difficulty_resolution:'resolved'},{requested_queue_transition:'answered'}]){const p=proposal('m');Object.assign(p.artifacts.message_dispositions[0],patch);assert.throws(()=>validateDisposition(p,{messageId:'m',chapter:f.chapter()}));}const p=proposal('m');p.next_action.action='focused probe';assert.throws(()=>validateDisposition(p,{messageId:'m',chapter:f.chapter()}),{code:'CLASSROOM_MESSAGE_ACTION_UNAVAILABLE'});});
test('support report lanes are explicit; unsupported task response remains unavailable',()=>{for(const intent of ['technical_report','correction_report'])assert.equal(validateInput({schemaVersion:'classroom-messages.v1',sessionId:'s',operationKey:'k',content:'x',intent}).intent,intent);});
