'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const c=require('../../../teaching/classroom-remodel/contracts');
const p=require('../../../teaching/classroom-remodel/state-policy');
const s=require('../../../teaching/classroom-remodel/session-selection');
const schemas=require('../../../teaching/classroom-remodel/mode-schemas');
const g=require('../../../teaching/classroom-remodel/candidate-governance');
const {buildInventory}=require('../../../scripts/build-classroom-remodel-inventory');
const copy=x=>JSON.parse(JSON.stringify(x));
test('legacy adapters preserve D07 diagnostic fields and execute original scope validators',async()=>{
 const a=require('../../../teaching/classroom-remodel/legacy-consumer-adapter');
 const request=require('../../../teaching/d07/intelligence').diagnosticRequest({course:{course_id:'c1',state_version:1},requirement:{targets:['lu1']},audit:{curriculum_audit_id:'a1'}});
 const payload={purpose:'Verify prior knowledge',targets:['lu1'],opportunities:[{id:'o1'},{id:'o2'}],critical_criteria:[{target:'lu1',criterion:'Explain'}],non_graded:true};
 const extension=await a.wrapLegacyConsumer({request,payload,mode:'design_check'});assert.deepEqual(await a.unwrapLegacyConsumer({request,extension}),payload);assert.equal(extension.acceptance,'CANDIDATE_NOT_COMMITTED');
 const tampered=copy(extension);tampered.payload.targets=['lu2'];await assert.rejects(()=>a.unwrapLegacyConsumer({request,extension:tampered}));
 await assert.rejects(()=>a.wrapLegacyConsumer({request,payload:{...payload,targets:['lu2']},mode:'design_check'}));
 await assert.rejects(()=>a.wrapLegacyConsumer({request,payload,mode:'coordinate_lesson'}));
});
test('coordinator compatibility extension needs original validators and cannot inflate a held legacy status',async()=>{
 const a=require('../../../teaching/classroom-remodel/legacy-consumer-adapter');
 const request=require('../../../teaching/d07/intelligence').diagnosticRequest({course:{course_id:'c1',state_version:1},requirement:{targets:['lu1']},audit:{curriculum_audit_id:'a1'}});
 const payload={purpose:'Verify prior knowledge',targets:['lu1'],opportunities:[{id:'o1'},{id:'o2'}],critical_criteria:[],non_graded:true};
 const extension=await a.wrapLegacyConsumer({request,payload,mode:'design_check'});const v=coordinator('design_check','complete');v.artifacts={legacy_consumer:extension};
 assert.throws(()=>c.validateCoordinator(v));assert.equal((await schemas.getModeSchema('coordinator','design_check').validate(v)).ok,false);
 const schema=schemas.getModeSchema('coordinator','design_check',{legacyRequest:request});assert.equal((await schema.validate(v)).ok,true);assert.equal(Object.keys(v).length,9);
 extension.payload.purpose='Changed after validation';assert.throws(()=>c.validateCoordinator(v));assert.equal((await schema.validate(v)).ok,false);
 const held=await a.wrapLegacyConsumer({request,payload:{...payload,status:'validation_needed'},mode:'design_check'});v.artifacts={legacy_consumer:held};assert.equal((await schema.validate(v)).ok,false);
});
test('legacy profile and fresh verification extensions retain D12 detailed schemas and state guards',async()=>{
 const a=require('../../../teaching/classroom-remodel/legacy-consumer-adapter');const d=require('../../../teaching/d12/intelligence');
 const context={classRow:{class_id:'c1',student_id:'s1',course_lifecycle_state:'ACTIVE',course_state_version:1,schedule_version:1},session:{class_session_id:'session1',state_version:2},plan:{course_plan_id:'p1',version_no:1}};
 const learningUnit={learning_unit_id:'lu1',metadata:{}};
 const request=d.profileClassificationRequest({context,learningUnit,subjectTemplate:{}});
 const payload={status:'ok',review_required:false,review_reasons:[],profile:{learning_unit_ref:'lu1',knowledge_type:'mixed',primary_student_actions:['explain'],answer_space:'multiple_valid_approaches',representations:['text']},uncertainties:[]};
 const extension=await a.wrapLegacyConsumer({request,payload,mode:'prepare_guidance'});assert.deepEqual(await a.unwrapLegacyConsumer({request,extension}),payload);
 const bad=copy(payload);bad.profile.learning_unit_ref='other';await assert.rejects(()=>a.wrapLegacyConsumer({request,payload:bad,mode:'prepare_guidance'}));
 const fresh=d.freshVerificationRequest({context,learningUnit,evaluation:{evaluation_id:'e1'},verificationDirective:{}});
 const freshPayload={status:'ok',input_state_reference:'class-session:session1@2',decision_question:'Independent support?',verification_directive:{reuse_policy:'fresh_equivalent_required'},review_required:false,review_reasons:[],verification_plan:{},selection:{candidate_ref:'new1'},uncertainties:[],handoff:[]};
 const wrapped=await a.wrapLegacyConsumer({request:fresh,payload:freshPayload,mode:'design_check'});assert.deepEqual(await a.unwrapLegacyConsumer({request:fresh,extension:wrapped}),freshPayload);
 await assert.rejects(()=>a.wrapLegacyConsumer({request:fresh,payload:{...freshPayload,input_state_reference:'class-session:session1@1'},mode:'design_check'}));
});
const ref=(anchor=null,version='1',kind='chapter')=>({kind,id:'chapter1',version,anchor});
const chapter=()=>({id:'chapter1',version:'1',scope_ref:'scope1@1',title:'Force',completeness:'complete',validation:'validated',units:[{anchor:'U01',title:'Meaning',objective_refs:[],prerequisite_refs:[],designation:'essential',treatment:'scheduled',elements:[{anchor:'U01.P01',type:'paragraph',text:'Force changes motion through acceleration.',asset_ref:null,alt_text:null,source_refs:['source1@1']}]}],continuation:null,prior_version:null,remaps:[]});
test('candidate canonical alias and all 22 capability modes resolve without runtime authority',()=>{
 const r=require('../../../teaching/classroom-remodel/candidate-registry');
 const family=r.resolveCandidateFamily('TPF-5/8');assert.equal(family.canonicalId,'TPF-21');assert.equal(family.runtimeAuthorized,false);
 for(const binding of require('../../../teaching/classroom-remodel/migration-proposal.v1.json').bindings)for(const mode of binding.modes){const resolved=r.resolveCandidateBinding({familyId:'TPF-5/8',mode,capabilityId:binding.capabilityId});assert.equal(resolved.runtimeAuthorized,false);assert.equal(typeof resolved.schema.validate,'function');}
 assert.throws(()=>r.assertRuntimeActivation(),{code:'CLASSROOM_CANDIDATE_ACTIVATION_PROHIBITED'});
 assert.throws(()=>r.resolveCandidateBinding({familyId:'TPF-21',mode:'prepare_guidance',capabilityId:'unknown'}));
});
test('candidate successor census is generated without changing active or historical readers',()=>{
 const catalog=require('../../../teaching/prompt-runtime/prompt-catalog');const registry=require('../../../teaching/capability-registry');
 const release=require('../../../scripts/build-classroom-release-proposal').buildReleaseProposal();assert.deepEqual(release,require('../../../teaching/classroom-remodel/release-proposal.v1.json'));
 assert.equal(catalog.promptCatalogStatus().familyCount,20);assert.equal(registry.assertRegistryIntegrity().total,170);assert.equal(release.payload.counts.replacementBindings,22);assert.equal(release.payload.counts.retiredActiveBindings,0);
 assert.equal(catalog.getClassroomCandidateFamily('TPF-5/8').canonicalId,'TPF-21');assert.equal(registry.getClassroomCandidateBinding({familyId:'TPF-21',mode:'design_check'}).runtimeAuthorized,false);
 assert.throws(()=>catalog.getPromptFamily('TPF-21'));assert.equal(catalog.getPromptFamily('TPF-20').id,'TPF-20');
});
test('public snapshots exclude unreleased teacher output and retain accepted messages',()=>{
 const d=require('../../../teaching/classroom-remodel/domain-contracts');
 const snapshot={schema_version:'1',session_id:'s1',class_id:'c1',controller_version:1,delivery_version:1,delivery_epoch:1,control_epoch:1,server_time:'2026-10-09T21:00:00Z',cursor:1,chapter_ref:ref(),permitted_actions:[],delivery_state:'READY',conversation:[{id:'e1',sequence:1,role:'teacher',type:'portion',text:'Explain force',source_refs:[],status:'PREPARED',occurred_at:'2026-10-09T21:00:00Z'}],active_task:null};
 assert.throws(()=>d.projectSnapshot(snapshot));snapshot.conversation[0].status='RELEASED';assert.equal(d.projectSnapshot(snapshot).conversation.length,1);
 snapshot.conversation[0].role='student';snapshot.conversation[0].status='ACCEPTED';assert.equal(d.projectSnapshot(snapshot).conversation[0].status,'ACCEPTED');snapshot.private_criteria='secret';assert.throws(()=>d.projectSnapshot(snapshot));
});
test('public deltas preserve continuous cursors and reject private or prepared output',()=>{
 const d=require('../../../teaching/classroom-remodel/domain-contracts');
 const delta={schema_version:'1',session_id:'s1',from_cursor:4,to_cursor:5,server_time:'2026-10-09T21:00:00Z',events:[{id:'e5',sequence:5,role:'teacher',type:'portion',text:'Explain force',source_refs:[],status:'RELEASED',occurred_at:'2026-10-09T21:00:00Z'}]};
 assert.equal(d.projectDelta(delta).events[0].sequence,5);delta.events[0].sequence=4;assert.throws(()=>d.projectDelta(delta));delta.events[0].sequence=5;delta.to_cursor=6;assert.throws(()=>d.projectDelta(delta));delta.to_cursor=5;delta.events[0].private='answer key';assert.throws(()=>d.projectDelta(delta));
});
test('interpretation receipt requires D12 acceptance and pinned task/response/exposure versions',()=>{
 const d=require('../../../teaching/classroom-remodel/domain-contracts');
 const receipt={receipt_id:'r1',interpretation_ref:ref(null,'1','interpretation'),task_ref:ref(null,'1','task'),response_ref:ref(null,'1','response'),criterion_ref:ref(null,'1','criterion'),controller_version:1,chapter_version:'1',assistance_version:'1',exposure_version:'1',accepted_at:'2026-10-09T21:00:00Z',owner:'D12',accepted:true};
 d.validateInterpretationAcceptance(receipt);assert.throws(()=>d.validateInterpretationAcceptance({...receipt,owner:'TPF-21'}));const missing=copy(receipt);delete missing.exposure_version;assert.throws(()=>d.validateInterpretationAcceptance(missing));
});
const directive=()=>({academic_mode:'teaching',instructional_purpose:'Explain force',approved_action:'explain',target_competence_or_question:'objective1',allowed_interaction_kinds:['explanation'],assistance_ceiling:'full_instruction',current_assistance_state:'none',evidence_intent:'instruction_only',restrictions:[],expected_student_action:'none',current_learning_stage:'unknown',presentation_span:[ref('U01.P01','1','source_element')],response_budget:1000,source_refs:[ref('U01.P01','1','source_element')],board_refs:[],task_ref:null,time_constraints:{remaining_ms:null},response_window:null,resume_at:'U01.P01',accepted_evaluation:null});
const coordinator=(mode,status='blocked')=>({request_ref:null,task_mode:mode,input_state_reference:null,status,review_required:status!=='complete',artifacts:{},next_action:null,runtime_requests:[],issues:status==='complete'?[]:[{type:'insufficient context',scope:mode,evidence_or_missing_input:'Authoritative input not supplied',consequence:'Affected result withheld',owner:'D11',can_safely_continue:false}]});
const state=()=>({controllerId:'controller1',lifecycle:'ACTIVE',academicState:'INSTRUCTION',deliveryState:'PRESENTING',windowState:null,conversationalRemaining:0});
test('mechanical capability census and immutable legacy ceilings',()=>{const i=buildInventory();assert.deepEqual(i.counts,{'TPF-04':3,'TPF-06':7,'TPF-07':12});assert.equal(i.migratedCapabilityCount,22);assert.equal(i.entries.length,45);assert.ok(i.entries.every(e=>e.activeBinding==='RETAINED_LEGACY'));assert.ok(i.entries.filter(e=>e.targetModes).every(e=>e.targetModes.every(m=>c.COORDINATOR_MODES.includes(m))));});
test('hash-locked candidates do not become effective runtime prompts',()=>{const m=g.readCandidates();assert.equal(m.families.length,3);for(const f of m.families)assert.equal(g.candidateBody(f.familyId).runtimeAuthorized,false);assert.match(g.candidateBody('TPF-21').text,/Prefix only new coordinator-proposed/);assert.doesNotMatch(g.candidateBody('TPF-05').text,/approximately 15-minute/);});
test('governance proposal validates all 22 without granting any new authority',()=>{const i=buildInventory();const proposal={familyId:'TPF-21',behaviorBrief:{familyId:'TPF-21',purpose:'Approved classroom coordinator',legitimateContext:'Mode scoped',forbiddenContext:'Protected keys',failureBehavior:'Hold',outputSemantics:'Nine field candidate',approval:'APPROVED'},bindings:i.entries.filter(e=>e.targetModes).map(e=>({capabilityId:e.capability.id,modes:e.targetModes,authorityCeiling:e.capability.authority_ceiling,owner:e.capability.authoritative_owner_boundary,active:false}))};assert.equal(g.validateMigrationProposal(proposal).migrationCount,22);const changed=copy(proposal);changed.bindings[0].authorityCeiling='T4';assert.throws(()=>g.validateMigrationProposal(changed));changed.bindings[0]=proposal.bindings[0];changed.bindings[1].active=true;assert.throws(()=>g.validateMigrationProposal(changed));});
test('chapter anchors include identity/version and cannot be curriculum IDs',()=>{const ch=chapter();c.validateChapter(ch);assert.equal(c.resolveAnchor(ref('U01.P01','1','source_element'),ch).anchor,'U01.P01');assert.throws(()=>c.resolveAnchor(ref('U01.P01','2','source_element'),ch));assert.throws(()=>c.resolveAnchor(ref('U01.P01','1','course_learning_unit'),ch));const dup=chapter();dup.units.push(copy(dup.units[0]));assert.throws(()=>c.validateChapter(dup));});
test('partial chapter continuation requires exact identity, anchors and hashes',()=>{const ch=chapter();ch.completeness='partial';ch.continuation={candidate_id:ch.id,candidate_version:ch.version,last_complete_unit:'U01',remaining_units:['U02'],preserved_hashes:{U01:'a'.repeat(64)},next_task:'Continue U02'};c.validateChapter(ch);const bad=copy(ch);bad.continuation.candidate_version='2';assert.throws(()=>c.validateChapter(bad));const bad2=copy(ch);delete bad2.continuation.preserved_hashes.U01;assert.throws(()=>c.validateChapter(bad2));assert.throws(()=>c.projectChapter(ch));});
test('plan accounts for instruction, interaction, breaks, assessment and reserve once',()=>{const plan={id:'p',version:'1',chapter_ref:ref(),objectives:[],phases:[{purpose:'Explain',source_refs:[ref('U01.P01','1','source_element')],minutes:8,kind:'instruction'},{purpose:'Wait',source_refs:[],minutes:2,kind:'interaction'}],time_ledger:{usable_minutes:12,reserve_minutes:2,accounting_basis:'Assessment already deducted'},remediation_branches:[],carry_forward:[]};c.validatePlan(plan,chapter());plan.time_ledger.usable_minutes=11;assert.throws(()=>c.validatePlan(plan,chapter()),{code:'CLASSROOM_PLAN_INFEASIBLE'});});
test('public chapter is constructed from public fields and hides operational plan metadata',()=>{const ch=chapter();const publicChapter=c.projectChapter(ch);assert.equal(publicChapter.units[0].elements[0].text,ch.units[0].elements[0].text);assert.equal(publicChapter.units[0].treatment,undefined);assert.equal(publicChapter.units[0].objective_refs,undefined);ch.private={expected_answer:'secret'};assert.throws(()=>c.projectChapter(ch));});
test('all thirty mode descriptors accept bounded missing-context artifacts',async()=>{
 for(const mode of c.COORDINATOR_MODES)assert.equal((await schemas.getModeSchema('coordinator',mode).validate(coordinator(mode))).ok,true);
 for(const mode of c.AUTHOR_MODES){const v={task_mode:mode,input_state_reference:null,status:'insufficient_context',review_required:true,review_reasons:['Missing authoritative input'],completion:{},provenance:{},artifacts:{},handoff:[]};assert.equal((await schemas.getModeSchema('author',mode).validate(v)).ok,true);v.status='ok';assert.equal((await schemas.getModeSchema('author',mode).validate(v)).ok,false);}
 for(const mode of c.PRESENTER_MODES){const v={task_mode:mode,input_state_reference:null,status:'insufficient_context',review_required:true,provenance:{},interaction:{instructional_purpose:null,portions:[],silence:false,expects_student_response:false,expected_response_kind:null,preparation_completion:'blocked',stop_reason:'missing directive'},board:[],policy:{},content_integrity:{validation_status:'not_applicable',checkable_content_generated:false},teacher_correction:{},continuity:{},uncertainties:['Missing directive'],handoff:[]};assert.equal((await schemas.getModeSchema('presenter',mode).validate(v)).ok,true);v.status='ok';assert.equal((await schemas.getModeSchema('presenter',mode).validate(v)).ok,false);}
 assert.throws(()=>schemas.getModeSchema('coordinator','invented_mode'));
});
test('all ten author modes validate complete and partial artifacts with bound plans',async()=>{
 const ch=chapter();
 const artifacts={chapter:ch,unit_map:[ref('U01','1','chapter_unit')],teaching_plan:{id:'p1',version:'1',chapter_ref:ref(),objectives:[],phases:[{purpose:'Explain',source_refs:[ref('U01.P01','1','source_element')],minutes:8,kind:'instruction'}],time_ledger:{usable_minutes:10,reserve_minutes:2,accounting_basis:'Fixture duration, not adopted policy'},remediation_branches:[],carry_forward:[]},learning_trajectory:{current_stage:'unknown',evidence_goals:[],next_stage_requirements:[]},homework_proposal:{assign:false,purpose:'No assignment needed',student_tasks:[],private:{}},preparation_update:{dependency_refs:[],required_stages:[],pending_artifacts:[]},closure_or_replan:{preserved_work:[],carry_forward:[],current_position:'U01.P01'}};
 for(const mode of c.AUTHOR_MODES){
  const v={task_mode:mode,input_state_reference:'controller1@1',status:'ok',review_required:false,review_reasons:[],completion:{},provenance:{},artifacts:{},handoff:[]};
  for(const key of schemas.REQUIRED_AUTHOR[mode]){v.completion[key]='complete';v.artifacts[key]=copy(artifacts[key]);}
  const schema=schemas.getModeSchema('author',mode,{chapter:ch});assert.equal((await schema.validate(v)).ok,true,mode);
  const partial=copy(v);partial.status='validation_needed';partial.review_required=true;partial.review_reasons=['Awaiting independent validation'];for(const key of Object.keys(partial.completion))if(key!=='chapter')partial.completion[key]='partial';assert.equal((await schema.validate(partial)).ok,true,mode);
  const blocked={...v,status:'insufficient_context',review_required:true,review_reasons:['Missing source'],completion:{},artifacts:{}};assert.equal((await schema.validate(blocked)).ok,true,mode);
  if(v.artifacts.teaching_plan){v.artifacts.teaching_plan.time_ledger.usable_minutes=0;assert.equal((await schema.validate(v)).ok,false,mode);}
 }
});
test('coordinator exactly nine fields, closed status and no implicit official outcomes',()=>{const v=coordinator('coordinate_lesson');c.validateCoordinator(v);assert.throws(()=>c.validateCoordinator({...v,extra:'hidden'}));assert.throws(()=>c.validateCoordinator({...v,status:'ok'}));v.artifacts.progress={mastery_state:'secure'};assert.throws(()=>c.validateCoordinator(v));});
test('complete routing preserves exactly one disposition per accepted message',()=>{const v=coordinator('handle_message','complete');const d={message_ref:'m1',question_or_unit_ref:'U01',reason:'Clarify the supplied term',grouping_refs:[],classification:'clarification request',disposition:'queue',response_timing:'at a suitable teaching pause',acknowledgement_status:'requested',reply_delivery_status:'not_delivered',difficulty_resolution:'unresolved',basis:'explicit fact',evidence_refs:['m1']};v.artifacts.message_dispositions=[d];c.validateCoordinator(v,{messageRefs:['m1']});assert.throws(()=>c.validateCoordinator(v,{messageRefs:['m1','m2']}));v.artifacts.message_dispositions.push(d);assert.throws(()=>c.validateCoordinator(v,{messageRefs:['m1']}));});
test('incomplete Directive cannot be constructed from action labels alone',()=>{assert.throws(()=>c.bindDirective({action:'continue'},{}));const result=c.bindDirective({action:'continue'},directive());assert.equal(result.directive.approved_action,'explain');assert.deepEqual(c.bindDirective({action:'pause'},{}),{kind:'engine_action',action:'pause',directive:null});assert.throws(()=>c.bindDirective({action:'invented'},directive()));});
test('WAIT is a permitted action; unrelated teaching cannot cross an open window',()=>{const d=directive();d.task_ref='task1';d.response_window={state:'OPEN'};assert.equal(c.bindDirective({action:'wait'},d).directive.approved_action,'wait');assert.throws(()=>c.bindDirective({action:'continue'},d));assert.equal(c.bindDirective({action:'clarify',targets:{task_ref:'task1'}},d).directive.approved_action,'explain');});
test('feedback acceptance identity cannot be substituted for another task',()=>{const d=directive();d.task_ref='task1';d.accepted_evaluation={receipt_id:'r1',task_ref:'task2',criterion_ref:'criteria1',source_version:'1',assistance_version:'1',state_reference:'controller1@1',accepted:true};assert.throws(()=>c.bindDirective({action:'clarify'},d));d.accepted_evaluation.task_ref='task1';assert.equal(c.bindDirective({action:'clarify'},d).kind,'presenter');});
test('composite states prevent assessed release, interrupted progression and closed timers',()=>{p.assertCompositeState(state());for(const patch of [{academicState:'ASSESSMENT'},{academicState:'CLASSWORK'},{lifecycle:'CLOSED'},{controllerId:null},{windowState:'OPEN'},{lifecycle:'INTERRUPTED'}])assert.throws(()=>p.assertCompositeState({...state(),...patch}));p.assertCompositeState({...state(),lifecycle:'CLOSED',deliveryState:'COMPLETED'});assert.throws(()=>p.assertCompositeState({...state(),lifecycle:'CLOSED',deliveryState:'COMPLETED',windowState:'OPEN'}));});
test('exhausted conversational balance never disables qualified Teacher response controls',()=>{const st={...state(),deliveryState:'WAITING_FOR_RESPONSE',windowState:'OPEN'};const commands=p.permittedCommands(st,{qualifiedActions:['message','task_response','task_clarification','extension','technical_report','pause']});assert.ok(commands.includes('task_response'));assert.ok(commands.includes('extension'));assert.ok(!commands.includes('message'));assert.deepEqual(p.permittedCommands(st),[]);});
test('assistance mapping preserves existing D12 limits without an invented finer inverse',()=>{assert.deepEqual(p.D11_CEILING_MAP,{NONE:'none',LIGHT:'directional',GUIDED:'partial_step',MODELED:'worked_example'});p.assertAssistance({d11Ceiling:'LIGHT',detailedCeiling:'directional',proposed:'attention'});assert.throws(()=>p.assertAssistance({d11Ceiling:'LIGHT',detailedCeiling:'full_instruction',proposed:'full_instruction'}));assert.throws(()=>p.assertAssistance({d11Ceiling:'UNKNOWN',detailedCeiling:'none',proposed:'none'}));});
test('missing numerical policy is not unlimited permission or zero',()=>{const policy={version:'fixture-policy.v1',fields:{}};assert.equal(p.capabilityReadiness(policy,'messages').ready,false);assert.ok(p.capabilityReadiness(policy,'tasks').missing.includes('taskDurations'));assert.throws(()=>p.validatePolicy({version:'1',fields:{invented:null}}));assert.throws(()=>p.validatePolicy({version:'1',fields:{conversationalAllowance:{value:0}}}));});
test('unqualified new sessions use legacy contract; existing sessions never downgrade on rollback',()=>{assert.equal(s.selectSessionContract({release:{status:'CANDIDATE'}}).engine,'LEGACY');const binding={engine:'CLASSROOM_V1',engineVersion:'fixture-engine',promptManifestHash:'hash1',schemaVersion:'1',policyVersion:'1'};assert.equal(s.selectSessionContract({existingBinding:binding}).engine,'CLASSROOM_V1');assert.deepEqual(s.rollbackDisposition(binding),{action:'pause_preserving_state',newAdmissionEnabled:false,resetTimers:false,resetAllowances:false,discardQuestions:false});});
test('model wording cannot confirm acknowledgement, delivered reply or resolved difficulty',()=>{const v=coordinator('handle_message','complete');v.artifacts.message_dispositions=[{message_ref:'m1',question_or_unit_ref:'U01',reason:'Clarify the supplied term',grouping_refs:[],classification:'clarification request',disposition:'answer',response_timing:'immediately',acknowledgement_status:'confirmed',reply_delivery_status:'delivered_confirmed',difficulty_resolution:'resolved',basis:'explicit fact',evidence_refs:['m1']}];assert.throws(()=>c.validateCoordinator(v,{messageRefs:['m1']}));assert.throws(()=>c.validateCoordinator(v,{messageRefs:['m1'],confirmedAcknowledgements:['m1'],confirmedReplies:['m1']}));c.validateCoordinator(v,{messageRefs:['m1'],confirmedAcknowledgements:['m1'],confirmedReplies:['m1'],resolvedDifficulties:['m1']});});
test('complete, partial and blocked fixtures for every coordinator mode preserve semantic lanes',()=>{
 const claim={basis:'proposal',evidence_refs:[]};const progress={...claim,current_position:'U01.P01',confirmed_delivered:[],unfinished:['U01'],waiting_state:'none',strategy_history:[],return_anchor:'U01.P01'};
 const continuity={...claim,record_or_summary:'No prior classes confirmed',source_links:[],demonstrated_evidence:[],unresolved_questions:[],unfinished_essentials:[],assistance_given:[],follow_up:{confirmed:[],proposed:[]}};
 const check={...claim,decision_question:'Can the student explain force?',target_objective:'objective1',intended_evidence_claim:'Conceptual explanation',candidate_ref:null,student_facing:{question:'How does a force change motion?'},private:{expected_solution_or_criteria:'Identify acceleration, not motion itself.',acceptable_alternatives:[]},lineage_exposure_reuse:{},task_demand:{familiarity:'fresh_equivalent',method_cueing:'none',representation_demand:'same_representation',integration_demand:'isolated_construct',retention_timing:'immediate'},permitted_assistance:'none',response_form:'explanation',response_window_requirements:{duration:null},inference_ceiling:'This explanation only; no mastery',sufficiency_condition:'Correct causal account',stopping_condition:'One bounded check',validation_status:'self-checked'};
 const interpretation={...claim,task_ref:'t1',response_ref:'r1',criterion_ref:'c1',feedback_points:[],item_validity:{findings:[],negative_attribution_protection:false},judgments:{correctness:'indeterminate',conceptual_support:'indeterminate',reasoning:'indeterminate',completeness:'indeterminate',alignment:'indeterminate',independence:'indeterminate',evidence_sufficiency:'indeterminate'},components:{supported:[],missing:[],incorrect:[],indeterminate:[]},errors:[],hypotheses:[],attempt_context:{attempts:[],self_correction:null,assistance:{},accommodations:[],contamination:null},supports:[],does_not_establish:['mastery'],next_evidence_need:'Clarify reasoning'};
 const guide={...claim,source_version:'1',covered_refs:[ref('U01.P01','1','source_element')],uncovered_refs:[],teaching_units:[{unit_ref:'U01',source_elements:['U01.P01'],passages:[{...claim,passage_ref:'U01.P01',meaning:'Force changes motion',intended_understanding:'Force causes acceleration',terms:['force'],reasoning:['Change in velocity'],representations:[],likely_confusion:[],essential:['Acceleration versus velocity'],optional_expansion:[],expand_when:'Concept remains unclear',stop_when:'Required reasoning explained',pauses:[],connections:[],interaction_or_check_refs:[]}]}]};
 const examples={prepare_guidance:{explanation_guides:guide},coordinate_lesson:{progress},handle_message:{message_dispositions:[]},design_check:{checks:[check]},interpret_response:{response_interpretation:interpretation},close_class:{continuity,progress},prepare_continuity:{continuity},guide_assessment:{assessment_guidance:{...claim,actual_coverage:[],objectives:[],evidence_needs:[],exposure_and_assistance:{},intended_independence:'unknown',constraints:[],required_handoff:'D16'}}};
 for(const mode of c.COORDINATOR_MODES){const complete=coordinator(mode,'complete');complete.artifacts=examples[mode];c.validateCoordinator(complete,{chapter:chapter()});const partial=coordinator(mode,'partial');partial.artifacts=copy(examples[mode]);c.validateCoordinator(partial,{chapter:chapter()});c.validateCoordinator(coordinator(mode));const invalid=copy(complete);invalid.task_mode='extra_mode';assert.throws(()=>c.validateCoordinator(invalid));}
});
test('raw prompt statuses never collapse generation, publication, rendering or learning',()=>{const {normalizeResult}=require('../../../teaching/classroom-remodel/result-semantics');for(const [role,statuses]of [['author',c.AUTHOR_STATUSES],['coordinator',['complete','partial','blocked']],['presenter',c.PRESENTER_STATUSES]])for(const status of statuses){const n=normalizeResult(role,status);assert.equal(n.rawStatus,status);assert.equal(n.publicationConfirmed,false);assert.equal(n.learningEstablished,false);assert.equal(n.officialOutcome,null);}assert.equal(normalizeResult('coordinator','blocked').handling,'hold');assert.equal(normalizeResult('presenter','insufficient_context').handling,'hold');});
test('complete and partial Presenter sequences for all twelve modes require authorized source and checked content',()=>{for(const mode of c.PRESENTER_MODES){const d=directive();const v={task_mode:mode,input_state_reference:'controller1@1',status:'ok',review_required:false,provenance:{},interaction:{instructional_purpose:'Explain',portions:[{id:'portion1',sequence:1,teacher_message:'Force produces acceleration: a change in velocity.',source_refs:d.presentation_span,board_refs:[],task_ref:null,boundary:'suitable_teaching_pause',publication_dependencies:[],wait_requirement:'none',resume_at:'U01.P01',expected_student_action:'none',correction_of:null}],silence:false,expects_student_response:false,expected_response_kind:'none',preparation_completion:'complete',stop_reason:'Authorized span prepared'},board:[],policy:{academic_mode:d.academic_mode,approved_action:d.approved_action,assistance_ceiling:d.assistance_ceiling},content_integrity:{validation_status:'checked',checkable_content_generated:true},teacher_correction:{},continuity:{},uncertainties:[],handoff:[]};schemas.validatePresenter(v,{directive:d,chapter:chapter()});v.interaction.preparation_completion='partial';schemas.validatePresenter(v,{directive:d,chapter:chapter()});const bad=copy(v);bad.interaction.portions[0].source_refs=[ref('U02.P01','1','source_element')];assert.throws(()=>schemas.validatePresenter(bad,{directive:d,chapter:chapter()}));const unchecked=copy(v);unchecked.content_integrity.validation_status='validation_needed';assert.throws(()=>schemas.validatePresenter(unchecked,{directive:d}));}});
test('unsupported Board operations do not silently become available',()=>{const d=directive();const v={task_mode:'board_instructional_content',input_state_reference:'controller1@1',status:'handoff_required',review_required:true,provenance:{},interaction:{instructional_purpose:'Board',portions:[],silence:false,expects_student_response:false,expected_response_kind:'none',preparation_completion:'blocked',stop_reason:'Unsupported operation'},board:[{id:'b1',operation:'restore',type:'text',content:{text:'Example'},target_ref:null,depends_on:[]}],policy:{academic_mode:d.academic_mode,approved_action:d.approved_action,assistance_ceiling:d.assistance_ceiling},content_integrity:{validation_status:'not_applicable',checkable_content_generated:false},teacher_correction:{},continuity:{},uncertainties:['Board needs supported operation'],handoff:[]};assert.throws(()=>schemas.validatePresenter(v,{directive:d}));schemas.validatePresenter(v,{directive:d,supportedBoardOperations:['restore']});});
test('task windows require delivery activation and survive projection without exposing private criteria',()=>{const d=require('../../../teaching/classroom-remodel/domain-contracts');const task={id:'t1',version:'1',session_id:'s1',source_refs:[ref('U01.P01','1','source_element')],target_ref:{kind:'course_learning_unit',id:'lu1',version:'1',anchor:null},public_question:{text:'Explain acceleration',board_refs:[],response_form:'explanation'},private:{criterion_ref:{kind:'criterion',id:'criterion1',version:'1',anchor:null},expected_solution:'A change in velocity',acceptable_alternatives:[]},evidence_intent:'practice',inference_ceiling:'One explanation only',assistance_ceiling:'none',window:{id:'w1',version:1,state:'PENDING_DELIVERY',opened_at:null,deadline_at:null,duration_ms:null,extension_count:0,class_end_at:'2026-10-09T22:00:00Z',activation_receipt_id:null},policy_version:'fixture.v1'};d.validateTask(task);assert.equal(d.projectTask(task).private,undefined);task.window.state='OPEN';assert.throws(()=>d.validateTask(task));task.window.opened_at='2026-10-09T21:59:00Z';task.window.deadline_at='2026-10-09T21:59:30Z';task.window.duration_ms=30000;task.window.activation_receipt_id='receipt1';d.validateTask(task);const projected=d.projectTask(task);assert.equal(projected.window.deadline_at,task.window.deadline_at);task.window.deadline_at='2026-10-09T22:01:00Z';assert.throws(()=>d.validateTask(task));});
test('commands require exact target and version guards; receipts cannot claim unapplied work',()=>{const d=require('../../../teaching/classroom-remodel/domain-contracts');const command={operation_id:'op1',idempotency_key:'key1',session_id:'s1',intent:'pause',target_ref:null,expected_controller_version:1,expected_delivery_version:1,expected_delivery_epoch:1,expected_control_epoch:1,schema_version:'1'};d.validateCommand(command);const stale=copy(command);delete stale.expected_control_epoch;assert.throws(()=>d.validateCommand(stale));const receipt={operation_id:'op1',idempotency_key:'key1',session_id:'s1',accepted:false,applied:true,outcome:'applied',controller_version:1,delivery_version:1,delivery_epoch:1,control_epoch:1,server_time:'2026-10-09T21:00:00Z',reconciliation_required:false};assert.throws(()=>d.validateReceipt(receipt));receipt.accepted=true;d.validateReceipt(receipt);});
