'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const c=require('../../../teaching/classroom-remodel/task-contracts');
const {taskPolicy}=require('../fixtures/classroom-task-policy');
const window=()=>({id:'window',version:1,state:'PENDING_DELIVERY',duration_ms:1000,opened_at:null,deadline_at:null,activation_receipt_id:null,class_end_at:'2026-10-10T16:00:00.000Z',extension_count:0});
test('pending task opens only on actual render receipt and retains a committed absolute deadline',()=>{const t={window:window()};assert.throws(()=>c.openWindow(t,{now:'2026-10-10T15:00:00Z',classEnd:t.window.class_end_at}),{code:'CLASSROOM_TASK_RENDER_RECEIPT_REQUIRED'});const w=c.openWindow(t,{now:'2026-10-10T15:00:00Z',classEnd:t.window.class_end_at,receiptId:'receipt'});assert.equal(w.state,'OPEN');assert.equal(w.deadline_at,'2026-10-10T15:00:01.000Z');assert.equal(w.activation_receipt_id,'receipt');});
test('insufficient fair time cancels a pending question as a system outcome rather than a wrong answer',()=>{const t={window:window()};const w=c.openWindow(t,{now:'2026-10-10T15:59:59.500Z',classEnd:t.window.class_end_at,receiptId:'receipt'});assert.equal(w.state,'CANCELLED_SYSTEM');assert.equal(w.reason,'INSUFFICIENT_FAIR_RESPONSE_TIME');assert.equal(w.opened_at,null);});
test('extensions are adopted bounded changes to the same window and never exceed Class end',()=>{const w=c.openWindow({window:window()},{now:'2026-10-10T15:00:00Z',classEnd:'2026-10-10T16:00:00Z',receiptId:'receipt'});const ext=c.extendWindow(w,taskPolicy(),{now:'2026-10-10T15:00:00.500Z',classEnd:'2026-10-10T15:00:01.200Z'});assert.equal(ext.id,w.id);assert.equal(ext.deadline_at,'2026-10-10T15:00:01.200Z');assert.throws(()=>c.extendWindow(ext,taskPolicy(),{now:'2026-10-10T15:00:00.600Z',classEnd:ext.class_end_at}),{code:'CLASSROOM_TASK_EXTENSION_EXHAUSTED'});assert.throws(()=>c.extendWindow(w,taskPolicy(),{now:w.deadline_at,classEnd:w.class_end_at}),{code:'CLASSROOM_TASK_EXTENSION_INELIGIBLE'});});
test('missing owner-adopted policy holds tasks and browser authority fields cannot enter a response',()=>{assert.throws(()=>c.policy({version:'missing',fields:{}}),{code:'CLASSROOM_TASK_POLICY_MISSING'});const s={schemaVersion:c.VERSION,sessionId:'session',operationKey:'key',taskId:'task',taskVersion:'1',windowId:'window',windowVersion:2,text:'My reasoning'};assert.equal(c.submission(s),s);assert.throws(()=>c.submission({...s,submittedAt:'2026-10-10T15:00:00Z'}),{code:'CLASSROOM_TASK_SUBMISSION_INVALID'});assert.throws(()=>c.submission({...s,charged:false}),{code:'CLASSROOM_TASK_SUBMISSION_INVALID'});});
test('extension requests reject client-owned duration and deadlines',()=>{const input={schemaVersion:c.VERSION,sessionId:'s',operationKey:'o',taskId:'t',windowId:'w',windowVersion:2};assert.equal(c.extension(input),input);for(const field of ['deadline','durationMs','charged','submittedAt'])assert.throws(()=>c.extension({...input,[field]:1}),{code:'CLASSROOM_TASK_EXTENSION_INVALID'});assert.throws(()=>c.extendWindow({...window(),state:'OPEN',deadline_at:'invalid'},taskPolicy(),{now:'invalid',classEnd:'invalid'}),{code:'CLASSROOM_TASK_EXTENSION_INELIGIBLE'});});
test('late-review policy remains held until its independent route exists',()=>{const p=taskPolicy();p.fields.lateSubmissionPolicy.value='separate_authorized_review';assert.throws(()=>c.policy(p),{code:'CLASSROOM_TASK_LATE_REVIEW_ROUTE_HELD'});});
const f=require('../fixtures/classroom-remodel-academic'),tf=require('../fixtures/classroom-tasks');
function designed(){const p=tf.proposal();return c.check(p,{chapter:f.chapter(),targetRef:{kind:'course_learning_unit',id:'lu1',version:'1',anchor:null},validation:tf.validation(p),policy:taskPolicy(),sessionId:'s',classEnd:window().class_end_at,taskId:'t',windowId:'w',criterionId:'criterion'}).task;}
test('task design requires explicitly authorized evidence intent and independent validation',()=>{const p=tf.proposal(),args={chapter:f.chapter(),targetRef:{kind:'course_learning_unit',id:'lu1',version:'1',anchor:null},validation:tf.validation(p),policy:taskPolicy(),sessionId:'s',classEnd:window().class_end_at,taskId:'t',windowId:'w',criterionId:'criterion'};assert.equal(c.check(p,args).task.evidence_intent,'practice');assert.throws(()=>c.check(p,{...args,validation:{...args.validation,evidenceIntent:undefined}}),{code:'CLASSROOM_TASK_EVIDENCE_INTENT_NOT_AUTHORIZED'});assert.throws(()=>c.check(p,{...args,validation:{...args.validation,independent:false}}),{code:'CLASSROOM_TASK_INDEPENDENT_VALIDATION_REQUIRED'});});
test('canonical evaluation projects into D12 without discarding findings or upgrading independence',()=>{const task=designed(),output=tf.interpretation(task,'r');const result=c.interpretation(output,{task,responseId:'r',demand:tf.proposal().artifacts.checks[0].task_demand,stateReference:'fixture@1',exposure:{answer_or_method_exposed:true,uncertain_exposure:true,released_assistance_level:'none'}});assert.equal(result.evaluation.response_assessment.final_result_correctness,'correct');assert.equal(result.evaluation.response_assessment.evidence_sufficiency,'contaminated');assert.equal(result.evaluation.assistance_and_independence.independence_interpretation,'contaminated');assert.deepEqual(result.evaluation.canonical_interpretation,output.artifacts.response_interpretation);assert.equal(result.officialOutcome,false);});
test('incorrect work on an item needing protection cannot supply unrestricted negative evidence',()=>{const task=designed(),output=tf.interpretation(task,'r');output.artifacts.response_interpretation.item_validity.negative_attribution_protection=true;output.artifacts.response_interpretation.judgments.correctness='incorrect';output.artifacts.response_interpretation.judgments.evidence_sufficiency='supported';const result=c.interpretation(output,{task,responseId:'r',demand:tf.proposal().artifacts.checks[0].task_demand,stateReference:'fixture@1',exposure:{}});assert.equal(result.evaluation.item_validity.evidence_use_limit,'do_not_use_negative_evidence');assert.equal(result.evaluation.response_assessment.evidence_sufficiency,'insufficient');});
test('interpretation must refer to the exact admitted response and private criterion version',()=>{const task=designed(),args={task,responseId:'r',demand:tf.proposal().artifacts.checks[0].task_demand,stateReference:'fixture@1',exposure:{}};const output=tf.interpretation(task,'other');assert.throws(()=>c.interpretation(output,args),{code:'CLASSROOM_TASK_INTERPRETATION_TARGET_MISMATCH'});});
