'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
async function client(t,api,onChange=()=>{}){const {createSessionClient}=await import('../../../public/classroom/session-client.js');global.document={visibilityState:'visible'};const c=createSessionClient({api,transport:async()=>{},classId:'class',onChange});t.after(()=>c.close());await c.start();return c;}
const snap=(extra={})=>({schema_version:'classroom-domain.v1',wire_schema_version:'classroom-presentation-wire.v1',class_id:'class',session_id:'session',controller_version:1,delivery_version:1,delivery_epoch:1,control_epoch:0,cursor:0,chapter_ref:{id:'chapter',version:'1'},permitted_actions:['claim'],conversation:[],transport:{clientRenewalMs:60000,reconnectBackoffMs:10},...extra});
test('unknown mutation outcome retries exactly the same committed operation identity',async t=>{let calls=[],failed=true;const c=await client(t,async(path,opts)=>{if(path.endsWith('session'))return snap();calls.push(opts.body);if(failed){failed=false;throw Error('network');}return {leaseToken:'owned'};});await assert.rejects(()=>c.lease());await c.lease();assert.deepEqual(calls[0],calls[1]);assert.ok(c.hasLease);});
test('unsupported controls do not reach the backend; schema/session mismatch is rejected',async t=>{let requests=0;const c=await client(t,async()=>{requests++;return snap();});await assert.rejects(()=>c.control('resume'),/UNAVAILABLE/);assert.equal(requests,1);});
test('history/delta overlap deduplicates by sequence but conflicting committed content is rejected',async t=>{let last;const c=await client(t,async()=>snap(),v=>last=v);const event={id:'event',sequence:1,text:'Teacher'};c.delta({session_id:'session',from_cursor:0,to_cursor:1,events:[event]});c.delta({session_id:'session',from_cursor:0,to_cursor:1,events:[event]});assert.equal(last.events.length,1);assert.throws(()=>c.delta({session_id:'session',from_cursor:0,to_cursor:1,events:[{...event,text:'different'}]}),/CONFLICT/);assert.throws(()=>c.delta({session_id:'session',from_cursor:1,to_cursor:3,events:[]}),/INCOMPLETE/);});
test('protected snapshot clears prior content and active-client credential without inventing progress',async t=>{let current=snap(),last;const c=await client(t,async()=>current,v=>last=v);c.delta({session_id:'session',from_cursor:0,to_cursor:1,events:[{sequence:1,text:'Private after takeover'}]});current=snap({delivery_version:2,chapter_ref:null});await c.refresh();assert.equal(last.events.length,0);assert.equal(c.hasLease,false);});

test('a committed takeover clears the old tab credential and exposes the real takeover control',async t=>{let current=snap();const c=await client(t,async(path)=>path.endsWith('session')?current:{leaseToken:'owned',controlEpoch:0});await c.lease();assert.equal(c.hasLease,true);current=snap({delivery_version:3,control_epoch:2,permitted_actions:['takeover']});await c.refresh();assert.equal(c.hasLease,false);});

test('closing clears the academic cache and prevents later refresh or control requests',async t=>{let requests=0;const c=await client(t,async()=>{requests++;return snap();});c.close();assert.equal(c.snapshot,null);await c.refresh();await assert.rejects(()=>c.control('pause'),/READ_ONLY/);assert.equal(requests,1);});

test('a new authoritative session replaces the old event cache even when its version starts lower',async t=>{let current=snap({delivery_version:5}),last;const c=await client(t,async()=>current,v=>last=v);c.delta({session_id:'session',from_cursor:0,to_cursor:1,events:[{sequence:1,text:'Old teaching'}]});current=snap({session_id:'replacement',delivery_version:1});await c.refresh();assert.equal(c.snapshot.session_id,'replacement');assert.equal(last.events.length,0);});
