'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {validateIdentityOutput,validateInteractionOutput}=require('../../../teaching/d22/intelligence');
const {SAFE_PROFILE_LIBRARY,buildStyleEnvelope}=require('../../../teaching/d22/contracts');
const env=buildStyleEnvelope({teacherIdentityRef:'t1',coreTraits:SAFE_PROFILE_LIBRARY.BALANCED,familiarityLevel:'new'});
function good(){return {prompt_family:'TPF-18',prompt_version:'1.0',task_mode:'GENERATE_IDENTITY_CANDIDATE',status:'CANDIDATE_READY',teacher_identity_candidate:{teacher_identity_ref:'t1',style_envelope:env,presentation_metadata:{display_name:'Teacher Rowan',avatar_ref:null,voice_ref:null,gender_presentation:null},preference_fit:'NOT_APPLICABLE',influence_trace:[]},transition:{approved_request_ref:null,previous_teacher_identity_ref:null,new_teacher_identity_ref:null,academic_state_continuity:'NOT_APPLICABLE',student_message:null},compatibility_checks:{matches_tpf08_style_envelope:true,subject_stereotype_used:false,sensitive_attribute_used:false,academic_rule_dependency_detected:false,cartoon_extremity_detected:false,false_human_biography_detected:false,familiarity_inferred_without_authority:false,presentation_metadata_policy_violation:false},handoff:{required:false,owner:null,reason:null}};}
test('TPF-18 candidate must pass every frozen compatibility check',()=>{assert.equal(validateIdentityOutput(good(),{expectedRef:'t1'}).ok,true);const bad=good();bad.compatibility_checks.subject_stereotype_used=true;assert.equal(validateIdentityOutput(bad,{expectedRef:'t1'}).ok,false);});
test('TPF-18 candidate exact style envelope is mandatory',()=>{const bad=good();bad.teacher_identity_candidate.style_envelope={...env,subject:'physics'};assert.equal(validateIdentityOutput(bad,{expectedRef:'t1'}).ok,false);});
test('TPF-08 presentation output cannot smuggle marks or progression',()=>{assert.equal(validateInteractionOutput({status:'ok',interaction:{text:'Hello'}}).ok,true);assert.equal(validateInteractionOutput({status:'ok',interaction:{official_grade:'A'}}).ok,false);assert.equal(validateInteractionOutput({status:'ok',handoff:{progression_outcome:'PASS'}}).ok,false);});
