'use strict';
const fs=require('node:fs');const path=require('node:path');const test=require('node:test');const assert=require('node:assert/strict');
const {D24_TASK_IDS,assertD24TaskAccounting}=require('../../../teaching/d24/task-accounting');
const {VIEWPORT_COMPOSITIONS,ASSESSMENT_SEMANTICS,VISUAL_STATE_COVERAGE,AUTHORITY_BOUNDARIES,publicAccommodationSummary}=require('../../../teaching/d24/contracts');

test('D24 accounts for its exact frozen task scope',()=>{assert.equal(assertD24TaskAccounting(),true);assert.equal(D24_TASK_IDS.length,35);assert.equal(D24_TASK_IDS[0],'TCH-0504');assert.equal(D24_TASK_IDS[17],'TCH-0521');assert.equal(D24_TASK_IDS[18],'TCH-0582');assert.equal(D24_TASK_IDS.at(-1),'TCH-0598');});
test('D24 recomposes Classroom by viewport instead of shrinking desktop',()=>{assert.deepEqual(Object.keys(VIEWPORT_COMPOSITIONS),['desktop','tablet','mobile']);assert.equal(VIEWPORT_COMPOSITIONS.desktop.classroomZones,3);assert.equal(VIEWPORT_COMPOSITIONS.tablet.classroomZones,2);assert.equal(VIEWPORT_COMPOSITIONS.mobile.classroomZones,1);});
test('assessment semantics include every frozen non-visual state',()=>{for(const key of ['class-mode','question-position','marks-available','authoritative-timer','response-state','save-state','navigation-state','significant-warning'])assert.ok(ASSESSMENT_SEMANTICS.includes(key));});
test('visual coverage spans canonical desktop and mobile states without gamification',()=>{assert.equal(VISUAL_STATE_COVERAGE.length,14);for(const key of ['course-plan','classroom-break','assessment-constructed','results-record-gpa','remediation-resit-recovery','mobile-today','mobile-classroom','mobile-assessment'])assert.ok(VISUAL_STATE_COVERAGE.includes(key));});
test('accommodation summary never exposes marks or a stigmatizing label',()=>{const summary=publicAccommodationSummary({accommodation_policy:{extra_time_percent:25,breaks_allowed:true,standard_unchanged:true}});assert.deepEqual(summary,{timerAdjusted:true,accessSettingsApplied:true,standardUnchanged:true});assert.equal(Object.keys(summary).some(key=>/mark|disab|special|diagnos/i.test(key)),false);});
test('D24 preserves prior academic owners and server timer authority',()=>{assert.equal(AUTHORITY_BOUNDARIES.informationArchitecture,'D23');assert.equal(AUTHORITY_BOUNDARIES.timer,'D17_SERVER');assert.equal(AUTHORITY_BOUNDARIES.marks,'D20');assert.equal(AUTHORITY_BOUNDARIES.progression,'D21');assert.equal(AUTHORITY_BOUNDARIES.accommodationApproval,'EXTERNAL_AUTHORITY_UNRESOLVED_NOT_D24');});
test('Teaching drawers and mobile Classroom tabs remain fully keyboard operable',()=>{const source=fs.readFileSync(path.resolve(__dirname,'../../../public/teaching-d24.js'),'utf8');for(const marker of ['trapDrawerFocus','setAttribute(\'inert\'','removeAttribute(\'inert\'','aria-modal','control.dataset.menu !== \'true\'','handleClassroomTabs','.tc-mobile-tabs [role="tab"]'])assert.ok(source.includes(marker),marker);});
