'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {
  packageStartReadiness,timerProjection,protectedFailureMessage,syncProjection,SYNC_STATE,SYSTEM_FAILURE_KIND,
}=require('../../../teaching/d25/contracts');
const {createD25ReliabilityService}=require('../../../teaching/d25/service');
function goodPackage(){return {assessment_package_id:'p1',assessment_id:'a1',package_state:'LOCKED',locked_at:'2026-10-03T20:00:00Z',package_hash:'hash',locked_by:'D17_DETERMINISTIC_PACKAGE_OWNER',duration_minutes:45,validation_summary:{whole_package_validation:'v-whole',item_validations:[{candidate_version_id:'cv1',outcome:'PASS'},{candidate_version_id:'cv2',outcome:'PASS'}]}};}
function goodItems(){return [{package_item_id:'i1',candidate_version_id:'cv1',item_state:'ACTIVE',answer_exposed:false},{package_item_id:'i2',candidate_version_id:'cv2',item_state:'ACTIVE',answer_exposed:false}];}
function foundation(overrides={}){
  const classContext={controller:{lifecycleState:'ACTIVE',instructionalSubstate:'INSTRUCTION',stateVersion:4,resumeInstructionalSubstate:null}};
  const attempt={assessment_attempt_id:'at1',assessment_id:'a1',assessment_package_id:'p1',attempt_state:'ACTIVE',active_device_id:'device-a',expires_at:'2026-10-03T21:00:00Z',state_version:3,finalization_version:0,started_at:'2026-10-03T20:00:00Z'};
  const f={d11:{repository:{},service:{getClass:async()=>classContext,transition:async(_u,_c,input)=>({controller:{...classContext.controller,instructionalSubstate:input.toState,lifecycleState:input.toState==='INTERRUPTED'?'INTERRUPTED':'ACTIVE',stateVersion:5,resumeInstructionalSubstate:input.toState==='INTERRUPTED'?'INSTRUCTION':null}})}},d14:{service:{snapshot:async()=>({modeKey:'INSTRUCTION',controller:classContext.controller,interruption:null}),signal:async()=>({interactionId:'ix1',kind:'TECHNICAL_ISSUE'})}},d16:{service:{getAssignment:async()=>({assignmentId:'w1',submission:{kind:'DRAFT',version:2}})}},d17:{repository:{packageById:async()=>goodPackage(),packageItems:async()=>goodItems(),requireAttempt:async()=>attempt,latestResponses:async()=>[],candidateVersion:async()=>null},service:{startAttempt:async(_u,_a,input)=>({attempt:{...attempt,active_device_id:input.deviceId}}),saveResponse:async(_u,_at,input)=>({response:{idempotency_key:input.idempotencyKey,response_version:1}}),submit:async(_u,_at,input)=>({attempt:{...attempt,attempt_state:'SUBMITTED'},key:input.idempotencyKey}),transferDevice:async(_u,_at,input)=>({attempt:{...attempt,active_device_id:input.deviceId},key:input.idempotencyKey})}}};
  return Object.assign(f,overrides);
}
test('TCH-0531 package gate requires locked hash + whole package + every item PASS',()=>{assert.equal(packageStartReadiness(goodPackage(),goodItems()).ready,true);const broken=goodPackage();broken.validation_summary={whole_package_validation:null,item_validations:[{candidate_version_id:'cv1',outcome:'PASS'}]};const result=packageStartReadiness(broken,goodItems());assert.equal(result.ready,false);assert.ok(result.reasons.includes('WHOLE_PACKAGE_VALIDATION_MISSING'));assert.ok(result.reasons.some((r)=>r.startsWith('ITEM_VALIDATION_NOT_PASS:i2')));});
test('TCH-0527 assessment timer remains server-owned and continues offline',()=>{const value=timerProjection({expiresAt:'2026-10-03T21:00:00Z',serverNow:'2026-10-03T20:55:00Z',connected:false});assert.equal(value.remainingMs,300000);assert.equal(value.timerAuthority,'SERVER');assert.equal(value.pausesOffline,false);assert.match(value.studentMessage,/continues/i);});
test('TCH-0525/0526 local recovery is visibly non-authoritative until acknowledged',()=>{const local=syncProjection({connected:false,localDraft:true,serverAcknowledgedVersion:3});assert.equal(local.state,SYNC_STATE.LOCAL_RECOVERY_ONLY);assert.equal(local.official,false);const saved=syncProjection({connected:true,localDraft:false,serverAcknowledgedVersion:4});assert.equal(saved.state,SYNC_STATE.SERVER_ACKNOWLEDGED);assert.equal(saved.official,true);});
test('TCH-0524/0536 system-failure copy explicitly protects academic consequences',()=>{const copy=protectedFailureMessage(SYSTEM_FAILURE_KIND.NETWORK);assert.match(copy,/academic record is protected/i);assert.match(copy,/absence/);assert.match(copy,/late submission/);assert.match(copy,/wrong answer/);assert.match(copy,/mark/);});
test('TCH-0522 active Class restoration uses D11/D14 server state, never browser truth',async()=>{const service=createD25ReliabilityService({foundation:foundation()});const restored=await service.restoreClass({id:'u1'},'c1');assert.equal(restored.reliability.sourceOfTruth,'D11_D14_SERVER');assert.equal(restored.reliability.browserStateAuthoritative,false);assert.equal(restored.reliability.recoveredFromAuthoritativeSession,true);});
test('TCH-0524 protected interruption commits through D11 owner and is idempotent when already interrupted',async()=>{let transitions=0;const f=foundation();const original=f.d11.service.transition;f.d11.service.transition=async(...args)=>{transitions++;return original(...args);};const service=createD25ReliabilityService({foundation:f});const value=await service.protectClassInterruption({id:'u1'},'c1',{failureKind:SYSTEM_FAILURE_KIND.SERVICE,idempotencyKey:'failure-1'});assert.equal(value.protected,true);assert.equal(value.academicPenaltyAllowed,false);assert.equal(transitions,1);f.d11.service.getClass=async()=>({controller:{lifecycleState:'INTERRUPTED',instructionalSubstate:'INTERRUPTED',stateVersion:5,resumeInstructionalSubstate:'INSTRUCTION'}});const again=await service.protectClassInterruption({id:'u1'},'c1',{failureKind:SYSTEM_FAILURE_KIND.SERVICE,idempotencyKey:'failure-1'});assert.equal(again.idempotent,true);assert.equal(transitions,1);});
test('TCH-0531 start attempt fails closed before D17 owner sees broken package',async()=>{let starts=0;const f=foundation();f.d17.repository.packageById=async()=>({...goodPackage(),package_hash:null});f.d17.service.startAttempt=async()=>{starts++;return {};};const service=createD25ReliabilityService({foundation:f});await assert.rejects(service.startAssessmentAttempt({id:'u1'},'a1',{packageId:'p1',deviceId:'d'}),(e)=>e.code==='TEACHING_D25_PACKAGE_START_BLOCKED');assert.equal(starts,0);});
test('TCH-0532 final submission keeps one logical idempotency key across retry',async()=>{let seen=null;const f=foundation();f.d17.service.submit=async(_u,_a,input)=>{seen=input.idempotencyKey;return {ok:true};};const service=createD25ReliabilityService({foundation:f});await service.submitAssessmentAttempt({id:'u1'},'at1',{confirm:true,idempotencyKey:'logical-submit-1'});assert.equal(seen,'logical-submit-1');});
test('TCH-0533 device transfer is a no-op when the requested device already owns the active Attempt',async()=>{let transfers=0;const f=foundation();f.d17.service.transferDevice=async()=>{transfers++;return {};};const service=createD25ReliabilityService({foundation:f});const value=await service.transferAssessmentDevice({id:'u1'},'at1',{deviceId:'device-a'});assert.equal(value.idempotent,true);assert.equal(value.transferred,false);assert.equal(transfers,0);});
test('TCH-0534 assignment recovery exposes server draft as authoritative and local draft as editing-only',async()=>{const service=createD25ReliabilityService({foundation:foundation()});const value=await service.restoreAssignment({id:'u1'},'w1');assert.equal(value.recovery.sourceOfTruth,'D16_WORK');assert.equal(value.recovery.authoritativeDraftVersion,2);assert.equal(value.recovery.browserRecoveryDraftAuthoritative,false);});
test('TCH-0535 owner retry reuses the same idempotency key and only retries transient failure',async()=>{const calls=[];const service=createD25ReliabilityService({foundation:foundation(),sleep:async()=>{}});const result=await service.retryOwnerOperation({operationName:'request-application',idempotencyKey:'req-apply-7',execute:async({idempotencyKey,attempt})=>{calls.push([idempotencyKey,attempt]);if(attempt===1){const e=new Error('temporary');e.status=503;throw e;}return {applied:true};}});assert.deepEqual(calls,[['req-apply-7',1],['req-apply-7',2]]);assert.equal(result.recovered,true);let badCalls=0;await assert.rejects(service.retryOwnerOperation({operationName:'schedule',idempotencyKey:'sched-1',execute:async()=>{badCalls++;const e=new Error('stale');e.status=409;throw e;}}));assert.equal(badCalls,1);});
test('TCH-0529/0530 teacher timeout uses bounded simpler fallback without direct provider call',async()=>{const service=createD25ReliabilityService({foundation:foundation(),sleep:async()=>{}});let fallback=0;const value=await service.runTeacherOperationWithRecovery({user:{id:'u1'},classId:'c1',idempotencyKey:'teacher-turn-1',execute:async()=>{const e=new Error('timeout');e.code='TEACHING_AI_TIMEOUT';throw e;},simplerFallback:async()=>{fallback++;return {kind:'TEXT_EXPLANATION'};}});assert.equal(value.state,'SIMPLER_REPRESENTATION');assert.equal(value.directProviderCall,false);assert.equal(fallback,1);});
test('TCH-0529/0530 repeated transient AI/resource outage becomes protected Class interruption',async()=>{const f=foundation();let transitions=0;const original=f.d11.service.transition;f.d11.service.transition=async(...args)=>{transitions++;return original(...args);};const service=createD25ReliabilityService({foundation:f,sleep:async()=>{}});const value=await service.runTeacherOperationWithRecovery({user:{id:'u1'},classId:'c1',idempotencyKey:'teacher-turn-2',execute:async()=>{const e=new Error('provider down');e.status=503;throw e;},simplerFallback:async()=>{const e=new Error('resource down');e.status=503;throw e;}});assert.equal(value.state,'PROTECTED_INTERRUPTION');assert.equal(value.systemProtected,true);assert.equal(transitions,1);});
test('D25 status claims no D26 Recovery Case ownership',()=>{const service=createD25ReliabilityService({foundation:foundation()});const s=service.status();assert.equal(s.d26RecoveryCaseOwnershipClaimed,false);assert.equal(s.centralAiOrchestratorOwnsModelRetryAndFallback,true);});
