'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const contracts=require('../../../teaching/d25/contracts');
const {createD25ReliabilityService}=require('../../../teaching/d25/service');
function mockFoundation(){
  const official={classState:'INSTRUCTION',attendance:null,mark:null,evidence:[],scheduleVersion:4,requestApplications:0,gradeVersions:0};
  const packageRow={assessment_package_id:'p',assessment_id:'a',package_state:'LOCKED',locked_at:'2026-10-03T20:00:00Z',package_hash:'h',locked_by:'D17_DETERMINISTIC_PACKAGE_OWNER',duration_minutes:60,validation_summary:{whole_package_validation:'whole',item_validations:[{candidate_version_id:'cv',outcome:'PASS'}]}};
  const attempt={assessment_attempt_id:'at',assessment_id:'a',assessment_package_id:'p',attempt_state:'ACTIVE',active_device_id:'dev',expires_at:'2026-10-03T22:00:00Z',state_version:1,finalization_version:0,started_at:'2026-10-03T21:00:00Z'};
  let finalizations=0;
  const foundation={d11:{repository:{},service:{getClass:async()=>({controller:{lifecycleState:'ACTIVE',instructionalSubstate:official.classState,stateVersion:1,resumeInstructionalSubstate:null}}),transition:async(_u,_c,input)=>{official.classState=input.toState;return {controller:{lifecycleState:input.toState==='INTERRUPTED'?'INTERRUPTED':'ACTIVE',instructionalSubstate:input.toState,stateVersion:2,resumeInstructionalSubstate:'INSTRUCTION'}};}}},d14:{service:{snapshot:async()=>({modeKey:official.classState,controller:{stateVersion:1},interruption:null}),signal:async()=>({kind:'TECHNICAL_ISSUE'})}},d16:{service:{getAssignment:async()=>({assignmentId:'w',submission:{kind:'DRAFT',version:7,response:{text:'server draft'}}})}},d17:{repository:{packageById:async()=>packageRow,packageItems:async()=>[{package_item_id:'i',candidate_version_id:'cv',item_state:'ACTIVE',answer_exposed:false}],requireAttempt:async()=>attempt,latestResponses:async()=>[{package_item_id:'i',response_version:4,renderer_payload:{text:'server answer'}}],candidateVersion:async()=>null},service:{startAttempt:async()=>({attempt}),saveResponse:async()=>({response:{response_version:5}}),submit:async()=>{finalizations++;return {attempt:{...attempt,attempt_state:'SUBMITTED'}};},transferDevice:async()=>({attempt})}}};
  return {foundation,official,getFinalizations:()=>finalizations};
}
test('TCH-0537 chaos: class network loss does not invent attendance, marks, evidence or schedule changes',async()=>{const {foundation,official}=mockFoundation();const service=createD25ReliabilityService({foundation});await service.restoreClass({id:'u'},'c');assert.equal(official.classState,'INSTRUCTION');assert.equal(official.attendance,null);assert.equal(official.mark,null);assert.deepEqual(official.evidence,[]);assert.equal(official.scheduleVersion,4);});
test('TCH-0537 chaos: break/assessment timer projection never becomes browser authority during disconnect',()=>{const projected=contracts.timerProjection({expiresAt:'2026-10-03T22:00:00Z',serverNow:'2026-10-03T21:10:00Z',connected:false});assert.equal(projected.timerAuthority,'SERVER');assert.equal(projected.pausesOffline,false);assert.equal(projected.remainingMs,50*60*1000);});
test('TCH-0537 chaos: assignment/browser draft recovery cannot become official work by itself',async()=>{const {foundation}=mockFoundation();const service=createD25ReliabilityService({foundation});const restored=await service.restoreAssignment({id:'u'},'w');assert.equal(restored.recovery.browserRecoveryDraftAuthoritative,false);assert.equal(restored.recovery.authoritativeDraftVersion,7);});
test('TCH-0537/0538 duplicate final-submit transport relies on stable owner idempotency rather than fabricated second result',async()=>{const {foundation}=mockFoundation();const seen=new Set();let committed=0;foundation.d17.service.submit=async(_u,_a,input)=>{if(!seen.has(input.idempotencyKey)){seen.add(input.idempotencyKey);committed++;}return {committed};};const service=createD25ReliabilityService({foundation});await service.submitAssessmentAttempt({id:'u'},'at',{confirm:true,idempotencyKey:'final-at'});await service.submitAssessmentAttempt({id:'u'},'at',{confirm:true,idempotencyKey:'final-at'});assert.equal(committed,1);});
test('TCH-0538 duplicate owner mutation after transport timeout is reconciled without replaying side effect',async()=>{const {foundation}=mockFoundation();const service=createD25ReliabilityService({foundation,sleep:async()=>{}});let mutations=0;const value=await service.retryOwnerOperation({operationName:'request-apply',idempotencyKey:'request-9',execute:async()=>{mutations++;const e=new Error('reply lost after commit');e.status=503;throw e;},revalidate:async()=>({applied:true,value:{applicationRef:'app-1'}})});assert.equal(mutations,1);assert.equal(value.alreadyApplied,true);assert.equal(value.value.applicationRef,'app-1');});
test('TCH-0539 partial AI outage preserves official state and routes to protected interruption',async()=>{const {foundation,official}=mockFoundation();const service=createD25ReliabilityService({foundation,sleep:async()=>{}});const before={mark:official.mark,attendance:official.attendance,evidence:[...official.evidence]};const value=await service.runTeacherOperationWithRecovery({user:{id:'u'},classId:'c',idempotencyKey:'ai-fail',execute:async()=>{const e=new Error('AI offline');e.status=503;throw e;}});assert.equal(value.state,'PROTECTED_INTERRUPTION');assert.equal(official.classState,'INTERRUPTED');assert.equal(official.mark,before.mark);assert.equal(official.attendance,before.attendance);assert.deepEqual(official.evidence,before.evidence);});
test('TCH-0534/0536 static regression: D25 browser layer is local-only and explicit about protected consequences',()=>{const source=fs.readFileSync(path.resolve(__dirname,'../../../public/teaching-d25-reliability.js'),'utf8');assert.match(source,/localRecoveryOnly:true/);assert.match(source,/authoritative:false/);assert.match(source,/not be treated as an absence, late submission, wrong answer, or mark/);assert.match(source,/Restore local draft/);assert.match(source,/authoritative server state/);});
