'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {estimateWorkload,coordinate,rankRecoverySlots}=require('../../../teaching/d26/scheduler');
const {safeNotification,shouldDeliver}=require('../../../teaching/d26/notifications');
const {recoveryTransition}=require('../../../teaching/d26/contracts');
const {assertD26TaskAccounting}=require('../../../teaching/d26/task-accounting');
function item(id,courseId,minutes,start='2026-10-05T08:00:00.000Z',kind='CLASS'){return {id,courseId,kind,startsAt:start,endsAt:new Date(Date.parse(start)+minutes*60000).toISOString(),minutes,hardDeadline:kind!=='REVISION',priority:kind==='ASSESSMENT'?100:50,source:{owner:kind==='HOMEWORK'?'D16_WORK':kind==='ASSESSMENT'?'D17_ASSESSMENT':'D09_SCHEDULER',entityType:kind,entityId:id,version:'1'}};}
test('D26 accounts for exactly 27 canonical tasks',()=>assert.equal(assertD26TaskAccounting().taskCount,27));
for(const count of [2,4,8])test(`global scheduler detects overlap across ${count} courses`,()=>{const items=Array.from({length:count},(_,i)=>item(`i${i}`,`c${i}`,120));const result=coordinate(items,{dailyCapacityMinutes:Math.max(120,count*90)});assert.equal(result.estimate.days[0].totalMinutes,count*120);assert.equal(result.requiresChoice,true);assert.equal(result.perCourseTruthMutated,false);assert.equal(result.conflicts[0].silentOverbooking,false);});
test('workload includes class, homework, assessment, recovery and deadline kinds',()=>{const kinds=['CLASS','HOMEWORK','ASSESSMENT','RECOVERY','DEADLINE'];const result=estimateWorkload(kinds.map((kind,i)=>item(String(i),'c',20,'2026-10-05T08:00:00.000Z',kind)));assert.deepEqual(Object.keys(result.days[0].byKind).sort(),kinds.sort());});
test('weekend recovery is absent by default and always needs Scheduler approval',()=>{const rows=rankRecoverySlots([{startsAt:'2026-10-10T09:00:00Z',priority:10},{startsAt:'2026-10-12T09:00:00Z',priority:1}]);assert.equal(rows.length,1);assert.equal(rows[0].schedulerApprovalRequired,true);});
test('notification links to authoritative UI and is never evidence',()=>{const n=safeNotification({kind:'ASSIGNMENT_DEADLINE',studentId:'s',courseId:'c',title:'Work due',body:'Open Work for current details.',dueAt:'2026-10-05T08:00:00Z',source:{owner:'D16_WORK',entityType:'Assignment',entityId:'a1',version:'2'}});assert.equal(n.deepLink,'/teaching/work/view?focus=a1');assert.equal(n.deliveryIsAcademicEvidence,false);assert.equal(n.attendanceConsequenceAllowed,false);});
test('notification dedupes, suppresses stale and suppresses non-actionable risk',()=>{const candidate={kind:'COURSE_RISK_ACTIONABLE',studentId:'s',courseId:'c',title:'Review course',body:'Open Course for current details.',dueAt:'2026-10-05T08:00:00Z',actionable:false,source:{owner:'D21_PROGRESSION',entityType:'Course',entityId:'c',version:'4'}};assert.equal(shouldDeliver({candidate}).reason,'RISK_NOT_ACTIONABLE');assert.equal(shouldDeliver({candidate:{...candidate,actionable:true},sourceStillCurrent:false}).reason,'SOURCE_SUPERSEDED');});
test('Recovery Case transition graph rejects shortcuts',()=>{assert.equal(recoveryTransition('DETECTED','CLASSIFIED'),true);assert.throws(()=>recoveryTransition('DETECTED','RESOLVED'),/cannot transition/);});
