'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {createD26Service}=require('../../../teaching/d26/service');
function service(overrides={}){const calls=[];const repository={listWorkload:async()=>[],lastNotificationDelivery:async()=>null,recordNotificationDelivery:async x=>(calls.push(x),x),upsertReviewNeed:async x=>x,createRecoveryCase:async x=>x,getRecoveryCase:async()=>({state:'DETECTED',version:1}),transitionRecoveryCase:async x=>x,supportSnapshot:async()=>({dueEvents:[]}),...overrides.repository};const due=[];return {calls,due,service:createD26Service({repository,notificationInterface:{send:async x=>({id:'n1',x})},dueEventStore:{enqueue:async x=>(due.push(x),x)},randomUUID:(()=>{let i=0;return()=>`id-${++i}`;})(),clock:()=>new Date('2026-10-04T10:00:00Z'),...overrides})};}
test('Review Needs retain source reference and do not claim mastery mutation',async()=>{const x=service();const result=await x.service.upsertReviewNeed({id:'s'},{courseId:'c',learningUnitId:'lu',misconceptionKey:'fractions',severity:'HIGH',selfReport:true,source:{owner:'D13_SKM',entityType:'Evidence',entityId:'e',version:'1'}});assert.equal(result.source.owner,'D13_SKM');assert.equal(x.service.status().reviewNeedsDoNotMutateMastery,true);});
test('Recovery Case requires source references and is idempotency keyed',async()=>{const x=service();const result=await x.service.createRecoveryCase({id:'s'},{courseId:'c',idempotencyKey:'case-1',classification:'MISSED_CLASS',cause:'APPROVED_ABSENCE',policyAtEvent:'p1',nextAction:'Choose repair',sources:[{owner:'D15_ATTENDANCE',entityType:'Attendance',entityId:'a',version:'2'}]});assert.equal(result.idempotencyKey,'case-1');assert.equal(result.sources[0].owner,'D15_ATTENDANCE');});
test('durable notification uses due-event runtime and source version key',async()=>{const x=service();await x.service.enqueueNotification({id:'s'},{kind:'CLASS_START',courseId:'c',title:'Class starting',body:'Open Class for current details.',dueAt:'2026-10-05T08:00:00Z',source:{owner:'D09_SCHEDULER',entityType:'Class',entityId:'cl',version:'7'}});assert.equal(x.due.length,1);assert.equal(x.due[0].eventType,'teaching.notification.delivery_due');assert.match(x.due[0].idempotencyKey,/cl:7$/);});
test('support inspection is authorization gated and read-only',async()=>{const x=service();await assert.rejects(()=>x.service.supportInspection({id:'x'},{studentId:'s'}),e=>e.code==='TEACHING_D26_SUPPORT_FORBIDDEN');const result=await x.service.supportInspection({id:'a',is_admin:true},{studentId:'s'});assert.equal(result.readOnly,true);assert.equal(result.casualAcademicEditAllowed,false);});
test('status freezes D26 authority boundaries',()=>{const status=service().service.status();assert.equal(status.globalSchedulerCoordinatesOnly,true);assert.equal(status.recoveryCasesReferenceTruth,true);assert.equal(status.automaticWeekendClass,false);});
