'use strict';
const test=require('node:test'); const assert=require('node:assert/strict');
const d30=require('../../../teaching/d30');

test('D30 exact task census is 46',()=>{assert.equal(d30.D30_TASK_IDS.length,46);assert.equal(new Set(d30.D30_TASK_IDS).size,46);assert.ok(d30.D30_TASK_IDS.includes('TCH-0920'));});
test('Phase-16 corpus meets exact historical floor plus TPF-20 amendment',()=>{assert.equal(d30.ISOLATED_FAMILY_CORPUS.length,1832);assert.equal(d30.CROSS_FAMILY_CORPUS.length,72);assert.equal(d30.TPF20_CORPUS.length,96);assert.equal(d30.FULL_CORPUS.length,2000);assert.equal(new Set(d30.FULL_CORPUS.map(x=>x.id)).size,2000);});
test('corpus spans adversarial, uncertainty, counterfactual and cross-subject cases',()=>{const c=new Set(d30.ISOLATED_FAMILY_CORPUS.map(x=>x.caseClass));for(const x of ['negative','counterfactual','uncertainty','injection','authority_attack'])assert.ok(c.has(x));assert.equal(new Set(d30.ISOLATED_FAMILY_CORPUS.map(x=>x.subject)).size,8);});
test('TPF-20 corpus covers all required scenario classes and three stages',()=>{assert.equal(new Set(d30.TPF20_CORPUS.map(x=>x.caseClass)).size,16);assert.deepEqual([...new Set(d30.TPF20_CORPUS.map(x=>x.runKind))].sort(),['tpf20_end_to_end','tpf20_preclass','tpf20_reconciliation']);});
test('route qualification fails closed on missing evidence',()=>{const s=d30.summarizeRoute([],{requiredCaseIds:['a']});assert.equal(s.decision,'BLOCKED');assert.deepEqual(s.missingCaseIds,['a']);});
test('P0/P1 cannot be averaged away',()=>{const base={runId:'r',caseId:'a',familyId:'TPF-01',routeId:'primary',modelId:'model',promptVersion:'1',validation:{schemaValid:true,invariantsValid:true}};const records=[{...base,runId:'r1',defects:[{severity:'P1'}]},{...base,runId:'r2'}];assert.equal(d30.summarizeRoute(records,{requiredCaseIds:['a'],minStabilityRuns:2}).decision,'BLOCKED');});
test('C4 requires independent human academic review',()=>{const b={caseId:'a',familyId:'TPF-15',routeId:'p',modelId:'m',promptVersion:'1',validation:{schemaValid:true,invariantsValid:true}};const rs=[{...b,runId:'1'},{...b,runId:'2'}];assert.equal(d30.summarizeRoute(rs,{criticality:'C4',requiredCaseIds:['a']}).decision,'BLOCKED');assert.equal(d30.summarizeRoute(rs,{criticality:'C4',requiredCaseIds:['a'],humanReviews:[{independent:true,decision:'PASS'}]}).decision,'QUALIFIED');});
test('fallback must have independent evidence',()=>{assert.throws(()=>d30.assertIndependentFallback({evidenceCount:2},{evidenceCount:0}),/inherit/);});
test('D31 production authorization cannot be pulled forward',()=>{const r=d30.buildProductionQualificationReport([{routeId:'x',decision:'QUALIFIED'}]);assert.equal(r.productionQualified,true);assert.equal(r.productionAuthorized,false);assert.equal(r.authorizationGate,'D31');});
test('progressive preparation is reduced without material value',()=>{assert.equal(d30.comparePreparationProfiles({qualityScore:.9,seriousDefectRate:.01,costUsd:1,latencyMs:100},{qualityScore:.9,seriousDefectRate:.01,costUsd:1.2,latencyMs:120}).recommendation,'REDUCE_PREPARATION_PROFILE');});
test('prompt governance blocks provider/model text and hidden CoT demands',()=>{const r=d30.auditPromptArtifact({familyId:'TPF-01',behaviorBriefApproved:true,familyVersion:'1',constitutionVersion:'1',capabilityContractVersions:['1'],schemaVersion:'1',evaluationSuiteVersion:'1',providerModelText:true,hiddenCotDemand:true});assert.equal(r.pass,false);assert.ok(r.findings.includes('provider_model_assignment_inside_prompt'));assert.ok(r.findings.includes('hidden_chain_of_thought_demand'));});
test('authoring freeze requires brief, evaluation and defect closure',()=>{assert.throws(()=>d30.transitionAuthoringState('BEHAVIOR_BRIEF_APPROVED','FROZEN_VERSION',{behaviorBriefApproved:true,evaluationPassed:false}));assert.equal(d30.transitionAuthoringState('CANDIDATE_APPROVED','FROZEN_VERSION',{behaviorBriefApproved:true,evaluationPassed:true}),'FROZEN_VERSION');});
test('hidden chain-of-thought is rejected from provenance',()=>{assert.throws(()=>d30.assertNoHiddenChainOfThought({scratchpad:'secret'}),/chain-of-thought/);});
