'use strict';

const {getCapability}=require('../capability-registry');
const {normalizeAssignmentSpec,subjectEvaluationProfile}=require('./contracts');

function ownerFor(id){return getCapability(id).authoritative_owner_boundary;}
function forbidden(value,path=''){
  if(Array.isArray(value)){for(let i=0;i<value.length;i+=1){const hit=forbidden(value[i],`${path}[${i}]`);if(hit)return hit;}return null;}
  if(!value||typeof value!=='object')return null;
  const denied=new Set(['official_mark','official_grade','gradebook_write','progression_outcome','misconduct_verdict','guilt_probability','cheating_probability','permanent_student_label','mastery_state','skm_state']);
  for(const [k,v] of Object.entries(value)){const here=path?`${path}.${k}`:k;if(denied.has(k))return here;const hit=forbidden(v,here);if(hit)return hit;}return null;
}
function schema(id,fields,validate){return Object.freeze({id,version:'1',uncertainty_states:Object.freeze(['INSUFFICIENT_EVIDENCE','UNRESOLVED_CONFLICT','REVIEW_NEEDED']),review_needed_field:'review_required',declared_fields:Object.freeze(fields),validate});}
function genericValidator(output){
  if(!output||typeof output!=='object'||Array.isArray(output))return {ok:false,reason:'TEACHING_D16_AI_OUTPUT_INVALID'};
  const hit=forbidden(output);if(hit)return {ok:false,reason:'TEACHING_D16_AI_AUTHORITY_EXCEEDED',details:{field:hit}};
  return {ok:true,value:output};
}
function baseRequest({capabilityId,taskMode,studentId,aggregateType,aggregateId,stateVersion,academicInput,outputSchema,provenanceRefs=[],requestKey,declaredAuthorityLevel='T2'}){
  const capability=getCapability(capabilityId);
  return {
    trigger:{type:'workflow_continuation',ref:`${aggregateType.toLowerCase()}:${aggregateId}:${taskMode}`,source:'teaching.d16',actor_id:studentId},
    capabilityId,declaredAuthorityLevel,idempotencyKey:String(requestKey),correlationId:String(requestKey),
    stateReference:{aggregate_type:aggregateType,aggregate_id:String(aggregateId),state_version:String(stateVersion??'0')},
    preconditions:{policy_at_event_required:true,formal_assessment_owner_preserved:true,official_gradebook_write_allowed:false},
    provenanceRefs,resultContract:{output_schema_id:outputSchema.id,output_schema_version:outputSchema.version,validator_ids:['schema','domain','provenance','current-state']},taskMode,
    directive:{bounded_actions:['produce only the requested provisional Homework/independent-work analysis from supplied authoritative context'],allowed_operations:['return schema-valid provisional output inside the capability authority ceiling'],prohibited_operations:['write Gradebook truth','assign SKM state directly','declare misconduct or guilt','create a permanent student label','change a locked formal Assessment attempt','select provider or model','bypass Assignment assistance policy'],evidence_purpose:taskMode,downstream_handoff:{type:'validated_candidate',validator_ids:['schema','domain','provenance','current-state'],commit_owner_boundary:ownerFor(capabilityId)}},
    contextSpec:{authoritative_refs:provenanceRefs.map((ref)=>({ref})),provenance_refs:[],untrusted_refs:[],context_kind:'d16_work',access_purpose:taskMode},
    outputSchema,academicInput,schemaValidator:outputSchema.validate,domainValidator:outputSchema.validate,provenanceValidator:async()=>({ok:true}),commit:false,capabilityPromptFamily:capability.prompt_family_id,
  };
}
function assignmentGenerationRequest({studentId,classId,classStateVersion,academicInput,requestKey}){
  const validate=async(out)=>{const base=genericValidator(out);if(!base.ok)return base;if(out.assign===false)return {ok:true,value:out};try{return {ok:true,value:{...out,assignment:normalizeAssignmentSpec(out.assignment||{})}};}catch(error){return {ok:false,reason:error.code||'TEACHING_D16_HOMEWORK_PROPOSAL_INVALID',message:error.message};}};
  return baseRequest({capabilityId:'teaching.scheduling.purposeful_homework_selection_generation',taskMode:'purposeful_homework_selection_generation',studentId,aggregateType:'CLASS',aggregateId:classId,stateVersion:classStateVersion,academicInput,outputSchema:schema('d16.homework-proposal',['status','review_required','assign','reasons','assignment','unresolved_items'],validate),provenanceRefs:academicInput.provenance_refs||[],requestKey,declaredAuthorityLevel:'T3'});
}
function workloadRequest({studentId,aggregateId,stateVersion,academicInput,requestKey}){return baseRequest({capabilityId:'teaching.scheduling.homework_workload_estimation',taskMode:'homework_workload_estimation',studentId,aggregateType:'WORKLOAD',aggregateId,stateVersion,academicInput,outputSchema:schema('d16.workload-estimate',['status','review_required','estimated_effort_range','risk_flags','unresolved_items'],genericValidator),provenanceRefs:academicInput.provenance_refs||[],requestKey,declaredAuthorityLevel:'T2'});}
function assistanceRequest({studentId,assignmentId,stateVersion,academicInput,requestKey}){return baseRequest({capabilityId:'teaching.scheduling.homework_assistance_policy_interpretation',taskMode:'homework_assistance_policy_interpretation',studentId,aggregateType:'ASSIGNMENT',aggregateId:assignmentId,stateVersion,academicInput,outputSchema:schema('d16.assistance-response',['status','review_required','response','disclosure_level','source_refs','unresolved_items'],genericValidator),provenanceRefs:academicInput.provenance_refs||[],requestKey,declaredAuthorityLevel:'T2'});}
function evaluationRequest({studentId,assignmentId,stateVersion,academicInput,responseKind,requestKey}){const profile=subjectEvaluationProfile(responseKind);const validate=async(out)=>{const base=genericValidator(out);if(!base.ok)return base;if(!Array.isArray(out.criterion_results))return {ok:false,reason:'TEACHING_D16_CRITERION_RESULTS_REQUIRED'};return {ok:true,value:{...out,evaluation_profile:profile}};};return baseRequest({capabilityId:'teaching.scheduling.homework_independent_work_evaluation',taskMode:'homework_independent_work_evaluation',studentId,aggregateType:'ASSIGNMENT',aggregateId:assignmentId,stateVersion,academicInput:{...academicInput,evaluation_profile:profile,official_gradebook_write_allowed:false},outputSchema:schema('d16.homework-evaluation',['status','review_required','criterion_results','feedback','learning_evidence','unresolved_items'],validate),provenanceRefs:academicInput.provenance_refs||[],requestKey,declaredAuthorityLevel:'T4'});}
function verificationTaskRequest({studentId,assignmentId,stateVersion,academicInput,requestKey}){return baseRequest({capabilityId:'teaching.scheduling.long_form_authenticity_verification_task_generation',taskMode:'targeted_controlled_verification_generation',studentId,aggregateType:'ASSIGNMENT',aggregateId:assignmentId,stateVersion,academicInput,outputSchema:schema('d16.integrity-verification-task',['status','review_required','verification_task','target_capability','allowed_resources','unresolved_items'],genericValidator),provenanceRefs:academicInput.provenance_refs||[],requestKey,declaredAuthorityLevel:'T3'});}
function similarityRequest({studentId,assignmentId,stateVersion,academicInput,requestKey}){return baseRequest({capabilityId:'teaching.scheduling.similarity_plagiarism_interpretation',taskMode:'similarity_plagiarism_interpretation',studentId,aggregateType:'ASSIGNMENT',aggregateId:assignmentId,stateVersion,academicInput,outputSchema:schema('d16.similarity-interpretation',['status','review_required','contextual_observations','rule_alignment_evidence','verification_recommended','unresolved_items'],genericValidator),provenanceRefs:academicInput.provenance_refs||[],requestKey,declaredAuthorityLevel:'T2'});}
function nextLessonRequest({studentId,assignmentId,stateVersion,academicInput,requestKey}){return baseRequest({capabilityId:'teaching.scheduling.homework_to_next_lesson_synthesis',taskMode:'homework_to_next_lesson_synthesis',studentId,aggregateType:'ASSIGNMENT',aggregateId:assignmentId,stateVersion,academicInput,outputSchema:schema('d16.next-lesson-synthesis',['status','review_required','learning_unit_signals','repair_priorities','practice_adjustments','unresolved_items'],genericValidator),provenanceRefs:academicInput.provenance_refs||[],requestKey,declaredAuthorityLevel:'T2'});}
function createD16Intelligence({orchestrator}={}){if(!orchestrator||typeof orchestrator.execute!=='function')throw new TypeError('D16 intelligence requires the Teaching Orchestrator.');return Object.freeze({generateHomework:(args)=>orchestrator.execute(assignmentGenerationRequest(args)),estimateWorkload:(args)=>orchestrator.execute(workloadRequest(args)),interpretAssistance:(args)=>orchestrator.execute(assistanceRequest(args)),evaluateHomework:(args)=>orchestrator.execute(evaluationRequest(args)),generateVerificationTask:(args)=>orchestrator.execute(verificationTaskRequest(args)),interpretSimilarity:(args)=>orchestrator.execute(similarityRequest(args)),synthesizeForNextLesson:(args)=>orchestrator.execute(nextLessonRequest(args))});}
module.exports={genericValidator,baseRequest,assignmentGenerationRequest,workloadRequest,assistanceRequest,evaluationRequest,verificationTaskRequest,similarityRequest,nextLessonRequest,createD16Intelligence};