'use strict';
const crypto = require('node:crypto');
const { getTeachingDecision } = require('../policy');

const SOURCE_CLASSES = Object.freeze(Object.keys(getTeachingDecision('TCH-0691').decision.classes));
const SOURCE_KINDS = Object.freeze(['PRIMARY_KIWI_SUBJECT','PRIMARY_STUDY_NOTE','KIWI_SUBJECT_FLASHCARDS','STUDENT_SUPPLEMENT','AUTHORITATIVE_SCHOOL_SCOPE','AI_SUPPLEMENTATION']);
const MAX_INTAKE_BYTES = 16_384;
const MAX_SIGNAL_ITEMS = 50;
function failure(message, code='TEACHING_D07_CONTRACT_INVALID'){const e=new Error(message);e.code=code;throw e;}
function text(value, field, max=2000, required=true){if(value==null&&!required)return null;const v=String(value||'').trim();if(required&&!v)failure(`${field} is required.`);if(Buffer.byteLength(v)>max)failure(`${field} exceeds ${max} bytes.`);return v||null;}
function array(value, field, max=MAX_SIGNAL_ITEMS){if(value==null)return Object.freeze([]);if(!Array.isArray(value)||value.length>max)failure(`${field} must contain at most ${max} items.`);return Object.freeze(value.map((v,i)=>text(v,`${field}[${i}]`,500)));}
function stable(value){if(Array.isArray(value))return value.map(stable);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().map(k=>[k,stable(value[k])]));return value;}
function digest(value){return crypto.createHash('sha256').update(JSON.stringify(stable(value))).digest('hex');}
function normalizeIntake(input={}){
 if(!input||typeof input!=='object'||Array.isArray(input))failure('Intake must be an object.');
 const original=text(input.originalFreeFormText,'originalFreeFormText',MAX_INTAKE_BYTES,false);
 return Object.freeze({originalFreeFormText:original,learningPreferences:array(input.learningPreferences,'learningPreferences'),difficultAreas:array(input.difficultAreas,'difficultAreas'),priorExperience:array(input.priorExperience,'priorExperience'),knownStrengths:array(input.knownStrengths,'knownStrengths'),goals:array(input.goals,'goals'),importantDeadlines:array(input.importantDeadlines,'importantDeadlines')});
}
function normalizeMaterial(value,index,field='supplementaryMaterials'){if(!value||typeof value!=='object'||Array.isArray(value))failure(`${field}[${index}] must be an object.`);const kind=text(value.sourceKind,`${field}[${index}].sourceKind`,100);const allowed=field==='originalMaterials'?['PRIMARY_STUDY_NOTE']:['STUDENT_SUPPLEMENT','AUTHORITATIVE_SCHOOL_SCOPE'];if(!allowed.includes(kind))failure(`${field}[${index}] has an invalid source role.`);return Object.freeze({sourceKind:kind,sourceRef:text(value.sourceRef,`${field}[${index}].sourceRef`,500),versionRef:text(value.versionRef,`${field}[${index}].versionRef`,200,false),content:text(value.content,`${field}[${index}].content`,65536),locator:value.locator&&typeof value.locator==='object'&&!Array.isArray(value.locator)?Object.freeze({...value.locator}):Object.freeze({})});}
function buildSourceInventory({corpus,originalMaterials=[],supplementaryMaterials=[],subjectMaterialRole=null}={}){
 if(!corpus||typeof corpus!=='object'||!corpus.subject)failure('Authoritative Subject corpus is required.','TEACHING_D07_SUBJECT_CORPUS_REQUIRED');
 const subject=corpus.subject; const items=[];
 const add=(sourceKind,sourceRef,versionRef,content,locator)=>{const normalized=text(content,'source content',65536);items.push(Object.freeze({sourceKind,sourceRef:text(sourceRef,'sourceRef',500),sourceVersionRef:versionRef==null?null:String(versionRef),locator:Object.freeze(locator||{}),content:normalized,contentHash:digest({sourceKind,sourceRef,versionRef,content:normalized,locator})}));};
 const hasOriginal=originalMaterials.length>0||subjectMaterialRole==='SUPPLEMENTAL_FLASHCARD';
 for(const deck of corpus.decks||[]){add(hasOriginal?'KIWI_SUBJECT_FLASHCARDS':'PRIMARY_KIWI_SUBJECT',`subject:${subject.id}:deck:${deck.id}`,deck.updated_at||deck.created_at||subject.updated_at||subject.created_at,deck.name,{subject_id:String(subject.id),deck_id:String(deck.id),element:'deck_heading',material_role:hasOriginal?'SUPPLEMENTAL_FLASHCARD':'SUBJECT_BASELINE'});}
 for(const card of corpus.cards||[]){const deckId=String(card.deck_id||'');add(hasOriginal?'KIWI_SUBJECT_FLASHCARDS':'PRIMARY_KIWI_SUBJECT',`subject:${subject.id}:deck:${deckId}:card:${card.id}`,card.updated_at||card.created_at||subject.updated_at||subject.created_at,`${card.front_content||''}\n\n${card.back_content||''}`,{subject_id:String(subject.id),deck_id:deckId,card_id:String(card.id),element:'learning_card',material_role:hasOriginal?'SUPPLEMENTAL_FLASHCARD':'SUBJECT_BASELINE'});}
 for(const [i,item] of originalMaterials.map((value,index)=>normalizeMaterial(value,index,'originalMaterials')).entries())add(item.sourceKind,item.sourceRef,item.versionRef,item.content,{...item.locator,submitted_index:i,material_role:'PRIMARY_ORIGINAL_NOTE'});
 for(const [i,item] of supplementaryMaterials.map((value,index)=>normalizeMaterial(value,index,'supplementaryMaterials')).entries())add(item.sourceKind,item.sourceRef,item.versionRef,item.content,{...item.locator,submitted_index:i,material_role:'SUPPLEMENTAL_MATERIAL'});
 if(!items.length)failure('Subject corpus has no auditable academic content.','TEACHING_D07_SUBJECT_CORPUS_EMPTY');
 const keys=new Set();for(const item of items){const key=`${item.sourceKind}|${item.sourceRef}|${item.contentHash}`;if(keys.has(key))failure(`Duplicate source item: ${item.sourceRef}`);keys.add(key);}
 return Object.freeze({subjectRef:String(subject.id),snapshotDigest:digest(items),items:Object.freeze(items)});
}
function normalizeIntakeExtraction(output,intakeId){if(!output||typeof output!=='object'||Array.isArray(output))return {ok:false,reason:'INTAKE_EXTRACTION_SCHEMA_INVALID'};try{const candidate={interaction_preferences:array(output.interaction_preferences,'interaction_preferences'),academic_self_report:Object.freeze({strengths:array(output.academic_self_report?.strengths,'academic_self_report.strengths'),weaknesses:array(output.academic_self_report?.weaknesses,'academic_self_report.weaknesses'),prior_exposure:array(output.academic_self_report?.prior_exposure,'academic_self_report.prior_exposure')}),goals:array(output.goals,'goals'),deadlines:array(output.deadlines,'deadlines'),planning_hypotheses:array(output.planning_hypotheses,'planning_hypotheses'),diagnostic_targets:array(output.diagnostic_targets,'diagnostic_targets'),uncertainty:Array.isArray(output.uncertainty)?Object.freeze(output.uncertainty.map((x,i)=>Object.freeze({signal:text(x?.signal,`uncertainty[${i}].signal`,500),reason:text(x?.reason,`uncertainty[${i}].reason`,1000),confidence:Number.isFinite(x?.confidence)&&x.confidence>=0&&x.confidence<=1?x.confidence:null}))):Object.freeze([]),provenance:Object.freeze({intake_id:text(output.provenance?.intake_id||intakeId,'provenance.intake_id',200),source:'STUDENT_SELF_REPORT',evidence_status:'NON_EVIDENCE_PLANNING_HYPOTHESIS'})};return {ok:true,value:Object.freeze(candidate)};}catch(e){return {ok:false,reason:e.code||'INTAKE_EXTRACTION_SCHEMA_INVALID'};}}
function validateCurriculumAuditSchema(output){if(!output||typeof output!=='object'||Array.isArray(output))return {ok:false,reason:'CURRICULUM_AUDIT_SCHEMA_INVALID'};for(const key of ['topics','learning_units','dependencies','source_accounting','assumed_prerequisites','likely_misconceptions'])if(!Array.isArray(output[key]))return {ok:false,reason:`CURRICULUM_AUDIT_${key.toUpperCase()}_REQUIRED`};return {ok:true,value:output};}
function validateCurriculumAuditDomain(output,{sourceItems=[]}={}){try{
 const topics=new Map();for(const [i,t] of output.topics.entries()){const id=text(t.id,`topics[${i}].id`,200);if(topics.has(id))failure(`Duplicate topic ${id}`);topics.set(id,t);if(!Array.isArray(t.subtopics))failure(`topics[${i}].subtopics must be an array.`);const sub=new Set();for(const s of t.subtopics){const sid=text(s.id,'subtopic.id',200);if(sub.has(sid))failure(`Duplicate subtopic ${sid}`);sub.add(sid);}}
 const units=new Map();for(const [i,u] of output.learning_units.entries()){const id=text(u.id,`learning_units[${i}].id`,200);if(units.has(id))failure(`Duplicate learning unit ${id}`);if(!topics.has(text(u.topic_id,`learning_units[${i}].topic_id`,200)))failure(`Learning unit ${id} has unknown topic.`);text(u.intended_competence,`learning_units[${i}].intended_competence`,4000);if(!Array.isArray(u.exit_conditions)||!u.exit_conditions.length)failure(`Learning unit ${id} has empty exit conditions.`);u.exit_conditions.forEach((x,j)=>text(x,`learning_units[${i}].exit_conditions[${j}]`,2000));if(!['LOW','MEDIUM','HIGH','FOUNDATIONAL'].includes(String(u.criticality)))failure(`Learning unit ${id} has invalid criticality.`);if(!Number.isInteger(u.instructional_load_min_minutes)||!Number.isInteger(u.instructional_load_max_minutes)||u.instructional_load_min_minutes<0||u.instructional_load_max_minutes<u.instructional_load_min_minutes)failure(`Learning unit ${id} has invalid instructional load.`);units.set(id,u);}
 if(!units.size)failure('Curriculum Audit contains no Learning Units.');const edges=new Map([...units.keys()].map(k=>[k,[]]));for(const d of output.dependencies){const from=text(d.learning_unit_id,'dependency.learning_unit_id',200),to=text(d.prerequisite_learning_unit_id,'dependency.prerequisite_learning_unit_id',200);if(!units.has(from)||!units.has(to)||from===to)failure('Invalid Learning Unit dependency.');edges.get(from).push(to);}const visiting=new Set(),done=new Set();function walk(n){if(visiting.has(n))failure('Curriculum dependency graph contains a cycle.','TEACHING_D07_CURRICULUM_CYCLE');if(done.has(n))return;visiting.add(n);for(const x of edges.get(n))walk(x);visiting.delete(n);done.add(n);}for(const n of units.keys())walk(n);
 const expected=new Map(sourceItems.map(x=>[x.sourceRef,x]));const seen=new Set();for(const [i,a] of output.source_accounting.entries()){const ref=text(a.source_ref,`source_accounting[${i}].source_ref`,500);if(!expected.has(ref)||seen.has(ref))failure(`Unknown or duplicate source accounting item ${ref}.`);seen.add(ref);if(!SOURCE_CLASSES.includes(a.classification))failure(`Invalid source classification for ${ref}.`);if(a.classification==='ACADEMICALLY_MEANINGFUL'){if(!Array.isArray(a.learning_unit_ids)||!a.learning_unit_ids.length||a.learning_unit_ids.some(id=>!units.has(String(id))))failure(`Meaningful source ${ref} is not mapped.`);}else{text(a.reason,`source_accounting[${i}].reason`,2000);if(a.classification==='DUPLICATE'&&!expected.has(String(a.canonical_source_ref)))failure(`Duplicate source ${ref} lacks valid canonical source.`);}}
 if(seen.size!==expected.size){const missing=[...expected.keys()].filter(x=>!seen.has(x));failure(`Curriculum Audit omitted source items: ${missing.join(', ')}`,'TEACHING_D07_SOURCE_ITEM_OMITTED');}
 return {ok:true,value:Object.freeze(output)};
 }catch(e){return {ok:false,reason:e.code||e.message};}}
function selectDiagnosticRequirement({dependencies=[],intakeSignals={},existingEvidence=[]}={}){const targets=new Set();for(const d of dependencies)if(d.material!==false)targets.add(String(d.prerequisite_ref||d.prerequisite_learning_unit_id||'').trim());for(const x of [...(intakeSignals.diagnostic_targets||[]),...(intakeSignals.academic_self_report?.prior_exposure||[]),...(intakeSignals.academic_self_report?.weaknesses||[])])if(String(x).trim())targets.add(String(x).trim());for(const e of existingEvidence)if(e.secure===true)targets.delete(String(e.target_ref));const values=[...targets].filter(Boolean);return Object.freeze({required:values.length>0,reason:values.length?'MATERIAL_PRIOR_KNOWLEDGE_UNCERTAINTY':'NO_MATERIAL_UNCERTAINTY',targets:Object.freeze(values),nonGraded:true});}
function evaluateValidatedPriorKnowledge(input={}){const policy=getTeachingDecision('TCH-0692');const evidence=Array.isArray(input.evidence)?input.evidence:[];const independent=evidence.filter(e=>e&&e.independent===true&&e.passed===true&&String(e.evidenceRef||'').trim()&&String(e.probeRef||'').trim());const probes=new Set(independent.map(e=>String(e.probeRef)));const critical=Array.isArray(input.criticalCriteria)?input.criticalCriteria:[];const passedCriteria=new Set(independent.flatMap(e=>Array.isArray(e.criteriaPassed)?e.criteriaPassed.map(String):[]));const variedOk=input.constructSupportsVariation===false||independent.some(e=>e.variedOrUncued===true);const noConflict=input.unresolvedMaterialContradiction!==true;const verified=independent.length>=policy.decision.minimum_independent_verification_opportunities&&probes.size>=2&&critical.every(c=>passedCriteria.has(String(c)))&&variedOk&&noConflict;return Object.freeze({status:verified?'VALIDATED_PRIOR_KNOWLEDGE':'NOT_VALIDATED',instructionalCompletionBasis:verified?'VALIDATED_PRIOR_KNOWLEDGE':null,assessmentEligible:verified,evidenceRefs:Object.freeze(independent.map(e=>String(e.evidenceRef))),probeRefs:Object.freeze([...probes]),policyVersion:policy.policy_version,validatorId:text(input.validatorId,'validatorId',200),validatorVersion:text(input.validatorVersion,'validatorVersion',100),provenanceRefs:Object.freeze(array(input.provenanceRefs,'provenanceRefs')),reasons:Object.freeze([...(independent.length<2?['INSUFFICIENT_INDEPENDENT_OPPORTUNITIES']:[]),...(probes.size<2?['DISTINCT_PROBES_REQUIRED']:[]),...(!critical.every(c=>passedCriteria.has(String(c)))?['CRITICAL_CRITERIA_NOT_ALL_PASSED']:[]),...(!variedOk?['VARIED_OR_UNCUED_EVIDENCE_REQUIRED']:[]),...(!noConflict?['UNRESOLVED_MATERIAL_CONTRADICTION']:[])])});}
module.exports={SOURCE_CLASSES,SOURCE_KINDS,MAX_INTAKE_BYTES,normalizeIntake,buildSourceInventory,normalizeIntakeExtraction,validateCurriculumAuditSchema,validateCurriculumAuditDomain,selectDiagnosticRequirement,evaluateValidatedPriorKnowledge,digest};
