'use strict';
const {normalizeIntake,buildSourceInventory,selectDiagnosticRequirement,evaluateValidatedPriorKnowledge,digest}=require('./contracts');
const {validateSupplementaryMaterialInput}=require('../d28/security');
function createD07Service({subjects,repository,intelligence=null,outboxStore=null,randomUUID=null,clock=()=>new Date()}={}){
 if(!subjects||typeof subjects.getForUser!=='function'||typeof subjects.getCorpusForUser!=='function')throw new TypeError('D07 service requires the authenticated KIWI Subject corpus interface.');
 if(!repository)throw new TypeError('D07 service requires its D04-backed repository.');
 const held=()=>{const e=new Error('Course preparation is temporarily unavailable.');e.status=503;e.code='TEACHING_ROUTE_UNQUALIFIED';throw e;};
 const queueUnavailable=()=>{const e=new Error('Background analysis is temporarily unavailable.');e.status=503;e.code='TEACHING_BACKGROUND_ANALYSIS_UNAVAILABLE';throw e;};
 async function createCourse(user,input={}){const subjectId=String(input.subjectId||'').trim();if(!subjectId){const e=new Error('subjectId is required.');e.status=400;throw e;}const subject=await subjects.getForUser(user.id,subjectId);if(!subject){const e=new Error('Subject not found.');e.status=404;e.code='TEACHING_SUBJECT_NOT_FOUND';throw e;}const corpus=await subjects.getCorpusForUser(user.id,subjectId);const originalMaterials=(input.originalMaterials||[]).map((material)=>validateSupplementaryMaterialInput({...material,sourceKind:'PRIMARY_STUDY_NOTE'}));const supplementaryMaterials=(input.supplementaryMaterials||[]).map((material)=>validateSupplementaryMaterialInput(material));const inventory=buildSourceInventory({corpus,originalMaterials,supplementaryMaterials});const title=String(input.title||subject.name||'Untitled Course').trim();const existing=typeof repository.findMatchingDraft==='function'?await repository.findMatchingDraft({studentId:user.id,subjectId,title}):null;if(existing){const e=new Error('A Draft Course already exists for this KIWI Subject. Open the existing Course instead of creating a duplicate.');e.status=409;e.code='TEACHING_D07_DUPLICATE_DRAFT';e.courseId=existing.course_id;throw e;}const course=await repository.createDraft({studentId:user.id,subject,title,inventory});if(input.intake&&typeof input.intake==='object')await submitIntake(user,course.course_id,input.intake);return course;}
 const listCourses=user=>repository.listCourses(user.id);
 const getSetup=(user,id)=>repository.getSetup(user.id,id);
 async function submitIntake(user,courseId,input){const intake=await repository.saveIntake({studentId:user.id,courseId,intake:normalizeIntake(input)});if(!intelligence)return {intake,extraction:null,extractionStatus:'ROUTE_HELD_UNTIL_D30'};const setup=await repository.getSetup(user.id,courseId);const result=await intelligence.extractIntake({course:setup.course,intake});if(!result.accepted)return {intake,extraction:null,extractionStatus:'REJECTED'};const output=result.validatedResult.output;const extraction=await repository.saveExtraction({studentId:user.id,intakeId:intake.intake_id,capabilityId:'teaching.curriculum.intake_signal_extraction',contractVersion:'d07.intake-extraction.v1',signals:{interaction_preferences:output.interaction_preferences,academic_self_report:output.academic_self_report,goals:output.goals,deadlines:output.deadlines,planning_hypotheses:output.planning_hypotheses,diagnostic_targets:output.diagnostic_targets,evidence_status:'NON_EVIDENCE_PLANNING_HYPOTHESIS'},uncertainty:output.uncertainty,provenance:output.provenance});const changed=[];
    if(output.diagnostic_targets.length) changed.push(`Targeted diagnostic attention added for ${output.diagnostic_targets.join(', ')}.`);
    if(output.interaction_preferences.length) changed.push('Your interaction preferences will shape explanation and representation choices.');
    if(output.planning_hypotheses.length) changed.push('Reported academic concerns were retained as planning hypotheses for later verification.');
    return {intake,extraction,extractionStatus:'VALIDATED',planningExplanation:changed.join(' ')||'Your Intake was preserved without changing academic scope or standards.'};}
 async function editPreferences(user,courseId,input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).some(k=>!['explanation_pace','example_first','feedback_style','explanation_length'].includes(k))){const e=new Error('Only minor interaction preferences may be edited here; academic scope changes require Course Plan review.');e.status=400;e.code='TEACHING_D07_MATERIAL_SCOPE_CHANGE_REQUIRES_PLAN_REVIEW';throw e;}return repository.updateInteractionPreferences({studentId:user.id,courseId,preferences:input});}
 async function runAudit(user,courseId){if(!intelligence)held();const setup=await repository.getSetup(user.id,courseId);const result=await intelligence.runCurriculumAudit({course:setup.course,sources:setup.sources});if(!result.accepted){const e=new Error('Curriculum Audit was rejected by validation.');e.status=422;e.code='TEACHING_D07_CURRICULUM_AUDIT_REJECTED';throw e;}const output=result.validatedResult.output;return repository.saveAudit({studentId:user.id,courseId,subjectSnapshotRef:setup.course.subject_snapshot_ref,inventoryDigest:digest(setup.sources.map(s=>[s.source_ref,s.content_hash])),output,provenanceRefs:setup.sources.map(s=>`source:${s.source_content_item_id}`),validationMetadata:{schema:'d07.curriculum-audit.v1',domain_validated:true,source_census:setup.sources.length}});}
 async function queueAudit(user,courseId){if(!intelligence)held();if(!outboxStore||typeof outboxStore.append!=='function'||typeof randomUUID!=='function')queueUnavailable();const setup=await repository.getSetup(user.id,courseId);const now=clock().toISOString();const eventId=randomUUID();const queued=await outboxStore.append({eventId,schemaVersion:1,eventType:'teaching.curriculum.audit_requested',eventCategory:'operational_recovery_event',triggerType:'background_analysis',source:'teaching.d07',origin:'teaching.course_setup',actorId:String(user.id),aggregateType:'teaching_course',aggregateId:String(courseId),aggregateVersion:Number(setup.course.state_version),occurredAt:now,correlationId:eventId,causationId:null,idempotencyKey:`d07:curriculum-audit:${courseId}:${setup.course.state_version}`,payload:{course_id:String(courseId),expected_state_version:String(setup.course.state_version)},auditRefs:[],provenanceRefs:(setup.sources||[]).map(s=>`source:${s.source_content_item_id}`)});return {accepted:true,background:true,jobId:queued.event.event_id,status:queued.event.status};}
 async function planDiagnostic(user,courseId,input={}){const setup=await repository.getSetup(user.id,courseId);const signals=input.intakeSignals||{};const deps=setup.curriculumAudit?.audit_output?.assumed_prerequisites||[];const requirement=selectDiagnosticRequirement({dependencies:deps,intakeSignals:signals,existingEvidence:input.existingEvidence||[]});if(!requirement.required)return repository.saveDiagnosticPlan({studentId:user.id,courseId,auditId:setup.curriculumAudit?.curriculum_audit_id,requirement});if(!intelligence)held();const result=await intelligence.designDiagnostic({course:setup.course,requirement,audit:setup.curriculumAudit});if(!result.accepted){const e=new Error('Diagnostic design was rejected by validation.');e.status=422;e.code='TEACHING_D07_DIAGNOSTIC_DESIGN_REJECTED';throw e;}return repository.saveDiagnosticPlan({studentId:user.id,courseId,auditId:setup.curriculumAudit?.curriculum_audit_id,requirement,design:result.validatedResult.output,provenanceRefs:[`curriculum-audit:${setup.curriculumAudit?.curriculum_audit_id}`]});}
 async function decideVpk(user,courseId,input={}){const setup=await repository.getSetup(user.id,courseId);if(!setup.course)throw new Error('Course not found.');const targetKind=String(input.targetKind||'').trim(),targetRef=String(input.targetRef||'').trim();if(!['PREREQUISITE','SOURCE_CONTENT_ITEM','LEARNING_UNIT'].includes(targetKind)||!targetRef){const e=new Error('Valid targetKind and targetRef are required.');e.status=400;throw e;}const requestedRefs=Array.isArray(input.evidenceRefs)?input.evidenceRefs.map(String):[];
    if(!requestedRefs.length){const e=new Error('At least one server-held Diagnostic evidence reference is required.');e.status=400;e.code='TEACHING_D07_VPK_EVIDENCE_REQUIRED';throw e;}
    const stored=await repository.loadDiagnosticEvidence({studentId:user.id,courseId,targetKind,targetRef,evidenceRefs:requestedRefs});
    if(stored.length!==new Set(requestedRefs).size){const e=new Error('Every VPK evidence reference must resolve to server-held Diagnostic evidence.');e.status=422;e.code='TEACHING_D07_VPK_EVIDENCE_UNRESOLVED';throw e;}
    const design=setup.diagnosticPlan?.diagnostic_design||{};
    const evidence=stored.map(row=>({evidenceRef:row.evidence_event_id,probeRef:row.response_quality?.probe_ref,independent:row.independent_performance===true,passed:row.response_quality?.passed===true,variedOrUncued:row.response_quality?.varied_or_uncued===true,criteriaPassed:row.response_quality?.criteria_passed||[]}));
    const validators=new Set(stored.map(row=>`${String(row.response_quality?.validator_id||'').trim()}\u0000${String(row.response_quality?.validator_version||'').trim()}`));
    if(validators.size!==1||[...validators][0].startsWith('\u0000')||[...validators][0].endsWith('\u0000')){const e=new Error('Diagnostic evidence must carry one consistent validator identity and version.');e.status=422;e.code='TEACHING_D07_VPK_VALIDATOR_PROVENANCE_INVALID';throw e;}
    const [validatorId,validatorVersion]=[...validators][0].split('\u0000');
    const decision=evaluateValidatedPriorKnowledge({evidence,criticalCriteria:design.critical_criteria||[],constructSupportsVariation:design.construct_supports_variation!==false,unresolvedMaterialContradiction:stored.some(row=>row.response_quality?.unresolved_material_contradiction===true),validatorId,validatorVersion,provenanceRefs:stored.map(row=>`evidence:${row.evidence_event_id}`)});return repository.saveVpkDecision({studentId:user.id,courseId,targetKind,targetRef,decision});}
 return Object.freeze({createCourse,listCourses,getSetup,submitIntake,editPreferences,runAudit,queueAudit,planDiagnostic,decideVpk});
}
module.exports={createD07Service};
