'use strict';

const EVENT_CATEGORIES = Object.freeze({
  AUTHENTICATED_COMMAND: 'authenticated_command',
  COMMITTED_DOMAIN_EVENT: 'committed_domain_event',
  SCHEDULED_DUE_EVENT: 'scheduled_due_event',
  INTELLIGENCE_WORK_RESULT: 'intelligence_work_result',
  OPERATIONAL_RECOVERY_EVENT: 'operational_recovery_event',
});

const EVENT_CATEGORY_VALUES = Object.freeze(Object.values(EVENT_CATEGORIES));

const EVENT_STATUSES = Object.freeze({
  PENDING: 'PENDING',
  CLAIMED: 'CLAIMED',
  RETRY_WAIT: 'RETRY_WAIT',
  COMPLETED: 'COMPLETED',
  NOOP: 'NOOP',
  SUPERSEDED: 'SUPERSEDED',
  FAIRNESS_RECOVERY_REQUIRED: 'FAIRNESS_RECOVERY_REQUIRED',
  CANCELLED: 'CANCELLED',
});

const TERMINAL_EVENT_STATUSES = Object.freeze([
  EVENT_STATUSES.COMPLETED,
  EVENT_STATUSES.NOOP,
  EVENT_STATUSES.SUPERSEDED,
  EVENT_STATUSES.FAIRNESS_RECOVERY_REQUIRED,
  EVENT_STATUSES.CANCELLED,
]);

const RECONCILIATION_DISPOSITIONS = Object.freeze({
  ACTIONABLE: 'ACTIONABLE',
  ALREADY_SATISFIED: 'ALREADY_SATISFIED',
  SUPERSEDED: 'SUPERSEDED',
  FAIRNESS_RECOVERY_REQUIRED: 'FAIRNESS_RECOVERY_REQUIRED',
});

module.exports = {
  EVENT_CATEGORIES,
  EVENT_CATEGORY_VALUES,
  EVENT_STATUSES,
  TERMINAL_EVENT_STATUSES,
  RECONCILIATION_DISPOSITIONS,
};
