'use strict';

const WORKLOAD_KINDS=Object.freeze(['CLASS','HOMEWORK','ASSESSMENT','RECOVERY','DEADLINE','REVISION']);
const RECOVERY_STATES=Object.freeze(['DETECTED','CLASSIFIED','AWAITING_STUDENT_ACTION','RECOVERY_PROPOSED','SCHEDULED','IN_PROGRESS','AWAITING_VERIFICATION','RESOLVED','ESCALATED','CLOSED']);
const NOTIFICATION_KINDS=Object.freeze(['CLASS_START','ASSIGNMENT_DEADLINE','ASSESSMENT_SCHEDULED','REQUEST_DECIDED','RESULT_RELEASED','RECOVERY_ACTION_AVAILABLE','COURSE_RISK_ACTIONABLE','BREAK_ENDING']);
const SOURCE_OWNERS=Object.freeze(['D09_SCHEDULER','D10_REQUESTS','D13_SKM','D14_CLASSROOM','D15_ATTENDANCE','D16_WORK','D17_ASSESSMENT','D18_ASSESSMENT_SHELL','D19_ASSESSMENT_TYPES','D20_GRADEBOOK','D21_PROGRESSION','D25_RELIABILITY']);

function fail(message,code,status=400,details=null){const error=new Error(message);error.code=code;error.status=status;if(details)error.details=details;throw error;}
function text(value,field){const out=String(value||'').trim();if(!out)fail(`${field} is required.`,`TEACHING_D26_${field.toUpperCase()}_REQUIRED`);return out;}
function timestamp(value,field){const out=new Date(value);if(Number.isNaN(out.getTime()))fail(`${field} must be an ISO timestamp.`,`TEACHING_D26_${field.toUpperCase()}_INVALID`);return out.toISOString();}
function positiveMinutes(value,field='minutes'){const out=Number(value);if(!Number.isFinite(out)||out<=0)fail(`${field} must be positive.`,'TEACHING_D26_WORKLOAD_INVALID');return Math.ceil(out);}
function sourceReference(input={}){const owner=text(input.owner,'sourceOwner');if(!SOURCE_OWNERS.includes(owner))fail('Unsupported authoritative source owner.','TEACHING_D26_SOURCE_OWNER_INVALID');return Object.freeze({owner,entityType:text(input.entityType,'sourceEntityType'),entityId:text(input.entityId,'sourceEntityId'),version:text(input.version,'sourceVersion'),eventId:input.eventId?text(input.eventId,'sourceEventId'):null});}
function workloadItem(input={}){const kind=text(input.kind,'workloadKind').toUpperCase();if(!WORKLOAD_KINDS.includes(kind))fail('Unsupported workload kind.','TEACHING_D26_WORKLOAD_KIND_INVALID');return Object.freeze({id:text(input.id,'workloadId'),courseId:text(input.courseId,'courseId'),kind,startsAt:timestamp(input.startsAt,'startsAt'),endsAt:timestamp(input.endsAt,'endsAt'),minutes:positiveMinutes(input.minutes),hardDeadline:Boolean(input.hardDeadline),priority:Number.isFinite(Number(input.priority))?Number(input.priority):0,source:sourceReference(input.source)});}
function notification(input={}){const kind=text(input.kind,'notificationKind').toUpperCase();if(!NOTIFICATION_KINDS.includes(kind))fail('Unsupported notification kind.','TEACHING_D26_NOTIFICATION_KIND_INVALID');const source=sourceReference(input.source);return Object.freeze({kind,studentId:text(input.studentId,'studentId'),courseId:input.courseId?text(input.courseId,'courseId'):null,title:text(input.title,'title'),body:text(input.body,'body'),deepLink:text(input.deepLink,'deepLink'),source,dueAt:timestamp(input.dueAt,'dueAt'),sourceVersion:source.version,actionable:input.actionable!==false});}
function recoveryTransition(from,to){if(!RECOVERY_STATES.includes(from)||!RECOVERY_STATES.includes(to))fail('Unknown Recovery Case state.','TEACHING_D26_RECOVERY_STATE_INVALID');const allowed={DETECTED:['CLASSIFIED','CLOSED'],CLASSIFIED:['AWAITING_STUDENT_ACTION','RECOVERY_PROPOSED','ESCALATED','CLOSED'],AWAITING_STUDENT_ACTION:['RECOVERY_PROPOSED','ESCALATED','CLOSED'],RECOVERY_PROPOSED:['SCHEDULED','AWAITING_STUDENT_ACTION','ESCALATED'],SCHEDULED:['IN_PROGRESS','RECOVERY_PROPOSED','ESCALATED'],IN_PROGRESS:['AWAITING_VERIFICATION','ESCALATED'],AWAITING_VERIFICATION:['RESOLVED','IN_PROGRESS','ESCALATED'],RESOLVED:['CLOSED','IN_PROGRESS'],ESCALATED:['RECOVERY_PROPOSED','CLOSED'],CLOSED:['DETECTED']};if(!(allowed[from]||[]).includes(to))fail(`Recovery Case cannot transition ${from} -> ${to}.`,'TEACHING_D26_RECOVERY_TRANSITION_INVALID',409);return true;}

module.exports={WORKLOAD_KINDS,RECOVERY_STATES,NOTIFICATION_KINDS,SOURCE_OWNERS,fail,text,timestamp,positiveMinutes,sourceReference,workloadItem,notification,recoveryTransition};
