'use strict';
const {notification}=require('./contracts');
const {notificationDeepLink}=require('../d23/contracts');

const DEFAULT_COOLDOWN_MS=Object.freeze({CLASS_START:30*60e3,ASSIGNMENT_DEADLINE:12*60*60e3,ASSESSMENT_SCHEDULED:24*60*60e3,REQUEST_DECIDED:0,RESULT_RELEASED:0,RECOVERY_ACTION_AVAILABLE:6*60*60e3,COURSE_RISK_ACTIONABLE:24*60*60e3,BREAK_ENDING:5*60e3});
function authoritativeLink(kind,source,courseId=null){const map={CLASS_START:'CLASS',ASSIGNMENT_DEADLINE:'ASSIGNMENT',ASSESSMENT_SCHEDULED:'ASSESSMENT',REQUEST_DECIDED:'REQUEST',RESULT_RELEASED:'RESULT',RECOVERY_ACTION_AVAILABLE:'RECOVERY_CASE',COURSE_RISK_ACTIONABLE:'COURSE',BREAK_ENDING:'CLASS'};return notificationDeepLink(map[kind]||kind,source.entityId,{courseId});}
function safeNotification(input={}){const link=authoritativeLink(String(input.kind||'').toUpperCase(),input.source,input.courseId);if(input.deepLink&&input.deepLink!==link){const e=new Error('Teaching notification deep link must target its authoritative source object.');e.code='TEACHING_D26_NOTIFICATION_LINK_MISMATCH';throw e;}const out=notification({...input,deepLink:link});return Object.freeze({...out,containsAuthoritativeFact:false,attendanceConsequenceAllowed:false,deliveryIsAcademicEvidence:false,privacyClass:'AUTHORITATIVE_UI_EQUIVALENT'});}
function dedupeKey(n){return `teaching:d26:${n.kind}:${n.studentId}:${n.source.owner}:${n.source.entityId}:${n.source.version}`;}
function shouldDeliver({candidate,lastDeliveredAt=null,now=new Date(),sourceStillCurrent=true,userOnActiveClassSurface=false}={}){const n=safeNotification(candidate);if(!sourceStillCurrent)return Object.freeze({deliver:false,reason:'SOURCE_SUPERSEDED',notification:n});if(n.kind==='COURSE_RISK_ACTIONABLE'&&!n.actionable)return Object.freeze({deliver:false,reason:'RISK_NOT_ACTIONABLE',notification:n});if(n.kind==='BREAK_ENDING'&&userOnActiveClassSurface)return Object.freeze({deliver:false,reason:'ACTIVE_SURFACE_HANDLES_BREAK',notification:n});const cooldown=DEFAULT_COOLDOWN_MS[n.kind]||0;if(lastDeliveredAt&&new Date(now)-new Date(lastDeliveredAt)<cooldown)return Object.freeze({deliver:false,reason:'ANTI_SPAM_COOLDOWN',notification:n});return Object.freeze({deliver:true,reason:'CURRENT_ACTIONABLE',notification:n,dedupeKey:dedupeKey(n)});}
module.exports={DEFAULT_COOLDOWN_MS,authoritativeLink,safeNotification,dedupeKey,shouldDeliver};
