'use strict';
const {coordinate,rankRecoverySlots}=require('./scheduler');
const {safeNotification,shouldDeliver}=require('./notifications');
const {sourceReference,recoveryTransition,text,fail}=require('./contracts');

function createD26Service({repository,notificationInterface,dueEventStore=null,ownerReaders={},clock=()=>new Date(),randomUUID}={}){
  if(!repository)throw new TypeError('D26 requires its coordination repository.');
  if(!notificationInterface||typeof notificationInterface.send!=='function')throw new TypeError('D26 requires the shared KIWI notification interface.');
  if(typeof randomUUID!=='function')throw new TypeError('D26 requires randomUUID().');
  const now=()=>{const value=clock();return value instanceof Date?value:new Date(value);};
  async function globalSchedule(user,{semesterId,dailyCapacityMinutes=480,timeZone='UTC'}={}){const items=await repository.listWorkload(String(user.id),text(semesterId,'semesterId'));return coordinate(items,{dailyCapacityMinutes,timeZone});}
  async function coordinateSemesterChange(user,{semesterId,changeType,source,expectedVersion}={}){if(!['ACADEMIC_BREAK','PERMANENT_AVAILABILITY','ASSESSMENT_WINDOW','REVISION_WINDOW'].includes(String(changeType||'')))fail('Unsupported semester-wide coordination change.','TEACHING_D26_CHANGE_TYPE_INVALID');const ref=sourceReference(source);const current=await ownerReaders[ref.owner]?.read?.(String(user.id),ref);if(current&&String(current.version)!==String(expectedVersion||ref.version))fail('Source owner changed before global reconciliation.','TEACHING_D26_SOURCE_VERSION_STALE',409,{currentVersion:String(current.version)});const review=await globalSchedule(user,{semesterId});return Object.freeze({changeType,source:ref,review,commandApplied:false,requiresOwnerCommands:true,perCourseTruthMutated:false});}
  async function enqueueNotification(user,input={}){const candidate=safeNotification({...input,studentId:String(user.id)});if(!dueEventStore)fail('Durable Teaching event store is unavailable.','TEACHING_D26_DUE_EVENT_STORE_UNAVAILABLE',503);return dueEventStore.enqueue({eventId:input.eventId||randomUUID(),schemaVersion:1,eventType:'teaching.notification.delivery_due',eventCategory:'scheduled_due_event',triggerType:'system_time',source:'teaching.d26.notifications',origin:candidate.source.owner,actorId:String(user.id),aggregateType:candidate.source.entityType,aggregateId:candidate.source.entityId,aggregateVersion:Number(candidate.source.version),occurredAt:now().toISOString(),dueAt:candidate.dueAt,idempotencyKey:`notify:${candidate.kind}:${candidate.studentId}:${candidate.source.owner}:${candidate.source.entityId}:${candidate.source.version}`,payload:{notification:candidate},auditRefs:[],provenanceRefs:[candidate.source.eventId].filter(Boolean)});}
  async function deliverNotificationEvent(event){const candidate=event?.payload?.notification;if(!candidate)fail('Notification event payload is missing.','TEACHING_D26_NOTIFICATION_PAYLOAD_MISSING');const ref=sourceReference(candidate.source);const current=await ownerReaders[ref.owner]?.read?.(candidate.studentId,ref);const sourceStillCurrent=current?String(current.version)===String(ref.version)&&current.actionable!==false:true;const last=await repository.lastNotificationDelivery(candidate.studentId,`teaching:d26:${candidate.kind}:${candidate.studentId}:${ref.owner}:${ref.entityId}:${ref.version}`);const decision=shouldDeliver({candidate,lastDeliveredAt:last?.delivered_at||null,now:now(),sourceStillCurrent,userOnActiveClassSurface:Boolean(current?.userOnActiveClassSurface)});if(!decision.deliver)return Object.freeze({disposition:'ALREADY_SATISFIED',reason:decision.reason,safeMetadata:{kind:candidate.kind,sourceOwner:ref.owner}});const result=await notificationInterface.send({...decision.notification,dedupeKey:decision.dedupeKey});await repository.recordNotificationDelivery({deliveryId:randomUUID(),studentId:candidate.studentId,dedupeKey:decision.dedupeKey,kind:candidate.kind,source:ref,deepLink:decision.notification.deepLink,deliveredAt:now().toISOString(),providerRef:result?.id||null});return Object.freeze({disposition:'ACTIONABLE',safeMetadata:{kind:candidate.kind,sourceOwner:ref.owner}});}
  async function upsertReviewNeed(user,input={}){const source=sourceReference(input.source);return repository.upsertReviewNeed({reviewNeedId:input.reviewNeedId||randomUUID(),studentId:String(user.id),courseId:text(input.courseId,'courseId'),learningUnitId:text(input.learningUnitId,'learningUnitId'),misconceptionKey:text(input.misconceptionKey,'misconceptionKey'),severity:String(input.severity||'MEDIUM'),selfReport:Boolean(input.selfReport),source,createdAt:now().toISOString()});}
  async function createRecoveryCase(user,input={}){const refs=(input.sources||[]).map(sourceReference);if(!refs.length)fail('Recovery Case requires authoritative source references.','TEACHING_D26_RECOVERY_SOURCE_REQUIRED');return repository.createRecoveryCase({caseId:input.caseId||randomUUID(),studentId:String(user.id),courseId:text(input.courseId,'courseId'),idempotencyKey:text(input.idempotencyKey,'idempotencyKey'),classification:text(input.classification,'classification'),cause:text(input.cause,'cause'),policyAtEvent:text(input.policyAtEvent,'policyAtEvent'),missingInstruction:input.missingInstruction||null,missingEvidence:input.missingEvidence||null,nextAction:text(input.nextAction,'nextAction'),repairProposal:input.repairProposal||null,verificationCriteria:input.verificationCriteria||null,sources:refs,createdAt:now().toISOString()});}
  async function getRecoveryCase(user,caseId){const row=await repository.getRecoveryCase(String(user.id),String(caseId));if(!row)fail('Recovery Case not found.','TEACHING_D26_RECOVERY_NOT_FOUND',404);return row;}
  async function transitionRecoveryCase(user,caseId,input={}){const current=await repository.getRecoveryCase(String(user.id),String(caseId));if(!current)fail('Recovery Case not found.','TEACHING_D26_RECOVERY_NOT_FOUND',404);if(Number(input.expectedVersion)!==Number(current.version))fail('Recovery Case changed before transition.','TEACHING_D26_RECOVERY_VERSION_STALE',409,{currentVersion:current.version});recoveryTransition(current.state,String(input.to||''));return repository.transitionRecoveryCase({studentId:String(user.id),caseId:String(caseId),expectedVersion:Number(input.expectedVersion),to:String(input.to),reason:text(input.reason,'reason'),studentAction:input.studentAction||null,occurredAt:now().toISOString()});}
  async function proposeRecovery(user,caseId,{candidates=[],allowWeekend=false,sharedWorkload=[]}={}){const recovery=await repository.getRecoveryCase(String(user.id),String(caseId));if(!recovery)fail('Recovery Case not found.','TEACHING_D26_RECOVERY_NOT_FOUND',404);const schedule=coordinate(sharedWorkload);const slots=rankRecoverySlots(candidates,{allowWeekend});return Object.freeze({caseId:String(caseId),caseVersion:recovery.version,slots,sharedWorkload:schedule,schedulerApprovalRequired:true,automaticWeekendClass:false,authoritativeScheduleMutation:false});}
  async function supportInspection(actor,{studentId,courseId=null,classId=null}={}){if(!actor?.is_admin&&!actor?.isAdmin&&!actor?.supportRole)fail('Support/admin authorization is required.','TEACHING_D26_SUPPORT_FORBIDDEN',403);const snapshot=await repository.supportSnapshot({studentId:text(studentId,'studentId'),courseId,classId});return Object.freeze({...snapshot,readOnly:true,casualAcademicEditAllowed:false,mutationLinks:Object.freeze([])});}
  function status(){return Object.freeze({contractVersion:'d26.coordination.v1',taskCount:27,globalSchedulerCoordinatesOnly:true,perCourseOwnersPreserved:true,sharedNotifications:true,notificationDeliveryIsNotEvidence:true,recoveryCasesReferenceTruth:true,reviewNeedsDoNotMutateMastery:true,automaticWeekendClass:false});}
  return Object.freeze({globalSchedule,coordinateSemesterChange,enqueueNotification,deliverNotificationEvent,upsertReviewNeed,createRecoveryCase,getRecoveryCase,transitionRecoveryCase,proposeRecovery,supportInspection,status});
}
module.exports={createD26Service};
